mozilla/addons-frontend

- .eslintignore
- .eslintrc
- .jscsrc
- .travis.yml
- bin/server.js
- config/webpack.config.js
- config/webpack.prod.config.js
- package.json
- src/routes.js
- src/server.js
> Basic eslint and travis

- package.json
- src/core/client.js
- src/core/server/base.js
- src/disco/client.js
- src/search/client.js
> Fix deprecated history warning

- package.json
- src/core/server/base.js
This adds a very basic index page so when we hit / we can navigate to pages that have content. 
Ideally this would be generated from routes etc etc but this will serve it's purpose for now.
> Add a very basic index page

- .travis.yml
> Use the latest firefox for travis tests

- src/core/server/base.js
> Fix content-type

- .eslintrc
- bin/server.js
- karma.conf.js
- package.json
- src/config/index.js
- src/config/webpack.dev.config.babel.js
- src/config/webpack.prod.config.babel.js
- src/core/api/index.js
- tests/core/api/test_api.js
Fixes #105
I changed the test so it will work based on defaulting to a production environment. I'll add some config tests in a follow-up.
> Add definePlugin and environmentPlugin

- src/config/webpack.dev.config.babel.js
> Override babel config from .babelrc

- src/core/client/index.js
The path the routes changed and I missed updating it.
> Correctly import routes in core/client/index.js

- package.json
> Use npm-better-run

- src/core/components/Paginate/index.js
- src/search/components/SearchForm.js
- src/search/components/SearchPage.js
- src/search/containers/CurrentSearchPage.js
- tests/karma/core/components/TestPaginate.js
- tests/karma/search/components/TestSearchForm.js
- tests/karma/search/components/TestSearchPage.js
- tests/karma/search/containers/TestCurrentSearchPage.js
> Universal search view

- README.md
- package.json
- src/config/webpack.dev.config.babel.js
- src/config/webpack.prod.config.babel.js
> Provide a bundle per app

- .eslintrc
- package.json
- src/core/css/inc/lib.scss
- src/core/css/inc/mixins.scss
- src/core/utils.js
- src/disco/components/Addon.js
- src/disco/components/InstallButton.js
- src/disco/containers/DiscoPane.js
- src/disco/css/Addon.scss
- src/disco/css/App.scss
- src/disco/css/InstallButton.scss
- src/disco/fakeData.js
- src/search/css/App.scss
- src/search/css/lib/buttons.scss
- tests/karma/core/test-utils.js
- tests/karma/disco/components/TestAddon.js
- tests/karma/disco/containers/TestDiscoPane.js
Fixes #208 
Fixes #12 
More in-depth testing of the install button will come in the next branch when I represent the various states of the install button as a component.
> Add basic disco pane

- src/config/index.js
- src/core/containers/LoginRequired/index.js
- src/search/routes.js
- tests/karma/core/containers/TestLoginRequired.js
> Show a login page when unauthenticated

- .gitignore
- package.json
- src/config/webpack.prod.config.babel.js
- src/core/server/base.js
- tests/server/TestDiscoViews.js
- tests/server/TestSearchViews.js
- tests/server/helpers.js
Fixes #51 - only outputs SRI attrs in production mode.
> Setup SRI for assets

- src/config/index.js
- src/core/actions/index.js
- src/core/api/index.js
- src/core/components/LoginPage/index.js
- src/core/containers/HandleLogin/index.js
- src/core/containers/LoginRequired/index.js
- src/core/reducers/authentication.js
- src/core/server/base.js
- src/search/containers/AddonPage/index.js
- src/search/routes.js
- tests/karma/core/actions/test_index.js
- tests/karma/core/api/test_api.js
- tests/karma/core/components/TestLoginPage.js
- tests/karma/core/containers/TestHandleLogin.js
- tests/karma/core/containers/TestLoginRequired.js
- tests/karma/search/containers/TestAddonPage.js
Depends on https://github.com/mozilla/addons-server/issues/2519.
Fixes #230.
> Login user on FxA redirect page

- package.json
- src/core/api/index.js
> Use url to format query strings

- .travis.yml
- tests/server/TestConfig.js
> Fix + run server tests on travis

- config/default.js
- config/dev.js
- config/development.js
- config/stage.js
- tests/server/TestCSPConfig.js
> Add more CSP directives

- package.json
> See if bumping the servertest timeout helps prevent spurious failures

- config/default.js
Relates to #364 - I'll leave that bug open so we can track the upstream bugs better.
> Temporarily remove upgrade-insecure-requests

- src/disco/css/Addon.scss
- src/disco/css/App.scss
- src/disco/css/inc/vars.scss
> Update header to header spec

- config/dev.js
- config/stage.js
Will allow the svg which is inlined as a data uri in the CSS.
> Add data: to dev/stage for img-src CSP directive

- src/disco/css/Addon.scss
- src/disco/css/inc/vars.scss
How's it look @pwalm?
Fixes #401.
> Match background with other addons manager panels

- Dockerfile
As we're using git for a dep (temporarily).
r? @jasonthomas
> Install git

- config/default-disco.js
- tests/server/TestCSPConfig.js
> Set frame-ancestors specifically for disco pane

- config/default-disco.js
- config/default.js
- src/core/server/base.js
- tests/server/TestFrameGuardConfig.js
> Set x-frame-options to match frame-ancestors

- config/default.js
- src/core/i18n/utils.js
- src/disco/components/Addon.js
- src/disco/reducers/installations.js
- src/disco/themePreview.js
> Use includes over indexOf

- config/default-disco.js
- config/default.js
- config/dev-disco.js
- config/dev.js
- config/development.js
- config/stage-disco.js
- config/stage.js
- tests/server/TestCSPConfig.js
- tests/server/TestDiscoViews.js
- tests/server/TestSearchViews.js
- webpack.prod.config.babel.js
> Use CDN urls for statics

- package.json
See these randomly fail on travis. Let's see if bumping the timeout a little makes the necessary difference.
> Increase servertest timeout

- tests/server/TestConfig.js
> Add test to check disbleSSR config

- webpack.prod.config.babel.js
> Use contenthash for CSS

- package.json
- src/disco/components/Addon.js
- src/search/components/SearchResult/index.js
- src/search/components/SearchResults.js
Fixes #516
Makes a small difference to the disco bundle size:
* Before: 430K  dist/disco-f0233826549f9800cc0e.js
* After: 427K  dist/disco-3e774a55dcfc1db745f9.js
> Remove sprintf and use the same one that's in Jed

- src/core/server/base.js
- tests/server/TestDiscoViews.js
> Redirect invalid locales

- config/default.js
- config/dev.js
- config/development.js
- src/core/client/logger.js
- tests/client/core/client/test_logger.js
> Make client console logging configurable

- src/disco/constants.js
- tests/client/disco/components/TestInstallButton.js
> Add DISABLING/ENABLING to valid install states

- src/disco/addonManager.js
- src/disco/components/Addon.js
> Add more logging

- src/disco/components/Addon.js
- tests/client/disco/components/TestAddon.js
> Install theme when clicking the image

- .stylelintrc
- package.json
- src/core/css/inc/mixins.scss
- src/disco/css/Addon.scss
- src/disco/css/App.scss
- src/disco/css/InstallButton.scss
> Add stylelint

- src/disco/css/InstallButton.scss
> Remove transition from install background

- src/disco/addonManager.js
- src/disco/components/Addon.js
- src/disco/constants.js
- src/disco/reducers/installations.js
- tests/client/disco/components/TestAddon.js
- tests/client/disco/reducers/test_installations.js
> Add catch() to install/uninstall/setCurrentStatus

- package.json
- src/disco/css/InstallButton.scss
- src/disco/img/tick.svg
- webpack.dev.config.babel.js
- webpack.prod.config.babel.js
* Simplify the svg tick icon display
* Don't use base64 for svg in data uris.
* Transition tweaks.
> Improve SVG + transition perf

- config/default-search.js
- config/dev-search.js
- config/stage-search.js
> Add custom staticHost for search app

- src/disco/components/InstallButton.js
- tests/client/disco/components/TestInstallButton.js
> Fix checked states causing switch bounce

- circle.yml
Circle CI is a thing to run tests, this makes it work if you want it to work but it is in no way optimised.
> Circle CI config

- src/core/server/base.js
> Always send an STS header on secure requests

- src/core/server/base.js
- tests/server/TestDiscoViews.js
> Always set HSTS header

- src/locale/de/disco.json
- src/locale/dsb/disco.json
- src/locale/es/disco.json
- src/locale/fr/disco.json
- src/locale/hsb/disco.json
- src/locale/hu/disco.json
- src/locale/ja/disco.json
- src/locale/nl/disco.json
- src/locale/pt_BR/disco.json
- src/locale/pt_PT/disco.json
- src/locale/ru/disco.json
- src/locale/sl/disco.json
- src/locale/sv_SE/disco.json
- src/locale/uk/disco.json
- src/locale/zh_CN/disco.json
Build the locale JSON with the latest localizations.
> Build locales 2016-07-11

- README.md
- config/default-amo.js
- config/default.js
- package.json
- src/amo/client.js
- src/amo/containers/App.js
- src/amo/containers/Home.js
- src/amo/css/App.scss
- src/amo/routes.js
- src/amo/store.js
- tests/client/amo/containers/TestApp.js
- tests/client/amo/containers/TestHome.js
- tests/client/amo/test_store.js
- tests/server/TestCSPConfig.js
- tests/server/TestConfig.js
- tests/server/TestFrameGuardConfig.js
- tests/server/disco/TestCSPConfig.js
- tests/server/disco/TestViews.js
- tests/server/search/TestViews.js
Fixes #701 
Adds a basic hello world app stub and refactors some of the server tests.
> Setup stub amo app

- package.json
- src/disco/components/InfoDialog.js
- tests/client/disco/components/TestInfoDialog.js
Fixes #725 
Uses https://github.com/Pomax/react-onclickoutside
> Dismiss notification when clicking outside

- config/uitests-disco.js
Fix the tracking setting for uitests.
> Fix tracking setting

- config/custom-environment-variables.json
- package.json
- src/core/server/base.js
- src/core/tracking.js
- src/core/utils.js
- tests/client/core/test_tracking.js
- tests/client/core/test_utils.js
- tests/server/helpers.js
> Allow disabling of the tracking via env var

- .eslintrc
- src/core/store.js
- tests/client/core/test_store.js
Fixes https://github.com/mozilla/addons-frontend/issues/29
> Support redux-devtools

- src/disco/containers/DiscoPane.js
Fixes mozilla/addons-server#3204
> Update copy as requested by legal

- src/disco/components/Addon.js
- tests/client/disco/components/TestAddon.js
> Install a theme when image is clicked and the theme is disabled

- locale/pl/LC_MESSAGES/disco.po
> Update Polish (pl) localization of AMO Frontend

- src/search/components/JsonData/index.js
- src/search/components/JsonData/style.scss
- src/search/containers/AddonPage/index.js
- tests/client/search/components/TestJsonData.js
> Show the JSON from the API on add-on detail

- config/default-disco.js
- src/locale/fa/disco.json
- src/locale/id/disco.json
- src/locale/it/disco.json
- src/locale/ko/disco.json
- src/locale/sq/disco.json
Fixes #928
Looks like this will mean we fall-back to english for these few locales however the majority of the locales have been updated.
> Disable fuzzy for disco

- src/disco/css/Addon.scss
> Fix RTL close link

- src/search/components/SearchForm.js
- tests/client/search/components/TestSearchForm.js
> I'm feeling lucky! with Shift+Enter

- src/core/utils.js
- src/disco/addonManager.js
- tests/client/core/test_utils.js
- tests/client/disco/TestAddonManager.js
> Add promo src query param to install urls

- src/disco/containers/DiscoPane.js
General copy improvements. Add "free", and link to AMO
> update disco pane intro copy

- docs/adding-a-page.md
- package.json
- src/admin/containers/AddonPage/index.js
- src/admin/containers/CurrentSearchPage.js
- src/admin/containers/UserPage/index.js
- src/admin/store.js
- src/amo/containers/DetailPage.js
- src/amo/store.js
- src/core/api/index.js
- src/core/client/base.js
- src/core/server/base.js
- src/disco/containers/DiscoPane.js
- src/disco/store.js
- tests/client/core/api/test_api.js
- tests/server/amo/TestDetailsPage.js
@mstriemer - this works but feels a bit clunky, but I'm just posting it up for some early feedback on the approach.
I've kept it simple for the one error versus many case.
> Migrate to redux-connect

- src/admin/components/NavBar/index.js
- src/admin/containers/App.js
- src/core/components/NavBar/index.js
- src/core/components/NavBar/styles.scss
- src/core/reducers/authentication.js
- tests/client/admin/components/TestNavBar.js
- tests/client/admin/containers/TestApp.js
- tests/client/core/components/TestNavBar.js
- tests/client/core/reducers/test_authentication.js
Just a button to log out.
Fixes #974.
> Log out button in admin nav bar

- ISSUE_TEMPLATE.md
This has already been reviewed over on mozilla/addons, so once green this is good to go.
> Copy the ISSUE_TEMPLATE from mozilla/addons

- config/development-amo.js
- src/core/api/index.js
- tests/client/core/api/test_api.js
This allows dev login in development with https://github.com/mozilla/addons-server/pull/3540 and sends the config name on login so it actually works.
> Dev fxa login and fix

- config/development-amo.js
Config name is changing in https://github.com/mozilla/addons-server/pull/3540
> Development config name is now local

- .eslintrc
- src/admin/components/SearchForm.js
- src/amo/components/SearchForm.js
- src/core/components/InstallButton/index.js
- src/core/components/NotFound.js
- src/core/components/Search/SearchResults.js
- src/core/css/SearchForm.scss
- src/core/i18n/translate.js
- src/disco/components/Addon.js
- src/disco/containers/DiscoPane.js
- tests/client/admin/components/TestSearchForm.js
- tests/client/amo/components/TestSearchForm.js
- tests/client/core/components/TestInstallButton.js
- tests/client/core/components/TestNotFound.js
- tests/client/core/components/TestSearchResults.js
- tests/client/disco/components/TestAddon.js
There's the odd bit of reformatting/clean up in here too.
> Switch all components to functional ref (fix #970)

- src/amo/containers/App.js
- src/core/containers/SearchPage.js
- tests/client/amo/containers/TestSearch.js
> Add lang to search (fix #1123)

- src/amo/containers/App.js
- tests/client/amo/components/TestSearchForm.js
- tests/client/amo/containers/TestApp.js
Sorry, I missed this in my PR.
> Render query on server-side request to search (fix #1148)

- .gitignore
- tests/ui/README.md
> Update documentation for discopane UI tests

- src/admin/components/SearchForm.scss
- src/amo/components/SearchForm.scss
Improved the search bar a bit:
> Address comments in search PR (close #1151)

- src/core/components/Paginate/index.js
- tests/client/core/components/TestPaginate.js
fixes #1132
fixed in core so should apply to admin as well.
> don't show pagination when there's only one page

- config/test-disco.js
- tests/client/core/api/test_api.js
> override apiHost when running tests

- .eslintrc
- src/amo/actions/reviews.js
- src/amo/api/index.js
- src/amo/constants.js
- src/core/middleware.js
- src/core/store.js
- src/disco/actions.js
- tests/client/amo/helpers.js
- tests/server/helpers.js
> Remove prefer-default-export

- config/dev-amo.js
- config/stage-amo.js
I copied the current configs for dev and stage disco app and updated the staticHost to reflect the amo app's CDN.
r?
> Add unique staticHost for dev and stage amo APP

- .travis.yml
Just going to see what travis makes of this to know if we have any compat changes we will need to make for node 6.
> Test with node 6 too

- circle.yml
> Don't rely on DOCKERHUB_REPO env variable during test runs (fix #1254)

- config/default-amo.js
- config/dev-amo.js
- config/stage-amo.js
- tests/server/amo/TestViews.js
> Configure font-src and form-action directives for amo dev

- package.json
- src/amo/components/MastHead.js
- yarn.lock
Greenkeeper change with lint fix.
Fixes #1204
> chore(package): update eslint-plugin-react to version 6.4.1

- src/amo/components/Footer.scss
- src/amo/css/App.scss
> Make footer stick to bottom of the viewport

- src/amo/components/Footer.js
- tests/client/amo/components/TestFooter.js
Changes the links to point to Mozilla.org links, with the right lang set.
> Add proper footer links (close #1339)

- package.json
- src/core/client/base.js
> Scroll restoration

- src/core/api/index.js
- tests/client/core/api/test_api.js
Needed for #1286 and #1285, plus I just wanted a tiny PR and something quick to knock out that didn't touch other things they needed while #1237 is in review.
> Add featured API support (fix #1335)

- src/amo/components/AddonReview.js
- tests/client/amo/components/TestAddonReview.js
Fixes https://github.com/mozilla/addons-frontend/issues/1366
> Use an appropriate prompt based on the star rating

- package.json
- src/core/server/base.js
* Supercedes #1336
Once this lands need to do quick manual check to diff the header output on -dev.
> greenkeeper helmet 3.1.0

- src/amo/components/Footer.js
- src/amo/containers/App.js
- tests/client/amo/containers/TestApp.js
> Hookup "view desktop" link to delete cookie and reload

- package.json
- src/amo/containers/CategoryPage.js
- src/core/searchUtils.js
- tests/client/amo/components/TestAddonDetail.js
This should be a simple fix for the second page not loading.
> Fix page loading bug (close #1401)

- src/amo/components/SearchForm.js
- tests/client/amo/components/TestSearchForm.js
Had this issue open in my tabs and figured I'd knock it out.
> Translate SearchForm (fix #1362)

- package.json
> fix(package): update react-cookie to version 1.0.1

- src/amo/actions/reviews.js
- src/amo/components/AddonReview.js
- src/amo/reducers/reviews.js
- tests/client/amo/components/TestAddonReview.js
- tests/client/amo/components/TestOverallRating.js
- tests/client/amo/helpers.js
- tests/client/amo/reducers/testReviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/1381
> Allow existing review text to be edited

- karma.conf.js
> <img width="668" alt="screenshot 2016-12-01 20 55 47" src="https://cloud.githubusercontent.com/assets/211578/20821498/98d42f42-b808-11e6-8959-7efde864ee8b.png">
> Before
> <img width="666" alt="screenshot 2016-12-01 20 55 32" src="https://cloud.githubusercontent.com/assets/211578/20821497/98d39636-b808-11e6-816a-9d5d40828276.png">
> After
Fixes #1447
> Show diffs in test failures

- src/ui/components/ShowMoreCard/index.js
- tests/client/ui/components/TestShowMoreCard.js
A few tweaks mentioned after I merged, sorry!
> Fix comments in #1448

- src/amo/components/AddonDetail.js
- src/amo/css/AddonDetail.scss
- src/core/css/inc/vars.scss
- src/core/installAddon.js
- src/disco/components/Addon.js
- tests/client/amo/components/TestAddonDetail.js
- tests/client/core/TestInstallAddon.js
- tests/client/disco/components/TestAddon.js
- yarn.lock
I'm going to look into fixing the dimensions of the image in the morning which should make the label look better.
> [With label (missing icon) (old)](https://cloud.githubusercontent.com/assets/211578/20743427/e9853634-b69b-11e6-8da7-6f93942d13a0.png)
>[Previewing (and sometimes scrolling) (old)](https://cloud.githubusercontent.com/assets/211578/20743367/8c9b6ace-b69b-11e6-8e12-864866fc6414.gif) 
Fixes #1422.
> Theme preview

- src/amo/components/LanguagePicker.scss
- src/amo/css/App.scss
- src/amo/img/icons/globe.svg
- src/amo/img/icons/triangle-down.svg
- src/core/css/inc/vars.scss
> Fix RTL language switcher and update style (fix #1363)

- src/amo/containers/App.js
- tests/client/amo/containers/TestApp.js
- yarn.lock
> Mamo cookie off 1480

- package.json
- tests/server/amo/TestDetailsPage.js
> chore(package): update fetch-mock to version 5.8.0

- config/default-disco.js
- src/core/installAddon.js
- tests/client/core/TestInstallAddon.js
Fixes #1380 
@mstriemer please check if I have done it right.
> Remove UITour code 

- package.json
Before:
```
[1] {"name":"server","app":"disco","hostname":"markbook-pro","pid":18387,"level":50,"err":{"message":"add is not defined","name":"ReferenceError","stack":"ReferenceError: add is not defined\n    at mapStateToProps (/Users/mark/projects/addons-frontend/src/disco/components/Addon.js:221:15)\n    at Connect.configureFinalMapState (/Users/mark/projects/addons-frontend/node_modules/react-redux/lib/components/connect.js:155:27)\n    at Connect.computeStateProps (/Users/mark/projects/addons-frontend/node_modules/react-redux/lib/components/connect.js:142:23)\n    at Connect.updateStatePropsIfNeeded (/Users/mark/projects/addons-frontend/node_modules/react-redux/lib/components/connect.js:204:35)\n    at Connect.render (/Users/mark/projects/addons-frontend/node_modules/react-redux/lib/com …
```
> Use the bunyan CLI in development mode for nicer output

- src/amo/components/AddonsCard/AddonsCard.scss
- src/amo/components/AddonsCard/index.js
- src/amo/components/LandingAddonsCard/LandingAddonsCard.scss
- src/amo/components/LandingAddonsCard/index.js
- src/amo/components/LandingPage.js
- src/amo/components/LandingPage.scss
- src/amo/constants.js
- src/amo/routes.js
- src/amo/utils.js
- src/core/api/index.js
- src/core/css/SearchResult.scss
- src/core/searchUtils.js
- tests/client/amo/components/TestLandingPage.js
- tests/client/amo/test_utils.js
- tests/client/core/api/test_api.js
> Add extension/theme landing pages

- docs/adding-a-page.md
- package.json
- src/core/api/index.js
- src/disco/api.js
- tests/client/core/api/test_api.js
- tests/client/disco/test_api.js
> fix(package): update normalizr to version 3.0.1

- src/amo/components/SearchForm.scss
- src/ui/components/SearchInput/style.scss
Make the text white, as it is in the mocks.
> White text in search placeholder

- src/amo/components/AddonDetail.js
- src/amo/components/AddonMeta.js
- tests/client/amo/components/TestAddonDetail.js
- tests/client/amo/components/TestAddonMeta.js
- tests/client/amo/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/1293
> Show average daily users on add-on page

- package.json
> chore(package): update babel-plugin-istanbul to version 3.1.2

- .travis.yml
> Use yarn on Travis

- package.json
Fixes mozilla/addons-server#4312
Reverts mozilla/addons-frontend#1591 since it appears to cause a regression https://github.com/mozilla/addons-server/issues/4312
> Revert "Update react-redux to the latest version 🚀"

- src/amo/components/AddonMoreInfo.scss
- src/amo/components/AddonsCard/AddonsCard.scss
- src/amo/components/Footer.scss
- src/amo/components/LandingAddonsCard/LandingAddonsCard.scss
- src/amo/components/LandingAddonsCard/index.js
- src/amo/components/LandingPage.scss
- src/amo/components/LanguagePicker.scss
- src/amo/components/MastHead.scss
- src/amo/components/SearchForm.scss
- src/amo/components/SearchPage.scss
- src/amo/components/SearchResults.scss
- src/amo/css/AddonDetail.scss
- src/amo/css/AddonReview.scss
- src/amo/css/App.scss
- src/amo/css/Home.scss
- src/amo/css/ScreenShots.scss
- src/amo/css/inc/vars.scss
- src/core/css/inc/vars.scss
- src/ui/components/Card/Card.scss
- src/ui/components/ShowMoreCard/ShowMoreCard.scss
- src/ui/components/ShowMoreCard/index.js
- tests/client/ui/components/TestShowMoreCard.js
You can click these things to see the image (fancy).
<details>
<summary>Button</summary>
</details>
<details><summary>Switch (off)</summary>
</details>
<details><summary>Switch (on)</summary>
</details>
Fixes #1597.
> Update to mocks and pwalm's comments

- package.json
> fix(package): update react-helmet to version 4.0.0

- src/disco/constants.js
Since updating this list I identified 4 more system add-ons in Nightly.
> Adding Nightly System Add-ons to the ignore list.

- locale/pl/LC_MESSAGES/disco.po
> Update Polish (pl) localization of AMO Frontend 170124

- src/admin/components/SearchPage.js
- src/amo/components/SearchPage.js
- src/core/components/Paginate/index.js
- tests/client/core/components/TestPaginate.js
Fixed the linting error and merge conflicts in #1564; closes #1564.
> refactor(core): 'Paginate' is default to showPages={0}

- Dockerfile
Fixes https://github.com/mozilla/addons-frontend/issues/1661
> Fix UI tests

- Dockerfile
- circle.yml
Our Jenkins V2 pipeline requires CIRCLE_BUILD_URL for validation purposes before stage and prod deployments. 
r?
> Create version.json via circle-ci

- config/default.js
Add config entry for the 'th' locale (Thai).
> Add th locale

- src/core/server/base.js
- tests/server/admin/TestViews.js
- tests/server/amo/TestDetailsPage.js
- tests/server/amo/TestViews.js
- tests/server/disco/TestViews.js
- tests/server/helpers.js
This addresses https://github.com/mozilla/addons-frontend/issues/1682 but only in that it should show us what the real error was.
> Report runServer() failures better

- package.json
> fix(package): update react-onclickoutside to version 5.9.0

- package.json
> chore(package): update svg-url-loader to version 2.0.1

- package.json
> fix(package): update config to version 1.25.1

- package.json
> fix(package): update redux-logger to version 2.8.1

- package.json
> chore(package): update sass-loader to version 5.0.1

- src/core/api/index.js
- tests/client/core/api/test_api.js
- tests/server/amo/TestDetailsPage.js
> fix: fetch hangs on server-side (fix #1726)

- package.json
> chore(package): update autoprefixer to version 6.7.2

- src/amo/containers/Home.js
- src/amo/css/Home.scss
- yarn.lock
> Add welcome mat

- package.json
> fix(package): update normalizr to version 3.2.0

- src/amo/components/AddonReview.js
- src/amo/css/AddonReview.scss
- tests/client/amo/components/TestAddonReview.js
Fixes https://github.com/mozilla/addons-frontend/issues/1739
> Remove review title from entry form

- package.json
> fix(package): update normalizr to version 3.2.1

- src/admin/components/SearchResults.js
- src/amo/components/SearchResults.js
> fix: Change "Mozilla Add-ons" to "Firefox Add-ons" in the empty search string message

- src/amo/containers/Home.js
- tests/client/amo/containers/TestHome.js
> fix: Copy changes on Explore page

- src/amo/components/AddonMoreInfo.js
- tests/client/amo/components/TestAddonMoreInfo.js
Points to the correct URL for a privacy policy.
> fix: Use correct privacy policy link (fix #1826)

- src/amo/components/MastHead.scss
- yarn.lock
> Fix header non en locales

- src/disco/constants.js
Added more system addons and the new default dark & light themes...
Accidentally committed without creating a pull request yesterday, creating a pull request now.
> more system addons - commit fix

- src/amo/api/index.js
- src/amo/components/AddonReview.js
- src/amo/components/AddonReviewList.js
- src/amo/components/RatingManager/index.js
- src/core/api/index.js
- src/core/utils.js
- tests/client/amo/components/TestAddonReview.js
- tests/client/amo/components/TestAddonReviewList.js
- tests/client/amo/components/TestRatingManager.js
- tests/client/amo/testApi.js
- tests/client/core/TestAddonManager.js
- tests/client/core/api/test_api.js
- tests/client/core/test_utils.js
Fixes https://github.com/mozilla/addons-frontend/issues/1838
oof, this took way more effort than I thought it would.
> Switch review components to new API endpoints

- src/amo/components/AddonMoreInfo.js
- tests/client/amo/components/TestAddonMoreInfo.js
Fixes #1826
Sorry, I still got this URL wrong.
> fix: Privacy link URL (fix #1826)

- src/amo/components/AddonDetail.js
- src/amo/css/AddonDetail.scss
- tests/client/amo/components/TestAddonDetail.js
- tests/client/amo/helpers.js
> feat: Use summary text if description is empty

- src/core/themePreview.js
- tests/client/core/TestThemePreview.js
> Author will now be displayed in the more section

- src/amo/components/AddonDetail.js
- src/amo/components/RatingManager/index.js
- src/amo/components/RatingManager/styles.scss
- src/core/components/AuthenticateButton/index.js
- src/ui/components/Rating/styles.scss
- src/ui/components/Rating/vars.scss
- tests/client/amo/components/TestAddonDetail.js
- tests/client/amo/components/TestRatingManager.js
- tests/client/core/components/TestAuthenticateButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/1037
> Require login before rating an add-on

- package.json
> fix(package): update normalizr to version 3.2.2

- src/amo/components/LandingPage.js
- src/core/searchUtils.js
- tests/client/amo/components/TestLandingPage.js
> fix: Use addonType not type in query

- src/amo/components/RatingManager/index.js
- src/core/constants.js
- tests/client/amo/components/TestRatingManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/1898
> Fix log in to rate prompt for all add-ons

- src/core/server/base.js
Jason noticed that this was missing when working on https://github.com/mozilla/addons-frontend/issues/1886
> Fix Raven (Sentry) middleware

- src/amo/css/AddonDetail.scss
> Remove white background from detail icon

- locale/pl/LC_MESSAGES/amo.po
> Update Polish (pl) localization of AMO Frontend 170223

- .travis.yml
- tests/ui/README.md
- tests/ui/setup.cfg
- tox.ini
Fixes https://github.com/mozilla/addons-frontend/issues/1927
> Update package dependencies for discopane UI tests

- src/core/api/index.js
- tests/client/core/api/test_api.js
- tests/client/core/test_searchUtils.js
Fixes #1723
Admittedly a very hacky fix but it works.
> fix: Android lacks theme categories

- src/amo/components/SearchResult.js
- tests/client/amo/components/TestSearchResult.js
> Fix empty authors list

- locale/pl/LC_MESSAGES/amo.po
- locale/pl/LC_MESSAGES/disco.po
> Update Polish (pl) localization of AMO Frontend 170302

- src/amo/components/Footer.js
- tests/client/amo/components/TestFooter.js
> Add report a bug link

- src/core/server/base.js
Fixes https://github.com/mozilla/addons-frontend/issues/1942
> Fix how errors are passed to middleware (fixes Sentry)

- config/default-admin.js
- config/default-disco.js
- config/default.js
- config/dev-admin.js
- config/dev-disco.js
- config/dev.js
- config/stage-admin.js
- config/stage-disco.js
- config/stage.js
- package.json
- src/admin/routes.js
- src/amo/routes.js
- src/core/client/base.js
- src/core/containers/error-simulation/SimulateClientError.js
- src/core/containers/error-simulation/SimulateClientError.scss
- src/disco/routes.js
- tests/client/core/containers/error-simulation/TestSimulateClientError.js
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/1933
I used the Sentry test instance to get this working. However, it wasn't using source maps. I think this was just because it couldn't access my `localhost:3000` instance so we'll have to see what happens on dev.
> Report client-side errors to Sentry

- src/core/css/SearchResult.scss
> Fix addons icon on RTL

- config/default-admin.js
- config/default-amo.js
- config/default-disco.js
- config/default.js
- config/dev-admin.js
- config/dev-amo.js
- config/dev-disco.js
- config/dev.js
- config/development-disco.js
- config/development.js
- config/lib/shared.js
- config/stage-admin.js
- config/stage-amo.js
- config/stage-disco.js
- config/stage.js
- config/test-disco.js
- config/uitests-disco.js
- src/core/containers/error-simulation/SimulateClientError.js
- src/disco/routes.js
- tests/client/core/containers/error-simulation/TestSimulateClientError.js
Fixes https://github.com/mozilla/addons-frontend/issues/1933
> Fix CSP rules for Sentry client reporting

- circle.yml
This is a temporary workaround for https://github.com/mozilla/addons-frontend/issues/1995
> Disable UI tests on Circle CI

- config/default-amo.js
> Include staticHost in default-amo exports

- config/production.js
See https://github.com/mozilla/addons-frontend/issues/2016 for details.
> Temporarily enable error simulation in prod

- src/ui/components/SearchInput/index.js
- src/ui/components/SearchInput/style.scss
- tests/client/ui/TestSearchInput.js
> Fix invisible search input for long search label text

- src/amo/components/Footer.js
- tests/client/amo/components/TestFooter.js
> Fix footer report-bug locale

- src/disco/constants.js
found via https://ftp.mozilla.org/pub/system-addons/
> adding a system addon

- src/core/client/base.js
- src/core/server/base.js
Fixes https://github.com/mozilla/addons-frontend/issues/2062
> Configure Sentry logger for filtering

- .eslintrc
- src/core/api/index.js
- tests/client/amo/testApi.js
- tests/client/core/test_utils.js
Fixes https://github.com/mozilla/addons-frontend/issues/1252
> Relax arrow-body-style; let's duke it out in code reviews

- .travis.yml
- README.md
- bin/version-check.js
* Remove node 4 from both tests and version-check script.
> Remove node 4

- locale/it/LC_MESSAGES/amo.po
> Fix broken it placeholder

- config/default.js
- src/core/actions/index.js
- src/core/constants.js
- src/core/containers/HandleLogin/index.js
- src/core/reducers/api.js
- src/core/reducers/authentication.js
- src/core/server/base.js
- tests/client/admin/containers/TestApp.js
- tests/client/amo/components/TestRatingManager.js
- tests/client/amo/containers/TestSearch.js
- tests/client/core/actions/test_index.js
- tests/client/core/api/test_api.js
- tests/client/core/components/TestAuthenticateButton.js
- tests/client/core/containers/TestHandleLogin.js
- tests/client/core/reducers/test_api.js
- tests/client/core/reducers/test_authentication.js
- tests/client/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/2123
This needs to land in sync with https://github.com/mozilla/addons-server/pull/4960
> Supports the new API auth scheme which switched away from JWTs

- package.json
r? If you want but this was just a thing greenkeeper missed and it's not a major version bump so I'll assume r+ if Travis is green.
> chore: Update express

- package.json
> chore(package): update style-loader to version 0.16.0

- package.json
> fix(package): update webpack-isomorphic-tools to version 3.0.2

- package.json
> fix(package): update raven to version 1.2.0

- package.json
> chore(package): update autoprefixer to version 6.7.7

- package.json
> fix(package): update redux-logger to version 3.0.0

- package.json
> fix(package): update bunyan to version 1.8.9

- package.json
> fix(package): update moment to version 2.18.1

- package.json
> fix(package): update react-helmet to version 5.0.0

- package.json
Reverts mozilla/addons-frontend#2147
> Revert "fix(package): update webpack-isomorphic-tools to version 3.0.2"

- package.json
Reverts mozilla/addons-frontend#2160
> Revert "fix(package): update react-helmet to version 5.0.0"

- .travis.yml
- README.md
- yarn.lock
Travis `yarn --frozen-lockfile` installs were failing, seeing if this fixes it.
> fix: Travis yarn install

- docs/adding-a-page.md
- src/amo/components/MastHead.js
- src/amo/components/SearchResults.js
- src/core/components/InstallSwitch/index.js
- src/core/components/NavBar/index.js
- src/core/components/Paginate/index.js
- src/core/containers/InfoDialog/index.js
- src/core/containers/LoginRequired/index.js
Fix #909, seems we had most of these covered already.
> chore: Use compose() everywhere (fix #909)

- src/core/api/index.js
- tests/client/core/api/test_api.js
Fixes https://github.com/mozilla/addons-frontend/issues/2061
> Make API error message more useful for Sentry

- package.json
- src/ui/components/Rating/index.js
- tests/client/ui/components/TestRating.js
> chore: Remove round package (close #2173)

- config/default.js
Adds Urdu to locales to prevent server tests failures.
> fix: Add Urdu to langs

- src/disco/constants.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1351424
> add future system add-on

- package.json
> chore(package): update stylelint to version 7.10.1

- config/default.js
Easy r? before the tag. (fix #2226)
> fix: Add Urdu to RTL languages (fix #2226)

- src/disco/constants.js
https://ftp.mozilla.org/pub/system-addons/disable-prefetch/
> add new system add-on

- package.json
> chore(package): update react-addons-test-utils to version 15.5.1

- package.json
> fix(package): update react-onclickoutside to version 5.11.1

- src/amo/api/index.js
- src/amo/components/RatingManager/index.js
- tests/client/amo/components/TestRatingManager.js
- tests/client/amo/testApi.js
Fixes https://github.com/mozilla/addons-frontend/issues/2019
> Work around cache issues by filtering latest review more precisely

- package.json
> fix(package): update dompurify to version 0.8.9

- package.json
Closes #2188 
See https://github.com/mozilla/addons-frontend/pull/2188 for discussion about the changes.
> fix(package): update normalize.css to version 7.0.0

- src/core/store.js
- tests/client/core/test_store.js
Fixes https://github.com/mozilla/addons-frontend/issues/2239
> Don't log Redux actions on the server

- tests/client/amo/components/TestAddonDetail.js
> Re-instate summary test and cleanup santization assertions

- src/amo/components/LanguagePicker.js
- src/ui/components/Rating/index.js
> Add missing keys

- package.json
> chore(package): update potools to version 0.0.5

- src/amo/css/AddonMeta.scss
Fixes #2128
Some locales are causing rating stars from "ratings and user count" section to be unaligned
> FIX  #2128

- src/amo/css/AddonDetail.scss
- src/core/css/SearchResult.scss
>  Add-on with long name is causing layout issues

- src/amo/components/Categories.scss
> pseudo element approach

- package.json
Closes https://github.com/mozilla/addons-frontend/issues/2456
> chore(package): update redux-saga-tester to version 1.0.252

- .travis.yml
> Add build task to travis

- package.json
Closes https://github.com/mozilla/addons-frontend/issues/2452
> chore(package): update css-loader to version 0.28.3

- .travis.yml
- webpack.prod.config.babel.js
> Simplify the TravisCI build command

- README.md
- package.json
Closes #2473.
I wanted this functionality back as I find it handy. Also changed up the name of the tests (and adjusted the CI command to run it). A few tweaks to the README while I was at it.
> Add --watch with coverage reports to package.json

- src/core/css/SearchResult.scss
> Theme with no author causing layout issues

- README.md
- package.json
Fixes https://github.com/mozilla/addons-frontend/issues/2490
> Added note about how to debug Flow problems

- src/core/i18n/utils.js
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
@muffinresearch I may be partially responsible for this :)
> Quiet down the Intl logging

- src/core/i18n/utils.js
> Fix Intl error android

- src/disco/constants.js
found via https://ftp.mozilla.org/pub/system-addons/followonsearch/
> [add] another system add-on

- config/stage.js
Closes https://github.com/mozilla/addons-frontend/issues/2532
> Activate client console logging on stage

- src/amo/components/AddonReviewList.js
- src/core/utils.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/helpers.js
Fixes #2528.
Just adds this check to the AddonReviewList.
> chore: Use isAllowedOrigin in AddonReviewList

- package.json
Fixes https://github.com/mozilla/addons-frontend/issues/2556
> Work around a hang in flow:dev

- .stylelintrc
> fix: Clean up stylelint deprecation warning

- src/disco/constants.js
via https://sql.telemetry.mozilla.org/queries/4286#table
> add system add-on

- docs/moz-addon-manager.md
Closes https://github.com/mozilla/addons-frontend/issues/2682
> Document how to fully test add-on/theme installation locally

- src/amo/css/AddonReviewList.scss
Fixes: #2598 
Resized theme icon to make it bigger
After -
> fix: Theme icon from "All written reviews" page is too small

- locale/templates/LC_MESSAGES/amo.pot
- src/amo/components/SearchContextCard/index.js
Erroneous trailing quote #2698
> Fix Erroneous trailing quote #2698

- package.json
> chore(package): update autoprefixer to version 7.1.2

- src/core/store.js
I meant to push this and messed up. It's just the fix for the new redux-logger API.
> fix: Actually commit store change

- package.json
> fix(package): update raven-js to version 3.16.1

- package.json
> fix(package): update react-redux to version 5.0.5

- package.json
> fix(package): update extract-text-webpack-plugin to version 2.1.2

- package.json
> fix(package): update redux to version 3.7.1

- package.json
- src/core/window.js
- yarn.lock
> fix(package): update jsdom to version 11.1.0

- src/amo/css/AddonReviewList.scss
Fix #2415 (the review list part)
**Before**
**After**
>  Add-on with long name is causing layout issues #2415

- package.json
> fix(package): update react-onclickoutside to version 6.1.1

- package.json
- webpack-common.js
> chore(package): update postcss-loader to version 2.0.6

- .babelrc
- .eslintrc
- .flowconfig
- flow/libs/dedent.js.flow
- package.json
- src/amo/api/index.js
- src/amo/components/RatingManager/index.js
- src/core/api/index.js
- src/core/client/base.js
- src/core/client/config.js
- src/core/i18n/translate.js
- src/core/middleware/prefixMiddleware.js
- src/core/server/base.js
- src/core/utils.js
- tests/unit/core/i18n/test_utils.js
- tests/unit/helpers.js
Fixes: #2092
Removed babel-plugin-dedent
> fix: Remove babel-plugin-dedent

- src/disco/components/Footer/index.js
- src/disco/components/Footer/styles.scss
- src/disco/containers/App.js
- tests/unit/disco/components/TestFooter.js
Fixes #2789
Adds a privacy policy to the Disco Pane.
> fix: Add Privacy Policy to disco pane (fix #2789)

- src/core/tracking.js
- tests/unit/core/test_tracking.js
Adds a test ensuring GA is disabled when DNT is true, as well.
Fixes #2798
> fix: Check for DNT correctly

- src/core/tracking.js
- tests/unit/core/test_tracking.js
Fixes https://github.com/mozilla/addons-frontend/issues/2797
* Adds better tests for things like config reading logic
* DRYs up the tests
* Adds better logging so we can see exactly how GA gets enabled/disabled
> Fix up tests and add more logging for Tracking

- src/disco/constants.js
via https://ftp.mozilla.org/pub/system-addons/tls13-middlebox/
> new system add-on

- README.md
Closes https://github.com/mozilla/addons-frontend/issues/2832
> Minor tweaks to docs for the new hosted dev commands

- README.md
- docs/using-the-staging-sites-api.md
- package.json
Closes https://github.com/mozilla/addons-frontend/issues/2833
> Simplify development server commads

- config/default.js
> Add in missing "ms" locale

- package.json
> fix(package): update helmet to version 3.8.0

- package.json
Closes #2840 (which was failing because of a newly-added locale)
> fix(package): update redux-saga to version 0.15.6

- locale/it/LC_MESSAGES/amo.po
> Remove extra period from it translation

- config/default.js
> Add missing te locale

- README.md
Just a tiny tweak to the README that I somehow just noticed 😓
> Minor grammar tweak

- src/amo/components/Search/index.js
- src/amo/sagas/categories.js
- src/amo/sagas/featured.js
- src/amo/sagas/index.js
- src/amo/sagas/landing.js
- src/amo/sagas/reviews.js
- src/amo/store.js
- src/core/actions/search.js
- src/core/sagas/addons.js
- src/core/sagas/search.js
- src/core/sagas/utils.js
- src/core/searchUtils.js
- tests/unit/amo/components/TestCategory.js
- tests/unit/amo/components/TestSearchContextCard.js
- tests/unit/amo/testSearchUtils.js
- tests/unit/core/actions/test_search.js
- tests/unit/core/sagas/testSearch.js
- tests/unit/core/sagas/testUtils.js
- tests/unit/core/test_searchUtils.js
Adds the sagas and tests for them in preparation of #2737. Doesn't use them yet. 😄 
I separated this bit out so things are easier to review.
Fixes #2871.
> Search sagas

- src/amo/components/Search/styles.scss
- src/amo/components/SearchContextCard/styles.scss
Fixes #2880 
**Before:**
**After**
> Fixes  Long search term is not wrapped #2880

- .stylelintrc
> Fix style lint issue

- locale/bn_BD/LC_MESSAGES/amo.po
Fixes #2903
After patch:
```
$ dennis-cmd lint --errorsonly locale/
dennis version 0.9
Final totals
Number of files examined:            108
Total number of files with errors:     0
Total number of errors:                0
```
> Fix broken translation

- webpack.dev.config.babel.js
Fix #2907.
This will make development a bit nicer; I was running into a react-dom error locally on the search saga stuff and it was annoying not seeing the error right in the console.
> feat: Use unminified builds of react/redux in dev

- .eslintrc
- src/core/tracking.js
- tests/unit/core/test_tracking.js
> Add dimension3 to addons-frontend

- package.json
> fix(package): update bunyan to version 1.8.12

- package.json
- tests/unit/core/components/TestAuthenticateButton.js
- tests/unit/disco/containers/TestDiscoPane.js
- yarn.lock
> chore(package): update sinon to version 3.1.0

- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestFeaturedAddons.js
- tests/unit/amo/components/TestNotAuthorized.js
- tests/unit/amo/components/TestNotFound.js
- tests/unit/amo/components/TestServerError.js
- tests/unit/core/components/TestErrorPage.js
Fixes #2000 
---
This PR removes manual store creation in some test cases.
> Remove manual store creation in some test cases

- src/core/errorHandler.js
> Add missing doc in errorHandler

- src/amo/components/Search/styles.scss
- yarn.lock
Fixes #2880
See https://www.w3.org/TR/css3-grid-layout/#min-size-auto for more info on the defaults.
Before:
After:
> Fix grid overflow 2880

- package.json
- src/amo/api/index.js
- src/amo/components/AddonReviewList.js
- src/amo/components/App/index.js
- src/amo/components/ErrorPage/NotAuthorized/index.js
- src/amo/components/ErrorPage/NotFound/index.js
- src/amo/components/RatingManager/index.js
- src/amo/components/SearchResult/index.js
- src/amo/sagas/reviews.js
- src/core/api/index.js
- src/core/client/logger.js
- src/core/containers/ServerHtml.js
- src/core/i18n/utils.js
- src/core/localState.js
- src/core/reducers/api.js
- src/core/reducers/categories.js
- src/core/tracking.js
- src/disco/components/Addon.js
- src/ui/components/ErrorList/index.js
- tests/unit/amo/components/TestLandingPage.js
- tests/unit/core/TestAddonManager.js
- tests/unit/core/test_utils.js
- yarn.lock
eslint complained about a LOT of indentation errors here. I ran `eslint --fix`... but I wonder what the diff looks like and if it's what we wanted. Posting here to see the diff.
Closes #2721
> Eslint 4.3

- package.json
> fix(package): update dompurify to version 1.0.1

- src/amo/sagas/index.js
- src/amo/store.js
- src/core/api/index.js
- src/core/reducers/autocomplete.js
- src/core/sagas/autocomplete.js
- tests/unit/amo/helpers.js
- tests/unit/amo/test_store.js
- tests/unit/core/api/test_api.js
- tests/unit/core/reducers/test_autocomplete.js
- tests/unit/core/sagas/test_autocomplete.js
Refs #2747
---
This PR adds reducer/sagas/api for the autocomplete/suggestion/hint search feature.
> Search hints/autocomplete reducer/sagas

- README.md
Fixes https://github.com/mozilla/addons-frontend/issues/2992
> Document how to install fonts for Sketch

- src/core/api/index.js
- tests/unit/core/api/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/3008
> Include response status in API error messages

- src/core/errorHandler.js
- tests/unit/core/testErrorHandler.js
Fixes https://github.com/mozilla/addons-frontend/issues/3007
> Allow a custom error handler prop for testing

- Dockerfile
- bin/start-func-test-server.js
Fix #1391
---
This PR fixes an issue with the functional test suite on Travis: the Docker image could not be built.
> Use yarn in Dockerfile and functional test command

- src/amo/components/Addon/index.js
- src/amo/components/Addon/styles.scss
- src/core/utils.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/core/test_utils.js
Fixes https://github.com/mozilla/addons-frontend/issues/2760
Here are some examples using https://addons-dev.allizom.org/en-US/firefox/addon/fastest-search/
> Show version release notes

- src/amo/components/App/index.js
- src/amo/components/App/styles.scss
- src/amo/components/Footer/styles.scss
- src/amo/components/Header/styles.scss
- src/amo/css/inc/vars.scss
- src/core/css/inc/vars.scss
- src/ui/components/OverlayCard/OverlayCard.scss
> Restrict max content width

- src/amo/css/AddonReview.scss
> Prevent horizontal resize of textarea

- src/amo/components/SearchForm/styles.scss
Fixes #3109 
**Before / After**
> fix: text overflow of search form via ellipsis

- src/amo/components/Header/index.js
- src/amo/components/Link.js
- src/core/components/AuthenticateButton/index.js
- src/ui/components/DropdownMenu/index.js
- src/ui/components/DropdownMenuItem/index.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/core/components/TestAuthenticateButton.js
- tests/unit/helpers.js
- tests/unit/ui/components/TestDropdownMenu.js
- tests/unit/ui/components/TestDropdownMenuItem.js
Refs #2745
---
This PR adds more links to the menu to be able to submit add-ons. I also took the opportunity to clean a few things related to the menu.
> Add more links to the menu

- src/ui/components/DropdownMenu/index.js
- src/ui/components/DropdownMenu/styles.scss
- tests/unit/ui/components/TestDropdownMenu.js
> Fix long username in menu

- src/amo/components/AddonReviewList.js
- tests/unit/amo/components/TestAddonReviewList.js
Fixes: #3147 
I have also considered `401` error , referring from #3061.
**Before:**
**After:**
> fix: Broken 404, for all reviews

- src/amo/sagas/index.js
- src/amo/store.js
- src/core/api/abuse.js
- src/core/reducers/abuse.js
- src/core/sagas/abuse.js
- tests/unit/amo/testApi.js
- tests/unit/amo/test_store.js
- tests/unit/core/api/test_abuse.js
- tests/unit/core/reducers/test_abuse.js
- tests/unit/core/sagas/test_abuse.js
- tests/unit/helpers.js
Fixes #3170.
This is just the API/reducer/saga code needed to allow us to report add-ons for abuse. After this is merged I'll send the PR with the actual UI.
> feat: Add Report abuse API/sagas

- src/amo/components/Header/styles.scss
- src/amo/components/SearchForm/styles.scss
Fix: #3186 
**Before:**
**After:**
> fix : height fix for search box and register btn

- src/amo/components/Footer/index.js
- src/amo/components/Footer/styles.scss
> Fix epic click target on mozilla logo

- src/amo/components/Addon/styles.scss
Fixes: #3176 
**Before/After**
> fix: More extensions by author_name - section

- src/disco/components/Addon.js
- tests/unit/disco/components/TestAddon.js
> Allow links in the disco add-on descriptions

- package.json
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/3243
> Upgrade Express to prevent denial of service

- src/amo/components/Footer/styles.scss
- src/amo/components/SectionLinks/styles.scss
- src/amo/css/inc/vars.scss
> Fix contrast of grey links

- README.md
We now use the Open Sans font (at least in the footer).
> Add Open Sans to the list of fonts to install in README

- .eslintrc
- src/amo/components/AddonReview/index.js
- tests/unit/amo/components/TestAddonReview.js
> Selecting a star no longer erases the review you were editing

- src/amo/components/Home/index.js
- tests/unit/amo/containers/TestHome.js
> chore: Update Extensions page copy

- locale/he/LC_MESSAGES/amo.po
- locale/te/LC_MESSAGES/amo.po
- locale/zh_TW/LC_MESSAGES/amo.po
> Fix broken locales

- src/amo/components/AddonMoreInfo/index.js
- tests/unit/amo/components/TestAddonMoreInfo.js
> fix: Don't prefix links to license

- .eslintrc
- src/amo/actions/reviews.js
- src/amo/api/reviews.js
- src/amo/components/AddonReview/index.js
- src/amo/components/AddonReviewList/index.js
- src/amo/components/AddonReviewListItem/index.js
- src/amo/constants.js
- src/amo/reducers/reviews.js
- src/amo/sagas/reviews.js
- src/core/errorHandler.js
- src/core/types/addons.js
- src/core/types/util.js
- src/ui/components/DismissibleTextForm/index.js
- tests/unit/amo/actions/testReviews.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/amo/helpers.js
- tests/unit/amo/reducers/testReviews.js
- tests/unit/amo/sagas/testReviews.js
- tests/unit/helpers.js
- tests/unit/ui/components/TestDismissibleTextForm.js
Fixes https://github.com/mozilla/addons-frontend/issues/2775
Notes:
* The UX specs came while I was halfway done; I will fully implement those in https://github.com/mozilla/addons-frontend/issues/2773
* Showing the actual reply after it has been submitted will happen in https://github.com/mozilla/addons-frontend/issues/2773
* Sorry that this patch is massive. I tried splitting it in two but ran into a bunch of annoying conflicts.
> Initial UI for replying to a review

- src/amo/reducers/featured.js
- tests/unit/amo/reducers/testFeatured.js
Fix #3353
---
This PR is related to #3319. I thought I fixed all reducers but looks like I forgot this one, sorry 😢 
Only one review is needed I guess, first in, first served! Thank you.
> Use internal addon representation for featured addons too

- package.json
> chore(package): update bundlesize to version 0.15.1

- tests/unit/amo/components/TestFooter.js
rewrote footer tests using Enzyme
> rewrote footer tests using Enzyme

- src/amo/actions/landing.js
- src/amo/reducers/landing.js
- src/amo/sagas/landing.js
- src/core/api/search.js
- src/core/searchUtils.js
- tests/unit/amo/actions/test_landing.js
- tests/unit/amo/sagas/testLanding.js
Refs #3086
---
This PR adds the logic required to build the new category pages. Please see #3323 for the UI.
> Add reducer/saga logic for new category page

- src/ui/components/DropdownMenu/styles.scss
- src/ui/components/DropdownMenuItem/styles.scss
> fix: more menu layout issue

- src/ui/components/Icon/index.js
> Use semantically transparent element for icons

- package.json
- tests/unit/TestPackageJson.js
> Ensure dependencies are fixed versions

- .travis.yml
- tox.ini
> Integrate dennis linting for .po files.

- src/amo/components/Footer/index.js
Fixes #3416
Fixes #3411
Depends on https://github.com/mozilla/addons-frontend/issues/3409
> Add review_guide link and use to in place of href

- src/amo/components/Home/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
Fix #3312
---
This PR adds the fifth shelf on the homepage.
ℹ️ It is the 5th shelf but the 3rd has not been added yet (#3310), therefore it is the last (and 4th) shelf.
> Add up & coming shelf

- src/amo/components/AddonReviewListItem/index.js
- tests/unit/amo/components/TestAddonReviewListItem.js
Fixes #3368 
Here's what the new flow looks like, desktop and mobile:
> Allow developers to edit their review reply

- package.json
> fix(package): update ua-parser-js to version 0.7.17

- README.md
- config/custom-environment-variables.json
- src/ui/components/Button/index.js
- src/ui/components/DismissibleTextForm/index.js
- src/ui/components/DismissibleTextForm/styles.scss
- tests/unit/ui/components/TestButton.js
- tests/unit/ui/components/TestDismissibleTextForm.js
Fixes https://github.com/mozilla/addons-frontend/issues/3458
* The form looks and behaves the same as before
* I haven't been able to test this on an Android device. Do you think it will fix the hover issue?
* I started to document how to do local development on Android but it started taking so much time I just gave up and documented how far I got (which is better than nothing)
> Fix double-tap and hover bug in submit button for mobile

- package.json
> Upgrade moment to 2.9.1

- src/amo/components/Search/styles.scss
> Fix search message display

- package.json
- src/ui/components/ListItem/index.js
- src/ui/components/TooltipMenu/index.js
- src/ui/components/TooltipMenu/styles.scss
- tests/unit/core/api/test_index.js
- tests/unit/helpers.js
- tests/unit/ui/components/TestListItem.js
- tests/unit/ui/components/TestTooltipMenu.js
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/3534
We need a proper tooltip component (especially to handle edge collisions) for the *flag review* UI. Here is just the tooltip part.
You can see it with this patch:
```diff
diff --git a/src/amo/components/AddonReviewListItem/index.js b/src/amo/components/AddonReviewListItem/index.js
index 71b97881..c43a5bff 100644
--- a/src/amo/components/AddonReviewListItem/index.js
+++ b/src/amo/components/AddonReviewListItem/index.js
@@ -18,8 +18,10 @@ import {
showReplyToReviewForm,
} from 'amo/actions/reviews';
import Icon from 'ui/components/Icon';
+import ListItem from 'ui/components/ListItem';
import LoadingText from 'ui/components/LoadingText';
import Rating from 'ui/components/Rating';
+import TooltipMenu from …
```
> Adds a tooltip style menu component

- package.json
> chore(package): update react-hot-loader to version 3.1.1

- src/amo/components/AddonsCard/styles.scss
- src/amo/components/RatingManager/styles.scss
> Fix content overflow on details page

- package.json
Fixes https://github.com/mozilla/addons-frontend/issues/3583
> Disable jest colors for CI

- src/amo/components/Addon/index.js
- src/amo/components/AddonReviewList/index.js
- src/amo/components/App/index.js
- src/amo/components/Category/index.js
- src/amo/components/Collection/index.js
- src/amo/components/LandingPage/index.js
- src/amo/components/LanguageTools/index.js
- src/amo/components/Search/index.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestCategory.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestLandingPage.js
- tests/unit/amo/components/TestLanguageTools.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/containers/TestApp.js
Fix #2184
---
This PR adds HTML titles on each page and also adapts the title according to the `clientApp`.
For the search results, I tried to have titles for each page that we link in the app. It does not aim at covering every cases for now.
> Add HTML titles

- src/ui/components/Card/Card.scss
- src/ui/components/HeroSection/styles.scss
Fix #3568
---
This PR makes sure all links are keyboard-accessible on the homepage.
> Make all homepage links accessible

- src/ui/components/Card/Card.scss
> Fix overflow in long card header

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
> Do not link to user profile when url is null

- src/amo/components/Addon/index.js
- src/core/components/InstallButton/index.js
- src/core/installAddon.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/components/TestInstallButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/3618
> Add a src parameter to the install button URL

- src/amo/components/AddonsCard/styles.scss
> Fix hover shelf style

- src/amo/components/App/styles.scss
> Add default background colour to input and textarea

- src/amo/components/AddonReview/index.js
- src/amo/components/AddonReview/styles.scss
- tests/unit/amo/components/TestAddonReview.js
Fixes https://github.com/mozilla/addons-frontend/issues/3627
Before:
After:
> Link to review writing guidelines

- src/amo/components/SearchForm/index.js
- tests/unit/amo/components/TestSearchForm.js
> fix: limit search term to 100 characters

- src/amo/components/StaticPages/About.js
Fixes https://github.com/mozilla/addons-frontend/issues/3665
> Fix typo in Get Involved copy

- src/ui/components/HeroSection/styles.scss
> Set min-height on the Hero link, not the container

- src/amo/components/AddonsCard/styles.scss
Fix #3622
---
This PR allows to display the star rating of an add-on when hovered.
> Display star ratings on hover (addons card)

- src/disco/constants.js
> add new system add-ons

- src/amo/components/SectionLinks/styles.scss
Fix #3704
---
This PR updates the transition on the section links.
> Update section link transition

- src/amo/components/AddonMoreInfo/index.js
- tests/unit/amo/components/TestAddonMoreInfo.js
> Expose support email

- src/amo/components/ReportAbuseButton/index.js
- src/ui/components/Button/Button.scss
> Fix report button width

- src/amo/components/Search/styles.scss
> Fix search filters error style

- src/amo/components/SearchForm/index.js
> Add data-no-csrf tag to search form

- config/default.js
Fixes breakage from https://github.com/mozilla/addons-frontend/commit/4b0289be098c512650ef5a993ba53250613b1a62
> Configure the newly added cak locale

- src/amo/components/App/index.js
- src/amo/components/Category/index.js
- tests/unit/amo/components/TestCategory.js
> Use an en dash in place of hyphen

- src/amo/components/Header/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/3797
> Fix new logo margin

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
Fix #2705
---
This PR translates the add-on description header.
> Translate add-on description header

- src/core/utils/compatibility.js
- tests/unit/core/utils/test_compatibility.js
Fixes https://github.com/mozilla/addons-frontend/issues/3824
> Remove workarounds for add-on compatibility checks

- src/amo/components/SearchPage/index.js
- tests/unit/amo/components/TestSearchPage.js
> Add redir for atype=9 -> type=persona

- src/amo/components/Addon/index.js
- src/amo/sagas/reviews.js
- src/core/types/addons.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonMeta.js
- tests/unit/amo/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/2327
> Show correct count of reviews having text

- src/amo/components/Home/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> Add new top privacy extensions shelf

- src/amo/components/Home/index.js
- tests/unit/amo/containers/TestHome.js
>  adds comment fot IT at home

- locale/nn_NO/LC_MESSAGES/amo.po
> Fix locale nn_NO issue

- .travis.yml
See https://github.com/mozilla/addons-frontend/issues/3910
> Pin UI tests to an older Firefox

- src/amo/components/AddonReviewListItem/index.js
- src/core/constants.js
- src/core/reducers/user.js
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/core/reducers/test_user.js
Fix #3829
---
This PR allows admins to reply to any reviews, except their own reviews.
> Allow admins to reply to reviews

- src/amo/components/LanguageTools/index.js
- src/core/languages.js
> Remove unnecessary aliased export

- config/default.js
> chore: Add Bosnian to supported languages

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- src/amo/components/HomeHeroBanner/styles.scss
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
fix #4005 
This one took a lot longer than expected; there was a lot of tweaks needed to be made to tests, etc.
> chore: Update homepage content

- .nsprc
fix #3195
Pretty sure we fixed this, will let the tests run to make sure.
> chore: Remove NSP ignore now that fix is deployed

- src/core/components/ErrorPage/index.js
- tests/unit/core/components/TestErrorPage.js
Fixes https://github.com/mozilla/addons-frontend/issues/4050
Before:
After:
> Show a 500 for component errors

- .snyk
Fixes https://github.com/mozilla/addons-frontend/issues/4077
> Ignore content-type-parser vulnerability in jsdom

- locale/ro/LC_MESSAGES/amo.po
See https://travis-ci.org/mozilla/addons-frontend/jobs/318395884
> Fix reference to an invalid variable

- circle.yml
Fixes https://github.com/mozilla/addons-frontend/issues/4124
> Delete duplicate UI tests on CircleCI

- src/amo/components/App/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SearchFilters/styles.scss
- src/ui/components/Select/index.js
- src/ui/components/Select/styles.scss
- tests/unit/ui/components/TestSelect.js
Fixes https://github.com/mozilla/addons-frontend/issues/4114
> Extract a shared Select component

- src/amo/components/AddonReviewList/styles.scss
- src/amo/components/AddonReviewListItem/styles.scss
Fix: #4108 
**Before:**
**After:**
> I4108: Fix layout issue in All review

- .pyup.yml
> Add pyup configuration.

- config/default-disco.js
- config/test-disco.js
- src/disco/actions.js
- src/disco/api.js
- src/disco/containers/DiscoPane.js
- src/disco/sagas/disco.js
- tests/unit/disco/containers/TestDiscoPane.js
- tests/unit/disco/sagas/testDisco.js
- tests/unit/disco/test_actions.js
- tests/unit/disco/test_api.js
fix #4155.
See the params being sent:
> chore: Create generic taarParams object for #4155

- src/disco/constants.js
found via https://ftp.mozilla.org/pub/system-addons/
> add missing system addons

- src/amo/components/Collection/index.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/4170
> Fix infinite loop when loading a collection having a non-lower case user

- src/amo/components/Header/index.js
- src/amo/reducers/users.js
- src/core/constants.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/reducers/test_users.js
Fix mozilla/addons-server/issues/7280
> Add a `Reviewer Tools` link to the user dropdown if they have permission

- src/amo/api/collections.js
- src/core/api/index.js
- src/core/types/api.js
- tests/unit/amo/api/test_collections.js
- tests/unit/core/api/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/4194
> API helpers for editing a collection

- src/amo/components/AddAddonToCollection/index.js
- src/amo/components/Addon/index.js
- src/amo/components/AddonMoreInfo/index.js
- src/amo/components/AddonMoreInfo/styles.scss
- tests/unit/amo/components/TestAddAddonToCollection.js
Fixes https://github.com/mozilla/addons-frontend/issues/4181
**Before**
**After**
<details>
<summary>See a screenshot of the entire page</summary>
</details>
> Adjust add-to-collection dropdown UX

- src/amo/components/AddAddonToCollection/index.js
- tests/unit/amo/components/TestAddAddonToCollection.js
Fixes https://github.com/mozilla/addons-frontend/issues/4226
Before:
After:
> Disable the add-to-collection prompt option in the menu

- package.json
> fix(package): update jsdom to version 11.6.1

- package.json
- yarn.lock
> chore: Remove fetch-mock from package

- .stylelintrc
> Disallow random() in SASS

- package.json
> chore: Remove bundlesize devDep

- src/amo/components/Collection/index.js
> fix: Undo FormOverlay test

- src/ui/components/FormOverlay/index.js
- tests/unit/ui/components/TestFormOverlay.js
Fixes https://github.com/mozilla/addons-frontend/issues/4300
> FormOverlay should be closed by default

- src/core/actions/errors.js
- src/core/constants.js
- src/core/errorHandler.js
- src/core/reducers/errors.js
- tests/unit/core/actions/test_errors.js
- tests/unit/core/reducers/test_errors.js
- tests/unit/core/testErrorHandler.js
Fixes https://github.com/mozilla/addons-frontend/issues/4315
> Display generic errors with an error handler

- config/default.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/4313
> Prevent faking invalid config keys in tests

- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
Fixes https://github.com/mozilla/addons-frontend/issues/4322
Fixes https://github.com/mozilla/addons-frontend/issues/4323
> Collection updater: control overlay, fix localized params

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/App/styles.scss
- src/amo/components/Collection/index.js
- src/amo/components/CollectionManager/index.js
- src/core/css/inc/vars.scss
- src/ui/components/FormOverlay/styles.scss
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/4002
Notes:
* This is going to land behind a flag. It will need a lot of follow-ups, like for editing other parts of the collection.
* The mobile styles are happening in https://github.com/mozilla/addons-frontend/issues/4258
> UI to edit collection name and description

- package.json
> fix(package): update base62 to version 1.2.5

- package.json
> fix(package): update base62 to version 1.2.7

- yarn.lock
> Sync yarn.lock with master

- config/test.js
- src/amo/api/collections.js
- src/amo/components/Collection/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/components/CollectionManager/styles.scss
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/api/test_collections.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/amo/sagas/test_collections.js
- tests/unit/core/api/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/4336
Here are some screenshots but keep in mind that I've requested to fix these error messages. See https://github.com/mozilla/addons-server/issues/7547
> UI for editing a collection URL

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- tests/unit/amo/containers/TestHome.js
> March 1 homepage content programming update

- src/amo/components/Addon/index.js
- src/core/components/InstallButton/index.js
- src/core/installAddon.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- src/core/utils/compatibility.js
- src/disco/components/Addon.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/reducers/test_addons.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/containers/TestDiscoPane.js
Fixes #4426 
As noted in the issue, this is a blocker for issue #2757.
> Add a platformFiles map to internal addon object and use it to replace installURLs

- tests/ui/conftest.py
> Fix for discopane ui test errors.

- src/amo/components/Addon/index.js
- src/core/components/InstallButton/index.js
- src/core/installAddon.js
- src/core/utils/compatibility.js
- src/disco/components/Addon.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/amo/components/TestCategory.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestFlagReviewMenu.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestLanguagePicker.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/components/TestSearchForm.js
- tests/unit/amo/components/TestSearchPage.js
- tests/unit/amo/containers/TestApp.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/api/test_index.js
- tests/unit/core/components/TestAuthenticateButton.js
- tests/unit/core/components/TestInstallButton.js
- tests/unit/core/components/TestLoginPage.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/containers/TestDiscoPane.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/4270
I tested locally (AMO and Discopane) and it seems to be working.
> Preserve external tracking source on install

- config/default-disco.js
- config/default.js
- src/disco/api.js
- src/disco/containers/DiscoPane.js
- tests/unit/disco/test_api.js
Issue #4326 
Any thing else needs to done ?
> Rename taarParamsToUse to discoParamsToUse

- src/amo/components/AddonMeta/index.js
- tests/unit/amo/components/TestAddonMeta.js
> fix: Change Reviews to Ratings in detail card

- package.json
- src/amo/components/CollectionManager/index.js
- src/core/utils/index.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/core/utils/test_index.js
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/4375
Before:
After:
> Deal with HTML entities when editing a collection

- src/core/reducers/errors.js
- tests/unit/core/reducers/test_errors.js
Fixes https://github.com/mozilla/addons-frontend/issues/4434
> Do not prefix form errors with field keys

- package.json
> fix(package): update hot-shots to version 5.2.0

- package.json
> chore(package): update babel-jest to version 22.4.1

- package.json
> fix(package): update moment to version 2.21.0

- src/core/components/Paginate/index.js
- tests/unit/core/components/TestPaginate.js
> Fix Paginate so it does not require currentPage

- src/core/components/Paginate/index.js
- tests/unit/core/components/TestPaginate.js
> Fix broken pagination

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- tests/unit/amo/containers/TestHome.js
Fixes #4515 
I created the collections required for the home page on dev to make testing this possible. I guess we'll have to create them on stage as well once this gets pushed there. Is that something QA could do to support testing, or is it something we're required to do?
> 15 March homepage content programing update

- src/amo/components/AddonBadges/index.js
- src/ui/components/Badge/index.js
- src/ui/components/Icon/img/requires-payment.svg
- src/ui/components/Icon/styles.scss
- tests/unit/amo/components/TestAddonBadges.js
- tests/unit/ui/components/TestBadge.js
> Expose payment flag on public listing page

- src/amo/components/Collection/index.js
- src/amo/components/LanguageTools/index.js
- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/ReportUserAbuse/index.js
- src/amo/components/ReportUserAbuse/styles.scss
- src/amo/components/SearchPage/index.js
- src/amo/components/SectionLinks/index.js
- src/amo/reducers/userAbuseReports.js
- src/amo/sagas/index.js
- src/amo/sagas/userAbuseReports.js
- src/amo/store.js
- src/core/api/abuse.js
- src/core/reducers/abuse.js
- src/core/types/api.js
- src/ui/components/DismissibleTextForm/index.js
- src/ui/components/Hero/index.js
- tests/unit/amo/components/TestReportUserAbuse.js
- tests/unit/amo/reducers/test_userAbuseReports.js
- tests/unit/amo/sagas/testUserAbuseReports.js
- tests/unit/amo/test_store.js
- tests/unit/core/api/test_abuse.js
- tests/unit/helpers.js
- tests/unit/ui/components/TestDismissibleTextForm.js
fix #4473
It will be used in the user profile page implemented in #4469.
> feat: Add User Abuse Reports

- package.json
- src/core/api/index.js
- yarn.lock
This will pick up the rule change to turn off the no-await-in-loop rule
> Upgrade eslint-config-amo to v1.7.0

- .circleci/config.yml
Unfortunately circleci doesn't let you test a build that has to run on master until you merge it. My previous PR had some incorrect paths that I didn't know of until it was merged. This should help fix it but I won't really be able to test it until it is on master.
I did walk through the steps within the circleci container via SSH so they should work, but it may be the little nuances of file paths and permissions that we may run into.
> Updated file paths and removed caching.

- .circleci/config.yml
> Fixed rm command within circleci steps.

- .circleci/config.yml
Loading the image within the release jobs needed to be done.
> Fix for release jobs on circleci.

- src/ui/components/Icon/img/permissions/storage.svg
Maybe fixes #4543 
I tested it locally and this new SVG looks the same to me as the old one, but maybe it will fix the issue reported in #4543?
> Recreate the storage icon to see if it addresses a display issue

- src/amo/api/collections.js
- tests/unit/amo/api/test_collections.js
Fixes https://github.com/mozilla/addons-frontend/issues/4567
> API helper to create/update a collection add-on

- src/amo/components/AutoSearchInput/index.js
- src/amo/components/AutoSearchInput/styles.scss
- src/amo/components/SearchForm/index.js
- src/amo/components/SearchForm/styles.scss
- tests/unit/amo/components/TestAutoSearchInput.js
Fixes https://github.com/mozilla/addons-frontend/issues/4562
> Expose AutoSearchInput label, add a position:relative container

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/Header/index.js
- src/amo/components/UserProfile/index.js
- src/amo/components/UserProfile/styles.scss
- src/amo/reducers/users.js
- src/amo/routes.js
- src/core/utils/index.js
- src/ui/components/Card/index.js
- src/ui/components/Card/styles.scss
- src/ui/components/DefinitionList/index.js
- src/ui/components/Icon/styles.scss
- src/ui/components/Rating/index.js
- tests/unit/amo/components/TestUserProfile.js
- tests/unit/amo/reducers/test_users.js
- tests/unit/core/utils/test_index.js
- tests/unit/ui/components/TestRating.js
- tests/unit/ui/components/TestUserAvatar.js
> feat: Add a User Profile page with an info card

- .circleci/config.yml
Should fix  #4604
Tagging chris for review as well.
> Add circleci version 2 config back and update jobs to run on tags.

- src/amo/reducers/addonsByAuthors.js
- src/core/types/addons.js
Fixes https://github.com/mozilla/addons-frontend/issues/4624
> Use a SearchResultAddonType for search results

- .circleci/config.yml
> Add version.json to master release.

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> April 5 homepage content programming update

- src/amo/components/PermissionsCard/permissions.js
> Fix missing plurals for host permission strings

- package.json
> chore(package): update file-loader to version 1.1.11

- package.json
- src/amo/components/AddonReviewListItem/styles.scss
- src/amo/components/App/styles.scss
- src/amo/components/Collection/styles.scss
- src/amo/components/CollectionManager/styles.scss
- src/amo/components/Header/styles.scss
- src/amo/components/Home/styles.scss
- src/amo/components/LanguageTools/styles.scss
- src/amo/components/PermissionsCard/styles.scss
- src/amo/components/SearchFilters/styles.scss
- src/amo/components/StaticPages/StaticPages.scss
- src/core/css/inc/mixins.scss
- src/disco/css/inc/vars.scss
- src/ui/components/Badge/styles.scss
- src/ui/components/Button/styles.scss
- src/ui/components/DefinitionList/styles.scss
- src/ui/components/DismissibleTextForm/styles.scss
- src/ui/components/DropdownMenuItem/styles.scss
- src/ui/components/ExpandableCard/styles.scss
- src/ui/components/FormOverlay/styles.scss
- src/ui/components/HeroSection/styles.scss
- src/ui/components/LoadingText/styles.scss
- src/ui/components/MetadataCard/styles.scss
- src/ui/components/Notice/styles.scss
- src/ui/components/Select/styles.scss
- src/ui/css/vars.scss
> chore(package): update photon-colors to version 3.0.1

- package.json
> fix(package): update react-textarea-autosize to version 6.0.3

- package.json
> chore(package): update webpack-dev-server to version 3.1.1

- src/amo/components/SearchFilters/index.js
- src/amo/components/SearchTools/index.js
- src/amo/components/SectionLinks/index.js
- src/amo/routes.js
- src/core/constants.js
- tests/unit/amo/components/TestSearchTools.js
- tests/unit/amo/components/TestSectionLinks.js
> Tweak to #4597

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
> I4652 - disbales submit button if no name

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
> Fixes I4719 - disable submit if slug blank(edit collection)

- package.json
- src/amo/components/LanguageTools/styles.scss
> fix(package): update react-super-responsive-table to version 4.2.2

- src/amo/components/Addon/index.js
- src/amo/components/AddonCompatibilityError/index.js
- src/core/utils/compatibility.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/core/utils/test_compatibility.js
> feat: Add custom download URLs to `getClientCompatibility()`

- src/disco/constants.js
2 new system extension added to the list
> add new system extension

- src/amo/components/AddAddonToCollection/index.js
- tests/unit/amo/components/TestAddAddonToCollection.js
> Fixes:4755 sort collection by name

- src/amo/components/AutoSearchInput/index.js
- src/core/reducers/autocomplete.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/core/reducers/test_autocomplete.js
> Enhance the AutoSearchInput component to return addonIds

- .travis.yml
> Re-enable ui tests.

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/Collection/index.js
- src/amo/components/CollectionList/index.js
- src/amo/components/CollectionList/styles.scss
- src/amo/components/CollectionManager/index.js
- src/amo/routes.js
- src/core/types/router.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionList.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/helpers.js
- yarn.lock
Fixes #4003 
This is an initial attempt at this, and I know it has a number of issues, but I thought it worth submitting for a look anyway. That way I can respond to feedback rather than trying to guess what's best to do.
Note that I had to build it on top of what's currently in PR #4534, so there are three extra commits in here. For the purposes of reviewing my work for #4003, you can ignore the changes to:
- src/amo/reducers/collections.js
-  src/amo/sagas/collections.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
I will add some additional comments calling out the areas where I still see issues.
> Create a new collection (name, description, URL)

- src/amo/components/PermissionsCard/index.js
> Fixes permission kb article in new tab

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> 26 April Homepage programming update

- locale/fi/LC_MESSAGES/amo.po
> Fix dennis-lint failure on locale/fi/LC_MESSAGES/amo.po

- src/ui/components/Rating/index.js
- tests/unit/ui/components/TestRating.js
> Fix rounding of rating stars

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/AddonMoreInfo/index.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/helpers.js
- tests/unit/core/reducers/test_addons.js
> Remove beta-versions code

- .circleci/config.yml
- tests/ui/run-functional-tests.sh
This should fix the "Timed Out" failures on circleci.
> Fix ui test timeouts

- package.json
> fix(package): update jsdom to version 11.10.0

- package.json
- src/amo/components/App/index.js
- src/amo/utils.js
- tests/unit/amo/test_utils.js
- webpack.prod.config.babel.js
- yarn.lock
> Greenkeeper/base62 2.0.0

- src/amo/components/AddonReviewListItem/index.js
- tests/unit/amo/components/TestAddonReviewListItem.js
> I4880: remove review headers

- tests/ui/run-functional-tests.sh
Forgot that the login tests need another script to run to work correctly. This should fix it.
> Add hostname script to circleci integration test job.

- src/amo/components/CollectionList/index.js
- src/amo/components/CollectionList/styles.scss
this is a potential "fix" /start to this enhancement requested in #4843 (collections list create style enhancement)
note: 
copy here is a placeholder / tbd
regarding styles - I have very basic styles here  - please let me know if this is ok/suggestions:
desktop:
mobile:
@bobsilverberg  @pwalm @muffinresearch
> issue-4843-style-collectionlist/create-style-enhancement

- .eslintrc
- package.json
- src/amo/actions/viewContext.js
- src/amo/components/App/index.js
- src/amo/components/Categories/index.js
- src/amo/components/RatingManager/index.js
- src/amo/reducers/addonsByAuthors.js
- src/amo/reducers/users.js
- src/amo/reducers/viewContext.js
- src/core/actions/index.js
- src/core/constants.js
- src/core/i18n/utils.js
- src/core/reducers/api.js
- src/core/reducers/installations.js
- src/core/types/addons.js
- src/ui/components/DismissibleTextForm/index.js
- src/ui/components/DropdownMenu/index.js
- yarn.lock
> chore(package): update flow-bin to version 0.71.0

- tests/ui/run-functional-tests.sh
This should be the last attempt at this.
> Added hostname script to set correct hostname for integration tests.

- tests/ui/run-functional-tests.sh
> Fix typo within integration test script.

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
fixes #4541 - adds a few more checks for slug before trying to redirect
> i-4541 fixes slug leading dash issue

- src/amo/components/Collection/index.js
- tests/unit/amo/components/TestCollection.js
> Fix server error when navigating back to a collection page

- tests/setup.js
> Use sinon.createSandbox()

- src/amo/components/AddonsByAuthorsCard/index.js
- src/amo/components/UserProfile/index.js
- src/ui/components/Card/styles.scss
- tests/unit/amo/components/TestAddonsByAuthorsCard.js
fixes #4774  - sets up AddsonByAuthorsCard's so header text will be "More xxx by..." by default or can be changed via bool prop to "xxx by.." 
@bobsilverberg @muffinresearch
> issue 4774 addsonauthorscard show/hide More text option

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- tests/unit/amo/containers/TestHome.js
> 10 May homepage content programming update

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/Addon/index.js
- src/amo/components/AddonRecommendations/index.js
- src/amo/reducers/recommendations.js
- src/core/tracking.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonRecommendations.js
- tests/unit/amo/helpers.js
Fixes #4866 
Note that this builds upon the work in PR #4904, so the first two commits can be ignored for the purpose of this review.
Note as well that I have addressed all of the issues raised against PR #4869 and included those changes in this code.
Also note that all of the analytics reporting hasn't been fully figured out yet, but I think the general design of this component is ready for a review. I think the tests could use a bit of polish, but I wanted to submit the code for review now, with the hope of possibly landing it in this week's tag.
> Use taar for recommendations

- locale/ka/LC_MESSAGES/amo.po
- src/ui/components/Rating/index.js
fixes #4972  - this addresses translation bug that came up in a PR :
https://travis-ci.org/mozilla/addons-frontend/jobs/377046751
> I4972 - fixing rating locale bug

- docs/adding-a-pref.md
- docs/moz-addon-manager.md
> Fixing: Add pref xpinstall.signatures.dev-root to docs

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
> Only display add-on recommendations for extensions

- src/amo/components/AddonRecommendations/index.js
- src/core/tracking.js
- tests/unit/amo/components/TestAddonRecommendations.js
- tests/unit/core/test_tracking.js
> Set a custom dimension based on the TAAR Lite cohort of the user

- src/amo/components/Addon/index.js
- src/amo/components/Addon/styles.scss
fixes #4967 - minor nits on get firefox button
@bobsilverberg  or @willdurand - can you please take a look? thanks
> i4967 get ff style update

- src/amo/api/users.js
- src/amo/components/Header/index.js
- src/amo/components/UserProfileEdit/index.js
- src/amo/components/UserProfileEdit/styles.scss
- src/amo/reducers/users.js
- src/amo/routes.js
- src/core/constants.js
- tests/unit/amo/api/test_users.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestUserProfileEdit.js
- tests/unit/helpers.js
Replaces #4870 - Refs #3144
---
This is the first PR for the user profile edition, allowing to change:
- username
- metadata (display name, location, bio, homepage, occupation)
> Add an Edit User Profile page

- src/amo/components/Collection/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/reducers/test_collections.js
Fixes #4834 
Also fixes #4812 
Also fixes #4824
> Use pagination for the list of add-ons that are currently in a collection in edit mode

- .eslintrc
- src/core/api/index.js
- tests/unit/core/api/test_index.js
> Allow to call the API with form data

- src/amo/components/UserProfile/index.js
- src/amo/components/UserProfile/styles.scss
- tests/unit/amo/components/TestUserProfile.js
Fix #4997
Fix #4585 
---
Admin:
Current user (owner):
Logged-out or no permission:
> Add a edit link to user profile page

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
> Fixes 4919: autoflls slug

- src/amo/components/UserProfile/index.js
- tests/unit/amo/components/TestUserProfile.js
> Add user location and occupation on profile page

- src/amo/components/UserProfile/index.js
- tests/unit/amo/components/TestUserProfile.js
> Do not display edit profile link if user is not loaded

- src/amo/components/AddonRecommendations/index.js
- tests/unit/amo/components/TestAddonRecommendations.js
> Add additional custom dimension for recommendations

- src/ui/components/Rating/index.js
- tests/unit/ui/components/TestRating.js
> Fix: updating star rating title

- src/amo/components/UserProfileEdit/styles.scss
Suggesting default full width of biography and resize only vertically
Fixes : #5021
> fixes : 5021

- src/ui/components/DefinitionList/styles.scss
Fixes : #5062 & #4584 
Before:
After:
> fixes 5062 & 4584

- src/amo/components/Addon/index.js
> Fixing : cosmetic changes to non-firefox button

- src/amo/components/Addon/styles.scss
fixes #4967 
firefox browser (~ desktop)
non firefox browser (~ desktop):
> I4967 install btn style adjustments

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> 31 May homepage content programming update

- .eslintrc
- src/amo/api/users.js
- src/amo/components/UserProfile/index.js
- src/amo/components/UserProfileEdit/index.js
- src/amo/components/UserProfileEditPicture/index.js
- src/amo/components/UserProfileEditPicture/styles.scss
- src/amo/reducers/users.js
- src/amo/sagas/users.js
- src/ui/components/UserAvatar/index.js
- tests/unit/amo/api/test_users.js
- tests/unit/amo/components/TestUserProfileEdit.js
- tests/unit/amo/components/TestUserProfileEditPicture.js
- tests/unit/amo/components/TestUserProfilePictureEdit.js
- tests/unit/amo/sagas/test_users.js
- tests/unit/ui/components/TestUserAvatar.js
Fix #4276 – ~⚠️ Depends on #5013 and #5014~
---
> Add new UserProfileEditPicture component

- src/disco/components/Addon.js
- tests/unit/disco/components/TestAddon.js
> I4999 fixes disco pane click on img install issue

- src/amo/reducers/users.js
- tests/unit/amo/reducers/test_users.js
> Index user ID by *lowercase* username in users reducer to avoid lookup misses

- src/amo/components/Collection/index.js
- tests/unit/amo/components/TestCollection.js
Fixes #5022 
Please see the issue for a detailed explanation for why these changes were made.
> Fix problem with edit collection page when reloading the page in the browser

- src/ui/components/Overlay/Overlay.scss
> Change overlay background color

- locale/ka/LC_MESSAGES/amo.po
> fixing locale/bug

- src/amo/components/Addon/index.js
- src/amo/components/Addon/styles.scss
- src/amo/components/AddonsByAuthorsCard/index.js
- src/amo/components/AddonsByAuthorsCard/styles.scss
- src/amo/components/AddonsCard/index.js
- src/amo/components/SearchResult/index.js
- src/amo/components/SearchResult/styles.scss
- src/core/components/InstallButton/index.js
- src/core/constants.js
- src/core/css/inc/vars.scss
- src/core/utils/index.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonsByAuthorsCard.js
- tests/unit/amo/components/TestAddonsCard.js
- tests/unit/amo/components/TestSearchResult.js
- tests/unit/core/components/TestInstallButton.js
- tests/unit/core/reducers/test_categories.js
- tests/unit/core/utils/test_index.js
fixes #5018
fixes #5017 
fixes #5016 
fixes #5015 
fixes #4661 (also some additional notes here about sizes: https://github.com/mozilla/addons-frontend/issues/5018#issuecomment-390280137)
before (desktop):
after (~ desktop):
before    (~ mobile)        |  after (~ mobile)
:-------------------------:|:-------------------------:
before (~desktop):
after (~ desktop):
before    (~ mobile)        |  after (~ mobile)
:-------------------------:|:-------------------------:
> Static theme fixes round1

- package.json
> fix(package): update hot-shots to version 5.6.0

- src/amo/api/users.js
- src/amo/reducers/users.js
- src/amo/sagas/users.js
- tests/unit/amo/api/test_users.js
- tests/unit/amo/reducers/test_users.js
- tests/unit/amo/sagas/test_users.js
Refs #4279
---
Not sure whether I will do everyting in this PR or I will separate the
plumbing and the UI (as I've started here).
> Add reducer/saga/action/api to delete a user account

- src/amo/api/users.js
- src/amo/components/UserProfileEdit/index.js
- src/amo/components/UserProfileEditNotifications/index.js
- src/amo/reducers/users.js
- src/amo/sagas/users.js
- tests/unit/amo/api/test_users.js
- tests/unit/amo/components/TestUserProfileEdit.js
- tests/unit/amo/components/TestUserProfileEditNotifications.js
- tests/unit/amo/reducers/test_users.js
- tests/unit/amo/sagas/test_users.js
Fix #5000 – ~~Depends on #5122~~
---
This PR allows to update user notifications.
> Allow to update user notifications

- src/amo/components/UserProfile/index.js
- src/amo/routes.js
- tests/unit/amo/components/TestUserProfile.js
Close #5132 
---
I have updated the edit profile URL to be consistent with what was initially planned. See also: https://github.com/mozilla/addons-frontend/issues/5132#issuecomment-393854047.
> Fix user profile edit urls

- src/amo/components/UserProfileEdit/index.js
- tests/unit/amo/components/TestUserProfileEdit.js
Fixes: #4998 redirects to user profile page on user profile edit save
> I4998 - redirects to user profile page on user profile save

- locale/kab/LC_MESSAGES/amo.po
---
This PR fixes an issue in a locale file, causing Travis-CI to fail all the builds.
> Fix locale placeholder

- src/amo/components/UserProfileEdit/index.js
- tests/unit/amo/components/TestUserProfileEdit.js
> Fixes 5023: scroll top on eror and notifications

- src/amo/components/RatingManager/index.js
- tests/unit/amo/components/TestRatingManager.js
- yarn.lock
> updating Rating Manager component text for static theme

- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
> rename deleteCollectionBySlug to unloadCollectionBySlug

- src/amo/reducers/recommendations.js
> updating flow type for TAAR recommendation fallback reasons

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- tests/unit/amo/containers/TestHome.js
> June homepage content programming update

- src/amo/components/ReportUserAbuse/index.js
- tests/unit/amo/components/TestReportUserAbuse.js
> Add link in report user abuse UI

- .eslintrc
- src/amo/components/AddonsCard/index.js
- src/amo/components/Collection/index.js
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- src/core/types/addons.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/helpers.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_collections.js
Ref: #4578 
~~Depends on: #5165~~
> Reducer/Saga changes to support updating the notes for a collection add-on

- src/amo/api/users.js
I added flow types for the return values in the user api file
> Fixes #5177

- src/amo/components/RatingManager/index.js
- tests/unit/amo/components/TestRatingManager.js
fixes #3601 
PR #5237 should help with this but here i am addressing the error handling:
basically, i just took this out so it's a little bit more consistent (you can access this page when you're already logged in) - let me know what you think
> I3601 error handling for unknown type in rating manager

- src/amo/components/Home/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> Allow a single section to fails to load on the home page without breaking the home page

- src/amo/components/SearchResult/index.js
- src/amo/components/SearchResult/styles.scss
- tests/unit/amo/components/TestSearchResult.js
Fixes #3890 
Depends on #5240 
Screenshot of collection details page with notes:
> Display comments for collection addons

- package.json
- yarn.lock
This is needed to implement the suggestion at https://github.com/mozilla/addons-frontend/pull/5289#discussion_r195813619. I tried it locally and everything seems fine (although the tests did seem to take longer to run).
> Update jest to 23.1.0

- src/amo/sagas/home.js
- tests/unit/amo/sagas/test_home.js
> Fix the problem with private collections on the home page

- src/amo/components/UserProfile/index.js
- src/amo/components/UserProfile/styles.scss
- tests/unit/amo/components/TestUserProfile.js
Fix #5145
---
This PR adds a title for the bio of a user (if supplied).
> Add missing biography title in user profile

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
fixes #5217 
settimeout was the culprit here :/ but by clearing this out in unmount, this issue goes away
@willdurand / @bobsilverberg, please take a look? :)
> I5217 fixing settimeout memory leak

- src/amo/components/UserProfileEdit/index.js
- tests/unit/amo/components/TestUserProfileEdit.js
> Do not show success message when navigating to a new user profile

- src/core/utils/index.js
- tests/unit/core/utils/test_index.js
> I5304 show version history on static theme

- .eslintrc
- src/amo/components/AddAddonToCollection/index.js
- src/amo/components/AddonReview/index.js
- src/amo/components/AddonReviewList/index.js
- src/amo/components/AddonReviewListItem/index.js
- src/amo/components/AddonsCard/index.js
- src/amo/components/App/index.js
- src/amo/components/AutoSearchInput/index.js
- src/amo/components/RatingManager/index.js
- src/amo/components/SearchResult/index.js
- src/core/components/AuthenticateButton/index.js
- src/ui/components/DismissibleTextForm/index.js
- src/ui/components/FormOverlay/index.js
- src/ui/components/TooltipMenu/index.js
> disabling react/sort-comp globally

- README.md
- jest.config.js
- package.json
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/5367
> Add back typeahead test filtering for Jest 

- src/amo/components/AddonMoreInfo/index.js
- src/core/types/addons.js
- tests/unit/amo/components/TestAddonMoreInfo.js
> Hide last updated date when value is `null`

- src/amo/components/SectionLinks/index.js
- src/amo/routes.js
- tests/unit/amo/components/TestSectionLinks.js
fixes #5150
hey @willdurand / @bobsilverberg , I actually haven't got an android to officially test this (yet - I will look into this) but when I use android in the url, the link doesn't appear. 
Please let me know if you think this is sufficient or if this needs to be tested on an actual android. In the meantime, I will look into an emulator/set up for this..
> I5150 hiding/404ing language tools link on android

- src/amo/components/Category/index.js
- src/amo/components/Home/index.js
- src/amo/components/LandingPage/index.js
- src/amo/components/SearchFilters/index.js
- src/core/utils/index.js
- tests/unit/amo/components/TestCategory.js
- tests/unit/amo/components/TestLandingPage.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/containers/TestHome.js
- tests/unit/core/utils/test_index.js
> I5078 include statictheme in search filter if enabled

- src/amo/components/AddAddonToCollection/index.js
- src/amo/components/CollectionList/index.js
- src/amo/components/CollectionList/styles.scss
- src/amo/components/Header/index.js
- src/amo/reducers/collections.js
- src/amo/routes.js
- src/amo/sagas/collections.js
- src/ui/components/UserCollection/index.js
- src/ui/components/UserCollection/styles.scss
- tests/unit/amo/components/TestCollectionList.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
- tests/unit/ui/components/TestUserCollection.js
Fixes #3142 
~~Depends on PR #5303~~
> List user collections

- .eslintrc
- package.json
- yarn.lock
Fix #2108
---
There are probably edge cases but it works as intented so far, so let's
try in real life, what do you think? :fire:
> Use eslint-plugin-amo

- .prettierignore
- jest.config.js
- package.json
- webpack-common.js
- webpack.dev.config.babel.js
- webpack.l10n.config.babel.js
- webpack.prod.config.babel.js
Fix #5423
---
This should speed up the command a bit, but also allow us to enable Prettier on other files faster.
JS files at the root have been prettier-ized because... we use Prettier on all JS files.
> Add .prettierignore file

- tests/ui/tests/test_discopane.py
Should fix the failures on travis for the discopane ui tests.
> Updated theme test.

- config/stage-amo.js
Refs #5454
---
This PR enables the user profile feature in -stage. We also need #5453.
> Enable user profile feature in -stage

- src/amo/components/UserProfileEditPicture/index.js
- tests/unit/amo/components/TestUserProfileEditPicture.js
> Add accept attribute to file input

- src/amo/components/Collection/index.js
- src/core/constants.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/reducers/test_users.js
> Support allowing collaborators to edit a Mozilla collection

- src/amo/components/SearchResults/index.js
- tests/unit/amo/components/TestSearchResults.js
Fixes https://github.com/mozilla/addons-frontend/issues/5475
> Fix install source on featured search results

- src/amo/components/Header/index.js
- tests/unit/amo/components/TestHeader.js
> Fix link to My Collections when new collections UI is disabled

- src/amo/reducers/reviews.js
- tests/unit/amo/reducers/testReviews.js
> Reset thse byUserId data when adding a new review

- src/amo/actions/reviews.js
- src/amo/components/AddonReviewList/index.js
- src/amo/components/Collection/index.js
- src/amo/components/Search/index.js
- src/amo/components/UserProfile/index.js
- src/amo/reducers/collections.js
- src/amo/reducers/reviews.js
- src/amo/sagas/collections.js
- src/amo/sagas/reviews.js
- src/core/components/Paginate/index.js
- src/core/reducers/search.js
- tests/unit/amo/actions/testReviews.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/components/TestUserProfile.js
- tests/unit/amo/helpers.js
- tests/unit/amo/reducers/testReviews.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/testReviews.js
- tests/unit/amo/sagas/test_collections.js
- tests/unit/core/components/TestPaginate.js
Fix #5413
Fix #1971
---
I decided to tackle https://github.com/mozilla/addons-frontend/issues/1971 in order to fix this issue.
> Fix AddonsCard footer by using/passing page_size from the API

- src/ui/components/ErrorList/index.js
- src/ui/components/Notice/index.js
- tests/unit/amo/components/TestUserProfile.js
- tests/unit/ui/components/TestErrorList.js
- tests/unit/ui/components/TestNotice.js
Fixes https://github.com/mozilla/addons-frontend/issues/5532
> Support Notice button links

- package.json
> fix(package): update react-textarea-autosize to version 7.0.1

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
Refs #5541
---
I decided to keep the feature flag in case something goes really wrong. If everything works as intended, I'll remove the feature flag code in the next tag.
> Enable user profile pages on all envs

- src/amo/components/AutoSearchInput/index.js
- src/amo/components/EditableCollectionAddon/index.js
- src/amo/components/EditableCollectionAddon/styles.scss
- src/amo/components/SearchSuggestion/index.js
- src/amo/components/SearchSuggestion/styles.scss
- src/core/reducers/autocomplete.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/amo/components/TestEditableCollectionAddon.js
- tests/unit/amo/components/TestSearchSuggestion.js
fixes #5277 
BEFORE             |  AFTER
:-------------------------:|:-------------------------:
BEFORE             |  AFTER
:-------------------------:|:-------------------------:
> I5277 hiding static themes default icon

- src/amo/components/CollectionManager/styles.scss
> I5574 fixing focus styles on edit collection form

- src/amo/api/collections.js
- src/amo/api/recommendations.js
- src/amo/api/reviews.js
- src/amo/api/users.js
- src/core/api/abuse.js
- src/core/api/index.js
- src/core/api/languageTools.js
- src/core/api/search.js
- src/disco/api.js
- tests/unit/amo/api/test_collections.js
- tests/unit/amo/api/test_recommendations.js
- tests/unit/amo/api/test_reviews.js
- tests/unit/amo/api/test_users.js
- tests/unit/core/api/test_abuse.js
- tests/unit/core/api/test_index.js
- tests/unit/core/api/test_languageTools.js
- tests/unit/disco/test_api.js
> Rename state param to apiState in callApi()

- src/amo/components/AddonReviewList/index.js
- src/amo/components/SearchResult/index.js
- src/core/types/i18n.js
- src/ui/components/ConfirmButton/index.js
- src/ui/components/HostPermissions/index.js
- src/ui/components/ListItem/index.js
- src/ui/components/UserCollection/index.js
> Better I18nType

- config/default.js
- src/amo/components/Header/index.js
- src/amo/routes.js
- tests/unit/amo/components/TestHeader.js
> Remove the feature flag for user profile pages

- src/amo/components/AddonReviewListItem/index.js
- src/amo/components/AddonReviewListItem/styles.scss
- src/amo/components/UserProfile/index.js
- src/ui/components/UserReview/index.js
- src/ui/components/UserReview/styles.scss
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/amo/components/TestUserProfile.js
- tests/unit/ui/components/TestUserReview.js
Fix #5416
---
This PR introduces a new `UserReview` component to avoid duplicating code.
> Create UserReview component

- src/amo/components/HomeHeroBanner/index.js
> Replace hero sections

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
> Enable new collections UI and features on prod

- src/amo/components/EditableCollectionAddon/index.js
- src/amo/components/EditableCollectionAddon/styles.scss
- tests/unit/amo/components/TestEditableCollectionAddon.js
> EditableCollectionAddon - Replace comment icon with button and only show button when needed

- package.json
- src/amo/components/CollectionManager/index.js
- src/amo/components/CollectionManager/styles.scss
- src/disco/components/Addon/index.js
- src/disco/components/Addon/styles.scss
- yarn.lock
Fix #5155
---
This PR upgrades `react-transition-group` to its major version 2.
> Upgrade react-transition-group

- src/disco/components/DiscoPane/index.js
- src/disco/components/Footer/index.js
- src/disco/utils.js
- tests/unit/disco/components/TestDiscoPane.js
- tests/unit/disco/components/TestFooter.js
- tests/unit/disco/test_utils.js
Fix #5346
---
This PR adds UTM parameters on disco pane links (when possible).
> Add UTM parameters on Disco Pane

- src/amo/components/UserProfileEdit/styles.scss
- src/amo/components/UserProfileEditNotifications/styles.scss
- src/amo/components/UserProfileEditPicture/index.js
- src/amo/components/UserProfileEditPicture/styles.scss
- src/core/css/inc/mixins.scss
- tests/unit/amo/components/TestUserProfileEditPicture.js
Fix #5567 
Fix #5573
---
I have slightly updated the focus style to match the Photon spec: https://design.firefox.com/photon/components/buttons.html#behaviours.
Before:
After:
> Add focus style on upload button and notification checkboxes

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
> I5364 updating about this theme logic

- src/amo/components/Header/index.js
- tests/unit/amo/components/TestHeader.js
> adding manage my submissions under tool

- src/amo/components/Collection/index.js
- src/amo/components/Collection/styles.scss
- tests/unit/amo/components/TestCollection.js
Fixes #5628 
Logged in and creating, before:
Logged in and creating, after: 
Logged out and editing, before:
Logged out and editing, after:
> Hide sort card when creating a collection, and hide collection when not logged in and editing or creating

- src/amo/components/AddonReviewList/index.js
- src/amo/components/AddonReviewList/styles.scss
- tests/unit/amo/components/TestAddonReviewList.js
> I5277 removes default static theme icon from reviews

- src/core/constants.js
> Add warning about changing tracking event categories

- tests/unit/amo/test_store.js
Fix #5614
---
I don't think we can remove the test case for the disco pane yet,
though.
> Remove test case about reducers/store

- src/amo/components/Collection/index.js
- src/amo/components/Collection/styles.scss
- src/amo/components/CollectionSort/index.js
- src/amo/components/CollectionSort/styles.scss
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionSort.js
Fixes #5638 
Depends on #5619 
This only depends on #5619 because I didn't want to have to go back to fix conflicts which I know will exist, so it doesn't really depend on that, but I built it on top of it.
> Create a CollectionSort component

- src/amo/components/Collection/index.js
fixes #5661 (re-centers "Delete this Collection" text)
> I5661-collection btn style fix

- package.json
> fix(package): update helmet to version 3.13.0

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
> Disable the "Save collection" button unless one of the fields in the edit form has been changed

- src/amo/components/AddAddonToCollection/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/components/TestAddAddonToCollection.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/amo/sagas/test_collections.js
> Add an add-on to a new collection

- src/core/components/SurveyNotice/index.js
- src/core/constants.js
- src/ui/components/Notice/index.js
- tests/unit/amo/components/TestAddonRecommendations.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/components/TestSurveyNotice.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/components/TestDiscoPane.js
- tests/unit/helpers.js
- tests/unit/ui/components/TestNotice.js
Fixes https://github.com/mozilla/addons-frontend/issues/5670
> Track interaction with the survey notice for analytics

- src/amo/components/CollectionAddAddon/index.js
- src/amo/components/CollectionAddAddon/styles.scss
- src/amo/components/CollectionManager/index.js
- src/amo/components/CollectionManager/styles.scss
- tests/unit/amo/components/TestCollectionAddAddon.js
- tests/unit/amo/components/TestCollectionManager.js
Fixes #5667 
Note that while the diff is quite large, it's really mostly just moving code from one component to another. I did also take the opportunity to use the new `withUIState` HOC for the new component because it seemed silly to create a new component and still use local state.
> Create a CollectionAddAddon component to extract the display and logic for the AutoSearchInput for adding an add-on to a collection

- src/amo/components/UserProfileEditPicture/index.js
- src/ui/components/Button/index.js
- tests/unit/amo/components/TestUserProfileEditPicture.js
- tests/unit/ui/components/TestButton.js
> Allow a Button to be read only

- src/amo/components/UserProfileEdit/index.js
- tests/unit/amo/components/TestUserProfileEdit.js
Fix #5560
---
Copy: https://docs.google.com/document/d/1nnv1gwiQe5K3tvYXdsA2QmtWKO6XD75aD31V0hoyI_k/edit?ts=5b5600fb
> Update user profile copy

- config/default.js
Fixes https://github.com/mozilla/addons-frontend/issues/5725
> Turn off AMO experience survey

- locale/de/LC_MESSAGES/amo.po
> Fix typo in German translations

- tests/ui/run-functional-tests.sh
> Change permissions for integration-tests job on circleci.

- src/amo/components/StaticPages/About/index.js
> updating link of thunderbird and seamonkey

- src/ui/components/AnimatedIcon/styles.scss
> Add RTL support for AnimatedIcon

- src/disco/components/DiscoPane/index.js
- tests/unit/disco/components/TestDiscoPane.js
> Add/update find more add-ons links on Disco

- tests/ui/run-functional-tests.sh
> Fix user typo for docker-compose command.

- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/amo/components/TestAddonsByAuthorsCard.js
- tests/unit/amo/components/TestApp.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionList.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/amo/components/TestFlagReviewMenu.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestLanguagePicker.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/components/TestSearchPage.js
- tests/unit/amo/components/TestUserProfile.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/api/test_index.js
- tests/unit/core/components/TestAuthenticateButton.js
- tests/unit/core/components/TestInstallButton.js
- tests/unit/core/components/TestSurveyNotice.js
- tests/unit/disco/components/TestDiscoPane.js
- tests/unit/helpers.js
Fixes #5736 
Copy of PR https://github.com/mozilla/addons-frontend/pull/5738 with conflicts solved ;)
cc @willdurand
> renaming fakeRouterLocation helper

- src/amo/components/Routes/index.js
- src/disco/components/Routes/index.js
- tests/unit/amo/components/TestRoutes.js
- tests/unit/disco/components/TestRoutes.js
Fix #5751
---
Added a bunch of new test cases.
> Add tests for Routes components

- config/default.js
> Add az locale

- src/amo/components/UserProfileEdit/index.js
- tests/unit/amo/components/TestUserProfileEdit.js
> Fix login -> log in

- .travis.yml
> Update geckodriver version.

- config/stage-amo.js
> I5801-updating static theme config for stage

- src/amo/actions/reviews.js
- src/amo/reducers/reviews.js
- tests/unit/amo/actions/testReviews.js
- tests/unit/amo/components/TestFlagReview.js
- tests/unit/amo/components/TestFlagReviewMenu.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/reducers/testReviews.js
- tests/unit/ui/components/TestUserRating.js
> Rename denormalizeReview() to createInternalReview()

- webpack-common.js
Fix #3564
---
Diff:
```
master
696K    dist/amo-d65b0bff8cf4360c48f347579274ce16.css                                     
this branch
604K    dist/amo-4af089eec63e1b8a180517cdbb52eb8d.css
```
> Minify CSS

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- tests/unit/amo/components/TestHome.js
Fix #5808 
---
I was not brave enough to refactor the `HomeHeroBanner` code but we might improve things by having an array of data instead of just an array of components:
```js
const sections = [
{
title: i18n.gettext('addon'),
subtitle: i18n.gettext('super addon'),
slug: 'addon-slug',
},
];
```
That would at least help with the `key` prop that has to be updated.
> update home content for August 9th

- locale/az/LC_MESSAGES/amo.po
- locale/az/LC_MESSAGES/disco.po
Machine Translation of locale files for Azerbaijani locale.
App matches already translated strings in other projects in Pontoon and when match is 100% adds it to the po file.
All translations are manually verified.
> [l10n][az] Machine translation for AMO Frontend (manually verified)

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/production.js
- config/stage-amo.js
- tests/unit/amo/components/TestCategory.js
- tests/unit/amo/components/TestHome.js
- tests/unit/amo/components/TestLandingPage.js
- tests/unit/amo/sagas/test_addonsByAuthors.js
Fixes #5799 
I hope we need this only :see_no_evil:
> enabling static themes in prod

- src/amo/components/Addon/index.js
- src/amo/components/LanguagePicker/index.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/amo/components/TestApp.js
- tests/unit/amo/components/TestLanguagePicker.js
- tests/unit/core/components/TestServerHtml.js
- tests/unit/core/components/error-simulation/TestSimulateAsyncError.js
- tests/unit/core/components/error-simulation/TestSimulateSyncError.js
- tests/unit/core/utils/test_errors.js
- tests/unit/ui/components/TestCardList.js
- tests/unit/ui/components/TestShowMoreCard.js
Refs #1104
---
I did not touch the following files:
- `tests/unit/core/testErrorHandler.js`: not easy to convert, next PR
- `tests/unit/ui/components/TestOverlayCard.js`: modified in #5730 
- `tests/unit/ui/components/TestSwitch.js`: to be removed
- `tests/unit/ui/components/TestRating.js`: might conflict with WIP
- `tests/unit/amo/components/TestRatingManager.js`:  might conflict with WIP
- `tests/unit/amo/components/TestLink.js`: next PR
- `tests/unit/core/components/TestInstallSwitch.js`: to be removed
- `tests/unit/core/components/TestAuthenticateButton.js`: next PR
- `tests/unit/core/components/TestInfoDialog.js`: not easy to convert, next PR-
- `tests/unit/disco/components/TestApp.js`: next PR
> Use Enzyme (almost) everywhere

- src/core/components/AuthenticateButton/index.js
- src/disco/components/App/index.js
- tests/unit/amo/components/TestLink.js
- tests/unit/core/components/TestAuthenticateButton.js
- tests/unit/disco/components/TestApp.js
> Use Enzyme (almost) everywhere 2

- src/amo/store.js
- src/core/components/InfoDialog/index.js
- src/core/constants.js
- src/core/installAddon.js
- src/core/reducers/infoDialog.js
- tests/unit/core/TestInstallAddon.js
- tests/unit/core/reducers/testInfoDialog.js
Fix #5861
---
There are issues in the server logs, one of these issues is related to
`InfoDialog`, so I looked at the code and rewrote the reducer to fix the
error correctly.
> Refactor infoDialog reducer

- config/default.js
- src/core/languages.js
> Add support for Interlingua

- tests/unit/core/testErrorHandler.js
Refs #1104
---
One more converted! I converted only one file but it is easier to review.
> Use Enzyme (almost) everywhere 3

- src/core/components/ServerHtml/index.js
- src/core/constants.js
- src/core/i18n/utils.js
- tests/unit/core/components/TestServerHtml.js
- tests/unit/core/i18n/test_utils.js
[WIP]
Fixes #3362
how to approach with scss files, should I import constants from `core/constants` or any better approach
> updating rtl and ltr as constant

- package.json
Fix #5901
---
```
❯ NODE_APP_INSTANCE=amo NODE_ENV=production yarn start
yarn run v1.6.0
$ npm run version-check && better-npm-run --silent node bin/server.js | pino-mozlog
> mozilla-addons-frontend@0.0.1 version-check /Users/william/projects/mozilla/addons-frontend
> bin/version-check.js
{"EnvVersion":"2.0","Fields":{"msg":"Sentry reporting is disabled; Set config.sentryDsn to enable it."},"Hostname":"MacBook-Pro.local","Logger":"amo","Pid":64203,"Severity":4,"Time":"2018-08-09T23:28:47+02:00","Timestamp":1533850127293,"Type":"app.log"}
{"EnvVersion":"2.0","Fields":{"msg":"🔥  Addons-frontend server is running [ENV:production] [APP:amo] [isDevelopment:false] [isDeployed:true] [apiHost:https://addons.mozilla.org] [apiPath:/api/v3]"},"Hostname":"MacBook-Pro.local","Logger":"amo","Pid":64203, …
```
> Silent better-npm-run in yarn start

- src/amo/components/AddonMeta/index.js
- tests/unit/amo/components/TestAddonMeta.js
> Show average star rating

- src/amo/components/SearchFilters/index.js
- src/ui/components/ExpandableCard/index.js
- tests/unit/ui/components/TestExpandableCard.js
> I5552 updating expandable card to use setuistate

- .eslintrc
- src/amo/components/AutoSearchInput/index.js
- src/amo/components/RatingManager/index.js
- src/core/components/AuthenticateButton/index.js
- tests/unit/core/components/TestInstallSwitch.js
- tests/unit/ui/components/TestOverlayCard.js
- tests/unit/ui/components/TestSwitch.js
Fix #968
---
- Rewrite TestOverlayCard with enzyme
- Re-enable the ESLint rule about findDOMNode
> Remove findDOMNode usage

- src/amo/components/CollectionAddAddon/index.js
- tests/unit/amo/components/TestCollectionAddAddon.js
> Use the collection owner when adding an add-on to a collection from the collection edit screen

- src/amo/components/AddonMeta/index.js
- src/amo/components/AddonMeta/styles.scss
- tests/unit/amo/components/TestAddonMeta.js
> Change rating count to review count on add-on detail page

- package.json
> fix(package): update connected-react-router to version 4.4.1

- Dockerfile
Thanks for opening a Pull Request (PR), here's a few guidelines as to what we need in your PR before we review it.
Please delete anything that isn't relevant to your patch.
Once you have met the above requirements please replace this section with a `Fixes #ISSUENUM` linking to the issue fixed by this PR along with an explanation of the changes. Thanks for your contribution!
Upgrade to node 8 per discussions in weekly standup.
> Upgrade node to v8

- src/amo/components/Collection/index.js
- src/amo/components/CollectionAddAddon/index.js
- src/amo/components/CollectionAddAddon/styles.scss
- src/amo/components/CollectionControls/index.js
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionAddAddon.js
- tests/unit/amo/components/TestCollectionControls.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
Fixes #5937
<details>
<summary>New screen in edit mode</summary>
</details>
<details>
<summary>New screen with notice about adding an add-on</summary>
</details>
<details>
<summary>New screen with notice about removing an add-on</summary>
</details>
> Display a notification when an add-on is removed from a collection

- src/amo/components/RatingManager/index.js
- tests/unit/amo/components/TestRatingManager.js
> Rewrite RatingManager tests with Enzyme

- src/amo/components/Collection/index.js
- src/amo/components/CollectionDetailsCard/index.js
- tests/unit/amo/components/TestCollection.js
- tests/unit/amo/components/TestCollectionDetailsCard.js
> Move logic for Collection Details card into its own component

- src/ui/components/MetadataCard/index.js
> Fix key problem with MetadataCard

- src/amo/components/Home/index.js
- tests/unit/amo/components/TestHome.js
> Update home content

- tests/unit/amo/api/test_reviews.js
- tests/unit/amo/components/TestAddonReview.js
- tests/unit/amo/helpers.js
- tests/unit/core/api/test_index.js
- tests/unit/core/reducers/test_api.js
- tests/unit/core/utils/test_index.js
- tests/unit/helpers.js
> Replace signedInApiState with dispatched sign-in actions

- src/amo/components/AddonMeta/index.js
- tests/unit/amo/components/TestAddonMeta.js
> Copy edits for star string in new ratings/reviews panel

- locale/hu/LC_MESSAGES/disco.po
Ref: https://travis-ci.org/mozilla/addons-frontend/jobs/420134915
> Fix dennis-lint failure

- src/amo/components/AddonMeta/index.js
- src/amo/components/RatingManager/index.js
- src/ui/components/Rating/index.js
- src/ui/components/Rating/styles.scss
- src/ui/components/UserRating/index.js
- tests/unit/amo/components/TestAddonMeta.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/ui/components/TestRating.js
- tests/unit/ui/components/TestUserRating.js
Fixes https://github.com/mozilla/addons-frontend/issues/6014
<details>
<summary>Large stars example</summary>
</details>
<details>
<summary>Small stars example</summary>
</details>
> Show loading indicator for rating stars

- src/amo/components/Collection/styles.scss
- src/amo/components/CollectionDetails/index.js
- src/amo/components/CollectionDetails/styles.scss
- src/amo/components/CollectionDetailsCard/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/reducers/collections.js
- src/amo/sagas/collections.js
- tests/unit/amo/components/TestCollectionDetails.js
- tests/unit/amo/components/TestCollectionDetailsCard.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/amo/reducers/test_collections.js
- tests/unit/amo/sagas/test_collections.js
Fixes #5748 
Before (after clicking "Edit this collection"):
After (after clicking "Edit this collection"):
After (after clicking "Edit collection details"):
> Implement improvements to the edit collection flow

- tests/unit/core/components/TestInfoDialog.js
- tests/unit/ui/components/TestDropdownMenu.js
> Fix comments for react-onclickoutside

- src/amo/components/RatingManager/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/6079
> Remove untested, unsupported code for editing reviews against old add-on versions

- config/uitests-amo.js
- package.json
> Update new ui test configjs

- src/amo/components/AddonReviewListItem/index.js
- src/amo/components/AddonReviewListItem/styles.scss
- src/ui/components/UserReview/index.js
- src/ui/components/UserReview/styles.scss
- tests/unit/amo/components/TestAddonReviewListItem.js
Fixes #5924 
Add-on reviews listing before:
Add-on reviews listing after:
User profile before:
User profile after:
> Move rating stars to the top in the add-on review listing

- src/amo/components/AddonReview/styles.scss
- src/ui/components/Overlay/styles.scss
> I6082 ratings overlay style adjustment

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
> Fix notice for non-public add-ons

- src/amo/reducers/collections.js
- src/amo/reducers/users.js
Fixes https://github.com/mozilla/addons-frontend/issues/6102
> Remove delete statements from all reducers

- src/amo/reducers/reviews.js
- tests/unit/amo/reducers/test_reviews.js
> Fix problem with "Deleting" message after deleting a reply

- src/amo/actions/reviews.js
- src/amo/components/AddonReviewList/index.js
- src/amo/components/AddonReviewListItem/index.js
- src/amo/sagas/reviews.js
- src/core/reducers/addons.js
- tests/unit/amo/components/TestAddonReviewList.js
- tests/unit/amo/components/TestAddonReviewListItem.js
- tests/unit/amo/reducers/test_reviews.js
- tests/unit/amo/sagas/test_reviews.js
- tests/unit/core/reducers/test_addons.js
> Deleting a review does not update the number of reviews for the add-on

- src/amo/components/Addon/index.js
- src/core/installAddon.js
- tests/unit/core/test_installAddon.js
> Fix setCurrentStatus() call

- src/amo/components/Addon/index.js
- tests/unit/amo/components/TestAddon.js
Fix #5374
---
A small change to support ther Return to AMO project.
> Send add-on GUID to Firefox install page

- package.json
- yarn.lock
> Remove resolution (fbjs)

- package.json
- src/amo/components/Addon/index.js
- src/disco/components/Addon/index.js
- src/disco/components/DiscoPane/index.js
- tests/unit/amo/components/TestAddon.js
- tests/unit/disco/components/TestAddon.js
- yarn.lock
> Remove spreads in Addon components

- package.json
fixes #6175 
note: I saw this pkg included in node_modules and I don't see this as an issue locally but I think potentially when it's published to gh-pages it could be..
> I6175 fix unmet storybook/react dep issue

- src/amo/components/Home/index.js
- src/amo/components/HomeHeroBanner/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/components/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> Homepage content update 13 September

- config/stage-amo.js
> Enable AMInstallButton on AMO -stage

- src/amo/components/Home/styles.scss
Reverts mozilla/addons-frontend#5974 because of https://github.com/mozilla/addons-frontend/issues/4087#issuecomment-420287061
> Revert "Made homepage more responsive(720-760px width)"

- src/core/components/Root/index.js
> Add StrictMode component

- docs/moz-addon-manager.md
Follow up to https://github.com/mozilla/addons-frontend/issues/6143
> More docs on using example.com to develop mozAddonManager

- package.json
- src/amo/components/UserProfileEdit/index.js
- src/ui/components/Overlay/index.js
- tests/unit/ui/components/TestOverlay.js
- yarn.lock
> I5852 esc key modal

- src/core/components/AMInstallButton/index.js
- tests/unit/core/components/TestAMInstallButton.js
> Fix AMInstallButton for opensearch add-ons

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewCard/styles.scss
- src/amo/components/AddonReviewManager/index.js
- src/amo/components/AddonReviewManager/styles.scss
- src/amo/components/RatingManager/styles.scss
- src/amo/sagas/reviews.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAddonReviewManager.js
- tests/unit/amo/sagas/test_reviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/5944
<details>
<summary>Screencast</summary>
</details>
> Edit a review inline on the listing page

- .eslintrc
- src/core/addonManager.js
- src/core/installAddon.js
- tests/unit/helpers.js
Refs #6164 and #562 
---
I extracted a `getAddonStatus()` because I need it into #6168, but maybe I should just merge both PRs?
> Add flow types on addonManager

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/Header/index.js
- src/amo/components/RatingManager/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/Collection/index.js
- src/amo/pages/CollectionList/index.js
- src/amo/pages/UserProfileEdit/index.js
- src/core/components/AuthenticateButton/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestFlagReviewMenu.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/amo/pages/TestCollectionList.js
- tests/unit/core/components/TestAuthenticateButton.js
> adding withRouter to authenticateButton

- src/core/reducers/addons.js
- src/core/types/addons.js
- tests/unit/core/reducers/test_addons.js
- tests/unit/disco/pages/TestDiscoPane.js
> Remove iconUrl in addon

- src/amo/pages/Addon/index.js
- src/amo/pages/Addon/styles.scss
- src/core/actions/installations.js
- src/core/installAddon.js
- src/core/utils/addons.js
- src/disco/components/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/test_installAddon.js
- tests/unit/core/utils/test_addons.js
- tests/unit/disco/components/TestAddon.js
Fix #6261
---
This is something I was not aware of until today... It is already
available in Disco Pane, so it is mostly mimicking what is there.
> Show install errors on AMO

- src/amo/pages/Addon/index.js
- src/core/components/AMInstallButton/index.js
I am working on a bigger patch that brings flow to disco pane. Doing this made me discover these issues.
> Fix some flow definitions for AMInstallButton

- config/default.js
- config/dev-amo.js
- config/development-amo.js
> I6297 updating hero ab test config to be on

- src/amo/store.js
- src/core/types/store.js
- src/disco/store.js
Fix #6279
---
It is a small step for a better disco app.
> Add flow type to disco store

- .travis.yml
- package.json
fixes #6254 
I am using the following as references:
linter repo: https://github.com/mozilla/addons-linter/blob/master/.travis.yml#L38
storybook deployer ci: https://github.com/storybooks/storybook-deployer#deploying-storybook-as-part-of-a-ci-service
I am not sure if there is more to do
> Storybook gh-pages / adding travis script for this

- src/amo/components/AddonReviewCard/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
> Hide the "Write a review" button if the current user is signed out

- src/core/addonManager.js
- src/core/reducers/addons.js
- src/disco/pages/DiscoPane/index.js
- src/disco/reducers/discoResults.js
- tests/unit/disco/pages/TestDiscoPane.js
- tests/unit/helpers.js
Fixes #6318
---
I also removed some unused code.
> Add flow types to DiscoPane (disco) component

- src/disco/pages/DiscoPane/index.js
- src/disco/reducers/discoResults.js
- tests/unit/disco/reducers/test_discoResults.js
> Change discoResults state from array to object

- src/core/installAddon.js
- src/core/reducers/installations.js
- src/core/utils/addons.js
- src/disco/components/Addon/index.js
- src/disco/pages/DiscoPane/index.js
- tests/unit/disco/components/TestAddon.js
Fixes #6294 
---
The patch for normalizr should hopefully fix more test code. It is hard to recover from the "spread all the properties"-gate.
> Add flow types to Addon disco component

- src/disco/components/Addon/index.js
- src/disco/components/AddonCompatibilityError/index.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/components/TestAddonCompatibilityError.js
> Simplify AddonCompatibilityError disco component

- README.md
- config/default-disco.js
- config/default.js
- config/dev.js
- config/development.js
- config/stage.js
- config/test.js
> removing `enableClientConsole` config parameter

- webpack.prod.config.babel.js
Fixes https://github.com/mozilla/addons-frontend/issues/6352
I confirmed the fix before and after with this command:
```
NODE_APP_INSTANCE=amo NODE_ENV=production yarn build
```
> Fix source maps on hosted servers

- src/amo/components/HomeHeroBanner/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
> 27 September homepage content update

- config/default-amo.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
- config/uitests-amo.js
> Enable new install button on AMO (all envs, including -prod)

- src/amo/reducers/reviews.js
- tests/unit/amo/reducers/test_reviews.js
> Reset the reviews view state when LOCATION_CHANGE is dispatched

- .eslintrc
- src/amo/pages/UserProfileEdit/index.js
- src/core/components/AMInstallButton/index.js
- src/core/components/AuthenticateButton/index.js
- src/ui/components/Button/index.js
- src/ui/components/ConfirmButton/index.js
> I6310 adding flow to btn component

- src/amo/components/AddonReviewCard/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
Fixes #6289 
Thanks for the suggestion in #6289, @kumar303. It seems to have worked well.
> Make review link a Link rather than an <a>

- src/amo/components/AddonReviewCard/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
> Don't show the write a review button unless the user is the creator of the rating

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewCard/styles.scss
- src/amo/components/AddonReviewManager/index.js
- src/amo/components/RatingManager/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAddonReviewManager.js
Fixes #6346 
Here are some screenshots that show some of the changes:
> Minor tweaks to buttons and links in review flow

- src/amo/components/UserProfileEditPicture/styles.scss
> Fix button focus for picture

- src/amo/pages/Addon/index.js
- src/ui/components/ShowMoreCard/index.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/ui/components/TestShowMoreCard.js
fixes #5553 
this component seems so similar to the expandable Card I am wondering if they should be combined...
I also I had a few notes/ questions below : )
> I5553 showmorecard to use setuistate

- README.md
> I6427 adding github pgs link to docs

- config/stage-amo.js
> Enable the new ratings and reviews UI on stage

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewManager/index.js
- src/amo/components/FeaturedAddonReview/index.js
- src/amo/sagas/reviews.js
- tests/unit/amo/components/TestAddonReviewManager.js
- tests/unit/amo/components/TestFeaturedAddonReview.js
- tests/unit/amo/sagas/test_reviews.js
> Editing a developer reply from a permalink is visually awkward

- src/amo/pages/SearchPage/index.js
- src/core/middleware/prefixMiddleware.js
- src/core/server/base.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/core/middleware/test_datadogTiming.js
- tests/unit/core/middleware/test_prefixMiddleware.js
> Use 301 status code in local redirects

- src/amo/components/App/index.js
- tests/unit/amo/components/TestApp.js
Fix #5761
---
This PR adds the locale to each HTML title.
> Add locale to HTML titles

- README.md
> Update docs fro __frontend_version__ endpoint

- package.json
- yarn.lock
Fix #6410
---
We can now see the logs (prettified) in the console, enjoy!
> Upgrade pino-devtools to use --tee option

- src/amo/components/CollectionManager/index.js
- tests/unit/amo/components/TestCollectionManager.js
> I6338 adjusting back functionality on collection cancel

- src/amo/pages/Collection/index.js
- tests/unit/amo/pages/TestCollection.js
> I5928 collection remove pg switch fix

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
Fixes #5914
---
This PR adds a new title to the add-on detail pages.
> Add better title on add-on detail pages

- src/amo/components/HomeHeroBanner/index.js
- src/core/withExperiment.js
- src/ui/components/Hero/styles.scss
- src/ui/components/HeroSection/index.js
- src/ui/components/HeroSection/styles.scss
- tests/unit/amo/components/TestHomeHeroBanner.js
> Add more logging statements and remove CSS for HomeHeroBanner

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
- tests/unit/amo/components/TestRatingManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/6349
> Enable the inline review flow in production

- locale/sl/LC_MESSAGES/amo.po
- locale/zh_TW/LC_MESSAGES/amo.po
Fixes https://github.com/mozilla/addons-frontend/issues/6501
> Fix invalid variable in zh_TW and sl locales

- src/core/actions/installations.js
- src/core/installAddon.js
- src/core/reducers/addons.js
- src/disco/api.js
- src/disco/components/Addon/index.js
- src/disco/pages/DiscoPane/index.js
- src/disco/reducers/discoResults.js
- src/disco/sagas/disco.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/helpers.js
- tests/unit/disco/pages/TestDiscoPane.js
- tests/unit/disco/reducers/test_discoResults.js
- tests/unit/disco/sagas/test_disco.js
- tests/unit/disco/test_api.js
Fixes #6328
~~Depends on #6298~~
~~Depends on #6315~~
~~Depends on #6319~~
---
With the other PRs merged, this will be easier to review! I am sorry for the big diff though, it was waaay smaller until I got stuck with the `tests/unit/disco/components/TestAddon.js` file, which I entirely rewrote with `shallowUntilTarget`.
> Remove normalizr in disco app

- src/core/api/index.js
> Do not log a function

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Better title for search tools

- locale/az/LC_MESSAGES/amo.po
> Fix az locale

- src/amo/components/HomeHeroBanner/index.js
- src/amo/pages/Home/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
> 11 October homepage content update

- src/amo/pages/AddonReviewList/index.js
- tests/unit/amo/pages/TestAddonReviewList.js
Refs #5758
---
We do not want to index those pages, so let's tell robots about it.
> Do not index featured reviews

- bin/loading-page.html
- src/amo/components/Footer/index.js
> adding developer policies to footer

- src/amo/components/AddonAdminLinks/index.js
- tests/unit/amo/components/TestAddonAdminLinks.js
> Do not show a "Content review add-on" link for themes

- config/default.js
- src/core/utils/index.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/pages/TestCategory.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/core/utils/test_index.js
> Remove the static theme flag

- src/amo/components/AddonAdminLinks/index.js
- tests/unit/amo/components/TestAddonAdminLinks.js
> Make sure the "edit add-on" link directs to the correct page for LWTs

- src/amo/pages/Addon/index.js
- src/amo/pages/Collection/index.js
- src/core/reducers/addons.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/core/reducers/test_addons.js
- tests/unit/core/utils/test_index.js
Fixes #4271
---
Send a redirect when an add-on detail slug is not lower case OR a collection username/slug is not lower case.
> Redirect slug

- src/amo/components/AddonAdminLinks/index.js
- tests/unit/amo/components/TestAddonAdminLinks.js
> Make sure that the "review theme" link points to the correct place for LWTs

- src/amo/actions/reviews.js
- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewCard/styles.scss
- src/amo/components/RatingManager/index.js
- src/amo/components/RatingManager/styles.scss
- src/amo/reducers/reviews.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/reducers/test_reviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/6458; fixes https://github.com/mozilla/addons-frontend/issues/6347 (because it only required changing the prompt); fixes https://github.com/mozilla/addons-frontend/issues/6305 (which is irrelevant now)
Read https://github.com/mozilla/addons-frontend/issues/6347 for some known issues -- e.g. where this patch strays from the mocks. I have discussed some discrepancies with Phil but let me know if you have questions.
New screens:
> Simplify the confirm delete UI for reviews / ratings

- tests/ui/run-functional-tests.sh
Should fix the error the job is seeing on circleci.
> Update permissions for integration test circleci job.

- src/amo/components/RatingManager/styles.scss
Fixes #6248 
Reference for Old PR https://github.com/mozilla/addons-frontend/pull/6249
> fixing layout issue for login rate button

- src/amo/components/AddonTitle/index.js
- src/amo/components/AddonTitle/styles.scss
- src/amo/pages/Addon/index.js
- src/amo/pages/Addon/styles.scss
- tests/unit/amo/components/TestAddonTitle.js
- tests/unit/amo/pages/TestAddon.js
> Extract AddonTitle component

- src/amo/components/PermissionsCard/permissions.js
- src/amo/reducers/versions.js
- src/core/installAddon.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- src/core/utils/compatibility.js
- src/core/utils/index.js
- tests/unit/amo/components/TestPermissionUtils.js
- tests/unit/amo/reducers/test_versions.js
- tests/unit/core/reducers/test_addons.js
- tests/unit/core/test_installAddon.js
- tests/unit/core/utils/test_compatibility.js
- tests/unit/core/utils/test_index.js
- tests/unit/disco/components/TestAddon.js
> Update the versions reducer to use the correct file

- src/amo/reducers/collections.js
- tests/unit/amo/reducers/test_collections.js
> Make sure internal collections have a string value

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Add an Android version of the page title for detail pages

- package.json
- src/core/i18n/utils.js
- tests/unit/core/i18n/test_utils.js
- yarn.lock
> Create a formatFilesize utilitiy which deals with i18n

- src/amo/components/AddonAdminLinks/index.js
Fixes #6607 
@wagnerand and/or @jvillalobos Could one of you please review this? I made a best guess at what each of these links are for, but I could very well be wrong about some or all of them.
> Provide translation hints for add-on admin links

- src/amo/components/AddonHead/index.js
- src/amo/pages/Addon/index.js
- src/core/utils/addons.js
- tests/unit/amo/components/TestAddonHead.js
- tests/unit/amo/pages/TestAddon.js
Fixes #6647
---
Except 2 or 3 `invariant` statements, code has been moved without modification.
> Extract AddonHead component

- src/ui/components/DismissibleTextForm/styles.scss
> Limit max height for review entry form

- src/amo/reducers/versions.js
- tests/unit/amo/reducers/test_versions.js
> Store versions by id in the versions reducer state

- src/amo/components/AddonSummaryCard/index.js
- src/amo/components/AddonSummaryCard/styles.scss
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/AddonReviewList/styles.scss
- tests/unit/amo/components/TestAddonSummaryCard.js
- tests/unit/amo/pages/TestAddonReviewList.js
> Create an addon-summary card to use on the Review Listing and All Versions pages

- bin/build-locales
- config/default.js
- jest.config.js
- tests/unit/bin/test_build-locales.js
- tests/unit/test_config.js
Refs #1515 
Fixes #6623
---
(see the updated date in the left column)
(see the updated date in the left column)
> Add moment locale mapping

- src/amo/components/AutoSearchInput/index.js
- tests/unit/amo/components/TestAutoSearchInput.js
> Fix label on AutoSearchInput

- src/amo/components/SearchForm/index.js
- tests/unit/amo/components/TestSearchForm.js
> Add role="search" to the SearchForm

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewCard/styles.scss
- src/amo/components/AddonReviewManager/index.js
- src/amo/components/AddonReviewManager/styles.scss
- src/amo/components/AddonReviewManagerRating/index.js
- src/amo/components/AddonReviewManagerRating/styles.scss
- src/amo/components/RatingManager/index.js
- src/amo/components/RatingManager/styles.scss
- tests/unit/amo/components/TestAddonReviewManager.js
- tests/unit/amo/components/TestAddonReviewManagerRating.js
- tests/unit/amo/components/TestRatingManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/6577
**Before**
<hr/>
**After**
**Small screens (mobile)**
> Show small stars in delete review / rating prompts

- src/amo/components/AddonAdminLinks/index.js
> Provide translation hint for admin link

- src/amo/pages/UserProfileEdit/index.js
- src/amo/reducers/users.js
- tests/unit/amo/pages/TestUserProfileEdit.js
- tests/unit/helpers.js
> Use FxA link from the API

- bin/loading-page.html
- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
> Remove report trademark abuse link and redirect legal link

- config/default-disco.js
- config/default.js
- config/test.js
- package.json
- src/core/constants.js
- src/core/logger.js
- src/core/middleware/requestId.js
- src/core/server/base.js
- tests/unit/core/middleware/test_requestId.js
- yarn.lock
Fixes #6537
---
This should work.
> Pass correlation ID to the logger (amo_request_id)

- src/core/store.js
- tests/unit/core/test_store.js
Fixes https://github.com/mozilla/addons-frontend/issues/6722
I think this will be useful. Example:
> Use a minimal Redux logger during development on the server

- src/amo/components/AddonsByAuthorsCard/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/UserProfile/index.js
- src/amo/reducers/addonsByAuthors.js
- src/amo/sagas/addonsByAuthors.js
- tests/unit/amo/components/TestAddonsByAuthorsCard.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestUserProfile.js
- tests/unit/amo/reducers/test_addonsByAuthors.js
- tests/unit/amo/sagas/test_addonsByAuthors.js
> Pass author IDs to AddonsByAuthorsCard

- package.json
- src/core/logger.js
- yarn.lock
> Upgrade express-http-context

- src/core/components/AMInstallButton/index.js
- tests/unit/core/components/TestAMInstallButton.js
> I6718 AMInstall button label

- src/amo/components/AddonTitle/index.js
- tests/unit/amo/components/TestAddonTitle.js
> I6715-AddonTitle update

- src/amo/components/CategoryHead/index.js
- src/amo/pages/Category/index.js
- src/amo/types/categories.js
- tests/unit/amo/components/TestCategoryHead.js
- tests/unit/amo/pages/TestCategory.js
> Extract a CategoryHead component

- src/amo/components/CategoryHeader/index.js
- src/amo/components/CategoryHeader/styles.scss
- src/amo/components/CategoryIcon/index.js
- tests/unit/amo/components/TestCategoryHeader.js
Fixes #6741
~~⚠️ Depends on #6739~~
---
This PR updates the `CategoryHeader` according to the new-ish mock-ups in the issue linked above.
> Update category page header

- src/amo/api/users.js
- src/amo/reducers/users.js
- src/amo/sagas/users.js
- src/core/types/sagas.js
> Add Flow types to the user saga

- src/amo/components/AddAddonToCollection/index.js
- src/amo/components/AddonRecommendations/index.js
- src/amo/components/AddonReview/index.js
- src/amo/components/AddonsByAuthorsCard/index.js
- src/amo/components/App/index.js
- src/amo/components/Categories/index.js
- src/amo/components/CollectionAddAddon/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/components/FeaturedAddonReview/index.js
- src/amo/components/RatingsByStar/index.js
- src/amo/components/Search/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/Category/index.js
- src/amo/pages/Collection/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/pages/UserProfile/index.js
- src/core/installAddon.js
- src/ui/components/Overlay/index.js
- src/ui/components/ShowMoreCard/index.js
- tests/unit/amo/components/TestFeaturedAddonReview.js
- tests/unit/amo/pages/TestCategory.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/ui/components/TestOverlay.js
Fixes #6188
---
~~I don't know if I can remove all of them yet, so let's do this step by step. I start with the "easy" ones.~~ After this patch, only 3 `componentWillReceiveProps()` calls remain but there is one open issue for each occurrence.
> Remove componentWillReceiveProps() calls

- src/amo/components/RatingManager/index.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Update Addon to use a version stored in the versions redux state

- src/amo/pages/Collection/index.js
- src/amo/pages/Home/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/pages/LanguageTools/index.js
- src/amo/pages/SearchTools/index.js
- src/amo/pages/StaticPages/About/index.js
- src/amo/pages/StaticPages/ReviewGuide/index.js
- src/amo/pages/UserProfile/index.js
- tests/unit/amo/pages/StaticPages/TestReviewGuide.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/pages/TestLanguageTools.js
- tests/unit/amo/pages/TestSearchTools.js
- tests/unit/amo/pages/TestUserProfile.js
> Add last "description" meta tags

- src/core/types/addons.js
- tests/unit/amo/components/TestContributeCard.js
- tests/unit/helpers.js
> Update contributions_url type

- src/amo/pages/Addon/index.js
> Remove `componentWillReceiveProps()` in `Addon`

- src/amo/components/PermissionsCard/index.js
- src/amo/components/PermissionsCard/permissions.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/components/TestPermissionUtils.js
- tests/unit/amo/components/TestPermissionsCard.js
- tests/unit/amo/pages/TestAddon.js
> Update permissions code to use information from a version rather than an addon

- src/amo/components/AddonMoreInfo/index.js
- src/amo/reducers/recommendations.js
- src/amo/reducers/versions.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/reducers/test_versions.js
> Code to support AddonMoreInfo with internal version

- src/amo/components/HomeHeroBanner/index.js
- src/amo/pages/Home/index.js
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- src/core/reducers/versions.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/sagas/test_home.js
- tests/unit/core/reducers/test_versions.js
Fixes #6790
---
See this Google doc: https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#
ℹ️ there is more code that expected because I decided to keep the "trending extensions" code and introduce a boolean flag like the one we have for featured themes (I also fixed an edge case related to that, hence the changes in the `versions` and `home` reducers).
> Update homepage: November 8, 2018

- config/default-disco.js
- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/core/components/AMInstallButton/index.js
- src/core/components/AMInstallButton/styles.scss
- tests/unit/core/components/TestAMInstallButton.js
Fixes #6144
---
Only enabled in -dev for now.
> Setup a/b experiment: install button color

- src/disco/components/Footer/index.js
- tests/unit/disco/components/TestFooter.js
> Change policy link in disco pane

- README.md
- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/HomeHeroBanner/index.js
- src/core/components/AMInstallButton/index.js
- src/core/withExperiment.js
- tests/unit/core/components/TestAMInstallButton.js
- tests/unit/core/test_withExperiment.js
> Use camelcase for experiment/cookie names

- src/amo/components/HeadLinks/index.js
- tests/unit/amo/components/TestHeadLinks.js
> Only self-canonicalized pages must have hreflang
