mozilla/addons-frontend

.eslintignore
.jscsignore
.jscsrc
.travis.yml
README.md
package.json

I changed the tasks for lint + jscs because I think it makes sense to only use the `command:foo` format when we're specifying a sub-target. E.g. I think that's more undertandable particularly when coming from something like the grunt world.
Also I've added a table showing the command list to the README.

Rename lint + style scripts

---

package.json
src/core/server/base.js

Fixes #10
This adds CSP and other useful security headers. We'll need to tweak the config as we go.

Set up security headers

---

.eslintrc
bin/server.js
bin/version-check.js
config/karma.config.js

let and const preferred over var

---

package.json
src/core/reducers/addons.js
src/search/actions/index.js
src/search/client.js
src/search/components/App.js
src/search/components/SearchPage.js
src/search/containers/CurrentSearchPage.js
src/search/reducers/search.js
test-runner.js
tests/core/reducers/test_addons.js
tests/search/components/TestSearchForm.js
tests/search/components/TestSearchPage.js
tests/search/containers/TestCurrentSearchPage.js
tests/search/reducers/test_search.js

This probably still needs some cleanup. Fixes #8.

Redux with stub data (fixes #8)

---

package.json

Add clean-script

---

Dockerfile

I ran into a 'not a directory' error when building the docker image in our jenkins environment. Based on the documentation adding a forward slash resolved the issue [1]
[1] https://docs.docker.com/engine/reference/builder/#add

Add forward slash to directory destination when using ADD

---

package.json
src/config/webpack.prod.config.babel.js

Changes in 4.0.0 (removal of the main entry) mean we now require aliasing.

Add alias for normalize.css

---

src/config/index.js
src/core/api/index.js
src/core/containers/App.js
src/disco/components/hello-world.js
tests/core/containers/TestApp.js
tests/disco/components/test-hello-world.js
tests/search/components/TestSearchResults.js
tests/search/test_store.js

100% coverage

---

src/core/utils.js
src/search/components/SearchResult/index.js
src/search/components/SearchResult/style.scss
src/search/components/SearchResults.js
src/search/containers/AddonPage/index.js
src/search/containers/AddonPage/style.scss
src/search/css/SearchResults.scss
tests/karma/search/components/TestSearchResult.js
tests/karma/search/containers/TestAddonPage.js

Show more info about add-ons on the search results and detail pages.
> Search results
> Add-on detail
Fixes #166.

Include more add-on data

---

src/core/api/index.js
src/core/components/NotFound.js
src/search/actions/index.js
src/search/containers/AddonPage/index.js
src/search/containers/CurrentSearchPage.js
src/search/reducers/search.js
tests/karma/core/api/test_api.js
tests/karma/core/components/TestNotFound.js
tests/karma/search/actions/test_index.js
tests/karma/search/containers/TestAddonPage.js
tests/karma/search/containers/TestCurrentSearchPage.js
tests/karma/search/reducers/test_search.js

Renders a not found page for add-ons and just shows "no results" when you ask for a page that is past the result set. The search endpoint should probably still return the count though and then we'd be able to figure out that they've gone too far, currently it 404s though.
>  Add-on detail not found
> Search last page and last page + 1 (ignore the pagination bug, see #200)
Fixes #165.

Render a not found page when add-on isn't loaded

---

src/core/components/Paginate/index.js
tests/karma/core/components/TestPaginate.js

This fixes an off-by-one error that happened with some page sizes. I refactored the code in hopes of making it more straightforward by defining the different cases instead of having them mixed together in some `Math` function calls.
Fixes #200.

Don't show inaccessible page numbers in some cases

---

src/disco/server.js
src/disco/store.js

Fixes #214 
There's no reducers yet but this starts us off with a basic store so that the server doesn't blow up.

Add a createStore function to disco pane

---

src/config/webpack.dev.config.babel.js

Fixes `Cannot use [chunkhash] for chunk in 'search-[name]-[chunkhash].js' (use [hash] instead)` error in dev server

Fix chunkhash warning in dev webpack config

---

src/config/index.js

Reverts mozilla/addons-frontend#261
Need to revert this since it's not in node. We should be able to workaround it with a polyfill but to un-break things I'll revert for now.

Revert "Use includes in place of indexOf"

---

src/config/index.js

This should make https://discovery.addons-dev.allizom.org/ look a bit nicer since CSP is currently blocking the images.

Temporary fix for cdn images

---

src/core/server/base.js

Don't set SRI in dev, only throw when missing in production.
r? @muffinresearch

Only require SRI in production

---

config/custom-environment-variables.json
config/development.js
tests/server/TestConfig.js

Fixes #297
This config explicitly say what config options can be overriden with env vars. I've set-up `SERVER_HOST` and `SERVER_PORT` envvars to override the config values `serverHost` and `serverPort`.
_Note: that the way node-config works the envvars setup this way will override all other config._
@jasonthomas r?  Let me know if there's any other env vars you need.

Add customizable env vars

---

.eslintrc
package.json
src/core/containers/ServerHtml.js
src/core/server/base.js
src/disco/containers/App.js
src/disco/server.js
src/search/containers/App.js
src/search/server.js
tests/client/core/containers/TestServerHtml.js
tests/client/disco/containers/TestApp.js
tests/client/search/containers/TestApp.js

Fixes #270 
Fixes #255
Fixes #248
* Moves to using JSX for the HTML
TODO: As a follow-up will need to wrap the search code when login is required in the App component so that it gets the App title.

Refactor HTML for apps

---

package.json
src/disco/components/Addon.js
src/disco/containers/DiscoPane.js
src/disco/css/Addon.scss
src/disco/css/App.scss

Fixes #313
Fixes #315 
Fixes #316 
* Adds a basic header outline and a placeholder for the video.
* Fixes spec on addons (mainly width due to box-sizing) and a few other tweaks.
* Fix background colour of page
* Fix background to image (this will need ux looking at it because it looks to be too low contrast)
Future TODOs
* We need more specific spec for the header fonts etc.
* The video part should be split out into a separate component but we have an issue for dealing with that.
* I've not got into handling responsive content just yet as we need a spec to know what we're aiming for and the desired behaviour. 
* RTL
I'll file separate issues for any of these bits that we don't already have issues for.

Add header + fix spec

---

webpack.prod.config.babel.js

Fixes #328 
Also the built files are a bit smaller now. 233k vs 311k in disco pane for example.

Define NODE_ENV=production in webpack's prod config

---

src/disco/client.js
src/disco/components/InstallButton.js
src/disco/constants.js
src/disco/css/InstallButton.scss
tests/client/disco/components/TestInstallButton.js

Fixes: #259
Sets-up the UI for the various installation states
Download progress works via generated attribute selectors. We'll need to see how this works in practice - if the perf is bad or we want to reduce the stylesheet weight we could look to manipulating the style properties (not style attributes) via the DOM directly as this won't cause any problems with CSP.
I left out cancelled and error states because it's unclear if we're going to need them on this component. If we need them we can add them in later.

Install button states

---

config/default.js
config/dev.js
config/development.js
config/stage.js

Fixes #334
Using constants to try and keep things DRY in lieu of the deferred config values.

Eliminate deferred config values

---

config/default.js
config/dev.js
config/development.js
config/stage.js
src/core/api/index.js
src/core/components/LoginPage/index.js
src/core/server/base.js
src/search/containers/AddonPage/index.js
tests/client/core/api/test_api.js
tests/client/core/components/TestLoginPage.js
tests/client/search/containers/TestAddonPage.js

This uses the new internal search endpoint and pulls the URLs from its response.
This fixes a regression from removing the deferred config that caused `API_HOST` to not be able to change the value of `apiBase`.
Fixes #184.

Get URLs from search API

---

src/disco/components/Addon.js
src/disco/constants.js
src/disco/css/Addon.scss
src/disco/css/inc/vars.scss
src/disco/fakeData.js
src/disco/themePreview.js
tests/client/disco/TestThemePreview.js
tests/client/disco/components/TestAddon.js

Adds theme preview on hover and focus. 
Focus styles will need UX input and they probably should be customised and toned down in this specific application.
Fixes #317

Add theme preview

---

config/default.js
karma.conf.js
package.json
src/disco/css/InstallButton.scss
src/disco/img/tick.svg
webpack-isomorphic-tools-config.js
webpack.dev.config.babel.js
webpack.prod.config.babel.js

This results in the svg being inlined which I think is OK for something so small but we can always push it outside the CSS if we think mobile perf is negatively impacted.
Before:
After:

Add tick as svg

---

package.json
src/client-config.js
tests/client/test_client_config.js

Fixes #356
This also means the API for client config now should match node-config.

Remove footgun from client-config module

---

src/disco/addonManager.js
src/disco/constants.js
tests/client/disco/TestAddonManager.js

Add lib to wrap mozAddonManager

---

docs/adding-a-page.md
docs/index.md
src/core/api/index.js
src/core/reducers/addons.js
src/core/reducers/authentication.js
src/core/reducers/users.js
src/search/actions/index.js
src/search/containers/UserPage/index.js
src/search/containers/UserPage/styles.scss
src/search/routes.js
src/search/store.js
tests/client/core/api/test_api.js
tests/client/core/reducers/test_authentication.js
tests/client/core/reducers/test_users.js
tests/client/search/TestUserPage.js
tests/client/search/test_store.js

One commit with some documentation, one with the page that I made while writing the documentation. That might be weird that the page already exists so you can't really follow it but we'll probably want something like this so I included it.

Document adding pages

---

config/default.js
src/disco/components/Addon.js
src/disco/fakeData.js

Get imageURL and themeURL from data

---

src/disco/containers/InstallButton.js
src/disco/css/InstallButton.scss
tests/client/disco/containers/TestInstallButton.js

Fixes #355 Fixes #354
This makes it possible for a keyboard user to focus and interact with the install button checkboxes.
Notes: You can tab to the buttons and it should be focussed as per the styles above. Hitting spacebar interacts with it which is the same for a normal checkbox.
I'll file some separate bugs re: reflecting the state of the install better for AT users.

Interact with install buttons with keyboard only

---

test-runner.js
tests/client/core/api/test_api.js
tests/client/core/containers/TestHandleLogin.js
tests/client/disco/TestAddonManager.js
tests/client/init.js
tests/client/search/TestUserPage.js
tests/client/search/containers/TestAddonPage.js

Use sinon sandboxes by default

---

tests/client/core/api/test_api.js
tests/client/disco/TestAddonManager.js
tests/client/helpers.js
tests/client/search/containers/TestAddonPage.js

If we check for unexpected success using the the resolve callback in the `then` when it throws the tests will catch it (bypassing the reject callback) as long as the test returns the promise. 
This seems more ideal than assuming the catch's assertion will fail because of the unexpected success.
What do you think?

Clean up assert.fail usage

---

.babelrc
.eslintrc
README.md
config/default.js
locale/templates/LC_MESSAGES/disco.pot
locale/templates/LC_MESSAGES/search.pot
package.json
src/core/client/config.js
src/core/components/NotFound.js
src/disco/components/Addon.js
src/disco/containers/DiscoPane.js
src/search/components/SearchResult/index.js
src/search/components/SearchResults.js
webpack.l10n.config.babel.js
webpack.prod.config.babel.js

Fixes #418 
* Uses sprintf-js for placeholder subs 
* I forked babel-gettext-extractor and patched it for the following:
* 🐃  Fix for undefined translation keys which is what caused the empty output see https://github.com/muffinresearch/babel-gettext-extractor/commit/54991908110858db6f545dec9907fe2672293904
* 🐃 Fix for lack of content output idempotency. This is done by key sorting (which is a bit of a hack) but looks to work in practice. See https://github.com/muffinresearch/babel-gettext-extractor/commit/f0f00b2afb71cba5edfb43d377bde9e1b08cdb46
* Made the creation date dynamic
* Used a babel plugin for dedenting template literals so it gets pre-processed and is therefore correct in the translation.
Next up building some locales with the templates and using them...
Obviously we'll need …

Extract locale data

---

src/disco/routes.js

This just adds a route that matches the disco pane format. We'll actually use the locale in #147.
Fixes #306.

Support the disco pane URL format

---

bin/debug-locales
config/default.js
locale/dbg/LC_MESSAGES/disco.po
locale/dbg/LC_MESSAGES/search.po
locale/dbg_rtl/LC_MESSAGES/disco.po
locale/dbg_rtl/LC_MESSAGES/search.po

Create debug locales

---

config/default-disco.js
tests/server/TestCSPConfig.js
tests/server/TestFrameGuardConfig.js

Fixes #433
* x-frame-options *are* ignored (even if set to DENY) so there's no need to override them for the disco pane
* Setting just the protocol `about:` instead of `about:addons` appears to work modifying the directive via charles.

Relax frame-ancestors to just about: protocol for disco pane

---

Dockerfile
src/core/server/base.js

Fixes https://github.com/mozilla/addons-frontend/issues/321
r?

Add __version__ endpoint

---

config/default.js
tests/server/TestLocalesConfig.js

Add hsb and dsb to the config and test for orphaned locales

---

package.json
src/core/client/base.js
src/core/containers/ServerHtml.js
webpack.prod.config.babel.js

Fixes #458
* Builds all the locales into separate js files
* Excludes the bundles if it's not for a relevant app (this was the hardest part) see the ContextReplacementPlugin bit
* Excludes the bundles being output on the page by the server html since webpack does that bit itself.
* Webpack automatically loads the localization via jsonp.

Fix l10n bundling

---

src/disco/components/Addon.js
src/disco/containers/InstallButton.js
src/disco/fakeData.js
src/disco/themePreview.js
tests/client/disco/containers/TestInstallButton.js
tests/client/helpers.js
webpack.dev.config.babel.js

I'm cheating by always setting the theme to installed but I haven't been able to dig into whether or not it tells us if it worked or not. I'm guessing there's no way to tell but maybe some sort of event happens.
Fixes #461.

Install and uninstall themes

---

README.md
bin/extract-locales
package.json

Add an extraction script near to the rest of the l10n scripts that aliases the npm command.

Alias extract-locales

---

bin/merge-locales

Add merge locale script

---

src/disco/containers/DiscoPane.js
src/disco/css/Addon.scss
src/disco/css/App.scss
src/disco/css/inc/vars.scss

Add the link to amo as per #407
* There was no detailed spec for this but I'm happy to tweak this PR to whatever the details need to be.
@pwalm Currently the hover is a lightened version of the background color I grabbed from the docs. Let me know what the exact colours + paddings etc should be and I can update this PR or we can do that separately if you need more time since we need to get this string in to be localized.

Add link to page

---

src/disco/containers/DiscoPane.js
src/disco/css/Addon.scss
src/disco/css/App.scss
src/disco/css/inc/vars.scss

Will need to take another look when we have RTL editorial.
Also fixes a regression in the video display caused by the addition of the AMO link.
Before:
After:

First pass at improving RTL styles

---

src/disco/css/App.scss

Don't go more narrow than 680px

---

src/core/actions/index.js
src/core/api/index.js
src/core/reducers/api.js
src/core/server/base.js
src/disco/api.js
src/disco/store.js
tests/client/core/actions/test_index.js
tests/client/core/api/test_api.js
tests/client/core/reducers/test_api.js
tests/client/disco/test_api.js

We discussed pulling the lang from the state instead of `html[lang]` on the client but using the attribute is pretty straightforward and taking it from state means we should be checking `initialState && initialState.api && initialState.api.lang || config.get('defaultLang')` which seems crazy. We could of course just use it but that seems like it could bite us.
Fixes #147.

Use the user's lang in API requests

---

src/disco/css/App.scss

I don't know why only half of the margin is required, but it is.
> Before
> After
Fixes #493.

Centre the content in about:addons

---

src/disco/containers/DiscoPane.js

Without this the page won't load since it isn't on `discovery.addons.mozilla.org`.

Open see more add-ons in new tab

---

bin/create-locales
bin/debug-locales
docs/i18n.md
docs/index.md

Fixes #417
* Unifies all the locale commands to require `NODE_APP_INSTANCE`
* Adds docs for the commands

Add docs for i18n and unify debug-locales to run per app

---

config/stage-disco.js

Updated to match https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/stage/settings.py#L11. Currently CSP failures causing assets not to load on https://discovery.addons.allizom.org/.
r?

Update amoCDN for disco stage config

---

config/default-disco.js
config/default.js
config/dev-disco.js
config/development-disco.js
config/stage-disco.js
src/core/containers/ServerHtml.js
src/core/server/base.js
src/core/tracking.js
src/disco/client.js
src/disco/constants.js
src/disco/containers/InstallButton.js
tests/client/core/containers/TestServerHtml.js
tests/client/core/test_tracking.js
tests/client/disco/containers/TestInstallButton.js
tests/server/TestCSPConfig.js

Fixes #41 
* Adds tracking lib 
* Uses async setup as per GA docs
* Adds CSP config (we might need more than this if beacons go to other hosts).
* preventDefault added (I was seeing 2 beacons fired) this probably meant installs were kicked off twice too.
* adds the install and uninstall events.

Add tracking to disco pane

---

src/disco/api.js
src/disco/components/Addon.js
src/disco/containers/InstallButton.js
src/disco/reducers/installations.js
tests/client/disco/containers/TestInstallButton.js
tests/client/disco/reducers/test_installations.js
tests/client/disco/test_api.js

Use guids for keys instead of slugs

---

src/disco/containers/InstallButton.js
tests/client/disco/containers/TestInstallButton.js

Fixes up 'invalid' used as eventAction and adds more tests to cover that part of the code to make sure events are fired correctly.

Fix tracking and add tests

---

src/disco/css/App.scss
src/disco/css/inc/vars.scss

Fixes #489
Only real difference to the spec is that I used a larger L+R padding since the min-width is exceeded in this use-case. 
Setting to 1em looks balanced to me - but happy to update if needed.
This was the specced version with 8px.
I went with 1em (14px):

Update button to spec

---

src/disco/addonManager.js
src/disco/components/Addon.js
src/disco/containers/DiscoPane.js
tests/client/disco/TestAddonManager.js
tests/client/disco/components/TestAddon.js
tests/client/disco/containers/TestDiscoPane.js
tests/client/helpers.js

Changes the addon manager to not be a class.

Refactor addon manager

---

src/core/reducers/addons.js
src/disco/api.js
src/disco/constants.js
tests/client/core/reducers/test_addons.js
tests/client/disco/components/TestAddon.js
tests/client/disco/test_api.js

Fixes a bug where the theme install state would stay installed when it is disabled. Refreshing the page will update theme buttons to the correct state.
The reducer now normalizes `persona` to `theme` since that's what Firefox uses.

Use theme instead of persona for theme type

---

src/disco/components/Addon.js
src/disco/components/InstallButton.js
src/disco/constants.js
src/disco/css/Addon.scss
src/disco/reducers/installations.js
tests/client/disco/components/TestAddon.js
tests/client/disco/components/TestInstallButton.js
tests/client/disco/reducers/test_installations.js
tests/client/helpers.js

I had a little animation on the overlay at first but getting it to animate out was tricky so I removed it. It appears quite abruptly so we should probably add something but I'll let @pwalm say what. Maybe worth noting that I barely missed the close button there and it didn't register my click. I guess we should make that clickier.
> No animation
> In animation
Fixes #395.

Use error overlay for errors (fixes #395)

---

src/disco/addonManager.js
src/disco/components/Addon.js
src/disco/components/InstallButton.js
src/disco/constants.js
src/disco/containers/DiscoPane.js
src/disco/reducers/installations.js
tests/client/disco/TestAddonManager.js
tests/client/disco/components/TestAddon.js
tests/client/disco/containers/TestDiscoPane.js
tests/client/disco/reducers/test_installations.js
tests/client/helpers.js
tests/client/search/containers/TestAddonPage.js

Add events to disco pane

---

src/disco/css/Addon.scss

Fixes:  #548
@pwalm @designakt I've prepared this with 0.2 - but let me know what you think and if you prefer something else based on the screenshots in #548.
Before:
After:

Add box-shadow to addon blocks

---

src/disco/css/InstallButton.scss

Fixes: #553
Fixes: #552
* Buttons are now actually round.
* Button gaps are on spec
* The width of the background is to spec.
* The hover states are removed for uninstalling/installing and disabled states.
* The active button handle is in the right position as opposed to being too far to the right.
* Tick image allows mouse events to pass-through: Fixes #497
Before:
After:

Tighten up the install button to spec

---

src/disco/addonManager.js
src/disco/components/Addon.js
src/disco/constants.js
src/disco/reducers/installations.js
tests/client/disco/components/TestAddon.js
tests/client/disco/reducers/test_installations.js
tests/client/helpers.js

This just treats `ENABLED` and `DISABLED` as `INSTALLED` and `UNINSTALLED`. I suppose that since `ENABLED` and `DISABLED` imply that it is installed we could get rid of `INSTALLED` but I kept it for now.
Fixes #540.

Support ENABLED and DISABLED installation statuses

---

src/disco/css/InstallButton.scss

Fixes #559 
Fixes #563
* Use translateX for slide transitions ~~(there's a bit of a double bounce for themes but I think that's state change related).~~
* Transition the borders. (this fixes the weird problem with jank when the theme install bar appears see #563).

Use translateX for transitions

---

package.json
src/disco/components/Addon.js
src/disco/css/Addon.scss

I just guessed at a timing function, happy to change it. I manually changed the classes for the needs restart overlay, hence why the text is wrong.

Animate the overlays (fixes #570)

---

src/disco/css/App.scss

Center play button text when wrapping

---

config/default-disco.js
config/default.js
tests/server/TestCSPConfig.js

about:blank can be injected so frame-ancestors set to about: isn't useful. However, the x-frame-options DENY is still preventing framing (this works because about:addons seems to ignore that header but if you then try and iframe the page elsewhere that header prevents framing since it's set to DENY.
Since the the CSP 2 spec states frame-ancestors should take precedence over x-frame-options it seems to make sense to remove frame-ancestors for now in-case FF behaviour changes and follows the spec more closely. [1]
> The frame-ancestors directive obsoletes the X-Frame-Options header. If a resource has both policies, the frame-ancestors policy SHOULD be enforced and the X-Frame-Options policy SHOULD be ignored.
[1] https://www.w3.org/TR/CSP/#frame-ancestors-and-frame-options
Other apps will …

Remove frame-ancestors since x-frame-options DENY will suffice

---

src/disco/addonManager.js
src/disco/components/Addon.js
src/disco/components/InstallButton.js
tests/client/disco/TestAddonManager.js
tests/client/disco/components/TestAddon.js
tests/client/disco/components/TestInstallButton.js
tests/client/helpers.js

Extra button states are missing since I don't have the latest uplift for that to work.
Fixes #565.

UITour doorhanger on add-on install

---

src/core/css/inc/mixins.scss
src/disco/css/Addon.scss
src/disco/css/App.scss
src/disco/css/inc/vars.scss

I've ignored the bits we don't have for now and I've avoided trying to do the material-style buttons since we'd need quite a lot of changes to get that working in terms of modifications to the existing styles.
The breakpoints need playing with and tuning.
The tricky parts are:
* ~~When to switch the background (and turn off the 48px padding adjustment), we might need a better cue for that - we should think about how we can provide those hooks from the server (e.g. via the URL).~~
~~I'm thinking we could remove the background change part and leave the 48px padding and at least we have some steps towards being mobile compliant when the android UI makes changes towards exposing this page.~~ DONE
It looks like this (albeit the 48px is re-instated and the background is now consistent …

Mobile Styles

---

src/disco/components/Addon.js
src/disco/css/Addon.scss
tests/client/disco/components/TestAddon.js

Fixes #611
Since we're adding the attrs here (DOMPurify filters target by default) we can remove the attrs from the API HTML.

Allow links in headings, add attrs with DOMPurify

---

src/disco/css/Addon.scss

Remove focus outline for theme image hover

---

src/disco/components/Addon.js

Fixes #584
Moves tracking to the `then()` to make it more accurately reflect install/uninstall.
Fwiw: Tests for the tracking install/uninstall dispatches already exist.

Make tracking more accurate

---

src/disco/constants.js
src/disco/containers/DiscoPane.js
tests/client/disco/containers/TestDiscoPane.js

Add tracking for video and see more add-ons

---

config/default-disco.js
config/default.js
karma.conf.js
package.json
webpack.dev.config.babel.js
webpack.prod.config.babel.js

Fixes #662
* Use postcss-loader since autoprefixer-loader is now deprecated
* Don't provide prefixing for the disco app CSS, since it's FF only.
Before:
24K 28 Jun 19:45 dist/disco-7ac5aeceb3f4b1a1f7d19076b057f2e8.css
After:
18K 28 Jun 19:50 dist/disco-6d88730d5d44d891a6eaa83f61d0e97d.css

Make css prefixing configurable

---

package.json

Reverts mozilla/addons-frontend#651
Due to `https://github.com/karma-runner/karma/issues/2210`

Revert "Update karma to version 1.1.0 🚀"

---

config/default-disco.js
src/disco/components/Addon.js
src/disco/components/InfoDialog.js
src/disco/constants.js
src/disco/containers/DiscoPane.js
src/disco/css/InfoDialog.scss
src/disco/reducers/infoDialog.js
src/disco/store.js
tests/client/disco/components/TestAddon.js
tests/client/disco/components/TestInfoDialog.js
tests/client/disco/containers/TestDiscoPane.js
tests/client/disco/reducers/testDiscoResults.js
tests/client/disco/reducers/testInfoDialog.js

Fixes #658
* Add in-page notification post-install
* UiTour is configurable so we can turn it back on later if we want it.
* Uses role=dialog which should mean it gets announced, the button is focused on activation for a11y reasons too.
* It's not modal (like the uiTour) so I've not made it trap the focus.
* No animations for now, I need to double check but I don't think the uitour has them. If we want them we can add them separately. 
Looks like this:

Add in-page showInfo dialog

---

src/disco/css/Addon.scss
src/disco/css/InstallButton.scss

Fixes:  #669
I've kept the button transition movement the same as ltr as a quick fix. If we think the button should be inverted for RTL then that will take longer and we should take a look at doing that separately.
Before:
After:

Fix up buttons and messages for RTL

---

src/disco/addonManager.js
src/disco/components/Addon.js
src/disco/components/InstallButton.js
src/disco/constants.js
src/disco/css/InstallButton.scss
src/disco/reducers/installations.js
tests/client/disco/TestAddonManager.js
tests/client/disco/components/TestAddon.js
tests/client/disco/reducers/test_installations.js
tests/client/helpers.js

Fixes #547
* Makes `DISABLED` and `ENABLED` first-class states rather than being aliased.
* `ENABLED` shares the same styles as installed.
* Use the new browser API to enable an addon when it's been disabled
* Fallback to quietly logging an error (where logging is enabled e.g. -dev) if addon.setEnable is not present - this means landing this will work before and after the API is available.

Enable disabled Add-ons

---

src/disco/css/InstallButton.scss

Fixes #681
* Invert install button for RTL including transitions.

Invert install button for RTL

---

src/disco/css/Addon.scss

Fixes #700
Defining the height of the theme image helps the layout be defined up-front without waiting for the images to be downloaded.

Add height to theme to help initial layout

---

README.md
package.json

This is a start on #402
We also need to make `bin/server.js` blow-up if the NODE_APP_INSTANCE isn't defined which can come a as a follow-up.

Clean up npm commands and README

---

bin/build-checks.js
package.json

This prevents `npm run build` and `npm run start` from running without setting the name of the app via `NODE_APP_INSTANCE`.
Building all the apps is allowed with a special env var, this is because server tests still currently need to build all apps.

Prevent build and start without NODE_APP_INSTANCE

---

Dockerfile

These commands currently fail to run since we require `NODE_APP_INSTANCE` and `NODE_ENV` to be set. Since we run these as part of the deployment process I don't think we need them here as part of the Docker image build process. 
r?

Remove build and run commands from Dockerfile

---

src/core/server/base.js

Reverts mozilla/addons-frontend#720 
It's not working since the ssl looks to be terminating above the node service. Going to use force instead since we can be sure that aside from local development we'll always be using SSL.
I'll do a new PR for that which should make tracking it for a cherry-pick a bit easier.

Revert "Always send an STS header on secure requests"

---

src/disco/css/InfoDialog.scss

Fix notification orientation for RTL

---

src/disco/css/Addon.scss
src/disco/css/App.scss

Fix RTL padding and small vp widths

---

src/disco/components/Addon.js
src/disco/css/InstallButton.scss
tests/client/disco/components/TestAddon.js

Fixes #731 
@mstriemer see if you can repro the original issue with this. I don't appear to be able to for install or uninstall by focusing and hammering on the keyboard. 
Nice side-effect of this is you see the stripes for longer too.

Prospectively dispatch UNINSTALLING state earlier

---

src/disco/components/InstallButton.js
tests/client/disco/components/TestInstallButton.js
tests/client/helpers.js

Fixes #385 
This text content isn't visible but should mean that if a user is focused on the button the label is what should be read out by a screenreader.

Reflect state of add-on/theme in label

---

src/disco/css/App.scss

Fixes #767 - forces scrollbars if discopane width drops below 300px

Fix min-width

---

docs/i18n.md

Add docs re: component translation

---

config/default-search.js
config/default.js
package.json
src/amo/routes.js
src/core/client/base.js
src/core/i18n/utils.js
src/core/server/base.js
src/disco/routes.js
tests/client/core/i18n/test_utils.js
tests/server/disco/TestCSPConfig.js
tests/server/disco/TestViews.js
tests/server/helpers.js
tests/server/search/TestViews.js

* Add accept-language fallback to lang lookup (this is derived from mozilla/i18n-abide code + tests).
* remove lang query-string support since it's superfluous.
* Make routes with lang (optional) makes it possible to redirect if lang isn't supplied.
* Improve server tests, splits them up so that passing NODE_APP_INSTANCE is done correctly - which required some test fixes since not passing the NODE_APP_INSTANCE meant some of the older tests were wrong.

Add accept-language support

---

config/default-disco.js
config/default.js
src/core/server/base.js
tests/server/TestConfig.js

* Make node statics configurable
* Move the loop so that NODE_APP_INSTANCE is more reliably set for the tests.

Make node statics configurable

---

config/uitests-disco.js

Fixes #795
@davehunt can you check this PR out and verify it works for you. The config ensures the statics are served locally and allowed with CSP and that the tracking is off.
```
docker build .
...snip
Successfully built 9bfec4e5af1c
...snip
docker run -p 4000:4000 -e NODE_APP_INSTANCE=disco -e NODE_ENV=uitests 9bfec4e5af1c /bin/sh -c "npm run build && npm run start"
```
Results in this:

Add a uitests specific config

---

config/default-disco.js
config/dev-disco.js
config/stage-disco.js
tests/server/disco/TestCSPConfig.js

Fixes #784
This sets an explicit path for script-src for google-analytics as opposed to just the host.

Use full path to analytics for CSP

---

.eslintrc

So far, we've consistently used braces for arrow functions - adding this rule enforces it.

Add arrow-parens eslint rule

---

config/default-search.js
config/default.js
package.json
src/amo/containers/DetailPage.js
src/amo/css/App.scss
src/amo/routes.js
src/core/client/logger.js
src/core/i18n/utils.js
src/core/middleware.js
src/core/server/base.js
src/core/utils.js
src/disco/routes.js
tests/client/amo/containers/TestDetail.js
tests/client/core/i18n/test_utils.js
tests/client/core/test_middleware.js
tests/client/core/test_tracking.js
tests/client/core/test_utils.js
tests/server/amo/TestViews.js
tests/server/disco/TestViews.js

Fixes #786 and  #785
This PR:
* Adds a redirection for client application e.g. firefox/android
* Moves the lang and application redirects into an express middleware
* ~~slashes are appended unless configured not to be. This is off for the disco pane since the URL in the pref doesn't end with a slash. (If we are going to need more control over this we'll need to think again) FWIW: AMO currently seems to mostly favour always adding a slash.~~
_NOTE: I updated and removed the slash handling for now. I think this is potentially better added separately if we want it._
The reason for moving to a middleware is because redirections need to happen for URLS that may not match the routes. If it's all done in react-router the redirects can only happen for matching routes. This also means the router …

Add application redirects + vary headers

---

src/core/utils.js
tests/client/core/test_middleware.js
tests/client/core/test_utils.js

Add simplistic user-agent lookup

---

.gitignore

So we don't accidentally commit the byproducts of uittesting.

Add ignores for uitests

---

src/search/components/SearchForm.js
src/search/css/SearchForm.scss
src/search/css/lib/buttons.scss
tests/client/search/components/TestSearchForm.js

If you aren't lucky you'll get the regular search results.
Fixes #808.

Jump to add-on by id or slug

---

karma.conf.js

Fixes #903 
This addition will halt the tests and shows a nice message pointing to the error.

Bail test runs on test syntax error

---

src/disco/components/Addon.js
src/disco/css/Addon.scss
src/disco/css/inc/vars.scss

> Full view
> Hover over link
> Hover over link
Fixes #899.
This depends on the changes in https://github.com/mozilla/addons-server/pull/3270.

Tweak disco pane styles

---

src/amo/components/AddonDetail.js
src/amo/containers/DetailPage.js
src/core/purify.js
src/core/utils.js
src/disco/components/Addon.js
src/search/containers/AddonPage/index.js
tests/client/amo/components/TestAddonDetail.js
tests/client/amo/containers/TestDetail.js
tests/client/core/test_utils.js
tests/client/search/containers/TestAddonPage.js

Fixes https://github.com/mozilla/addons-frontend/issues/883

Hook up the details page to data

---

src/core/tracking.js
src/disco/components/Addon.js
src/disco/constants.js
tests/client/core/test_tracking.js
tests/client/disco/components/TestAddon.js

Add link tracking

---

src/search/components/SearchResult/index.js
src/search/components/SearchResult/style.scss
src/search/components/SearchResults.js
src/search/css/SearchResults.scss
src/search/css/lib/buttons.scss
tests/client/search/components/TestSearchResult.js

This adds the guid and links to the listing, edit and editors to the search results.
The fake data I have locally is missing theme icons and the links don't work but I checked the data on dev and it should be fine with real data.
Fixes #978.

Better admin search results

---

src/admin/components/NavBar/index.js
src/admin/containers/App.js
tests/client/admin/components/TestNavBar.js

Not sure if I didn't catch this in #967 or if it crept in via another later PR. Either way, now everything admin is in the admin app/folders :)

Move NavBar to admin app (fix #999)

---

config/default-disco.js
config/default.js
src/core/tracking.js
src/disco/client.js
src/disco/components/Addon.js
src/disco/constants.js
src/disco/containers/DiscoPane.js
src/disco/tracking.js
tests/client/core/test_tracking.js
tests/client/disco/test_tracking.js

Fixes #963 
Will send dimensions for `has-extensions`/`has-themes` with `true`, `false` or `'unknown'` if it can't be determined.

Send dimensions with initial page view

---

src/disco/css/Addon.scss

Fixes #1047
Looks like this:
Increasing the shadow alpha to 0.4 (from 0.3) looks like this (click to see best quality).

Tweak add-on blocks

---

config/default.js

This fixes the failing test and should allow kab to be used on the disco pane.

Add kab to supported languages

---

.travis.yml
tox.ini

Fixes #792
This adds python linting using flake8, and tweaks Travis to avoid running parts when they're not needed. This is bordering on readability issues, so it might be worth either splitting Tox tasks to CircleCI or at least calling scripts stored in the repo rather than having them in the Travis config.

Add python code linting with flake8

---

package.json

This reverts commit fefb2495cfe041bfd784204fc1a501955bdbfd70.
Hey @kumar303, looks like it did indeed still break things, so reverting this.
Sorry about that, I've made a note to not merge dev server stuff without testing.

Revert "chore(package): update webpack-dev-middleware to version 1.8.2"

---

src/amo/components/SearchResult.js
src/core/components/Search/SearchResults.js
src/core/css/SearchResult.scss
src/core/css/SearchResults.scss
src/core/css/inc/vars.scss
tests/client/amo/components/TestSearchResult.js
tests/client/core/components/TestSearchResults.js
tests/client/helpers.js

This styles the search result, but further work will be needed for the extension/theme separation in the mocks. Will file issues for that.

First pass at styled search result (fix #1117)

---

Dockerfile
circle.yml

This change will provide us with APP specific Docker Images and will remove the dependency to run `npm run build` during deployment time. 
Additional changes include switching to node:4.6 docker base image and also running discovery ui-tests as part of docker image build. I didn't add all the tests that are configured in travis-ci but if I should please let me know.
r?
cc @bqbn

Build APP specific Docker Images via CircleCI

---

Dockerfile
circle.yml

Since NODE_ENV is necessary for building correct APP ENV images I think it would be better to just maintain one image and build the assets as part of deployment.
r?

Build one docker image instead of APP specific

---

package.json

Other deps are complaining about unmet peer dependencies so this is a manual upgrade to `react@15.3.2`, I'm not sure why we didn't get a greenkeeper PR for this one.

Upgrade react to 15.3.2 to fix unmet dep warnings

---

src/core/server/base.js

This was bugging me so I stopped it.
Apparently this didn't do anything anymore, which does make me ask: what were we relying on it to do and will it break anything in development?
But everything seems fine so I submit this for review.

Stop using .development() on server (fix #1235)

---

src/core/i18n/translate.js
tests/client/amo/components/TestAddonDetail.js
tests/client/amo/components/TestAddonReview.js
tests/client/amo/components/TestLanguagePicker.js
tests/client/amo/components/TestMastHead.js
tests/client/amo/components/TestOverallRating.js
tests/client/amo/components/TestSearchResult.js
tests/client/core/components/TestPaginate.js
tests/client/core/components/TestSearchResults.js
tests/client/core/i18n/TestI18nProvider.js
tests/client/core/i18n/test_translate.js
tests/client/disco/components/TestAddon.js
tests/client/disco/components/TestInfoDialog.js
tests/client/disco/containers/TestApp.js
tests/client/disco/containers/TestDiscoPane.js
yarn.lock

This updates `translate()` to accept `i18n` from props which removes the need for setting up an `I18nProvider` component in many cases. I refactored the tests for `I18nProvider` since I think they were mostly testing `translate()` and moved those tests into their own file.
It also removes the `I18nProvider` and `Provider` wrappers from tests that did not need it.

Translate accept props

---

src/admin/containers/App.js
src/core/actions/index.js
src/core/actions/search.js
src/core/constants.js
src/core/reducers/api.js
src/core/reducers/authentication.js
src/core/reducers/search.js
src/disco/actions.js
src/disco/constants.js
src/disco/reducers/discoResults.js

This should capture the remaining types from #1087

Use constants for redux action types.

---

package.json
src/disco/containers/App.js
src/disco/css/App.scss
tests/client/disco/containers/TestApp.js

Relates to #639 and is a follow-up to #1308 
@mstriemer Thanks for the suggestions. 
This branch contains the switch to `parseInt` and I've pulled the padding out of the media query. The padding won't affect FF Android since mozAddonManager only works on ff Android from 51 onwards anyway (and we're not linking to it for android yet in any case).

Simplify version check

---

src/amo/components/Footer.js
src/amo/components/Link.js
src/amo/components/MastHead.js
src/amo/components/SearchForm.js
src/amo/components/SearchPage.js
src/amo/components/SearchResult.js
src/amo/containers/App.js
src/amo/containers/Home.js
src/core/components/Paginate/index.js
src/core/components/Search/SearchResult.js
src/core/components/Search/SearchResults.js
tests/client/amo/components/TestFooter.js
tests/client/amo/components/TestLanguagePicker.js
tests/client/amo/components/TestLink.js
tests/client/amo/components/TestMastHead.js
tests/client/amo/components/TestSearchForm.js
tests/client/amo/components/TestSearchPage.js
tests/client/amo/components/TestSearchResult.js
tests/client/amo/containers/TestHome.js

Finally got around to doing this as I was being driven mad by all the `lang` passing.
Moves all of our AMO links to use a local `<Link />` component that still uses `to` instead of the propsed `href` in #1136 (so it looks the same as other React links).
r?

Add Link component for auto-URL-prefixes (fix #1136)

---

src/amo/css/OverallRating.scss

Fixes https://github.com/mozilla/addons-frontend/issues/1360
Using the keyboard to navigate and submit a rating was working for me so this fix just adds some styling:

Make a star look selected during keybaord navigation

---

config/default.js
src/amo/components/Categories.js
src/amo/components/Categories.scss
src/amo/containers/CategoryList.js
src/amo/routes.js
src/amo/store.js
src/core/actions/categories.js
src/core/api/index.js
src/core/constants.js
src/core/reducers/categories.js
src/core/utils.js
tests/client/amo/components/TestCategeories.js
tests/client/amo/containers/TestCategoryList.js
tests/client/amo/test_store.js
tests/client/core/actions/test_categories.js
tests/client/core/api/test_api.js
tests/client/core/reducers/test_categories.js
tests/client/core/test_utils.js

Okay, this *only* implements the category listing page and not the addons inside a result. That'll come next as a separate PR so this is easier to review.
This is largely just separated out of the work in #1237 with issues addressed.

Add Category Page (close #1183)

---

src/amo/actions/reviews.js
src/amo/api/index.js
src/amo/components/AddonReview.js
src/amo/components/OverallRating.js
src/amo/css/OverallRating.scss
src/amo/reducers/reviews.js
tests/client/amo/components/TestAddonReview.js
tests/client/amo/components/TestOverallRating.js
tests/client/amo/helpers.js
tests/client/amo/reducers/testReviews.js
tests/client/amo/testApi.js

Fixes https://github.com/mozilla/addons-frontend/issues/1088
* Saved stars are rendered as "selected"
* The rating button is disabled since you can't rate an add-on twice

Render saved star ratings on detail page

---

package.json
src/amo/components/AddonDetail.js
src/amo/components/AddonMoreInfo.js
src/amo/components/AddonMoreInfo.scss
src/amo/containers/DetailPage.js
src/core/css/inc/mixins.scss
tests/client/amo/components/TestAddonDetail.js
tests/client/amo/components/TestAddonMoreInfo.js
tests/client/amo/helpers.js

So! I've fixed this up and sent it as a separate PR. Supersedes #1354.
Adds "More information" to addon detail pages. (Same as before.)

Add more info to addon details page (fix #1294)

---

src/amo/components/AddonDetail.js
src/amo/components/OverallRating.js
tests/client/amo/components/TestAddonDetail.js
tests/client/amo/components/TestOverallRating.js

This is pretty edge-casey since we don't currently have a way to view history add-on versions but I think it's the right thing to do. It should future proof the site for when we do show multiple versions (or is that YAGNI? Sigh).
Fixes https://github.com/mozilla/addons-frontend/issues/1390

Updating an old review should create a new review against the current add-on version

---

.travis.yml
package.json
src/core/installAddon.js
src/disco/components/Addon.js
tests/client/core/TestInstallAddon.js
yarn.lock

The props weren't getting set for the updated `withInstallHelpers` HOC so it was failing on install. I made it throw now if it is misconfigured.
Just had to reorder the `compose()` in `Addon` to fix this.
This also tells Travis to use `npm install` instead of `yarn` to install things since their update seems to have broken the build? Maybe we need to update some config but I'm not sure what.
Fixes mozilla/addons-server#4035.
Moved from https://github.com/mozilla/addons-frontend/pull/1400 since when Travis runs yarn it seems to break that PR for good.

Ensure installURL is set before calling withInstallHelpers 

---

src/amo/components/Categories.js
src/amo/components/SearchPage.js
src/amo/containers/CategoryPage.js
src/amo/routes.js
src/core/searchUtils.js
tests/client/amo/containers/TestCategoryPage.js
tests/client/core/test_searchUtils.js

Add the actual category URL (matches addons-server) including pagination.
Screenshot:

Add category page (close #1378)

---

src/amo/components/SearchForm.js
tests/client/amo/components/TestSearchForm.js

Simple fix to hide virtual keyboard (I did the screenshot on the simulator because I broke my Android simulator and I'm too lazy to fix it but it should work).
Before:
After:

Blur search input on search (fix #1384)

---

src/amo/components/AddonDetail.js
src/amo/css/AddonDetail.scss
src/ui/components/ShowMoreCard/ShowMoreCard.scss
src/ui/components/ShowMoreCard/index.js
tests/client/amo/components/TestAddonDetail.js
tests/client/amo/helpers.js
tests/client/ui/components/TestShowMoreCard.js

Screenshot:
-----
This moves some things from the `AddonDetail` component into an `AddonDescription` component (which is nice for smaller components used to build bigger ones) so it looks like more than it actually is as I moved the tests about too.
It also shows the description in the new style and deals with truncation using size rather than text content (anything too tall is rendered with a "show more" link that just sets a new class). Stuff that is short enough just shows with no truncation.

Truncate and style description (fix #1296)

---

src/amo/components/AddonDetail.js
src/core/addonManager.js
src/core/components/InstallButton/index.js
src/core/components/InstallSwitch/index.js
src/core/installAddon.js
src/disco/components/Addon.js
src/disco/containers/DiscoPane.js
src/ui/components/Button/Button.scss
src/ui/components/Button/index.js
src/ui/components/Switch/Switch.scss
tests/client/amo/components/TestAddonDetail.js
tests/client/core/TestAddonManager.js
tests/client/core/TestInstallAddon.js
tests/client/core/components/TestInstallButton.js
tests/client/core/components/TestInstallSwitch.js
tests/client/disco/components/TestAddon.js
tests/client/ui/components/TestButton.js

Buttons on http://localhost:3000 and switches on https://discovery.addons.mozilla.org.
TODO: Make sure we aren't calling `setCurrentStatus()` anywhere it won't work, or make it a no-op if we don't have `mozAddonManager`. That's probably nicer.
Fixes #946.

Link fallback for installation without mozAddonManager

---

src/amo/containers/Home.js
src/amo/css/Home.scss

Refactor homepage cat CSS and reduce nesting

---

src/amo/components/Footer.js
src/amo/components/LanguagePicker.js
src/amo/containers/App.js
src/core/languages.js
tests/client/amo/components/TestLanguagePicker.js

Just grabbed the `language.json` from product details and tossed it in here rather than dealing with importing it and running it and all that jazz. That should be fine (as discussed with @kumar303) and we can always add to it if we add locales outside of what it has in it in the future.

Add language picker (fix #1289)

---

src/amo/components/AddonReview.js
src/amo/css/AddonReview.scss
src/core/css/ErrorHandler.scss
tests/client/amo/components/TestAddonReview.js

At first I wanted to make a global error handler (https://github.com/mozilla/addons-frontend/issues/1484) but that got hairy so I set it aside.
As a compromise, I looked through all AMO components that work with the API and added `withErrorHandling()` to make sure they display errors. I didn't look at any of the API actions that are executed via `asyncConnect` because that's not compatible with our higher order error handler component (specifically, there is no way to get the `errorHandler` property from the component props, unless I'm missing a way?). This leaves only one component: `AddonReview`. Am I forgetting anything?
Adding API error handling for it is pretty straight forward. The new behavior looks like this:

Hook up AddonReview for API error handling

---

src/amo/css/OverallRating.scss

Fixes #1399 by removing the padding and replacing with a margin to retain the whitepace now makes the height of the span the same as the buttons.

Fix hover on ratings

---

src/amo/components/SearchResults.js
src/core/actions/search.js
src/core/reducers/search.js
src/core/searchUtils.js
tests/client/amo/components/TestSearchResults.js
tests/client/amo/containers/TestCategoryPage.js
tests/client/amo/containers/TestSearch.js
tests/client/core/actions/test_search.js
tests/client/core/reducers/test_search.js
tests/client/core/test_searchUtils.js

Fixes #1485.
This fixes some of the wonky search result text we had in the past. It also preserves the search results on screen during the `SEARCH_STARTED` action so they stay until new results are loaded, which is less jarring.
Obvious the "searching..." text isn't great, we might UX on that in the future, but already this is better.

Don't show "no results" in between searches

---

karma.conf.js
package.json
src/amo/components/AddonDetail.js
src/amo/components/ScreenShots.js
src/amo/css/ScreenShots.scss
src/core/css/inc/mixins.scss
src/core/server/webpack-isomorphic-tools-config.js
tests/client/amo/components/TestScreenShots.js
tests/client/amo/helpers.js
webpack.dev.config.babel.js
webpack.prod.config.babel.js
yarn.lock

Going to look through this diff one more time later tonight but wanted to get the PR up.
Fixes #936.

Screenshot viewer on add-on detail

---

src/amo/components/LandingAddonsCard/index.js
src/amo/components/LandingPage.js

fix #1542.
I should have been using `convertFilterstoQueryParams` here and wasn't, so the extension type wasn't being passed to search.

fix: Use convertFiltersToQueryParams on LandingPage

---

src/amo/components/AddonDetail.js
src/amo/css/AddonDetail.scss
tests/client/amo/components/TestAddonDetail.js

This fixes the not being able to scroll while previewing a theme bug by replacing the `<img>` with a `<div>` that has a background image once the component mounts. This is done to avoid the CSP errors that we'd get for rendering on the server with inline styles.
> [div version?](https://cloud.githubusercontent.com/assets/211578/21670248/7beff1c8-d2d8-11e6-85e6-bc527e1abc97.png)
> [img version?](https://cloud.githubusercontent.com/assets/211578/21670249/7c11d0f4-d2d8-11e6-8889-0fc127c4cff0.png)
> Screenshots of the two versions, I forget which is which but they look the same
Fixes #1445.

Allow scrolling when previewing theme

---

src/ui/components/Overlay/Overlay.scss
src/ui/components/Overlay/index.js
src/ui/components/OverlayCard/OverlayCard.scss
src/ui/components/OverlayCard/index.js
tests/client/ui/components/TestOverlay.js
tests/client/ui/components/TestOverlayCard.js

Adds a very generic overlay and more useful `OverlayCard` for the restyle of the reviews (and probably other things too, this seemed a useful thing to make generic).
The component automatically stretches to fill the screen and has a max height of 75% of the viewport.
Fixes #1553.

Add overlay and card overlay components

---

src/ui/components/Switch/Switch.scss

The switch uninstalled colour was a bit darker than the mocks. I've lightened it up a bit.

Match switch uninstalled background to mocks

---

config/custom-environment-variables.json
src/core/addonManager.js
src/core/components/InstallButton/index.js
src/core/components/InstallButton/styles.scss
src/core/components/InstallSwitch/index.js
src/disco/components/Addon.js
src/disco/css/Addon.scss
src/ui/components/Button/Button.scss
src/ui/components/Button/index.js
tests/client/core/TestAddonManager.js
tests/client/core/components/TestInstallButton.js
tests/client/disco/components/TestAddon.js

This makes the install buttons default to the switch when rendering on the server then flips to the blue button if `mozAddonManager` isn't supported once the page loads.
No support for `<noscript>` yet (I have it working in dev but need to get around CSP still for production).
> With `mozAddonManager`
> No `mozAddonManager`
Fixes #1568.

Show install switch by default

---

tests/ui/README.md

@davehunt does this look right? I was getting `UsageError: --driver must be specified` when running it the old way. This brings it closer to how the `.travis.yml` file runs the tests.

Update docs on running UI tests

---

package.json

I was a little surprised the tests passed but didn't see and upgrade docs so figured they just rewrote a bunch and decided on a major bump.
This entirely broke the unit tests even though they kept passing 😠
Backing out the change, not sure if it's meant for webpack 2. We can deal with it later.

Downgrade karma-webpack from 2.0.0 to 1.8.1

---

src/amo/components/SearchPage.js
src/amo/components/SearchSort/SearchSort.scss
src/amo/components/SearchSort/SearchSortLink.js
src/amo/components/SearchSort/SearchSortLink.scss
src/amo/components/SearchSort/index.js
src/amo/img/icons/arrow-link-color.svg
src/amo/img/icons/sort.svg
src/core/api/index.js
src/core/css/inc/mixins.scss
src/ui/components/ShowMoreCard/index.js
tests/client/amo/components/TestSearchPage.js
tests/client/amo/components/TestSearchResults.js
tests/client/amo/components/TestSearchSort.js

Fixes #1297.
Right now we're using "relevance" from the mocks as the default but I'm not sure that's exactly what the default search from the API actually is. http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search says "sorted by weekly downloads" is the default, so perhaps we need to add a "relevance" sort option (which should be the default).
cc @diox: should I file a bug for addons-server to get "relevance" as a sort option? Or is calling the default sort "relevance" appropriate enough here?
(Note: is keyboard accessible)

Add search sort

---

karma.conf.js
package.json

Fixes #1103 
@kumar303 Give this a spin it - should not bail when running with `npm run unittest:dev` when there's an syntax error.
Note: if the syntax error is in a test file then the syntax error info will be above the rest of the test output. If it's a src file it will not run the tests. Coverage is the useful guide in the first case.

Don't bail if watch arg is supplied

---

package.json
src/amo/noscript.css
src/core/containers/ServerHtml.js
src/core/server/base.js
src/disco/containers/DiscoPane.js
src/disco/noscript.css
tests/client/core/containers/TestServerHtml.js
tests/server/admin/TestViews.js
tests/server/amo/TestViews.js
tests/server/disco/TestViews.js
tests/server/helpers.js
tests/server/test_helpers.js
yarn.lock

This will read a `noscript.css` file from the app's root and include that in `<noscript><style>{contents}</style></noscript>` if it exists. It also sets the CSP header so that this will work in production.
I have some updates to make this work with webpack as well but I'm running into some problems with webpack-isomorphic-tools so just putting this up for now to look at.
Fixes #1604.

Install button noscript fallback

---

README.md
src/core/server/base.js

We used to have support for `CSP: false`. We should probably just bring that back but until then, this seems worth documenting.

Disable CSP for development

---

src/amo/components/AddonMeta.js
src/amo/components/SearchResult.js
src/core/client/base.js
src/core/i18n/utils.js
src/core/server/base.js
tests/client/amo/components/TestAddonMeta.js
tests/client/amo/components/TestSearchResult.js
tests/client/core/i18n/test_utils.js
tests/client/helpers.js

I updated how the lang is acquired. Rather than using state it uses `i18n.lang` and the lang is passed to the `makeI18n()` function to be set rather than pulling it from the first message (I'm curious what that would do if the string wasn't translated or we maybe didn't have any translations for a locale).
I updated the string to match the one from `AddonMeta` since they have different names for the number so it would have caused there to be an extra translation string (I think).
Screenshots:
<details><summary>English</summary><img src="https://cloud.githubusercontent.com/assets/211578/22001524/5843545e-dc0b-11e6-843f-5b380c0a6190.png" alt="screen shot 2017-01-16 at 16 31 59" style="width: 300px; max-width:50%;">
</details>
<details><summary>French</summary>
</details>
&nbsp;
Fixes #1608.

Localise user count in search results

---

Dockerfile

Switching to the -slim image reduces the image size by 500MB, currently it is 1.3GB.
r?

Switch to node:6-slim and perform build optimization. fixes #1120

---

src/admin/containers/App.js
src/amo/components/MastHead.js
src/amo/components/MastHead.scss
src/amo/containers/App.js
src/amo/img/icons/login-person.svg
src/core/actions/index.js
src/core/components/AuthenticateButton/index.js
src/core/containers/HandleLogin/index.js
src/core/css/inc/mixins.scss
src/core/reducers/api.js
src/core/server/base.js
src/ui/components/Button/Button.scss
src/ui/components/Icon/styles.scss
src/ui/components/Icon/user-dark.svg
tests/client/amo/components/TestMastHead.js
tests/client/amo/components/TestRatingManager.js
tests/client/amo/containers/TestApp.js
tests/client/core/actions/test_index.js
tests/client/core/components/TestAuthenticateButton.js
tests/client/core/reducers/test_api.js

Logs you out in the same way as it does on the admin. We have an extra cookie that we'll need to clear on addons-server. I'll submit a follow up patch for that later, tracked in #1557 and an addons-server issue near you.
This also clears the JWT from the `api` reducer on log out. That was definitely a bug.
Maybe we should get rid of the authentication reducer. I filed #1644 for that, I think it was intended to store info about the user but that can go in a "user" reducer and shouldn't store the JWT.
I also renamed `setJWT` to `setJwt` since it was bothering me, in a separate commit.
[demo gif (7.5MB)](https://cloud.githubusercontent.com/assets/211578/22137092/91609c20-de9e-11e6-915b-d0f78fec2f03.gif)
Fixes #1632.

Make log out work on mobile pages

---

src/amo/components/SearchSort/SearchSort.scss

Fixes #1663
The problem was in the first argument (the 0) in the line - https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchSort/SearchSort.scss#L16.

Fix for top margin for search sort

---

src/core/css/SearchResult.scss

fix: Long author names float images to right

---

src/core/components/HoverIntent/index.js
src/disco/components/Addon.js
tests/client/core/components/TestHoverIntent.js
tests/client/disco/components/TestAddon.js

Closes #1634
Closes #1561
This fixes the first bug by requiring that the mouse has slowed below some threshold (10 pixels in 100 ms) before previewing the theme. It assumes that anything faster than that is just the user trying to mouse through the element, not them trying to hover over it.
It _should_ fix the second bug by requiring that the mouse moves past some threshold (5 pixels) before previewing the theme. When we get a mouseover event simply because a video closes (and the mouse is sitting on top of the theme image), the user hasn't moved their mouse yet. Once they move their mouse, they'll likely be moving it faster than the first threshold, and so they won't accidentally see the theme preview.
I was a _little_ shaky on the tests. They reliably pass for me, but I could see them …

Fix unintentional hovering causing theme previews

---

src/core/api/index.js
tests/client/core/api/test_api.js
tests/server/amo/TestDetailsPage.js

Fixes https://github.com/mozilla/addons-frontend/issues/1701

Handle non-JSON responses in callApi() correctly

---

src/core/addonManager.js
src/core/installAddon.js
tests/client/core/TestAddonManager.js
tests/client/core/TestInstallAddon.js
tests/client/helpers.js

Fixes #1679 
Conditionally dispatch the install notification based on detecting `extensions.webextPermissionPrompts`. 
With `extensions.webextPermissionPrompts` set to false:
With `extensions.webextPermissionPrompts` set to true:

Use native install notifications when permissionPromptsEnabled is true

---

src/amo/components/AddonReview.js
src/core/utils.js
tests/client/amo/components/TestAddonReview.js
tests/client/core/test_utils.js

Fixes https://github.com/mozilla/addons-frontend/issues/1738
After reading the bug, here's what you need to know about the patch:
* The behavior where the review is missing from the list seemed to be solved by https://github.com/mozilla/addons-frontend/pull/1706 (I could reproduce it before but not after). This patch did not need to address that.
* The review count was not getting updated on the add-on detail page after submitting a new review. This patch addresses that.

Refresh add-on after posting a review to update review count

---

src/amo/css/AddonReview.scss
src/ui/components/OverlayCard/OverlayCard.scss

Fixes https://github.com/mozilla/addons-frontend/issues/1773
Does what it says on the tin! The scrollbars are only added when needed.

Fix scrolling when Android keyboard is open

---

src/amo/css/AddonReviewList.scss

Fixes https://github.com/mozilla/addons-frontend/issues/1770

Break long words in add-on review listing

---

src/amo/actions/reviews.js
src/amo/components/AddonReview.js
tests/client/amo/actions/testReviews.js
tests/client/amo/components/TestAddonReview.js

Fixes https://github.com/mozilla/addons-frontend/issues/1779
Here's an explanation of what was happening:
* Let's say a user creates a rating and a written review
* The user returns to edit the written review
* When the user presses 'submit' on their text change, the component patches the API with the new review object and waits
* Meanwhile, the error handler resets itself since a new API request has been initiated. This triggers a re-render of the AddonReview component
* The AddonReview component renders using the old review object from state and sets the form text to the old text. To the user, it looks like pressing the submit button just erased what they had written.
* The API response finally completes and puts the new review object in state. By the time the overlay for the form has …

Don't reset review state when submitting a new review

---

src/ui/components/SearchInput/index.js
src/ui/components/SearchInput/style.scss
tests/client/helpers.js
tests/client/ui/TestSearchInput.js

There were two problems with `SearchInput`, when typing immediately after focus keystrokes would be dropped, and when dismissing the virtual keyboard the animation would stop working and this prevented the input from being focused again.
This patch fixes both problems. The text is now transparent until the animation ends so keystrokes are not lost (instead of cancelling the focus event and manually focusing later).
The virtual keyboard issue was due to how the icon is moved over for animating (there are two icons, one on the label and one that animates to the left-aligned position). The `resize` event fires when the keyboard opens or closes and the icon's position would be recalculated but the calculation only worked if the icon had not been positioned yet. The original location of the …

Fix SearchInput issues

---

src/amo/css/AddonDetail.scss

Fixes #1607 
Before - (contains a horizontal scroll bar at the bottom)
After - (no horizontal scroll bar at the bottom)

fix: Long author names cause horizontal scrolling

---

src/amo/css/Home.scss

Fixes #1741 
Before - 
After -

fix: Too much space between header and category buttons 

---

src/amo/components/AddonDetail.js
src/amo/components/LandingAddonsCard/index.js
src/core/css/ErrorHandler.scss
src/core/errorHandler.js
src/ui/components/Card/Card.scss
src/ui/components/Card/index.js
src/ui/components/OverlayCard/index.js
src/ui/components/ShowMoreCard/index.js
tests/client/amo/components/TestAddonDetail.js
tests/client/ui/components/TestCard.js
tests/client/ui/components/TestOverlayCard.js
tests/client/ui/components/TestShowMoreCard.js

* Fixes https://github.com/mozilla/addons-frontend/issues/1771
* The rating error no longer has a white dot
* Fixes https://github.com/mozilla/addons-frontend/issues/1782
* The 'No reviews yet' text is now styled more consistently. We don't technically have a mock of this.
* The error style is more consistent with the palette now

Fix rating error style and fix 'No reviews yet' style

---

src/amo/containers/App.js

Uses the right error component. I forgot to keep this in during a rebase in #1733, my bad.

fix: Use AMO getErrorComponent (fix #1829)

---

src/core/errorHandler.js
src/core/reducers/errors.js
tests/client/core/reducers/test_errors.js
tests/client/core/testErrorHandler.js

Fixes https://github.com/mozilla/addons-frontend/issues/1527
These are unlikely but possible:

Handle displaying 401 errors and other non-form-validation API responses

---

config/default-amo.js
config/default.js
src/core/middleware.js
src/core/server/base.js
tests/client/core/test_middleware.js
tests/server/amo/TestViews.js

This adds a config option to enable a middleware that adds trailing
slashes to all URLs that don't have one. It's only enabled on AMO
for now as Disco Pane definitely have URLs that are declared without
trailing slash and this does the dumbest thing possible which is
redirect all requests.

feat: Add trailing slashes to URLs (fix #843)

---

src/amo/components/SearchPage.js
src/amo/containers/CategoryPage.js
tests/client/amo/components/TestSearchPage.js
tests/client/amo/containers/TestCategoryPage.js

Removes the search sort from categories as it isn't needed there and was buggy.
-----

fix: Hide search sort in categories (fix #1626)

---

src/amo/components/AddonMoreInfo.js
tests/client/amo/components/TestAddonMoreInfo.js

Adds `http://` to homepage URLs that are missing it; will fix https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
Also omits the `http://` in the actual text of the URL in the page, which looks nicer.
I guess this means `gopher://` and `ftp://` homepages won't work. 😉
Seriously though it means a protocol other than HTTP(S) won't work, but I figure that's fine.

fix: Add protocol to homepage URLs (fix #1647)

---

README.md
bin/proxy.js
config/custom-environment-variables.json
config/default.js
config/development-amo.js
package.json
src/amo/routes.js
src/core/server/base.js

Start the proxy server with `npm run dev:amo`. You need to be running an API server at `http://olympia.dev`. Access the site as usual at http://localhost:3000.
Fixes #1716.
Depends on https://github.com/mozilla/addons-server/pull/4681.

Proxy server for AMO development

---

src/core/api/index.js
src/core/components/AuthenticateButton/index.js
tests/client/amo/helpers.js
tests/client/core/api/test_api.js
tests/client/core/components/TestAuthenticateButton.js
tests/client/helpers.js

Logging in and out now works across both addons-server and addons-frontend. The local development setup is unchanged, based on whether the app is running on the same domain as the API.
Fixes #1557.

Log out from server

---

src/amo/components/AddonMeta.js
src/amo/css/AddonMeta.scss
src/ui/components/Icon/star.svg
tests/client/amo/components/TestAddonMeta.js

Fix #1698.
This balances the icon size of the user icon and the star icon. The best way to keep the max amount of context seemed to be adding a line below with the number of ratings (not reviews) if available. That way the numerical rating is given context (1/5 with 1,000 reviews is different than 1/5 with 3 reviews). See the screenshots below, but I think this is the best option.
The number of reviews is displayed lower in the page, which I think is better.

fix: Balance icons in detail

---

src/amo/components/SearchResult.js
src/amo/css/AddonDetail.scss
src/core/css/SearchResult.scss
tests/client/amo/components/TestSearchResult.js
yarn.lock

Fixes #1746
Fixes the theme layout - I made an assumption that we'd want to keep ratings. I also didn't look at the hyphenating of the text since that's covered elsewhere and needs discussion anyway.
Before: 
After:
I also added some belt and braces fallbacks if images aren't set. End users are unlikely to see this but it covers the eventuality and we already did this on the details page for icons.
It will need extending for themes details pages at some point too but that could be done when revisiting the functionality for trying on a theme.
Extensions:
Themes:

Fix theme module layout

---

README.md
config/default-disco.js
config/default.js
config/dev.js
config/stage.js
config/test.js
package.json
src/admin/routes.js
src/amo/routes.js
src/core/containers/SimulateError.js
src/core/server/base.js
src/disco/routes.js
tests/client/core/containers/TestSimulateError.js
tests/server/admin/TestViews.js
tests/server/amo/TestViews.js
tests/server/disco/TestViews.js

Fixes https://github.com/mozilla/addons-frontend/issues/1559
We'll need ops to set `SENTRY_ENV` for each server but that can come in https://github.com/mozilla/addons-frontend/issues/1886

Hook up Sentry for error reporting

---

package.json

Reverts mozilla/addons-frontend#1887
This caused a regression making buttons disabled everywhere. We should definitely look at changelogs for major version bumps in future since that indicates there might be breaking changes.
Also seems odd there's nothing testswise that caught this but that's probably due to the degree to which things get mocked.

Revert "Update react-redux to the latest version 🚀"

---

src/admin/containers/AddonPage/index.js
src/admin/containers/SearchPage.js
src/admin/containers/UserPage/index.js
src/amo/components/AddonReviewList.js
src/amo/components/FeaturedAddons/index.js
src/amo/components/LandingPage.js
src/amo/containers/CategoryList.js
src/amo/containers/CategoryPage.js
src/amo/containers/DetailPage.js
src/amo/containers/SearchPage.js
src/core/utils.js
src/disco/containers/DiscoPane.js
tests/client/core/test_utils.js

Fixes https://github.com/mozilla/addons-frontend/issues/1880
This makes sure that any `promise` callback passed to `asyncConnect` never throws an error. As for the bug in question, the request will now render a 500 page. This fix should also prevent any other page from circumventing our 500 handler in the same way.

Show a 500 page for asyncConnect loaders that throw

---

src/amo/components/SearchForm.js
src/core/searchUtils.js
tests/client/amo/components/TestSearchForm.js
tests/client/amo/containers/TestSearch.js

Fix #1680.
Can't believe we weren't doing this!

fix: Encode query params (fix #1680)

---

src/amo/components/AddonMoreInfo.js
src/amo/components/AddonMoreInfo.scss
src/core/utils.js
tests/client/amo/components/TestAddonMoreInfo.js
tests/client/amo/helpers.js
tests/client/core/test_utils.js

fix: Outgoing add-on links (fix #1859)

---

tox.ini

This downgrades some sub-deps and freezes all deps to work around https://github.com/mozilla/addons-frontend/issues/1927

Freeze all tox deps for no suprise upgrades

---

src/disco/constants.js

more system addons that weren't present on my machine but in other versions/released of Firefox.
Identified via SystemAddons release ftp as described here: https://wiki.mozilla.org/Firefox/Go_Faster/Releasing_an_add-on_mechanics

added more system addons

---

src/core/containers/SimulateError.js
tests/client/core/containers/TestSimulateError.js
tests/server/amo/TestViews.js

whoops, this addresses more fallout from https://github.com/mozilla/addons-frontend/pull/1910 but because the Node shutdown sequence is a little random (or maybe mocha has a bug), the error first showed up in https://travis-ci.org/mozilla/addons-frontend/jobs/205981589

Fix set timeout breakage

---

src/amo/components/AddonDetail.js
src/amo/css/AddonDetail.scss
src/core/constants.js
src/core/css/SearchResult.scss
src/core/installAddon.js
src/core/reducers/installations.js
src/disco/components/Addon.js
tests/client/amo/components/TestAddonDetail.js
tests/client/core/TestInstallAddon.js
tests/client/core/reducers/test_installations.js
tests/client/disco/components/TestAddon.js
tests/client/init.js
yarn.lock

Fixes #1657
Fixes #1677
Fixes #1776
Fixes #1777 
Fixes #1879 
- Themes now previewed on a click. 
- Click again to turn off the theme preview. 
- Preview button goes if the theme is seen as installed + enabled
- Preview goes away when you navigate away (on component unmount)
- Previewing now dispatches in order to provide toggling based on state.

Button for trying on themes

---

src/amo/components/SearchSort/SearchSort.scss
src/core/css/inc/mixins.scss

fix: Correct search sort icons in RTL (fix #1918)

---

src/core/components/Paginate/index.js

Fixes #1946
This is a quick fix for #1946, the reason for the empty pages was we were assuming pages of 20 when the API by default returns 25.
The best way to fix this properly would be to have the API expose the perPage value in the results. That way the pagination would dynamically react to the API response and it would prevent needing to match a request page size with the pagination output configuration.
~I'll file an issue for that separately.~ See https://github.com/mozilla/addons-server/issues/4837 for an API issue to update the response to include the number of results per page in the response.

Make perPage default for pagination match the API

---

src/amo/components/ScreenShots.js

Fixes #1712 
Original function is here: https://github.com/minhtranite/react-photoswipe/blob/05602e52755cc69d1f530a64a65cc5b6b0b225b9/src/PhotoSwipeGallery.js#L36
This is a bit of a hack but it overloads the function used to get thumbnails so that the second time photoswipe is loaded it continues to work.
This will need coverage (or skips to coverage) but if you have a moment it would be spin this up in review and check it solves the problem.

Hack around bug in PhotoSwipe

---

src/amo/routes.js
tests/server/amo/TestViews.js

Kinda sorta addresses https://github.com/mozilla/addons-frontend/issues/1975
Dumbest fix ever? I couldn't fully test this locally but doing `curl -I http://localhost:3000/en-US/firefox/user/eXXile/` gave me a 500 before and a 404 after. I think our local proxy script is a little different which is maybe why I couldn't fully reproduce it when clicking on a user link from the details page.

Force a 404 on user pages

---

src/core/css/inc/mixins.scss
src/ui/components/SearchInput/style.scss

Fixes #1986 
Beyond the text overflowing there was also a problem of horizontal scrollbars too.
Before: 
After:

Fix horizontal scrollbars for search

---

config/default-amo.js
config/default.js
src/core/middleware.js
src/core/utils.js
tests/client/core/test_middleware.js

fix #1867
fix #1991
Sorry, more `middleware.js` URL handling. This patch allows root URLs like `/downloads/*` or `/contribute.json` to be served properly without infinite redirects.

fix: add locale URL exception (fix #1867)

---

config/default-amo.js

In [testing prod](https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-Testingaddons-frontendAMOinProd) I see the following CSP errors (screenshots). This adjusts the config to fix them.

Allow font-src in CSP rules for AMO prod

---

src/amo/routes.js
tests/server/amo/TestViews.js

Temporary workaround for https://github.com/mozilla/addons-frontend/issues/2029
The real fix will arrive in https://github.com/mozilla/addons-server/pull/4890

Force all /users/ URLs to be served by addons-server

---

src/amo/routes.js
tests/server/amo/TestViews.js

This will make https://github.com/mozilla/addons-frontend/issues/2037 go away but only until we shadow some other URL.
This reverts commit f42934e542ae7383a8302296d85ac7255238177c because a 500 is going to be more helpful until we have implementations of these pages.

Revert "Force all /users/ URLs to be served by addons-server (#2034)"

---

src/amo/css/AddonDetail.scss

Turns out I *did* have those styles in there but I forgot to update the component name during a refactor. 🎉

fix: Uncramp compatibility error (fix #2048)

---

config/default-amo.js
config/default.js
src/amo/routes.js
src/core/middleware.js
src/core/utils.js
tests/client/core/test_middleware.js
tests/server/amo/TestViews.js

Adds a config that prevents trailing slashes from being added to certain URLs.
fixes #2037

Fix redirect loop

---

package.json
src/amo/components/AddonCompatibilityError/index.js
src/amo/components/ErrorPage/NotAuthorized/index.js
src/amo/components/ErrorPage/NotFound/index.js
src/amo/components/ErrorPage/ServerError/index.js
src/amo/containers/Home.js
src/core/components/ErrorPage/GenericError/index.js
src/core/components/ErrorPage/NotFound/index.js
src/core/i18n/utils.js
tests/client/helpers.js
webpack.l10n.config.babel.js
yarn.lock

Fixes #2059
I've now updated the fork of babel-gettext-extractor [1] after a bit of a clean-up and overhaul adding more tests and fixing up the lint.
This branch updates to the rev of that lib with the new features this now supports removing leading indents from extracted values. 
This patch also wraps our Jed instance functions to support stripping the same indent from keys because otherwise the lookups would fail. This means from now on any multiline translations should use untagged template literals and not use dedent or oneLine. 
I'll also add a commit to this to update the docs so it's clear and we should also look to add a eslint rule to check for tagged template literals as args to any Jed gettext methods.
Lastly to ensure tests see the actual Jed output this changes the FakeJed to …

Strip indent from extract and gettext

---

config/default-amo.js
config/default.js

This will fix https://github.com/mozilla/addons-frontend/issues/2106 and probably other things in the future that we'll forget about.

Stop defaulting to Sentry prod for client side errors

---

src/ui/components/Rating/index.js
tests/client/ui/components/TestRating.js

Sorry I said I tweaked this locally and forgot to push. Just doesn't bother making a difference between `readOnly` and not `<Ratings>` for half-stars.

Allow non-ints for readOnly (#1888)

---

src/disco/containers/DiscoPane.js
tests/client/disco/containers/TestDiscoPane.js

This fixes #765, so our tests shouldn't have memory leaks and also shouldn't spook me when I'm testing with loud volume settings late at night.

fix: Don't play the disco pane video in tests (fix #765)

---

src/disco/constants.js

identified via https://ftp.mozilla.org/pub/system-addons/

add 2 new System Add-ons

---

webpack.prod.config.babel.js

This saves about 6kB which is pretty tiny, but it might save more in the future and is worth doing. It's an easy optimisation so why not?

fix: Remove all comments from production build (fix #2113)

---

src/core/reducers/categories.js
tests/client/core/reducers/test_categories.js

fix #2170
Similar to the solution used for searching Android Themes, except we patch the data in the reducer/state instead of the API call because the category list API just returns all categories for all clientApps.

fix: Use Firefox categories for Android themes (fix #2170)

---

src/ui/components/Rating/styles.scss

Fix half-stars for RTL

---

config/production.js

Fixes https://github.com/mozilla/addons-frontend/issues/2016
Errors are hooked up so we don't need to expose this anymore.

Disable error simulation in prod

---

src/core/utils.js
tests/client/core/test_utils.js

Fixes https://github.com/mozilla/addons-frontend/issues/2211
I tried to make a smarter test for this that sets up a `safeAsyncConnect` decoration and makes sure `LOAD_FAIL` gets dispatched but I think it's too difficult because of `redux-connect`'s reliance on middleware. Oh well. I manually tested it after this patch and `LOAD_FAIL` actions are getting dispatched.

Fill in empty safeAsyncConnect keys to preserve LOAD_FAIL

---

src/core/constants.js
src/core/css/inc/vars.scss
src/core/errorHandler.js
src/core/reducers/errors.js
src/ui/components/ErrorList/index.js
src/ui/components/ErrorList/styles.scss
tests/client/core/reducers/test_errors.js
tests/client/core/testErrorHandler.js
tests/client/ui/components/TestErrorList.js

Fixes https://github.com/mozilla/addons-frontend/issues/2238
This is a baby step toward helping users cope with expired sessions. It's definitely not ideal but it's a quick patch that may be worth landing. 
Here are some things to do later:
* We can probably set a timer and anticipate when a session will expire and change the state. This is a harder patch and will be done in https://github.com/mozilla/addons-frontend/issues/2237 Even after doing that patch, it will still be possible to get a signature expired result though (because the timer won't be exact).
* ~~We can switch to detecting a code instead of the 'Signature expired' string, which is https://github.com/mozilla/addons-server/issues/5122~~
* ~~I thought it would be nice to show a better message like 'Your session has expired. …

Prompt the user to refresh the page if their session expires

---

src/core/components/Paginate/Paginate.scss
src/core/css/inc/mixins.scss

fix: Make search result pagination match the UI mock

---

src/core/constants.js
src/core/installAddon.js
src/core/reducers/installations.js
tests/client/core/TestInstallAddon.js
tests/client/core/reducers/test_installations.js

Fixes #1435.
Allows an installation to be cancelled after the switch is toggled on. Resets the switch to uninstalled.
Screenshot:

Handle cancelled install

---

src/amo/css/AddonReviewList.scss

Fix wrapping to break long strings but leave words intact

---

src/amo/api/index.js
src/amo/components/AddonReviewList.js
src/amo/components/RatingManager/index.js
tests/client/amo/components/TestRatingManager.js
tests/client/amo/testApi.js

Fixes https://github.com/mozilla/addons-frontend/issues/2325
This is the quickest fix I can think of but it needs some follow-up. This works around the new logic introduced by https://github.com/mozilla/addons-server/pull/5227 which now hides empty reviews (i.e. star ratings) by default. I'd like for it not to hide star ratings by default but let's do that in future patches. For now, this passes authentication to the API for list requests which will unhide reviews created by the current user.

Fix editing of star ratings by adding auth to API request

---

src/core/themePreview.js
tests/client/core/TestThemePreview.js

Fixes: #1572 
Added description key to themeData and modified the corresponding test

fix: If installing a theme from Disco Pane, the description will not be displayed in more section for that theme

---

src/amo/components/AddonDetail.js

Remove noop ngettext usage from amo

---

package.json
tests/.eslintrc

I spent a few hours doing mindless tile replacement so I felt like doing mindless code linting cleanup too. 😉 
Adds returns to all Promises and ensures all test code that
uses a Promise returns it so all code is executed.
This is a lot of noise but and makes for slightly more verbose
tests with "needless" `return true;` statements, but it will
prevent us from writing unexecuted test code in the future. 👍🏻
-----
This ends up making the code a fair bit more verbose but I think it's worth it. I know it looks like a lot of noise here but it keeps us writing smarter Promises.

chore: Add eslint rule for Promises (fix #2065)

---

package.json

This restores the loading bar, tested locally with a prod build.

fix: Downgrade react-redux-loading-bar (fix #2395)

---

.eslintrc
src/admin/containers/AddonPage/index.js
src/amo/components/Categories.js
src/amo/components/SearchSort/index.js
src/core/components/Paginate/index.js
src/ui/components/ErrorList/index.js
src/ui/components/Rating/index.js
tests/client/amo/containers/TestApp.js

Enable eslint rule for missing jsx keys

---

src/amo/components/AddonMoreInfo.js
src/amo/components/Link.js
tests/client/amo/components/TestAddonMoreInfo.js
tests/client/amo/components/TestLink.js

Fixes #2419.
Simple fix to add clientApp and locales to `<Link href="/foo">` urls.

Prefix url

---

src/core/reducers/categories.js

This fixes #2443 and just stops spamming the logs, really. It shouldn't really happen outside tests anyway.

fix: Protect against empty category results (fix #2443)

---

bin/config-check.js

We still have tests that rely on the production config so local files will pollute those tests.

Reverts the change that allowed local production configs

---

src/core/i18n/utils.js

Fixes #2471 
Fixes #2472
Fixes #2470
Intl object is not available on FF Android until v54 see https://bugzilla.mozilla.org/show_bug.cgi?id=1215247

Fallback to number.toLocaleString when Intl not available

---

README.md

Restores the CI script info in the README.

docs: Restore `test-ci` to README (see #2474)

---

README.md

Fixes #2487
I missed this reading the docs then remembered it but I think calling extra attention to it is worthwhile. Maybe we should even have a "build prod" shortcut command that creates this file and does the `build && start` dance.
Now that the tests yell at you for having a `config/local-production-amo.js` it might be nice to be able to easily create one. (My editor ignores files in `.gitignore` so making it is extra annoying, heh)

docs: Make need for local config extra clear

---

.flowconfig
flow/libs/intl.js.flow
src/core/i18n/utils.js

This is a follow-up to https://github.com/mozilla/addons-frontend/pull/2480
I think this would be useful because we won't forget to be protective about accessing the `Intl` object in the future. If you forget to check it, you get:
```
src/core/i18n/utils.js:248
248:     return new Intl.NumberFormat(lang).format(number);
^^^^^^^^^^^^ property `NumberFormat`. Property cannot be accessed on possibly undefined value
248:     return new Intl.NumberFormat(lang).format(number);
^^^^ undefined
```

Add Flow types for the Intl object

---

flow/libs/intl.js.flow
src/core/i18n/utils.js

Fixes #2500
After using the flow env to try things out with a reduced test case this seems to work. It appears that you can't use `|` for global definitions or at least removing that makes it work.
See: http://bit.ly/2rI8UbW for the try flow env to see the reduced test case. (Works better in Chrome sadly)

Fix flow defs for Intl

---

docs/adding-a-page.md
src/core/actions/index.js
src/core/constants.js
src/core/reducers/authentication.js
tests/client/core/reducers/test_authentication.js

Fixes #2495.
I added a note to the `adding-a-page.md` doc just to mention it's quite out of date... and at least our saga usage is in `Categories.js` as a stop-gap until we make new docs.

Remove setCurrentUser

---

src/disco/constants.js

via https://ftp.mozilla.org/pub/system-addons/disable-ocsp-stapling/
and the other just got added to Nightly with the flag: isSystem = true

add 2 new system addons

---

README.md
docs/i18n.md

Closes https://github.com/mozilla/addons-frontend/issues/2543

Document the weekly locale extraction process better

---

src/amo/components/SearchSort/SearchSort.scss
src/amo/components/SearchSort/SearchSortLink.scss
src/core/components/Paginate/Paginate.scss

Closes #2436.
Fixes the search sort to not have a text-shadow after a button refresh.
In the future (as I redo the search page for desktop) the search sort could do with a general CSS cleanup but this fixes the issue for now.

fix: Button text-shadow and hover in SearchSort

---

src/amo/components/Header/styles.scss

fix: Hide devhub links on smaller screens

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fixes #2545
We were relying on weird object spread for this in the past and with the cleanup it got removed. Added a few tests so hopefully we don't get bit by this again.

fix: Use installStatus, not add-on status for InstallButton (fix #2545)

---

src/ui/components/Icon/styles.scss

Makes sure the fox icon doesn't get cut off.

fix: Fix the header when header is verbose (fix #2547)

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/amo/components/AddonMeta.js
src/amo/components/AddonMoreInfo.scss
src/amo/components/App/styles.scss
src/amo/components/SearchForm.scss
src/amo/css/AddonMeta.scss
src/core/css/inc/mixins.scss
src/ui/components/Card/Card.scss
src/ui/components/Card/index.js
src/ui/css/vars.scss
tests/unit/ui/components/TestCard.js
webpack-common.js

This is the first crack at a responsive detail page for extension. Fixes #2430.
Note that I reversed the screenshots and info from the mocks because of #2550. I'd argue this closes #2550 if there aren't any complains from UX.
-----

Create responsive detail page

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/amo/components/RatingManager/index.js
src/ui/components/Rating/vars.scss

Adds support for themes on the desktop site and fixes issues from the last update.
This also improves the HTML and CSS used to create the same page for extensions (#2430).
-----------------
-----------------
-----------------
-----------------

feat: Add desktop version of theme page (fix #2559)

---

src/amo/components/Addon/styles.scss

Fixes #2430 
Fixes #2570
Fix issues with Theme page details.

fix: Theme pages at different sizes (fix #2570)

---

src/core/css/inc/mixins.scss

Fixes #1904 by removing the hover styles on mobile browsers for buttons with a media query. Added some docs and a link to https://css-tricks.com/annoying-mobile-double-tap-link-issue/#article-header-id-2 because this one was weeeeeird.

fix: Don't force two taps on mobile <button> (fix #1904)

---

package.json

Fixes: #2489 
Modified `test-once` to include lint tests

fix: yarn test no longer runs lint test

---

src/disco/css/Addon.scss
src/disco/css/App.scss

Fix Disco buttons

---

src/core/components/AuthenticateButton/index.js
src/core/css/inc/mixins.scss
tests/unit/amo/helpers.js
tests/unit/core/components/TestAuthenticateButton.js

Fixes #1904
This is frustrating but because the `<button>` element used for the "Log in to review this extension" button doesn't actually relate to anything the mobile browser will use its hover and focus states after first tap. It's a mess.
The easiest fix is to put a `href="#"` on it and turn it into a link. That isn't great but it's the best we can do for now.

fix: Log in button works on first click

---

src/amo/components/AddonCompatibilityError/style.scss
src/core/css/inc/vars.scss
src/ui/components/ErrorList/styles.scss

Fix #2577
Improves the compatibility styling.

fix: Improve compatibility warning

---

src/amo/components/Addon/index.js
src/core/reducers/addons.js
tests/unit/amo/components/TestAddon.js
tests/unit/core/reducers/test_addons.js

Hide the "About this extension" when description and summary are blank.
Fixes #2233.
Fixes #2569.

fix: Don't spread theme_data description

---

src/amo/components/SectionLinks/styles.scss
src/ui/components/SearchInput/style.scss
src/ui/css/vars.scss

Fix #2189.
I opted for `#ffffff` at 50% opacity because it's what we're using in the section links right above the search form. I think it looks better as the "out of focus" colour in the header. @pwalm: let me know if that's okay or if I should still use `#dcdcdc` as the bug said.

Make palceholder text in header lighter

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fixes #2630
@tofumatt whoops, turns out there were two instances of 'No reviews yet' so I missed one. Here it is fixed:

Show 'Rate your experience' placeholder on Addon detail

---

config/test.js
src/amo/actions/reviews.js
src/amo/api/index.js
src/amo/components/Addon/index.js
src/amo/components/AddonReviewList.js
src/amo/constants.js
src/amo/sagas/index.js
src/amo/sagas/reviews.js
src/core/sagas/addons.js
src/core/sagas/utils.js
tests/unit/amo/actions/testReviews.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/amo/sagas/testReviews.js
tests/unit/core/sagas/testAddons.js

Convert AddonReviewList to a saga

---

src/amo/components/AddonsCard/index.js
src/amo/components/AddonsCard/styles.scss
src/amo/components/FeaturedAddons/FeaturedAddons.scss
src/amo/components/LandingAddonsCard/index.js
src/amo/components/Search/styles.scss
src/amo/components/SearchForm.scss
src/core/css/inc/mixins.scss
src/ui/components/Card/Card.scss
src/ui/components/CardList/index.js
src/ui/components/CardList/styles.scss
src/ui/css/vars.scss
tests/unit/amo/components/TestSearchResult.js

Add a horizontal result card according to mocks.
Fixes #2640.
These only appear on desktop; other pages should largely remain the same.

Different size addon cards

---

src/amo/components/AddonsCard/styles.scss

Very minor fix, I didn't catch this in the new card PR.
Fixes #2645
Fixes #2605
Closes #2610

fix: Padding on rtl horizontal cards

---

src/amo/components/Addon/index.js
src/core/constants.js
tests/unit/core/reducers/test_categories.js

fix: Complete themes are valid add-ons

---

src/amo/components/CategoriesHeader/styles.scss

This is a bit of a stop-gap if we end up implementing #2662, but it was easy so why not?

fix: Uncentre categories (fix #2660)

---

src/amo/components/Category/index.js
tests/unit/amo/components/TestCategory.js

Fix #2650.
Looks like we should improve the `hasSearchParams` in general, but this came about because we were still including a component named `Search` but it was changed to include `mapStateToProps` and was overriding our overrides 😒
Added a test to make sure that component is the right one and the flag is set.

fix: Show search results for categories

---

src/amo/components/Addon/styles.scss

Fixes #2654
Really simple, just prevents huge displays from stretching the text across hundreds of pixels.

fix: Limit width of addon description

---

src/amo/components/Home/index.js

Fixes #2685: Renaming slugs as per categories slug
**Before**
**After**

Rename Invalid category slugs in Homepage

---

src/amo/components/CategoryHeader/styles.scss

Fixes: #2688 
Removed white background to align category header correctly
After background removal -

fix: Categories titles are not correctly aligned

---

src/amo/components/LandingPage/styles.scss

Fixes #2689 
**Before:**
**After:**

Extensions page title is not correctly aligned in RTL #2689

---

package.json

Closes #2209.
Just changed `import createLogger from 'react-redux';` to `import { createLogger } from 'react-redux';` as https://github.com/evgenyrodionov/redux-logger/releases/tag/3.0.0 recommends. Tested and it passes tests and logs in browser 👍

fix(package): update redux-logger to version 3.0.6

---

.travis.yml

Trying this to see what happens, because these constantly "failing" tests are annoying and a bad thing–they're gonna make me think something is fine when it isn't soon.

fix: Disable docker log for now to fix tests

---

src/disco/components/Addon.js
src/disco/components/AddonCompatibilityError/index.js
src/disco/components/AddonCompatibilityError/style.scss
src/disco/css/Addon.scss
src/disco/css/App.scss
src/ui/css/vars.scss
tests/unit/disco/components/TestAddon.js
tests/unit/disco/components/TestAddonCompatibilityError.js

Working on showing errors in the disco pane; tests are failing right now and it's low-priority so just leaving here now but will revisit later.

feat: Show compatibility errors in Disco Pane (fix #2095)

---

src/core/installAddon.js
tests/unit/core/TestInstallAddon.js

Fixes https://github.com/mozilla/addons-frontend/issues/2314
Before the fix:
After the fix:
Here's another one after the fix that shows confirming the installation:

Enter installing state after download ends

---

src/amo/css/AddonMeta.scss

Fixes #2587 
For some Languages the character length for translation of `User` and `reviews` is long hence breaking alignment of review starts. This fixes them.

Rating Star Alignment Issue

---

src/amo/components/AddonsCard/index.js
src/amo/components/SearchResult/index.js
src/amo/components/SearchResult/styles.scss
tests/unit/amo/components/TestSearchResult.js

Fixes https://github.com/mozilla/addons-frontend/issues/2742
This patch doesn't apply it anywhere but here's an example of what's possible:

Allow search results to load without add-on data

---

package.json

adds an "engine" section so that Node can be pegged to a secure (LTS) version - see https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

Make sure things run on a secure version of Node.js

---

src/core/server/base.js
src/core/tracking.js
tests/unit/core/test_tracking.js

Fix #2792.
This patch disables the GA script from being included and sets Tracking as being off when DNT is set. It respects this on both the server and client.
Works for both AMO and the Disco Pane, so that's cool 👍 
Tested locally with tracking set to enabled and DNT on/off and things worked as expected.
One review for this should be fine, whoever can get to it first 😄

feat: Disable tracking/Google Analytics when DNT is enabled

---

src/amo/components/AddonsCard/styles.scss

fix: Restore grid styles to horizontal addons card

---

README.md
config/custom-environment-variables.json
docs/index.md
docs/using-the-staging-sites-api.md
package.json
src/core/middleware/security.js
tests/unit/core/middleware/test_cspMiddleware.js

Close #2535.
Add some docs and a few convience commands to run the dev server with:
* dev/staging API data
* dev/staging CDN setting
* `CSP: false` so the CDN data is loaded
Given this is often how we develop locally anyway I figured these settings were alright.

feat: Add command to run dev:amo with staging data

---

src/amo/css/AddonMeta.scss

fix: Tweak rating star alignment in addon detail header

---

src/amo/css/ScreenShots.scss

Fixes #2821  hide vertical scrollbar in Screenshots section from add-ons detail page

Fixes #2821 hide vertical scrollbar in Screenshots section from add-ons detail page

---

src/amo/components/AddonsCard/styles.scss
src/amo/components/SearchResult/styles.scss

feat: Improve font/line-height on horizontal addons cards

---

src/amo/components/Category/index.js
tests/unit/amo/components/TestCategory.js

Fix #2846.
We weren't checking to see if we had *any* category data yet (or even did a proper loading check) so we'd hit a temporary 404 screen during the load. Because we fetch all categories at once this just marks whether or not we've fetched them and only renders a 404 for a non-existent category once we've compared it to the fetched categories.

fix: Categories temporary 404 while loading

---

src/ui/components/ShowMoreCard/ShowMoreCard.scss

Workaround transparency issue in Safari

---

src/amo/components/Addon/styles.scss

Fix screenshots overlap in safari

---

.flowconfig
src/amo/components/App/index.js
src/disco/containers/App.js
tests/unit/amo/containers/TestApp.js
tests/unit/core/server/testServer.js
tests/unit/disco/containers/TestApp.js

Fixes https://github.com/mozilla/addons-frontend/issues/2886
**The problem:**
The [fix for Category 404s](https://github.com/mozilla/addons-frontend/pull/2684/files#diff-4623346018e51a6970a0e7b3ffb9e325R38) introduced a scenario where the [first render](https://github.com/mozilla/addons-frontend/blob/a1ccd6fde1b87c536046f69b9ec32f3888262e31/src/core/server/base.js#L312-L314) of the app declares a 404 status code but [later](https://github.com/mozilla/addons-frontend/blob/a1ccd6fde1b87c536046f69b9ec32f3888262e31/src/core/server/base.js#L320-L323) it does not. In the final successful render, nothing was declaring a 200 status code.
This bug was probably happening in a few other parts of the app too.
**The solution:**
Both AMO and Discopane will now always declare a 200 status code by …

Make sure all apps set a default status code

---

src/amo/components/Categories/index.js
src/core/reducers/categories.js
tests/unit/amo/components/TestCategories.js
tests/unit/core/reducers/test_categories.js

#2855 Categories were not alphabetically sorted. 
- Added a sorting function. 
- This can be added as a helper function if it's going to be reused.

Fixes #2855 Categories are not alphabetically sorted 

---

src/amo/components/AddonReview.js
src/amo/components/AddonReviewList.js
src/amo/components/Categories/index.js
src/amo/components/Category/index.js
src/amo/components/FeaturedAddons/index.js
src/amo/components/LandingPage/index.js
src/amo/components/Search/index.js
src/core/errorHandler.js
src/disco/containers/DiscoPane.js
tests/unit/core/testErrorHandler.js

Fixes #2929
---
This PR introduces a `renderErrorIfPresent()` method to the `ErrorHandler` as requested in #2929.

Add renderErrorIfPresent() method in ErrorHandler

---

tests/unit/amo/actions/test_featured.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonReview.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/amo/components/TestCategories.js
tests/unit/amo/components/TestCategory.js
tests/unit/amo/components/TestFeaturedAddons.js
tests/unit/amo/components/TestLandingPage.js
tests/unit/amo/components/TestSearch.js
tests/unit/amo/sagas/testCategories.js
tests/unit/amo/sagas/testFeatured.js
tests/unit/amo/sagas/testLanding.js
tests/unit/amo/sagas/testReviews.js
tests/unit/core/actions/test_addons.js
tests/unit/core/api/test_api.js
tests/unit/core/sagas/testAddons.js
tests/unit/core/sagas/testSearch.js
tests/unit/disco/containers/TestDiscoPane.js
tests/unit/disco/sagas/testDisco.js
tests/unit/helpers.js

Fixes #2936 
---
This PR introduces a new test helper `createStubErrorHandler()`, which takes a `capturedError` optionally. I have left all `ErrorHandler` objects relying on a custom `dispatch` as is.

Add createStubErrorHandler() helper in test suite

---

src/amo/components/RatingManager/index.js
src/core/errorHandler.js
tests/unit/core/testErrorHandler.js

Fixes #2931 
---
Rename a HOC to avoid confusion, cf. #2931.

Rename withErrorHandling() to withRenderedErrorHandler()

---

src/amo/components/SearchResult/index.js
src/amo/reducers/landing.js
tests/unit/amo/reducers/testLanding.js

Fixes #2882 
---
This PR enables the loader when we change from one landing page to another by resetting the add-ons sets when a new request is triggered. In addition, I fixed a visual glitch by reducing the size of the loader related to the number of users (a width of `100%` put the loader on a new line).

Show loading indicators when switching between landing pages

---

src/amo/components/AddonsCard/index.js
src/amo/components/Categories/index.js
src/amo/components/Category/index.js
src/amo/components/CategoryHeader/index.js
src/core/components/Paginate/index.js
src/core/components/PaginatorLink/index.js
src/core/reducers/categories.js
src/core/server/base.js
src/core/utils.js
src/ui/components/Rating/index.js
tests/unit/amo/components/TestCategories.js
tests/unit/amo/components/TestCategory.js
tests/unit/amo/helpers.js
tests/unit/core/reducers/test_categories.js
tests/unit/core/test_utils.js

Fixes https://github.com/mozilla/addons-frontend/issues/2949
Notes:
* `Category` loads data only when needed now
* `Search` is rendered while loading which is necessary so it can dispatch its own loading actions
* Category state is initialized properly but that required some re-design of a few things
* I spent extra time making sure the test coverage was right since this fixed a serious bug
* I was relying server logging to track this down so I cleaned up a bunch of PropType typos
* Since we need to cherry-pick this ASAP, I can address minor change requests in a follow-up

Fixes category loading problem (server side)

---

src/amo/components/FeaturedAddons/index.js
src/amo/components/FeaturedAddons/styles.scss
tests/unit/amo/components/TestFeaturedAddons.js

fix: Use AddonsCard instead of SearchResults for featured (fix #2957)

---

bin/proxy.js
config/custom-environment-variables.json
package.json

Fixes #2941 
This does a few things:
* Both `amo:dev` and `amo:stage` go through the proxy which means both the frontend site and the backend API are served on the same domain like production. This should help catch same origin issues locally.
* Sign-ins work on `amo:dev`
* Sign-ins do not work on `amo:stage` (like before) because we need to configure a new FxA client. I'll do that in a follow-up.

Fix sign-in while running a server from amo:dev

---

package.json
yarn.lock

This reverts commit ea532fc095269de702bf4f68fecfe00de063dea8.
Fixes #2981.
[Looks like this will be fixed in `1.0.2`](https://github.com/cure53/DOMPurify/issues/249) but that isn't out yet. For now we'll revert things so we can run stuff on -dev and can tag later today without needing to cherry-pick the 1.0.2 release.

Revert "fix(package): update dompurify to version 1.0.1 (#2974)"

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/core/reducers/addons.js
src/ui/components/Badge/index.js
src/ui/components/Badge/styles.scss
src/ui/components/Icon/restart.svg
src/ui/components/Icon/styles.scss
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/amo/helpers.js
tests/unit/core/reducers/test_addons.js
tests/unit/disco/containers/TestDiscoPane.js
tests/unit/ui/components/TestBadge.js

Fix #2753 
Fix #2990 
~~⚠️  depends on #2972~~
---
Adds a new badge for addons that need restart. Note: I used the same tip as for the `installURL` field to expose `is_restart_required`.

	Add badge for needs restart

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fix #3017
---
This PR updates an addon page whenever its slug changes.

Fetch addon on slug update

---

src/amo/components/SearchForm/index.js

Fix #3028 
---
Because there is already a textual content on this button, I do not think the `title` attribute adds anything meaningful.

Remove confusing/redundant title attribute on search button

---

package.json
src/amo/components/RatingManager/index.js
src/amo/sagas/index.js
src/amo/store.js
src/core/api/index.js
src/core/api/user.js
src/core/components/AuthenticateButton/index.js
src/core/containers/LoginRequired/index.js
src/core/reducers/api.js
src/core/reducers/user.js
src/core/sagas/user.js
src/core/server/base.js
tests/unit/amo/components/TestRatingManager.js
tests/unit/amo/helpers.js
tests/unit/amo/test_store.js
tests/unit/core/api/test_index.js
tests/unit/core/api/test_user.js
tests/unit/core/components/TestAuthenticateButton.js
tests/unit/core/containers/TestLoginRequired.js
tests/unit/core/containers/TestServerHtml.js
tests/unit/core/reducers/test_api.js
tests/unit/core/reducers/test_user.js
tests/unit/core/sagas/test_user.js
tests/unit/core/server/testServer.js
tests/unit/helpers.js
yarn.lock

Refs #1820 #1644 #1751
---
This PR does a few things, but the main goal was to fetch the current logged user profile. I hooked into the `SET_AUTH_TOKEN` action to fetch the user profile with a saga. This action is cool because it is used in both SSR and not SSR.
- The `userId` has moved to the `user` reducer now (it was in `api` since #2983).
- I removed the JWT token parsing to exclusively rely on the user profile data. This is now gone forever, but if we want to validate this token somehow, maybe we could re-introduce the method with a different name, _i.e._ `validateToken()`.
- a `user` ducks that owns the current logged user profile
- a `user` saga that fetches the user profile on `SET_AUTH_TOKEN`
- a selector `isAuthenticated` in `user` reducer to know whether user is logged in

Retrieve user profile on SET_AUTH_TOKEN 🔥

---

src/disco/css/inc/vars.scss

Heh, these colours are _very_ similar but this updates the Disco Pane's background colour for Photon styles.
fixes #2938

chore: Change Disco Pane background for Photon (fix #2938)

---

src/amo/components/SearchFilters/styles.scss

fix: RTL arrow for search filters

---

src/core/sagas/autocomplete.js
tests/unit/core/sagas/test_autocomplete.js

Fix #3031 
---
This PR cancels the autocomplete saga when `AUTOCOMPLETE_CANCELLED` is fired.
According to the [redux-saga doc (bottom)](https://redux-saga.js.org/docs/advanced/TaskCancellation.html), `race` should be used for automatic cancellation and that's why I used it. I made sure that the saga could be run again, even after cancellation (my first attempt was to use `cancel` but that cancelled the whole saga, and I could not run it again...).

Cancel autocomplete saga on AUTOCOMPLETE_CANCELLED

---

src/amo/components/Category/index.js
src/amo/components/SearchPage/index.js
tests/unit/amo/components/TestCategory.js
tests/unit/amo/components/TestSearchPage.js

Fixes #3039.
This is sort of a stop-gap as we *should* eventually support filters here. But we didn't before so this at least prevents the bug.

fix: Remove filters from categories

---

src/ui/components/ShowMoreCard/index.js
tests/unit/ui/components/TestShowMoreCard.js

Fix #3026 
---
This PR fixes an issue when the description of an add-on has a smaller size than the previously browsed one.

ShowMoreCard should expand if updated content changes

---

src/amo/components/SearchForm/index.js
src/core/reducers/autocomplete.js
tests/unit/amo/components/TestSearchForm.js
tests/unit/core/reducers/test_autocomplete.js

Fix #3030 
---
This PR slightly changes the autocomplete feature to avoid too many API calls.
This was more complicated than I thought 😞 Hopefully the new test cases are meaningful enough but they should cover all the edge cases I encountered.

Avoid fetching suggestions all the time

---

src/ui/components/ShowMoreCard/index.js

Refs #3077 
---
This PR removes the `setState` async callback in `ShowMoreCard`.

Remove setState async callback

---

src/amo/components/SearchForm/index.js
src/core/reducers/autocomplete.js
tests/unit/amo/components/TestSearchForm.js
tests/unit/core/reducers/test_autocomplete.js

Fix #3078
Refs #3077
---
This PR reverts the trailing edge debouncing implementation introduced in #3065. It also get rid of the async `setState` callback. Last but not the least, it provides a different fix for the search input corners.
Having a `isOpen` in the reducer was misleading: with the recent `autocompleteCancel()` change (cancelling the API call and everything else), the input could be desynchronized. Now, the `SearchForm` is synchronized with `Autosuggest` at the component level and it works better.

Fix search input corners and autocomplete

---

src/amo/reducers/addonsByAuthors.js
src/amo/sagas/addonsByAuthors.js
src/amo/sagas/index.js
src/amo/sagas/landing.js
src/amo/store.js
src/core/api/index.js
src/core/api/search.js
src/core/sagas/search.js
src/core/searchUtils.js
tests/unit/amo/reducers/test_addonsByAuthors.js
tests/unit/amo/sagas/testLanding.js
tests/unit/amo/sagas/test_addonsByAuthors.js
tests/unit/amo/test_store.js
tests/unit/core/api/test_search.js
tests/unit/core/sagas/testSearch.js
tests/unit/core/test_searchUtils.js

Refs #2767
---
This PR adds a new reducer (`addonsByAuthors`) to deal with other add-ons by developers (see #2767). ~~It would make sense to put it into the `addons` reducer but I think we should not touch it anymore until #3024 is resolved.~~ That is why I created a new reducer.
There is also a saga to retrieve add-ons based on a set of authors. I set the number of results to retrieve for each author to `6` because it is the number of add-ons displayed [on the existing website](https://addons.mozilla.org/en-US/firefox/addon/english-gb-language-pack/). It is configurable in the reducer though.
I reused the same principle as in the [`reviews` reducer](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/reviews.js) and exposed a `byAddon` map.
It can be used as follows: …

Add new addonsByAuthors reducer/saga to retrieve other add-ons by these authors

---

src/amo/components/SearchForm/index.js
src/core/api/search.js
src/core/searchUtils.js
tests/unit/amo/components/TestSearchForm.js
tests/unit/core/api/test_search.js
tests/unit/core/test_searchUtils.js

Fixes #2706 by sending the operating system (basically only for desktop searches right now, as we filter for android compatibility with `clientApp` instead).

Send platform in search and autocomplete

---

src/amo/components/Footer/styles.scss
src/amo/components/Header/styles.scss
src/amo/css/inc/vars.scss

A few tweaks to tighten up the spec on the header. There's some ambiguity in the mocks/specs re:  the gutter size. I've gone for the smaller one represented in the mocks. We can always adjust with the var later. 
Overall this gives the logo more room to breath. I quite like how the intended design has the header and footer on a different grid to the main content.
Before large:
Before medium:
After large:
After medium (updated)

Tighten up header spec

---

src/disco/actions.js
src/disco/api.js
src/disco/containers/DiscoPane.js
src/disco/sagas/disco.js
tests/unit/disco/containers/TestDiscoPane.js
tests/unit/disco/sagas/testDisco.js
tests/unit/disco/test_actions.js
tests/unit/disco/test_api.js

Fixes https://github.com/mozilla/addons-frontend/issues/2823
This isn't very exciting because it doesn't do anything yet. We still need to figure out how to test it. All it does is prep us for when the Discopane gets loaded with a telemetry client ID. We pass that ID to the API request so that `addons-server` can mix in results from the add-on recommendation engine.

Send telemetry-client-id to the Discovery API

---

.eslintrc
src/amo/components/Header/index.js
src/amo/components/Link.js
src/core/components/AuthenticateButton/index.js
src/ui/components/DropdownMenu/index.js
src/ui/components/DropdownMenu/styles.scss
src/ui/components/DropdownMenuItem/index.js
src/ui/components/DropdownMenuItem/styles.scss
src/ui/components/Icon/inverted-caret.svg
src/ui/components/Icon/styles.scss
tests/unit/amo/components/TestHeader.js
tests/unit/amo/helpers.js
tests/unit/core/components/TestAuthenticateButton.js
tests/unit/ui/components/TestDropdownMenu.js
tests/unit/ui/components/TestDropdownMenuItem.js

Fix #1751 
Refs #2745
~~⚠️  depends on #2989~~
---
This PR introduces a new `DropdownMenu` component according to the recent mock-ups. It displays the username if she is logged in, and a simple menu linking to account view/edit and providing the "log out" action. This PR also fixes warnings related to the `Header` and `Link` components.

Add dropdown menu and display username (when logged in)

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fixes: #3061 
Unable to have screenshot as no addon gives `401` at local (or may be I am just unaware)
But I got 401 error from `addons.mozilla.org`

fix:Handles 401 error for unathuorized addons

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/amo/components/AddonsCard/index.js
src/amo/components/SearchResult/index.js
src/amo/css/inc/vars.scss
src/core/types/addons.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestSearchResult.js
tests/unit/amo/helpers.js

Fix #2767
~~⚠️ depends on #3027~~
---
This PR adds a new section on the add-on detail page to show related add-ons (made by any of the authors).
~~⚠️  I am waiting for https://github.com/mozilla/addons-server/issues/6346 to get more add-ons by authors. Right now, it does not work well (user `name` must be her `username`).~~ => available in `dev`.
The card is not displayed if there is no "other add-ons", which is the same behavior as the old website.

More add-ons by authors UI

---

src/core/css/inc/mixins.scss

Use photon colors for log in button

---

src/amo/components/Categories/index.js
src/amo/components/Categories/styles.scss
src/amo/components/CategoryHeader/styles.scss
src/ui/css/vars.scss

Fixes #3114 
This updates the category colours to match the current spec. Note the colours in the spec are not actually photon colours but they're photon-like hence not using the photon vars.
I removed the use of button default classes to reduce the specificity issues and make these links their own thing. This enabled dedicated hover/focus styling much more easily and avoiding the pale blue default.
The photon colours removal was to make sure we're using the packaged vars not hard-coded ones - despite me not using the vars in this patch the import was needed to expose the photon vars elsewhere.
I removed another un-used CSS variable here too.
Before: 
After:

Update category link colours

---

src/ui/components/LoadingText/styles.scss

Fixes #2899
This makes use of a photon grey which is lighter than the current grey used as the base colour for the loading indicator animations. I've reduced the lightest opacity so it doesn't get too light. 
Before (ignore the arrow it's not relevant to this)
After (updated to grey-30 after feedback)

Make the loading indicators more subtle

---

src/amo/components/Addon/index.js
src/amo/components/AddonMoreInfo/index.js
src/amo/components/AddonMoreInfo/styles.scss
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonMoreInfo.js

This PR looks huge because I moved the tests to enzyme (and thus had to change from using `ref` because `shallow` won't find refs. I like putting classNames on stuff anyway.
* Fixes #2750
* Fixes #3127 
Adds the add-on's database ID to the more info card. Useful for admins/debugging/etc.
Check out 62b85c0a607a35f0459425e0c51b47acdb1edb1f for the meat of the change.
------
While I was here it was super-easy to add LoadingText support to this component so I did:

Add add-on DB ID to MoreInfoCard

---

src/amo/components/Header/index.js
src/core/reducers/user.js
src/ui/components/DropdownMenu/styles.scss
tests/unit/amo/components/TestHeader.js
tests/unit/amo/helpers.js
tests/unit/core/reducers/test_user.js
tests/unit/helpers.js

Fix #3118
---
This PR adds the `displayName` to the `user` state and uses it in the menu when possible.
Before (or without a display name):
After (I usually don't use my second name but I needed it for testing 😛 ):

Add display name to user state and use it in menu

---

src/core/api/index.js
tests/unit/core/api/test_index.js

Fix #3138
---
This PR prevents the client to call the API with URLs encoded twice. Encoding should only be forced on the server, see #1920.

Avoid encoding the slug twice on the client

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
tests/unit/amo/components/TestAddon.js

Fix #3123
---
This PR fixes a CSS grid issue that prevented the theme description to be shown when other add-ons by the artists are displayed. It sticks to the mock-ups and works perfectly on FF 55, FF Nightly and Chrome/Opera. It should work with short/long description, and no/one/many other add-ons.
⚠️ This is a "better-than-nothing" yet pixel-perfect fix. I spent too much hours on it and @tofumatt helped a lot too! I don't know if there is a better "css grid way" of doing this but this works without `margin` hacks or similar. Please see all the screenshots to see all the edge cases.

Show description for themes

---

src/amo/components/ScreenShots.js
tests/unit/amo/components/TestScreenShots.js

Fix #2571.
Well, this wasn't hard.
The `Screenshots` component we're using frustratingly *requires* height and width params so I couldn't just leave this blank or set them to `100%`, but this works well enough as it's as big as the max size of the size and are basically as big as the screenshots come down the wire from AMO anyway, for now.

fix: Make screenshots big

---

src/amo/components/ScreenShots.js
tests/unit/amo/components/TestScreenShots.js

I forgot to commit @willdurand's suggestion that I export constants in #3163. If this passes I'll merge it as it's just a fixup from r+wc'd code.

chore: Use constants for screenshots

---

src/core/containers/ServerHtml.js
tests/unit/core/containers/TestServerHtml.js

Fixes https://github.com/mozilla/addons-server/issues/6431
This is a quick fix to cache-bust the favicon on the frontend. 
Longer term we may as well point directly to the resource to save on a redirect. I'll file a separate issue for doing that if we don't have one already.

Quick fix to cachebust favicon

---

src/ui/components/ShowMoreCard/index.js
tests/unit/ui/components/TestShowMoreCard.js

Fixes: #3148 
**Before:** 
**After:**

fix: Read more link doesn't show more content for release notes

---

src/disco/css/Addon.scss

add in line under themes

---

src/amo/components/SearchContextCard/index.js
tests/unit/amo/components/TestSearchContextCard.js

Fixes #3154 
------------
This PR fixes the `Search Header mention type issue` which appears while searching a query.
I've updated the `SearchText` string by using `addonType` from `filters` which fixes this bug. Also, changed the `addonType` text to plural if search results are more than 1.
* Test Case: **All Passed**
* Search Preview after the fix:
* After updating test cases
Thanks!

Fix Search header doesn't mention type #3154

---

src/amo/components/SearchForm/styles.scss

Fixes: #3184 
**Before:**
**After:**

fix: Make the search look more obviously focused

---

.nsprc

See #3195.
As discussed because we don't use `FetchExternalResources` for JSDom it seems we're all good here.

chore: Ignore nsp issue for JSDom

---

src/amo/components/Addon/index.js
src/amo/components/AddonReviewList.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonReviewList.js

Fix #3218
Adds to #2769 
This deals with 403 errors, and shows them as 404 errors for addons and addon-review pages.

fix: Handles 403 for addons and reviews

---

src/core/api/index.js
src/core/api/search.js
src/core/searchUtils.js
tests/unit/core/api/test_index.js
tests/unit/core/test_searchUtils.js
tests/unit/helpers.js

Fix #3209
Creates a helper function to deal with adding version compatibility because we do this in two places now.
This just makes sure autcomplete results won't surface incompatible add-ons, because that's a bad UX.

fix: Limit 57+ autocomplete to compatible add-ons

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
tests/unit/amo/components/TestAddon.js

Fix #3226
This fixes a lot of issues with the addon detail's page grid. As we add more content (generally to the left side) we get weird mismatches.
Maybe we shouldn't even be really using grid here as we seem to nearly always have one huge item off to the right and a bunch of smaller ones to the left. For now this fixes the layout issues we hit.
Here are a tonne of screenshots showing it working:

fix: Prevent grid issues on Addon Details page

---

package.json
src/amo/components/AddonMoreInfo/index.js
src/amo/components/ReportAbuseButton/index.js
src/amo/components/ReportAbuseButton/styles.scss
src/core/api/abuse.js
src/core/css/inc/mixins.scss
src/core/reducers/abuse.js
src/core/sagas/abuse.js
src/ui/components/Button/Button.scss
tests/unit/amo/components/TestReportAbuseButton.js
tests/unit/core/api/test_abuse.js
tests/unit/core/reducers/test_abuse.js
yarn.lock

Fixes #2759.
Allows a user to report an add-on for abuse. This uses a new inline form that I didn't bother to abstract for now, but it should be pretty easy to do if we use this UI elsewhere. It could be tweaked a bit but the UX is a lot nicer than a modal.
It logs reported add-ons in the reducer so once you've reported an add-on, at least for the current session (until a full page reload, because abuse reports are stored in a database/accessible via an API), it appears as reported and you can't submit another one.
Sorry for the big PR; it's mostly tests. I wanted to get the interaction quite nice and it's very tested, but it meant a lot of tests.

Report add-on abuse UI

---

src/amo/components/AddonMoreInfo/index.js
src/amo/components/AddonMoreInfo/styles.scss
tests/unit/amo/components/TestAddonMoreInfo.js

Fixes https://github.com/mozilla/addons-frontend/issues/3229
This adds two external links to the More Info card for viewing and installing alternative versions.
I also made the loading screen match the final rendered card more closely which should make the loading transition less jarring.

Link to Version History / Development Channel

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss

fix #3241 
Now looks like this, which matches the order in the mocks:

fix: Put cards in proper order

---

src/disco/css/Addon.scss

Fixes #3245
Unfocused:
Hover:
Focus:

Fix link colours in description

---

src/amo/components/AddonMeta.js
src/amo/components/AddonMoreInfo/index.js
src/amo/components/App/styles.scss
src/core/utils.js
tests/unit/amo/components/TestAddonMeta.js
tests/unit/amo/components/TestAddonMoreInfo.js
tests/unit/core/test_utils.js

Fixes #2751.
Links to the stats dashboard from the user count on the `AddonMeta` section and also adds a link in the dashboard.
In order to see this locally you'll be signed in and visit an add-on you own.

feat: Add a link to the stats dashboard for add-on owners

---

.nsprc

See https://github.com/mozilla/addons-frontend/issues/3260

Ignore Node security advisory for `mime`

---

src/amo/components/ReportAbuseButton/index.js
tests/unit/amo/components/TestReportAbuseButton.js

Fix #3262
Add error handler to the report abuse button.
Looks like this:

chore: Add error handler output to ReportAbuseButton

---

src/amo/components/Header/styles.scss
src/ui/components/DropdownMenu/styles.scss

fix: Menu jumps vertically on logout

---

src/ui/components/DismissibleTextForm/index.js
src/ui/components/DismissibleTextForm/styles.scss
tests/unit/ui/components/TestDismissibleTextForm.js

Fixes https://github.com/mozilla/addons-frontend/issues/3277
I'm still working on the UI in another branch. This is what the UX looks like:

Add an inline text form component for review replies

---

package.json
src/amo/components/App/index.js
src/amo/components/App/styles.scss
src/amo/css/inc/vars.scss
src/amo/sagas/categories.js
src/amo/sagas/featured.js
src/amo/sagas/landing.js
src/amo/sagas/reviews.js
src/amo/store.js
src/core/sagas/addons.js
src/core/store.js
tests/unit/amo/sagas/testCategories.js
tests/unit/amo/sagas/testFeatured.js
tests/unit/amo/sagas/testLanding.js
tests/unit/amo/sagas/testReviews.js
tests/unit/amo/test_store.js
tests/unit/core/sagas/testAddons.js
yarn.lock

Close #1156
Close #2179
Close #3291
This removes the blue LoadingBar from the top of all pages and from our saga code. This tidies up the tests, sagas, and UI. Yay! 🎉

chore: Remove LoadingBar

---

src/amo/components/Header/styles.scss
src/amo/components/SectionLinks/index.js
src/amo/components/SectionLinks/styles.scss
src/amo/reducers/viewContext.js
src/core/constants.js
tests/unit/amo/components/TestSectionLinks.js

fix #3281.
This adds links to Language Tools, Search Tools, and other apps to the header. This is in advance of language tools page.
The Explore link is the same as the home link, so we hide it on smaller screens because otherwise the header gets too crammed.
----
I know we argued again the "More" link but using "Extensions" as both a link and a dropdown was awkward UX and inconsistent. Putting the link inside that dropdown seemed like bad UX because then it was extra work (and two taps on a touch device) to get to Extensions landing page which is a very important page. So I settled on the more link, especially because I think the Dropdown @willdurand added is quite nice 😄

feat: Add more section to header

---

src/amo/components/LandingPage/index.js

Also fixes a `oneLine` `i18n` bug.
Fixes #3282

fix: Add copy to landing page

---

src/core/components/Paginate/Paginate.scss
src/ui/components/Card/Card.scss

Fix #3190.
This removes the small-caps on all of our `Card` elements. Small-caps are very bad for accessibility.
I know we need to update the pagination styles (#3100) but I removed the small-caps for now, anyway.

fix: Remove small-caps

---

src/amo/api/collections.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
src/amo/sagas/index.js
src/amo/store.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/helpers.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js
tests/unit/amo/test_store.js

Refs #3140
---
This PR adds the reducer, saga, and API needed to build the collection view. It has a simplified state that could be extended later but for now, I focus on getting this collection view up and running as part of our MVP.
I do not reset the whole `current` collection when fetching a collection because it is nicer in the UI: only the list of add-ons has a "loading indicator" but the card with the detail on the left side do not change. I can't think of any issue with this so far, since we do not list collections in a list view. See:
I could maybe add a separate action for that, but I took the easy path.

Add reducer/saga/api for collection view

---

src/amo/components/AddonMoreInfo/index.js
src/core/types/addons.js
src/core/utils.js
tests/unit/amo/components/TestAddonMoreInfo.js
tests/unit/amo/helpers.js
tests/unit/core/test_utils.js

Fix #3265
Prevents showing version info is the version is "0" and only show versions for add-ons that support version history.
Themes more info cards now look like:

fix: Do not show version or history for themes

---

tests/unit/amo/helpers.js

Just fixes https://github.com/mozilla/addons-frontend/pull/3271/files/898b68b8aaf607001ea88fd884b3fb91fb82947a#diff-54c8950d51a2194d71ef543a52684043.
Will merge if green but feel free to review if you like 😉

chore: Fix current_version placement for #3265

---

src/amo/components/Collection/index.js
src/amo/components/Collection/styles.scss
src/amo/routes.js
tests/unit/amo/components/TestCollection.js

Fix #3140 
~~⚠️ depends on #3256~~
---
This PR adds a new page: collection view. I reuse the `AddonsCard` component that displays a list of add-ons. It does not match the mock-ups yet because this component needs some love but I believe this should be done in a separate PR. Same for the pagination (see #3100).
Loading:
Pagination:
Extensions:
Themes:
<details>
<summary>Smaller screens (more screenshots!)</summary>
</details>

Collection view

---

src/amo/components/AddonReview/styles.scss
src/amo/components/Home/styles.scss
src/amo/components/RatingManager/styles.scss

fix: Do not uppercase login text

---

src/amo/components/SearchResult/index.js
src/amo/reducers/addonsByAuthors.js
src/amo/reducers/landing.js
src/core/reducers/addons.js
src/core/reducers/search.js
src/core/types/addons.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestSearchResult.js
tests/unit/amo/reducers/testLanding.js
tests/unit/amo/reducers/test_addonsByAuthors.js
tests/unit/core/reducers/test_addons.js
tests/unit/core/reducers/test_search.js
tests/unit/disco/containers/TestDiscoPane.js

Fix #3318
Fix #3319 
---
This PR ensures we use an internal addon representation and exposes a `themeData` property to this internal representation. It helped fixing an issue with collections not displaying a preview (because the `collections` reducer uses internal addon representation).
(Note: I am aware of #3234 but did not want to open a big PR)
Before:
After:

Use internal addon representation and themeData

---

src/amo/components/SearchForm/styles.scss

fix: Text entered in the Search field appears cut

---

src/ui/components/Carousel/index.js
src/ui/components/Carousel/styles.scss
tests/unit/ui/components/TestCarousel.js

fix #3349 
No need for two reviews, just whoever gets to it first (feel free to clear the other person once you start reviewing it).
This fixes the CSP error on the carousel by rendering it on the client after `componentDidMount` runs. It's not lovely but it looks nice enough without huge jumps and it works. Pretty much any carousel, by their nature modifying style props, would require this 😢

fix: Render carousel on client to fix CSP errors (fix #3349)

---

src/amo/components/Home/index.js
src/amo/reducers/home.js
src/amo/sagas/home.js
src/amo/sagas/index.js
src/amo/store.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/reducers/test_home.js
tests/unit/amo/sagas/test_home.js
tests/unit/amo/test_store.js

Fix #3308
---
This PR adds the "most popular extensions" shelf to the homepage. It also adds all we need to add the other shelves. I have created a new reducer/saga to be able to fetch all the data in one round.
For example: here is the code to add the second shelf (#3309): https://gist.github.com/willdurand/88a24904de4e6b2567fb2e5ab7f63676 (no test and I used `happyholidays` because dev/stage does not have the required collection).

Add most popular extensions shelf to the homepage

---

src/amo/components/Category/index.js
src/amo/components/Category/styles.scss
src/amo/components/CategoryHeader/styles.scss
tests/unit/amo/components/TestCategory.js
tests/unit/amo/components/TestCollection.js

Fix #3086
~~⚠️ depends on #3343~~
---
This PR reuses the landing page logic to implement the new category pages.

New category page

---

src/amo/components/Home/index.js
src/amo/reducers/home.js

Fixes #3372 
There were few other array length checks such as in `amo/api/review.js` but those were being returned from API as an array so `=== null` check wouldn't work.

fix: Don't rely on empty arrays as being unloaded

---

src/amo/components/Header/styles.scss

fix: Developer Hub and Account Name options are not aligned

---

src/ui/components/DropdownMenu/styles.scss

Fixes https://github.com/mozilla/addons-frontend/issues/3389
I don't really understand what's going on here but this seems to fix it. Maybe it's a Firefox bug.
Before:
After:

Fix a visual glitch in the More menu item

---

src/amo/components/Home/index.js
src/amo/reducers/collections.js
src/amo/reducers/home.js
src/amo/sagas/home.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/reducers/test_home.js
tests/unit/amo/sagas/test_home.js

Fix #3309
---
This PR adds the featured collection shelf. It adds a test for the missing error rendering mentioned in https://github.com/mozilla/addons-frontend/pull/3365#discussion_r143070227.
⚠️ this collection does not exist in stage/dev 😢  I manually changed to `happy-2015` to test it, but I dont know what else to do. It could maybe part of the `config` (since it has different configs depending on the envs) but I did not see any similar config data...

Add collection based shelf to Homepage

---

src/amo/components/Home/index.js
src/amo/reducers/home.js
src/amo/sagas/home.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/reducers/test_home.js
tests/unit/amo/sagas/test_home.js

Fix #3311
---
This PR adds the featured themes shelf on the homepage.
Firefox:
Android:

Create featured themes shelf on the homepage

---

src/amo/components/AddonReviewListItem/index.js
src/amo/components/AddonReviewListItem/styles.scss
src/ui/components/DismissibleTextForm/index.js
src/ui/components/ErrorList/styles.scss
tests/unit/amo/components/TestAddonReviewListItem.js
tests/unit/ui/components/TestDismissibleTextForm.js

Fixes https://github.com/mozilla/addons-frontend/issues/3415
This does a few things:
* Fixes specificity issues in the `ErrorList` styles so that the error message is visible
* Allows the user to edit their reply and try again in case there's an error
* Prevents the user from submitting a blank reply, i.e. one with just white space
The error banner looks like this but keep in mind this specific error is no longer possible to trigger:

Fix error handling in review-reply form

---

src/amo/components/LandingPage/index.js
tests/unit/amo/components/TestLandingPage.js

Fix #3383
---
This PR makes sure a landing page fetches data again after having loaded a category page. It happens because we use the same (redux) action with an optional parameter (`category`) and the `LandingPage` component needed to check it to determine if it had to get data or not. I also made sure that we did not dispatch `setViewContext` too often.
This diff is rather large because I rewrote most of the test file with `shallowUntilTarget()`.

Fix landing page

---

src/core/api/index.js
src/core/api/search.js
src/core/searchUtils.js
tests/unit/core/api/test_index.js
tests/unit/core/api/test_search.js
tests/unit/core/test_searchUtils.js

Fix #3408
---
This PR fixes an issue with the themes for Android by porting the same workaround used in the search API to the featured API, since both are different.

Fetch featured themes on Android

---

package.json
src/amo/components/LanguageTools/index.js
src/amo/components/LanguageTools/styles.scss
src/amo/routes.js
src/core/reducers/addons.js
tests/unit/amo/components/TestLanguageTools.js
yarn.lock

Fix #2777.
Fix #3375.
Adds a responsive table similar to the old site with language tools and dictionaries. Tried a few different UIs but this one with a responsive table actually worked pretty well so I went with it.

feat: Add Language Tools and Dictionaries page

---

src/amo/components/Collection/index.js
src/amo/reducers/collections.js
tests/unit/amo/components/TestCollection.js

Fix #3482
---
This PR makes sure collections get loaded correctly on the client.
Before:
After:

make sure collections get loaded when params change

---

src/ui/components/HeroSection/styles.scss

Fixes #3488
Fixes #3484 
Before:
After:

Remove unnecessary z-index

---

package.json
tests/unit/TestPackageJson.js
yarn.lock

Try a fork of redux-saga-tester to see if we can work around the deps failures. 
Oddly this seems to be pulling in a different lower version number since the fork is based on master.

Try pinning redux-saga-tester deps

---

package.json
tests/unit/TestPackageJson.js
yarn.lock

Now the redux-saga-tester package has been updated we don't need to skip it any more.
I've left the skip list in play since it may be useful again in the future.

Upgrade to redux-saga-tester with fixed dependency

---

src/amo/components/Collection/styles.scss
src/amo/components/Search/styles.scss
yarn.lock

Fixes #3015
Before: 
After the fix there's no extra space rendered under the search results:

Fix chrome height bug

---

src/amo/components/Header/styles.scss

Fix safari header moving around

---

src/amo/components/SearchResult/styles.scss

Fix up long strings in search results so they wrap

---

src/amo/components/Header/styles.scss

Fixes: #3501
Before:
After:
Still works in safari too.

Fix search box visual length

---

src/amo/actions/reviews.js
src/amo/api/reviews.js
src/amo/constants.js
src/amo/reducers/reviews.js
src/amo/sagas/reviews.js
tests/unit/amo/actions/testReviews.js
tests/unit/amo/api/test_reviews.js
tests/unit/amo/sagas/testReviews.js

Fixes https://github.com/mozilla/addons-frontend/issues/3495
* Adds low-level API stuff needed for the UI (https://github.com/mozilla/addons-frontend/issues/2774)
* Adds type safety to the reviews reducer
* Fixes issues with the review saga test that I hadn't noticed before
For context, this is how I envision the UI will work:
* The user goes to the list of all add-on reviews
* They see one that needs flagging
* The click on 'Flag this review' and get a dropdown similar to the More menu item. 
* The can select things like: Flag for spam, inappropriate language, misplaced bug report, or other (this will allow them to enter a text explanation)

Add API/actions/sagas for flagging reviews

---

src/amo/sagas/featured.js
src/amo/sagas/home.js
src/amo/sagas/landing.js
src/core/api/index.js
src/core/constants.js
tests/unit/amo/sagas/testFeatured.js
tests/unit/amo/sagas/testLanding.js
tests/unit/amo/sagas/test_home.js
tests/unit/core/api/test_index.js

Fix #3307
---
This PR removes calls to the Featured API in favor of the Search API so that we can leverage all its parameters (including `appversion`) and return compatible add-ons only. The UI update will follow in #3137.

Get rid of the old featured API in favor of the search one

---

src/amo/components/LandingAddonsCard/index.js
tests/unit/amo/components/TestLandingAddonsCard.js

Fix #3135
---
This PR reduces the number of placeholders rendered while loading in a `LandingAddonsCard`.
Before:
After:

Render LANDING_PAGE_ADDON_COUNT placeholders in LandingAddonsCard

---

src/amo/components/Search/styles.scss

fix: consistent pagination layout

---

src/amo/components/Header/styles.scss

Fixes #3503 
Fixes #3505 
For #3503
Before: 
After:
For #3505
Before:
After:
The header no longer moves when hovering over "Explore"

Fix safari more link position and header dropdown movement

---

src/amo/components/Addon/styles.scss

Fixes #3509
Before (using firefox ESR 52.x)
After:

Fix screenshot overflow in FirefoxESR

---

src/amo/components/Addon/styles.scss

Fix wrapping of unbroken strings in detail page

---

src/amo/components/SearchFilters/index.js

Fix #3121
---
So, this PR fixes a weird bug related to the search filters being updated with the wrong values on page refresh. First, I thought that was an issue related to the `key` prop not correctly set on each `option`, so I changed that but it did not work actually... Yet, this still fixes something. I started to investigate more, but it was not easy to trigger the problem. Here are a few steps to make it work (or fail depending on your point of view):
- go to https://addons-dev.allizom.org/en-US/firefox/themes/
- click on "more trending themes"
- refresh (might not be necessary)
- go to "extensions" (header link)
- go to "more trending extensions" (well, looks good to me)
- refresh and 💥 
I thought that was a bug in the `render()` of the `SearchFilters` component, not being updated …

Fix search filters

---

src/amo/components/Addon/styles.scss

Fix text overflow on add-on summary

---

src/core/i18n/utils.js
tests/unit/core/i18n/test_utils.js

Fix #3443
---
This PR makes sure `moment` gets the correct locale all the time, otherwise it might reuse the wrong locale on the server, and the client will have to patch it on load, causing a visual glitch mentioned in #3443.
Steps to reproduce:
- load a page with a date, e.g., https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/change-up-your-tabs/
- change the language to something other than English, like German (Deutsch) or suomi
- refresh the page
- change the language to English (US)
- 💥
You should see the wrong formatted date loaded first and then updated when the client side is fully loaded. The aim of this PR is to solve this by always setting the current locale to `moment`.

Fix moment locale

---

src/ui/components/DropdownMenu/styles.scss

Fixes #3110
~~This is a workaround for #3110 - I can't find a root cause as to why the span is focusable. Since it doesn't need to be focused adding an explicit attribute fixes the problem.~~
~~At some point it would be nice to understand what the root cause of the span being focusable even when it's tabIndex property says it's -1 already.~~
~~Trying to reproduce it in isolation doesn't appear to be easy.~~
~~This also adds the outline so that the button is outlined on focus.~~
The fix to prevent the span focus was to remove the `overflow:hidden` which was done in a different PR.
This  PR adds the outline for FF and the default webkit focus back for chrome etc:
#

Workaround erroneous span focus and outline user button on focus.

---

src/amo/components/Header/styles.scss
src/amo/css/inc/vars.scss

Fixes  #3519
Moves the full-screen header to a later breakpoint.

Update header to work better with long translations

---

src/amo/components/Addon/index.js
src/core/components/InstallButton/index.js
tests/unit/amo/components/TestAddon.js
tests/unit/core/components/TestInstallButton.js

Force the InstallButton to always be a button on AMO.
Note that the Disco Pane should still stay a switch because it's nice to have a toggle there and it's less an issue.

fix: Use InstallButton all the time on AMO (fix #3557)

---

src/amo/components/Addon/index.js
src/amo/components/ReportAbuseButton/index.js
src/amo/components/ReportAbuseButton/styles.scss

fix #3553
Makes the "Report this add-on for abuse" button less intense and make it not the most obvious CTA on the page by making the "Add to Firefox" button larger and it smaller.
Upon further reflection, yeah, I really made this too out there. The new design uses the action button style until the "Send report" button where a red style appears, making it clear the action is serious 😄

fix: Make abuse button less intense

---

src/amo/components/SearchFilters/index.js
tests/unit/amo/components/TestSearchFilters.js

Fix #3579
---
This PR resets the `page` search filter when one of these filters is updated.

Reset page filter on change

---

src/amo/components/Addon/index.js
src/amo/components/AddonMoreInfo/index.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonMoreInfo.js

Fix #3567
---
This PR removes the site identifier in the meta info of an add-on. It adds this identifier as a data attribute (`data-site-identifier`) set on the `.Addon` element.

Remove "Site Identifier" from listing pages

---

src/amo/components/Addon/styles.scss

Fix #3571 (see comments)
---
Before:
After:

Fix header title

---

src/ui/components/TooltipMenu/index.js
src/ui/components/TooltipMenu/styles.scss
tests/unit/ui/components/TestTooltipMenu.js

Fixes https://github.com/mozilla/addons-frontend/issues/3556
You can now use the tab key to step through the menu. It's a little rough around the edges but this is an improvement from where it was before.

Improve TooltipMenu keyboard accessibility

---

src/core/reducers/heroBanners.js
tests/unit/amo/reducers/testHeroBanners.js

Fix #3608
---
While addressing changes in another PR related to the Hero Banner, I could not display the "Ad blocks" card, like never. I looked at the code of the reducer and it seems we never take all the sections into account, only the `MAX_ITEMS` first.
This PR fixes this by sorting all the sections first and then reducing the set of sections to display.

Be sure to sort all sections before slicing them

---

src/core/purify.js
src/core/utils/index.js
src/disco/components/Addon.js
src/disco/components/AddonCompatibilityError/index.js
src/disco/purify.js
src/disco/utils.js
tests/unit/core/utils/test_index.js
tests/unit/disco/test_utils.js

Fix #3554
---
This PR restricts the DOM Purify hook that adds `target="_blank"` to links (actually, "targetable" elements) to the `disco` project. Before it was used everywhere.

Add target=_blank attribute to disco links only

---

src/amo/components/LanguageTools/styles.scss

Fix #3454
---
This PR fixes a visual glitch when some entries are not present in a given language on the "Dictionaries and Language Packs" page and on small screens. I used `31px` because that was the height for other regular rows.
Before:
After:

Fix min height of language tool entries

---

src/amo/components/Addon/styles.scss
src/amo/components/AddonsCard/styles.scss
src/amo/components/Search/styles.scss
src/amo/components/SearchResult/styles.scss

refs #3593
---
This PR slightly improves the different shelves by adding a `hover` state with background fading. It is getting closer and closer to the mockups. It also aligns the different addon lists vertically and horizontally with the header title positions.

Update shelves style

---

src/amo/components/SearchForm/styles.scss

Fixes https://github.com/mozilla/addons-frontend/issues/3615
This only happens on mobile so I didn't make a screencast. I was able to reproduce the issue [with these steps](https://github.com/mozilla/addons-frontend/#configuring-an-android-device-for-local-development) before fixing it.

Prevent a flicker when focusing search box on mobile

---

src/core/components/InstallButton/index.js
src/core/constants.js
src/core/installAddon.js
tests/unit/core/TestInstallAddon.js
tests/unit/core/components/TestInstallButton.js
tests/unit/helpers.js

Fixes https://github.com/mozilla/addons-frontend/issues/3600
- is this the right way to do it?
- the `mozAddonManager` does it like this but only *after* a successful installation. I'm not sure if we need to set this event apart.
- the old site seems to be using a different analytics framework so I'm not sure if this matches what's going on there.

Track analytics of the standalone install button

---

src/amo/components/Home/index.js
src/amo/components/Home/styles.scss

Fix #3621 
---
This PR removes headlines on the subject shelves and makes things a little nicer.

Adjust subject shelf texts

---

src/core/utils/compatibility.js
tests/unit/amo/helpers.js
tests/unit/core/components/TestInstallButton.js
tests/unit/core/utils/test_compatibility.js
tests/unit/helpers.js

Fixes https://github.com/mozilla/addons-frontend/issues/3649
I think this has been broken since the dawn of `addons-frontend`. This explains the bug: https://github.com/mozilla/addons-frontend/issues/3649#issuecomment-339726425
The solution here is to mark a client incompatible if the add-on's current version has no compatibility data for it at all. Mat verified on IRC that this behavior is correct.
The implications is that many Android pages will have disabled buttons when they didn't have disabled buttons before.

Mark client as incompatible if add-on does not have a compatible version

---

src/amo/components/FlagReview/index.js
src/amo/components/FlagReviewMenu/index.js
src/amo/reducers/reviews.js
tests/unit/amo/components/TestFlagReviewMenu.js
tests/unit/amo/reducers/testReviews.js

Fixes https://github.com/mozilla/addons-frontend/issues/3598
* After you flag a review, the prompt changes from *Flag* to *Flagged*
* The UI indicates that you can only flag a review for a single reason
* You can still change your mind and switch the reason
Screencast:

Only flag a review for a single reason

---

src/core/utils/compatibility.js
tests/unit/amo/helpers.js
tests/unit/core/utils/test_compatibility.js

Fixes https://github.com/mozilla/addons-frontend/issues/3669
This fixes not only themes but also dictionaries and search providers.

Only require extensions to declare clientApp compatibility

---

src/amo/components/Addon/styles.scss

Fix long theme title

---

src/amo/components/Header/index.js

Fixes #3686
Easy fix here, just removing this item.

fix: Remove API keys from header menu (fix #3686)

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss

Fix #3684
---
I had to slightly change how the add-ons are listed by adding the rating stars, but it looks better now :)

Display rating stars on more extensions by authors

---

src/amo/components/SectionLinks/styles.scss
src/ui/components/DropdownMenu/index.js
src/ui/components/DropdownMenu/styles.scss
tests/unit/ui/components/TestDropdownMenu.js

Fix #3452.
Changes to use a JS hover to allow us to dismiss the menu on a click.

fix: Close dropdown on click

---

src/amo/components/AddonMoreInfo/index.js
tests/unit/amo/components/TestAddonMoreInfo.js

Fixes: #3603 
This patch was started by @tsl143 - thanks!
**Before:**
While logged out, viewing an add-on that has public stats looked like:
**After:**

Always link to add-on stats when they are declared public

---

src/amo/components/AddonReviewList/styles.scss

Fix long title in review page

---

src/amo/components/Addon/index.js
src/amo/components/ErrorPage/NotFound/index.js
src/core/components/ErrorPage/NotFound/index.js
src/core/constants.js
src/core/reducers/errors.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestNotFound.js
tests/unit/core/reducers/test_errors.js

Fixes https://github.com/mozilla/addons-frontend/issues/2261
**Before:**
**After** 
Developer disabled add-ons:
Admin disabled add-ons:
All other 404s:

Show disabled add-on error pages

---

src/amo/components/SectionLinks/styles.scss

Add missing border-bottom on active section link

---

src/amo/components/Addon/index.js
src/amo/components/AddonMoreInfo/styles.scss
src/amo/components/ReportAbuseButton/index.js
src/amo/components/ReportAbuseButton/styles.scss
src/ui/components/Button/Button.scss

Fix #3599
---
This PR updates the style of the report button and adds some space on the "More Info" card. It also moves the "rating" card before the "more info" one, as requested here: https://github.com/mozilla/addons-frontend/issues/3553#issuecomment-338252865.

Style report button and more info card in add-on detail page

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/amo/components/AddonBadges/index.js
src/amo/components/AddonBadges/styles.scss
src/amo/components/Collection/styles.scss
src/core/components/InstallButton/index.js
src/core/components/InstallButton/styles.scss
src/ui/components/Badge/index.js
src/ui/components/Badge/styles.scss
src/ui/components/Icon/plus.svg
src/ui/components/Icon/styles.scss
src/ui/components/MetadataCard/styles.scss
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonBadges.js
tests/unit/core/components/TestInstallButton.js

Fix #3588
Fix #3651 
Fix #3716
Note: Changes from the mocks–the badges on extensions are moved from the top-right to underneath the title. This is consistent across themes and extensions. Plus: @willdurand and I think it's nicer 😄

feat: Addon details styles/badges

---

src/amo/components/Home/index.js
src/amo/components/LandingPage/index.js
tests/unit/amo/components/TestLandingPage.js
tests/unit/amo/containers/TestHome.js

Fix #3633
---
This PR adds more meaningful texts to the "see more" links.
Landing page themes:
Landing page extensions:
Homepage:

Update see more links with more meaningful contents

---

src/core/constants.js
src/core/reducers/user.js
tests/unit/core/reducers/test_user.js
tests/unit/helpers.js

Fix #3702
---
This PR exposes the permissions in the `user` reducer.

Expose permissions in user reducer

---

src/amo/components/SearchPage/index.js
src/core/searchUtils.js
tests/unit/amo/components/TestSearchPage.js
tests/unit/core/test_searchUtils.js

(fix #3743)
Doesn't expose any tag UI, but this at least surfaces the query param to:
* the API
* the paginator (so clicking next/previous page works)
It should solve the issue of at least passing the link in #3743 around.
Just needs one review; whoever gets to it first.

fix: Add tag support to search query params

---

src/amo/components/AddonMoreInfo/index.js
src/core/constants.js
src/core/reducers/user.js
tests/unit/amo/components/TestAddonMoreInfo.js
tests/unit/amo/helpers.js
tests/unit/core/reducers/test_user.js

Fix #3604
---
This PR relies on the newly added `permissions` state (in `user` reducer) to display the stats link to any users with the `Stats:View` permission or admins.

Display stats links to admins or users with 'Stats:View' permission

---

src/amo/components/SearchFilters/index.js
tests/unit/amo/components/TestSearchFilters.js

Fix #3747
---
This PR does not display the add-on type select filter when a category filter is set.

Disably addonType search filter when category type is set

---

src/amo/components/AddonMoreInfo/index.js
tests/unit/amo/components/TestAddonMoreInfo.js

(fix #3768)
Simple tweak–just combines the version links into one section, similar to the links section at the top of the card.

fix: Combine all and beta versions

---

src/amo/components/AddonReviewList/styles.scss

Fixes #3786, there's a new issue filed to discuss this for future re-implementation here: https://github.com/mozilla/addons-frontend/issues/3793
Before: 
After:

Fix inconsistent border-radius

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fixes https://github.com/mozilla/addons/issues/522.

feat: Add newlines to add-on summary

---

src/amo/components/AddonCompatibilityError/index.js
src/amo/components/DownloadFirefoxButton/index.js
src/amo/utils.js
tests/unit/amo/components/TestAddonCompatibilityError.js
tests/unit/amo/components/TestDownloadFirefoxButton.js

Fix #3803
---
This PR adds `utm` query parameters to the "download firefox" links.

Fix download links (add utm query params)

---

src/amo/components/AddonBadges/index.js
src/amo/components/AddonBadges/styles.scss
src/core/reducers/addons.js
src/core/types/addons.js
src/ui/components/Badge/index.js
src/ui/components/Badge/styles.scss
src/ui/components/Icon/not-compatible.svg
src/ui/components/Icon/styles.scss
tests/unit/amo/components/TestAddonBadges.js
tests/unit/core/reducers/test_addons.js
tests/unit/disco/containers/TestDiscoPane.js

Fix #3780
---
This PR adds a new badge to mark the non-webext add-ons as "not compatible with FF Quantum".

Not compatible with Firefox Quantum

---

src/amo/components/SearchPage/index.js
src/core/reducers/redirectTo.js
tests/unit/amo/components/TestSearchPage.js

Fix #3791
---
This PR triggers a server-side redirect when `atype` search parameter is detected and we have a corresponding `addonType` for it.

Redirect atype parameters to their corresponding addonType

---

src/amo/components/Search/index.js
tests/unit/amo/components/TestSearch.js

Fix #3689 (comment)
---
This PR makes sure we set the right `viewContext` during a search.

Make sure to set the right context in search

---

src/amo/components/Category/index.js
tests/unit/amo/components/TestCategory.js

'see more' consistency fix

---

src/amo/components/Category/index.js
tests/unit/amo/components/TestCategory.js

Fixes see more string at themes category page

---

src/core/components/InstallButton/index.js
tests/unit/core/components/TestInstallButton.js

Fixes https://github.com/mozilla/addons-frontend/issues/3867
* This switches us to `InstallTrigger`, like the old AMO, which doesn't care if the TLS channel has a non built-in root CA. This is because it relies on the file hash. If a file hash were `undefined` *and* the redirect to the final file did not contain a special hash header then it would fall back to requiring a built-in root CA. 
* Getting a file hash is not too easy because we need to find it based on platform. We do have a file URL and URLs are unique enough so I'm using that to find the hash as a quick fix. The follow-up: https://github.com/mozilla/addons-frontend/issues/3871

Use InstallTrigger.install() for extensions

---

src/amo/components/AddonBadges/index.js
src/core/utils/compatibility.js
tests/unit/amo/components/TestAddonBadges.js
tests/unit/amo/helpers.js
tests/unit/core/utils/test_compatibility.js

Fix #3868
---
We use a forged User Agent string to be able to use the existing compatibility logic. It is not ideal but it is good-enough short-term. Th "not compatible with Firefox Quantum" badge should only be displayed if an add-on is not compatible with the desktop version of Quantum (`clientApp = firefox`).
Before:
After:
**Important:** On Android, we do not show the badge on purpose because this extension is compatible with Quantum Desktop:

Fix how we determine Quantum compatibility

---

src/amo/components/Search/index.js
src/core/reducers/search.js
tests/unit/amo/components/TestSearch.js
tests/unit/core/reducers/test_search.js

Fix #3746
---
This PR resets the search state when search filters become empty.

Reset search state when filters become empty

---

src/core/i18n/utils.js
tests/unit/core/i18n/test_utils.js

Fix #3819
Fix #3538
---
This PR changes the `i18n.moment` property and now only exposes a function to return localized moment instances. It is needed to avoid random locales to be used by moment (because it is used globally). The added test case simulates what is describe in both issues fixed above. The `locale` function has been added for the test suite and works as we expect.
Note that we cannot use global/static `moment` methods anymore like:
- https://momentjs.com/docs/#/durations/
- https://momentjs.com/docs/#/utilities/
Absolutely all other methods are called on an instance of `moment` and therefore will continue to work as intended. I don't think we should rely on any of the other global/static `moment` methods anyway because we would issue similar issues again.

Make sure i18n.moment uses the correct locale

---

src/amo/components/Collection/index.js
src/amo/reducers/collections.js
src/core/constants.js
src/ui/components/MetadataCard/index.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/helpers.js
tests/unit/ui/components/TestMetadataCard.js

Fix #3766
---
This PR adds a link to edit a collection when user is the owner or has the `Collections:Edit` permission.
It also fixes the special case when a user has a collection without any add-ons in it (it was not rendering the number of addons on the left and it the pagination was displayed on the right). Please see the first screenshots.
Before:
After:

Add link to edit a collection

---

src/amo/components/AddonReviewList/index.js
tests/unit/amo/components/TestAddonReviewList.js

Fixes https://github.com/mozilla/addons-frontend/issues/2327 (as a follow-up). The count on the listing screen also needed fixing: https://github.com/mozilla/addons-frontend/issues/2327#issuecomment-343863193

Fix count of written add-on reviews in listing

---

src/amo/components/AddonReviewList/index.js
tests/unit/amo/components/TestAddonReviewList.js

Fix #3273
---
This PR uses a "fixed" error handler to synchronize the server and client error handlers, avoiding to render a 200 and then a 404 when it is expected to get a 404. Now, the server returns a 404.

Use a fixed error handler for reviews list

---

src/amo/components/SearchPage/index.js
tests/unit/amo/components/TestSearchPage.js

Fix #3870
---
This PR triggers a server redirect when `platform=all` is passed in a search query so that we get the same results on both the old and new frontends. It is required because the new frontend expresses "all platforms"  with an empty string, resulting in the filter omitted. The old frontend uses the string `all` though, but if we do that then the API will look for add-ons with a platform/OS named `all` 😛

Handle platform=all from old frontend

---

src/amo/components/LanguageTools/index.js
src/core/languages.js
tests/unit/amo/components/TestLanguageTools.js

Fixes https://github.com/mozilla/addons/issues/528
The main change here was to use a unfiltered set of language data so all relevant locales are represented rather than using the default subset that's relevant to our site.
I also added sorting by English locale since this makes the ordering make more sense rather than the sorting on locale code when the display is the native locale string. We could look to improve on this in due course but it matches what's on the old site.
Before: 
After:

Fix langpack display

---

src/amo/components/LandingAddonsCard/index.js
tests/unit/amo/components/TestLandingAddonsCard.js
tests/unit/amo/components/TestLandingPage.js

Fix #3745
---
This PR hides the "see more" (footer) link when there are less than 4 add-ons displayed in a landing card.
Before:
After:

Do not display footer link if not enough add-ons in LandingAddonsCard

---

src/amo/components/HomeHeroBanner/index.js

Fix Lastpass => LastPass

---

src/amo/components/LandingPage/index.js
tests/unit/amo/components/TestLandingPage.js

Fix #3922
---
This PR hides a shelf on a landing page if there is no add-ons to show in it. It is similar to how category pages work. I also updated the test file for the `LandingPage` component.

Render LandingPageCard only if needed

---

src/amo/components/LanguageTools/index.js
src/amo/store.js
src/core/reducers/addons.js
src/core/reducers/languageTools.js
src/core/sagas/languageTools.js
src/core/types/addons.js
tests/unit/amo/components/TestLanguageTools.js
tests/unit/amo/test_store.js
tests/unit/core/api/test_languageTools.js
tests/unit/core/reducers/test_addons.js
tests/unit/core/reducers/test_languageTools.js
tests/unit/core/sagas/testLanguageTools.js
tests/unit/helpers.js

Fix #3939
---
This PR introduces a `languageTools` reducer because the language tools and search APIs return different results, hence the data sets should be separated.

Add a languageTools reducer

---

src/amo/components/Addon/index.js
src/amo/components/AddonReviewList/index.js
src/core/reducers/addons.js
src/core/utils/index.js
src/disco/components/Addon.js
src/disco/containers/DiscoPane.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/amo/test_store.js
tests/unit/core/reducers/test_addons.js
tests/unit/core/utils/test_index.js
tests/unit/disco/components/TestAddon.js

Fix #3421
---
This PR changes the shape of the `addons` reducer state. It introduces two hash maps to quickly lookup an add-on by GUID (disco) or slug (amo) and several selectors.
Add-ons are stored only once and by ID (slugs can change). The `bySlug` and `byGUID` state attributes are hash maps that store the `id` given a `slug` or `guid`.
If you want to retrieve an add-on by slug, you need to get its `id` first, and then get it in the set of `addons`. To ease that, there is a new `getAddonBySlug()` selector. It is the exact same thing for `guid` and `getAddonByGUID()`.
It is also possible to retrieve an add-on by ID using `getAddonByID()` and to get an array of all add-ons with `getAllAddons()`. These selectors should make things more readable.
---
Follow-up: #3957

Refactor the addons reducer state

---

src/amo/reducers/addonsByAuthors.js
src/amo/sagas/addonsByAuthors.js
src/core/searchUtils.js
tests/unit/amo/reducers/test_addonsByAuthors.js
tests/unit/amo/sagas/test_addonsByAuthors.js

Fix #3119
---
This PR cleans up the way we fetch the other add-ons by authors.

Use exclusion filter to retrieve other add-ons by authors

---

src/amo/components/Footer/index.js

Fixes #3972
Linking with the fragment id messes up the status site's history because it seems to eat the fragment. Also the fragment isn't doing anything to show the status for add-ons so we may as well just link to the root of the status site.

Link to the root of the status site

---

src/disco/actions.js
src/disco/api.js
src/disco/containers/DiscoPane.js
src/disco/sagas/disco.js
tests/unit/disco/containers/TestDiscoPane.js
tests/unit/disco/sagas/testDisco.js
tests/unit/disco/test_actions.js
tests/unit/disco/test_api.js

Fix #3804.
These tests are quite old so this patch is pretty meh... I didn't want to spend a lot of time fixing up the tests because it'd be a PITA to review and I need to start on the user pages... there aren't actually many more weeks to this quarter 😓
The lang is already sent to the API so this just adds the platform sent to the Disco Pane to the API request, which addons-server will send to TAAR.

chore: Send params to TAAR (fix #3804)

---

src/core/middleware/datadogTiming.js
tests/unit/core/middleware/test_datadogTiming.js

Follow up to https://github.com/mozilla/addons-frontend/issues/3755
The timing and count stats need to have different keys.

Use different datadog keys per count/timing (for stats)

---

.nsprc

Refs #3989
Since there is no fix yet, we add an exclusion entry so that next builds can pass.

Add moment to the NSP exclusions list

---

jest.config.js
src/amo/store.js
src/core/client/base.js
src/core/server/base.js
src/disco/store.js
tests/unit/amo/components/TestLanguagePicker.js
tests/unit/amo/components/TestSearchResults.js

Fixes https://github.com/mozilla/addons-frontend/issues/4013
I ran into this while trying to hook up the redux-router to some tests using the new react patch (https://github.com/mozilla/addons-frontend/pull/3975). This PR doesn't solve any immediate problems but adds a few things:
- prepares us for testing with `redux-router` in the future
- switches to object params in `createStore()` which will make `undefined` variables less confusing. Before this patch I was getting `TypeError: Cannot read property 'push' of undefined` which was hard to track down.

Ensure history is defined in the store while testing

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Fix #3610
---
In a previous PR, I thought `Number.isInteger` was more readable and explicit but it turns out it does not parse stringified numbers. I reverted the changes to use `!isNaN` and provided a test case.

Fix the way we detect IDs (integer) in slugs

---

src/amo/api/collections.js
src/amo/components/Collection/index.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/helpers.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes https://github.com/mozilla/addons-frontend/issues/4016
I will need to fetch/store user collections to make a dropdown on the add-on detail page that lets you add an extension to a collection.
Sorry for all the noise; the re-organization of the state will make this a bit cumbersome to review.

Expand state for user collections

---

src/amo/components/HomeHeroBanner/styles.scss

This was just an error on my part.
See: https://github.com/mozilla/addons-frontend/pull/4024#discussion_r154734047

chore: Use 6 not 7 as max hero section index

---

src/amo/components/SectionLinks/styles.scss

Fix More link position ESR52

---

src/amo/components/Search/styles.scss

Fixes https://github.com/mozilla/addons/issues/566
Before the fix the search results height is > 50000px high before you get to the pagination.
After the fix - there's no massive gap:

Fix column height calculation in ESR

---

src/amo/components/Addon/styles.scss

Fixes #4040 
**Before:**
**After**

I4040 - Highlight author names on details page

---

src/amo/components/Addon/index.js
src/amo/components/AddonMoreInfo/index.js
src/amo/components/AddonReviewList/index.js
src/amo/components/RatingManager/index.js
src/core/reducers/addons.js
src/core/types/addons.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonReviewList.js

Fixes https://github.com/mozilla/addons-frontend/issues/4045
In addition to addressing that issue, this changes the Flow type of `addon.current_version` so that all typed code will be forced to guard against it.
Visiting a broken add-on now looks like this:

Cope with null versions when dealing with incomplete add-ons

---

src/amo/components/CategoryIcon/styles.scss

Fixes #4033 
**Note:** _this doesn't show the full set of colours since the masking isn't supported in 52 but it should show the correct colours from 53 onwards and all other browsers that support masking._
Edge should continue to show the fall-back too.
Before: 
After:

Use masking fallback for ESR

---

src/core/api/index.js
tests/unit/core/api/test_index.js

Fixes https://github.com/mozilla/addons-frontend/issues/4116

Support absolute URLs, query string params in callApi()

---

src/amo/api/collections.js
src/amo/reducers/collections.js
src/core/api/index.js
src/core/client/base.js
src/core/polyfill.js
src/core/server/base.js
tests/unit/amo/api/test_collections.js
tests/unit/core/api/test_index.js
webpack-common.js

Fixes https://github.com/mozilla/addons-frontend/issues/4118

API functions for adding an add-on to a collection

---

src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes https://github.com/mozilla/addons-frontend/issues/4150
This adds two sagas along with reducers to support them:
* I implemented the `addAddonToCollection` saga. When the user goes to an add-on detail page, they can add the add-on to a collection by choosing it from a select box. That action will run this saga.
* The `fetchUserCollections` saga now fetches all collections, not just the first 25. This is so the select box can present all of them.

Sagas/reducers for adding an add-on to a collection

---

config/default.js
config/development-amo.js
src/core/searchUtils.js
tests/unit/core/test_searchUtils.js

Fixes #4152
Adds a config option (set to `true` for normal environments and `false` for development environments) that ignores version compatibility checks. This means we get add-ons returned in searches when using -stage data.

chore: Add config option to disable version checks in search

---

.eslintrc
src/amo/components/AddAddonToCollection/index.js
src/amo/components/AddAddonToCollection/styles.scss
src/amo/components/AddonMoreInfo/index.js
src/amo/components/AddonMoreInfo/styles.scss
src/ui/components/Button/index.js
tests/unit/amo/components/TestAddAddonToCollection.js
tests/unit/amo/helpers.js
tests/unit/helpers.js

Fixes https://github.com/mozilla/addons-frontend/issues/2768
This implements a simple UI for adding an extension to an existing collection from the detail page. If you add an extension to a collection and then reload the page (or visit it again later) you will not see an indication that it is a part of a collection. This was a deliberate choice to reduce complexity. Instead, you will see a clear and concise error if you try to add it.
UX mock: https://github.com/mozilla/addons-frontend/issues/3993#issuecomment-349064460

Add an add-on to a collection

---

src/amo/components/Addon/index.js
src/amo/components/Addon/styles.scss
src/amo/components/AddonCompatibilityError/index.js
src/ui/components/Notice/index.js
src/ui/components/Notice/styles.scss

Fixes https://github.com/mozilla/addons-frontend/issues/4169 (this issue contains a list of what was fixed).
Here is the updated link style as well as a fix for the vertical centering of the message:
I could only reproduce the reload-and-it-jumps bug on dev, not locally. However, while inspecting the markup I think the culprit was putting a `<div>` inside of a `<p>` tag which seems to have created wonky HTML on the server only:

Fix Photon notification issues

---

src/amo/components/SearchFilters/index.js
src/amo/components/SearchForm/index.js
tests/unit/amo/components/TestSearchForm.js

Fixes https://github.com/mozilla/addons-frontend/issues/4120
This patch preserves any existing filters for these user actions:
* Typing keywords in the search bar and viewing auto-completion results
* Typing a keyword and pressing enter in the search bar to go to the search results page

Preserve existing filters when typing a new search

---

src/amo/components/HomeHeroBanner/index.js
src/amo/components/HomeHeroBanner/styles.scss

Wow. So looking into this exposed how brutal our (admittedly more flexible) homepage CSS setup was for file size.
Last week's tag (and similar releases since the introduction of our homepage banners) had a CSS file size of `1.8MB`. This week's tag, with extra numbers of possible banners, because of how we created them, had a CSS size of `6.1MB`.
After this fix, our CSS file is down to ~`500kB`. So yeah. This reduces the dynamic backgrounds/colours found in the old homepage, but it cuts down on maintenance effort in updating the homepage and file size. I think it's worth it.

fix: Reduce homepage CSS (fix #4211)

---

src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes https://github.com/mozilla/addons-frontend/issues/4196
I envision this new saga, `updateCollection()`, to run when the user presses the submit button ([see mock](https://github.com/mozilla/addons-frontend/issues/4002)). It will do the following:
- Change state to *updating* so that the submit button can be disabled
- Send a patch to the collection API
- Report any API errors and reset state accordingly

Saga helpers for editing a collection

---

src/amo/components/HomeHeroBanner/styles.scss

Fixes https://github.com/mozilla/addons-frontend/issues/4229
The hash in the filename of the final stylesheet asset is generated from its contents. When we deployed a build to multiple server instances, they were each generating different file names.

Remove randomly generated style colors

---

config/default.js

This is complimentary to the server changes happening in https://github.com/mozilla/addons-server/issues/7396
The server cookie was changed in https://github.com/mozilla/addons-server/pull/7397

Change name of auth cookie to fix broken logout

---

src/amo/components/AddonReview/styles.scss
src/amo/components/App/styles.scss

Fixes #4135 
Inconsistent fonts in submit review popup.
Before:
After

I4135 - submit rating popup font consistency

---

src/ui/components/MetadataCard/styles.scss

Fixes: #4089 
Before: 
After:
**NOTE**
Need to change max-width from 30% to 25%, to adjust case when user number is large.

I4089 - distorted stats section fix

---

src/amo/components/Collection/index.js
tests/unit/amo/components/TestCollection.js

fix: Allow HTML entities in collection description

---

src/amo/components/SearchSuggestion/styles.scss

I4009: image alt overflow issue

---

src/ui/components/ShowMoreCard/ShowMoreCard.scss

Fixes: #4086 
PS: word wrapping on `showmore-card-contents` so that this may not replicate at other places too
Before:
After:

I4086: word wrap for show more card contents

---

src/amo/components/App/styles.scss
src/ui/components/DismissibleTextForm/styles.scss

fix: Don't set input to 100% (Fix #4268)

---

config/functional-development-amo.js

Fixes #4294
* A config named functional-development-amo for setting up the
addons-frontend server for running the uitests at the addons-server repo.
I followed the ```short-hostname``` option found here: https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order
My env variables to run this on docker-compose with the addons-frontend image as the base image are:
``` 
- NODE_APP_INSTANCE=amo
- NODE_ENV=development
- API_HOST=http://olympia.test
- HOSTNAME=functional.test
```

Add config for functional tests.

---

src/amo/components/LandingPage/styles.scss

fix: Explore mobile categories buttons

---

src/core/containers/ServerHtml.js
tests/unit/core/containers/TestServerHtml.js

Fixes #3275 
This uses the `amoCDN` key from the config object to create the favicon link in
ServerHtml.js.

Update the favicon urls to directly point to the CDN

---

src/amo/components/AddonReviewListItem/styles.scss
src/ui/components/TooltipMenu/styles.scss

Fixes #4303, by not overriding button styles inside these elements. The nesting on a lot of this CSS is pretty rough/complex by necessity and this was the most future-proof way to solve it for now. It could use future cleanup.

fix: Do not overwrite button styles in tooltip lists

---

config/default-disco.js

Fixes #4320 
Running this locally with `yarn run disco` and hitting http://127.0.0.1:3000/en-US/firefox/discovery/pane/48.0/Darwin/normal?edition=china shows up the different content.

Add edition to allowed params to be passed through to the disco pane API

---

src/amo/components/Category/index.js
tests/unit/amo/components/TestCategory.js

Fixes #4043 
When a category page is visited via direct link, the viewContext is not set to the proper value
which results in the wrong link in SectionLinks being highlighted. This patch adds a dispatch for
SET_VIEW_CONTEXT to the Category component to fix this issue.
I'm not entirely sure about the behaviour in the test for `does not fetch anything, but sets a viewContext when already loaded`. I think we still need to do this (i.e., set the viewContext), and that the test is therefore accurate, but I could be wrong about that.

Make sure the proper viewContext is set when loading a category page

---

src/amo/components/ScreenShots.js
tests/unit/amo/components/TestScreenShots.js

Fixes #3917
This adds a title attribute to the img tag that is generated for screenshot thumbnails
which will result in a tooltip when hovering.
It uses the value of item.title for the title, which comes from the caption property of
the preview object returned via the API.

Display a tooltip for screenshots

---

.eslintrc
src/amo/api/collections.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
src/amo/sagas/reviews.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

* Fixes https://github.com/mozilla/addons-frontend/issues/4350 by invalidating the collection object after an update
* Fixes https://github.com/mozilla/addons-frontend/issues/4351 by removing the `finishUpdateCollection()` action which is no longer needed

Fix update-collection saga, clean up collection reducer

---

package.json
yarn.lock

Allows us to start implementing #4339.

chore: Update React for fragments support (#4339)

---

src/amo/components/Home/index.js
src/amo/components/HomeHeroBanner/index.js
src/amo/reducers/home.js
src/amo/sagas/home.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/reducers/test_home.js
tests/unit/amo/sagas/test_home.js

Fixes #4330 
This changes all the necessary files for the content update, and also includes a change to the way that collections are requested by and fetched for the home page. A variable number of collections can now be requested without requiring changes to the reducer or the saga.
I feel like a further refactor could be beneficial. It would be nice if the home page could specify which datasets it needs, and the reducer and the saga could  maintain the logic for all of the possible datasets (as opposed to adding and  removing code each time a change is required). Then the saga could retrieve only the requested data, and pass only the requested data back. As this procedure is only in place temporarily, I wasn't sure if it was worth making that change as well, but I'm happy to do so if …

Update homepage content for Feb 15

---

src/amo/css/ScreenShots.scss

Fixes #4334
This is done by applying the overflow-wrap: break-word rule to the div that contains the caption.

Allow unbroken strings in screenshot captions to be wrapped

---

src/amo/components/LandingAddonsCard/index.js
tests/unit/amo/components/TestLandingAddonsCard.js

Fixes #4374 
It should really have been able to do this before, and this fixes the issue so we can now pass simple strings into LandingAddonsCard.footerLink.
Note that I'm fairly sure the way I am checking for the value in the test is wrong, but I wasn't sure how else to verify that the string passed made it into the AddonsCard properly. Feedback is appreciated.

Allow LandingAddonsCard to accept a string for the footerLink property

---

src/core/server/base.js
src/disco/css/Addon.scss
src/disco/css/App.scss

Close #4245.
Fix #4190.
This changes the redirect so we aren't pointing to a version of disco pane in development with padding compensation, but also fixes #4190.

fix: Tweak version redirect and small size for disco pane

---

src/amo/components/AddonReviewList/index.js
src/core/sagas/search.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/core/sagas/testSearch.js

Fixes #4081 
The problem here is that we are sanitizing the page number via `parsePage` before sending it to the API, which causes any non-numbers and the number 0 to be converted to a 1. When that is passed into `fetchReviews` it of course retrieves the first page of reviews.
Simply removing that sanitization fixes this issue and allows the API to return a 404 as expected, which is similar to how `SearchBase` behaves.
I'm not sure if there are any other repercussions to this change, but everything seems to behave as expected. I do wonder, however, if it might not be a better approach to check the page value before even dispatching `fetchReviews` to avoid making that call if the number is invalid? That's not what `SearchBase` does, but it might be worth considering.

Cause incorrect page numbers to return a 404 in "All reviews" pages

---

src/amo/components/Header/index.js

(fix #4397)
Looks like this slipped in unintentionally, sorry about that.

fix: Use href instead of to for Links in header

---

src/core/api/index.js
tests/unit/core/api/test_index.js
tests/unit/core/api/test_search.js
tests/unit/helpers.js

Fixes https://github.com/mozilla/addons-frontend/issues/4393 by configuring all API requests with the new parameter.
Because all API requests have a new query param, this broke a lot of tests that were too tightly coupled to the entire URL. I fixed all of those by making the tests ignore parts of the URL that were not relevant. This is something we've been meaning to do for a while now. I thought there was an issue on file but I couldn't find it.
Sorry for the noise but this cleanup should make the tests more robust.

Explicitly ask API to wrap outgoing URLs

---

config/dev-amo.js
config/development-amo.js

`addons-server` defines whether the API exposes beta-versions or not and the frontend only displays the link if there are beta versions. So this patch will make showing/hiding beta-versions work by just flipping the waffle switch in the backend.

Default to show beta-versions, gated by waffle switch on the backend

---

src/disco/constants.js

new system add-on identified via https://ftp.mozilla.org/pub/system-addons/

add new system add-on

---

config/default.js
src/core/containers/ServerHtml.js
tests/unit/core/containers/TestServerHtml.js

Fixes #4365 
I was unable to reproduce issue #4365, but @diox was, so we believe it is a caching issue. The favicon is configured to be cached with `Cache-Control: max-age=315360000` so we need to force a refresh on clients who still have the old favicon.

Add a query string to the favicon link to force clients to retrieve the newest one

---

src/ui/components/FormOverlay/index.js

Fixes https://github.com/mozilla/addons-frontend/issues/4433 by setting the cancel button to `type=button`. Previously, the default of `type=submit` was taking effect which triggered the `onCancel` handler. After this new patch, pressing enter will trigger the `onSubmit` handler.

Pressing enter should not cancel the form

---

src/amo/components/Addon/index.js
src/amo/components/AddonsCard/index.js
src/amo/components/Collection/index.js
src/amo/components/Home/index.js
src/amo/components/LandingAddonsCard/index.js
src/amo/components/SearchResult/index.js
src/amo/components/SearchResults.js
src/core/constants.js
src/core/utils/index.js
src/disco/components/Addon.js
src/ui/components/HeroSection/index.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonsCard.js
tests/unit/amo/components/TestLandingAddonsCard.js
tests/unit/amo/components/TestSearchResult.js
tests/unit/core/components/TestInstallButton.js
tests/unit/core/utils/test_index.js
tests/unit/ui/components/TestHeroSection.js

Fixes https://github.com/mozilla/addons-frontend/issues/4372 by adding the old add-on install source links. The issue specifies some old home page shelves that we aren't using anymore so I've asked about what to do there. I will file a follow-up issue for that if necessary.

Use add-on install source links like the old site

---

src/amo/components/AddonMeta/index.js
src/amo/components/AddonReview/index.js
src/amo/components/AddonReviewListItem/index.js
src/amo/components/RatingManager/index.js
src/amo/components/SearchResult/index.js
src/ui/components/Rating/index.js
src/ui/components/Rating/styles.scss
src/ui/components/UserRating/index.js
tests/unit/amo/components/TestAddonReview.js
tests/unit/amo/components/TestAddonReviewListItem.js
tests/unit/amo/components/TestRatingManager.js
tests/unit/ui/components/TestRating.js
tests/unit/ui/components/TestUserRating.js

Fixes #4355 
This adds a new styleName to the Rating component to support a different style of stars for a rating submitted by the current user.
Note that as per #4355, the only place this change needed to be made was on the list of reviews where a user's own review should appear with yellow starts, and all other reviews should appear with grey stars.
Before:
After:

Make all visual representations of the user's personal ratings yellow

---

src/amo/components/Category/index.js
src/amo/components/LandingPage/index.js
src/core/constants.js

Fixes https://github.com/mozilla/addons-frontend/issues/4475
This only fixes the missing install sources on extension landing pages and category pages. When I get clarification on the `src=filter` part of the original issue, I'll address them with a separate patch.

Fix missing add-on install sources

---

src/ui/components/Icon/img/anonymous-user.svg
src/ui/components/UserAvatar/index.js
tests/unit/amo/components/TestAddonMoreInfo.js
tests/unit/amo/components/TestAddonReviewListItem.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/components/TestHeader.js
tests/unit/amo/helpers.js
tests/unit/amo/reducers/test_users.js
tests/unit/helpers.js
tests/unit/ui/components/TestUserAvatar.js

Adds a user avatar component that renders an anonymous user icon when the user is `null` (loading) or has no picture set.
fix #4471

feat: Add User Avatar component

---

src/amo/components/Collection/styles.scss
src/ui/components/MetadataCard/styles.scss

Fixes #4185 
Fixes #4493 
Closes #4493
Before:
After:

I4185: fix text overfow in collection

---

package.json
yarn.lock

Fixes #4497 
For some reason Greenkeeper didn't issue a PR for this. This also syncs the yarn.lock file.

Upgrade eslint-config-amo to version 1.6

---

bin/build-locales
src/amo/sagas/home.js
src/core/addonManager.js
src/core/components/InstallButton/index.js
src/core/i18n/utils.js
src/core/utils/index.js
tests/unit/TestCSPConfig.js
tests/unit/TestFrameGuardConfig.js
tests/unit/TestLocalesConfig.js
tests/unit/core/middleware/test_frameguardMiddleware.js
tests/unit/helpers.js
webpack.dev.config.babel.js
webpack.prod.config.babel.js

Fixes #4477
Support for this syntax landed in https://github.com/mozilla/addons-frontend/commit/23f4d49813bba0eed1b0f19fb0729ee2cb1ea5d3, so we can now remove all the eslint comments that were added before this was supported.

Remove all eslint-disable comments for for...of syntax

---

package.json
src/amo/api/collections.js
tests/unit/amo/api/test_collections.js
yarn.lock

Fixes #4504 
This adds helpers for creating a collection, and refactors the code for updating a collection to be shared with that for creating a collection.

API helpers for creating a collection

---

src/amo/components/App/styles.scss

Fixes mozilla/addons#657.
This sets explicit `color` for `input, textarea`.
Before:
After:

Fix input text color on dark GTK themes (fix mozilla/addons#657)

---

src/amo/components/AddonCompatibilityError/index.js
src/ui/components/Notice/index.js
src/ui/components/Notice/media/generic-info-mark.svg
src/ui/components/Notice/styles.scss
tests/unit/amo/components/TestAddonCompatibilityError.js

fix: Make "Download Firefox" notice less red

---

src/amo/components/Addon/styles.scss
src/amo/components/AddonBadges/styles.scss
src/ui/components/Badge/index.js
src/ui/components/Badge/styles.scss

I4520 : layout change for addon badges

---

src/amo/api/collections.js
src/amo/sagas/collections.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes https://github.com/mozilla/addons-frontend/issues/4574
Whoops, in the last patch I forgot to remove the old API helper and make `Addon` use the new one. We needed a new "modifier" API helper to support both create/update in a DRY way.

Use new collection add-on modifier on add-on detail page

---

src/amo/components/CollectionManager/index.js
src/amo/components/CollectionManager/styles.scss
src/amo/components/EditableCollectionAddon/index.js
src/amo/components/EditableCollectionAddon/styles.scss
src/ui/components/FormOverlay/index.js
src/ui/components/FormOverlay/styles.scss
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/components/TestEditableCollectionAddon.js

Fixes https://github.com/mozilla/addons-frontend/issues/4579 but check out that issue for a list of what this patch adds. It's pretty much just styles.

Styles for viewing add-ons within collection manager

---

src/amo/components/Header/index.js

Fixes #4619 
I cleaned these up after an r+wc and just mixed up the props/ternary. Easy r?–I'm dumb.

fix: Don't show next UserProfile when config disabled

---

src/amo/components/AutoSearchInput/index.js
src/core/reducers/autocomplete.js
tests/unit/amo/components/TestAutoSearchInput.js
tests/unit/core/reducers/test_autocomplete.js

Fixes #3070 - Only initiate autocomplete for the search bar after `𝑛` characters have been entered. In this case, `𝑛` should be a configurable integer value.

Fixes #3070 - Only initiate autocomplete when 𝑛 characters are present

---

src/amo/components/AddonCompatibilityError/index.js
tests/unit/amo/components/TestAddonCompatibilityError.js

Hello, 
I have changed the color of the "Download Firefox" message bar from the grey to green, as requested in #4633. Here is a screenshot of how the message looks right now:

Fixes #4633: changed color of "Download Firefox" message bar

---

src/amo/components/PermissionsCard/styles.scss

Fixes #4689 
`display: flex` doesn't respect the `width` so enforcing consistent it with `min-width`
Before:
After:

Fixes 4689 - icon size in permissions box

---

src/ui/components/Rating/index.js
tests/unit/ui/components/TestRating.js

Fixes #3231 - Let's display a more appropriate tool-tip when the user has not rated the current add-on.
**Before:**
**After:**

Fixes #3231 - Hovering over a star shows the tooltip "No ratings"

---

src/amo/components/UserProfile/styles.scss
src/ui/components/Icon/styles.scss

Hello,
I have changed the default profile picture's size to 50px #4648. 
Here is a screenshot of what it looks like right now:
Please let me know if that is the desired picture size and I will change it if required.

Fixes #4648: changed anonymous profile picture size

---

src/amo/components/AddonBadges/styles.scss

I have added spacing between 'featured' badge and theme preview in Theme details page. 
I have modified left margins only by 6px and 12px based on the screen size. #4626 
Before:
After:

Fixes #4626: added spacing between 'featured' badge and theme preview in Theme details page

---

src/amo/components/Collection/styles.scss
src/amo/components/CollectionManager/styles.scss

#4645 
The `overflow` of `card-contents` is hidden that causes the issue, limiting `AutoSearchInput` to `max-height: 90px` that is 3 addon.
Before:
After:

I4645 - fix autocomplete height in collection

---

src/ui/components/Rating/index.js
tests/unit/ui/components/TestRating.js

fix: Do not show rating option when readOnly set

---

docs/i18n.md

I think this tripped up @bobsilverberg and meant we didn't get locales
merged until later than usual.
No issue for this one; it's just a docs change and needs no QA.

docs: Don't suggest reviewing locale changes

---

src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes #4505
This adds code to reducers and sagas for creating a collection, as well as refactoring the code for updating a collection so that create/update can share some code.
It also removes `collectionUpdates` from state as it is never used.

Saga helpers for creating a collection

---

src/ui/components/ShowMoreCard/ShowMoreCard.scss

Fixes #3787 
I know that this patch is highly flawed, but I figured providing some sample code would help illustrate the problems I'm struggling with and make the questions I'm going to ask below more clear...
We want to increase the amount of space that the `ShowMoreCard` allows on desktop, for the add-on description. I increased the allowable space by adding a rule for `respond-to(large)`, which seems to work, but I'm not sure if that's the correct approach. Are we equating desktop with `large`? What about `medium`?
Assuming the above is okay, the other part of the problem is deciding when to show the "Read more" footer. The current code has 150px hardcoded as a limit in the `ShowMoreCard` component, but now the limit is different between desktop and mobile. I tried to solve this with a …

Increase the possible height of the add-on description on desktop

---

src/amo/api/users.js
src/amo/reducers/users.js
tests/unit/amo/api/test_users.js

Gonna do the API/reducer/saga stuff for this all separately and maybe it'll make the PRs nice and easy.
Here's the API and tests for editing a user profile. I've exclude the image upload for now as I'll do that last.
Part of #4668.

chore: add API for edit user profile (#4668)

---

src/amo/components/Addon/index.js
tests/unit/amo/components/TestAddon.js

Closes #4621.
Restores the correct number of add-ons to the "more add-ons by authors" cards on the add-on details.

fix: #4621 regressions

---

src/amo/components/AddonReviewListItem/styles.scss

#4318 : The button was centered already, so I have fixed width of the pop-up window and made it less 'weird' as was suggested in comments. Please let me know if that is something you were looking for or if you would like to make it shorter.
Before:
After:

Fixes #4318: Made 'Log in to flag review' button shorter and less weird

---

src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes #4717 
This finishes implementing the collectionUpdates state which is managed by the collections reducer. The state will be set to `updating: true` when an update is started, and to `updating: false` when an update finishes. In addition, the state will have a `successful: true` if there were no errors, and a `successful: false` if there were errors. It also introduces a `getCollectionUpdateStatus` function which will return the current update status of a collection. This will be used on the CollectionManager screen to address issue #4635, which will be completed in a separate PR.

Properly implement the collectionUpdates state

---

src/amo/components/CollectionManager/index.js
tests/unit/amo/components/TestCollectionManager.js

Fixes #4720 
Removed validation code. 
As described by @bobsilverberg in issue #4720, validation was insufficient, as it allowed a name which consisted of only blanks. This validation is no longer needed after PR #4698 addressed the issue by preventing the form from being submitted with a blank collection name.

Remove validation for collection name from CollectionManager form

---

.travis.yml

More of a band-aid than a fix, but right now the constantly failing master builds are making it too easy to ignore an actual failing build.

Temporarily disable Disco Pane tests on Travis (#4747)

---

src/amo/reducers/users.js
tests/unit/amo/reducers/test_users.js

Part of #4668.
This adds the reducer code needed to allow us to edit users. The `editUserAccount` action will be used to dispatch an action to a saga that will call the edit API.
That API returns the updated edit user object, so we'll just use the existing `loadUserAccount` action to update the user account in state after editing.

chore: Add edit user reducer actions (#4668)

---

src/amo/components/PermissionsCard/permissions.js

Fixes:4770 Fixing "s" for setting in Control browser proxy settings permission

---

src/amo/components/AddonsByAuthorsCard/index.js
src/amo/components/AddonsByAuthorsCard/styles.scss
src/amo/components/AddonsCard/index.js
src/amo/components/UserProfile/index.js
src/amo/components/UserProfile/styles.scss
tests/unit/amo/components/TestUserProfile.js

Fix #4280
Fix #4281
Screenshots:
(they would both show for a user with both extensions and themes, but I couldn't find one 😆)

feat: Add extensions and themes to profile

---

src/amo/components/AddonsCard/index.js
src/amo/components/Collection/index.js
src/amo/components/CollectionManager/index.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
src/core/api/index.js
src/core/components/Paginate/index.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/components/TestAddonsCard.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/helpers.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/reducers/test_home.js
tests/unit/amo/sagas/test_collections.js
tests/unit/amo/sagas/test_home.js
tests/unit/core/api/test_index.js
tests/unit/core/components/TestPaginate.js
tests/unit/helpers.js

Fixes #4590 
Sorry the PR is so large. The changes to support the feature are fairly large, but I also had to touch a bunch of other files because I had to make a couple of other changes to implement my feature.
These are:
- I needed to add a new const, `DEFAULT_API_PAGE_SIZE` and I thought it best to use that const in all places it should be used. 
- I renamed a helper function from  `createFakeCollectionAddons` to  `createFakeCollectionAddonsListResponse`, because the former wasn't really accurate and I needed to create a new one called `createFakeCollectionAddons` which was accurate.
Those changes resulted in a bunch of extra files being touched, but it should be pretty easy to review those changes.

Add an add-on to a collection from the edit screen

---

src/amo/reducers/addonsByAuthors.js
tests/unit/amo/reducers/test_addonsByAuthors.js

Fixes #4818 
Prior to this fix, if one of the usernames passed didn't have any add-ons loaded, then the
whole function returned null, even if there were some add-ons loaded for some of the
usernames. This situation can arise because when add-ons are fetched for a set of
usernames not all add-ons are fetched and loaded, so we can end up with a username
without any loaded add-ons.

Fix getAddonsForUsernames so it will work consistently with multiple usernames

---

src/amo/components/Addon/index.js
src/amo/components/AddonsByAuthorsCard/index.js
src/amo/components/UserProfile/index.js
src/amo/reducers/addonsByAuthors.js
src/amo/sagas/addonsByAuthors.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonsByAuthorsCard.js
tests/unit/amo/reducers/test_addonsByAuthors.js
tests/unit/amo/sagas/test_addonsByAuthors.js

Fixes #4806 
Note that this is built on top of the commit in PR #4828, so only the 2nd commit in this PR needs to be looked at.
This fixes the issue both on the User Profile page and on the Addon Details page.
Before:
After:
Before:
After:

Output the author's displayName rather than their username on the AddonsByAuthorsCard

---

src/amo/components/Collection/styles.scss

I4825 - fixes overflow issue

---

docs/i18n.md

I noticed this error when I started doing the weekly extract/merge, and only now am getting around to updating the docs.

Fix i18n docs to have correct command line for committing changes

---

src/amo/components/AddonsByAuthorsCard/styles.scss
src/amo/components/UserProfile/styles.scss

fixes #4830 - user profile page style fixes
BEFORE EX:
AFTER EX:
@bobsilverberg @muffinresearch

issue 4830 profile style fix

---

src/amo/components/AddonsCard/styles.scss

I have truncated addon names on the homepage as requested in #4070.
Please let me know if any additional changes are required.

Fixes #4070: fixed unbroken long addon names on the homepage

---

src/amo/components/AddonReviewListItem/index.js
tests/unit/amo/components/TestAddonReviewListItem.js

fixes #4054  - remove reply to review link on dev's reply
BEFORE:
AFTER:
@bobsilverberg @muffinresearch

i-4054 remove dev reply url to their own reply

---

src/amo/components/EditableCollectionAddon/styles.scss

Fixes #4813 - addresses style issue in collections text while in editing mode
example of before and after screenshots:
BEFORE EX:
AFTER EX:
@bobsilverberg @muffinresearch

issue 4813 - fixes collection text style issue

---

src/ui/components/HostPermissions/index.js
tests/unit/ui/components/TestHostPermissions.js

I4871: fixes duplicate site permissions

---

src/amo/components/AddonsCard/styles.scss

This reverts commit d758b5be960d83ebc6abed6acb221e6f69a952c0.
I'm reverting this since using truncation is not something we're currently doing for long strings.
Truncating a string with an ellipsis has some issues related to accessibility and it's preferable to keep the wrapping of the string so it's fully readable.

Revert "fixed long extension names on the homepage (#4856)"

---

src/amo/components/SearchFilters/index.js
src/amo/components/SearchFilters/styles.scss

Fixes #4188: Improved styling for the `Featured add-ons only` checkbox to be easier to click for users in responsive views.
Changes include:
1. The `label` element now wraps the `checkbox`
2. `padding-right` has been added to increase the click target for users in both desktop and mobile viewports
3. Increased the `font-size` and `height`/`width` of both the `label` text as well as the `checkbox` for easier readability

Allow "Featured add-ons only" checkbox to be selected more easily

---

bin/build-locales

Fixes #4927
See this spreadsheet for a before and after https://docs.google.com/spreadsheets/d/1im9GjQu4Sl_dpsGZjwB5cmrTvNSUH00XystddmTm7qQ/edit#gid=0
This will cache-bust AMO and disco pane's JS

Cachebust all JS files via locale build modification.

---

.travis.yml

I had to open each job to select the one I actually wanted to browse, this patch adds a way to know which job runs which tool.
Before:
After:

Add name to each travis job

---

src/ui/components/HeroSection/styles.scss

Fixes #4886 
The line-height between lines is small, which impact reading experience.
Before:
Screen width under 500px:
Screen width over 500px:
After:
Screen width under 500px:
Screen width over 500px:
The issue creator indicated to change the `line-height` from 1 to initial, I think the default line-height looks better, 1.5 seems too big. However, I am not sure if there is any concerns for changing it. 
Please correct me if I miss something. Thanks!

i-4886 Line height less in 320*480 dimension of Webpage

---

src/ui/components/Rating/index.js
tests/unit/ui/components/TestRating.js

#Fixes #4692 - Each rating star should have its own title attribute with the rating number respective to it.

Add a more intuitive tool-tip for each add-ons rating star

---

src/core/i18n/translate.js

We have many warnings and I don't think we use context to pass the
`i18n` prop anymore. This should remove some warnings in the devtools.

Remove childContextTypes in Translate HOC

---

package.json
yarn.lock

Remove stylefmt from dependencies to eliminate nsp-check failure

---

src/amo/components/CollectionManager/index.js
tests/unit/amo/components/TestCollectionManager.js

Fixes https://github.com/mozilla/addons-frontend/issues/4951
Because only if a collection is saved, it is able to search add-ons. Thus, this PR hide the add-on search field when a collection is creating.
On adding a collection:
On editing a collection:

i-4951 hide search addon field before collection saved

---

src/amo/components/CollectionList/index.js
tests/unit/amo/components/TestCollectionList.js

fixes #4969 - placeholder text was always showing whether logged in or not...this fixes that so only shows when logged in
logged out:
logged in:

I4969-fixing collection placeholder text to display for loggedin user only

---

src/ui/components/Rating/index.js
tests/unit/ui/components/TestRating.js

Fixes #4995 - remove the trailing period from rating tooltip messages as it makes the tooltip text instructive/imperative rather than infinitive, which negatively affects a number of localizations.

Remove trailing period from rating tooltip message

---

src/amo/components/Header/index.js
src/amo/components/UserProfile/index.js
src/amo/components/UserProfileEdit/index.js
src/amo/reducers/users.js
tests/unit/amo/components/TestUserProfileEdit.js
tests/unit/amo/reducers/test_users.js
tests/unit/helpers.js

Fix #4958
---
I do not think we should have logic for retrieving the display name
since the API already does that by exposing a `name` field.

Remove getDisplayName() logic and use 'name' API field

---

src/amo/components/Addon/styles.scss

fixes #4967 - adjusts both get-firefox and Install btn styles to be consistent and align with their respective text

I4967-adjusting styles so get-firefox/Install btns look is consistent/align with text

---

.eslintrc
src/amo/api/users.js
src/amo/reducers/users.js
src/amo/sagas/users.js
tests/unit/amo/api/test_users.js
tests/unit/amo/sagas/test_users.js

Fix #5029 – Refs #4276 – ⚠️ Depends on #5013 
---
This PR allows to send a picture file along with editable fields when editing a user profile. Only the second comment is relevant.

Allow to send a user picture along with editable fields

---

src/amo/components/UserProfileEdit/styles.scss

Fix margin in user profile edit page

---

src/amo/components/UserProfileEdit/styles.scss

Fix input width in edit profile page

---

src/amo/components/UserProfile/index.js
tests/unit/amo/components/TestUserProfile.js

Fix #5060
---
This PR fixes the behavior observed in https://github.com/mozilla/addons-frontend/issues/5036#issuecomment-390570679 by using a "fixed" error handler, which is the handler we should be using on most of our "page level components".
It allows to synchronize the errors between the server and the client, thus avoiding unnecessary data re-fetching on the client if the server gets an error.

Use fixed error handler in user profile page

---

src/amo/components/Link.js

Refs #2448
---
This PR removes a warning in the devtools logs (`dispatch` is not a valid prop for `<a>`).

Do not pass dispatch to <a> in Link component

---

src/amo/components/UserProfile/styles.scss

Fixes #5020 
Added word break property to user profile biography section.
Change successfully run locally in FF browser 61.0b6 Ubuntu and works on all media breakpoints.
Before:
After:

Wrap unbroken strings in profile page biography

---

src/amo/components/UserProfileEdit/index.js
tests/unit/amo/components/TestUserProfileEdit.js

Fix #5034
Fix #4965
---
I have added a login button to the user profile edit page:
Important: the button is named "Log in to continue" because we don't know if the user is going to edit their profile, another profile (admin) or get a 404 because the user cannot access this page.

Login button user edit

---

src/amo/components/UserProfileEdit/index.js
tests/unit/amo/components/TestUserProfileEdit.js

Fix #5056
---
This PR makes sure the server returns a 404 when loading a non-existent
user edit page. It is achieved by a "fixed" error handler, which
synchronizes error handling between the server and the client. That is
also why there is no need to check whether there is a current user
logged-in or not anymore.

Returns a 404 when loading a non-existent user edit page

---

src/amo/components/Addon/styles.scss

Fixes #4878 
This PR introduces css changes to the details page of individual add ons. 
The original issue was opened to fix the line containing the author, which at times would overlap with the title (depending on the letters contained in the title, such as `g, y, p, q` and the size of screen) like so: 
<p align="center">
</p><br/>
To fix this problem, I just added a `line-height` of `1.5` to the `Addon-author` class:
<p align="center">
</p><br/>
While implementing this change and testing the results, I also noticed that at times the title itself ran into the same problem: 
<p align="center">
</p>
and another example: 
<p align="center">
</p><br/>
So I added a `line-height` property to the `Addon-title` class as well, with a value of `normal` (1.5 was too much for the title): 
<p …

Css fix for add ons (extensions) detail page

---

src/amo/components/CollectionManager/index.js
src/amo/components/CollectionManager/styles.scss
src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes #4979 
Also fixes #4982 
Note that the message does not currently fade out. I'm going to open a follow-up issue about that. I also think the placement could be improved as well, which can also be dealt with in a follow-up.
Pending @pwalm's response to https://github.com/mozilla/addons-frontend/issues/4979#issuecomment-389245823, it just uses a generic message rather than one customized by add-on type.
Screenshot of message:

Add a confirmation when adding add-ons to a collection

---

.travis.yml
tests/ui/conftest.py

This is an attempt to try and get the discopane tests more stable, first by updating the geckodriver version.

Updating geckodriver for discopane tests

---

src/amo/components/Collection/index.js
src/amo/components/Collection/styles.scss
src/amo/components/CollectionManager/index.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes #4977 
Also fixes #4978
This addresses the main issue, but I think the UX can be improved. Implementing #4978 will help, and I may just roll that into this PR.
I am also having a problem with coordinating the finishing of the create action with the redirection to the edit page. The initial problem was that, when the user is redirected to the edit page, it has to fetch and load the collection first, so the loading gifs on the right show up causing a flash of content that then gets replaced by the placeholder text.
I've tried a few things and cannot get it quite right. I could use some advice. My current attempt has me loading the collection in the saga after creating it (because we have access to the details after creating it), but that doesn't seem to make the collection available …

Change the workflow for Add A Collection to leave the user at the edit screen

---

src/amo/api/users.js
src/amo/components/UserProfileEdit/index.js
src/amo/reducers/users.js
src/amo/sagas/users.js
tests/unit/amo/api/test_users.js
tests/unit/amo/components/TestUserProfileEdit.js
tests/unit/amo/reducers/test_users.js
tests/unit/amo/sagas/test_users.js
tests/unit/helpers.js

Fix #5070
---
This PR adds everything we need to load user notifications when browsing
a user profile edit page. It does not show anything in the UI yet, though.

Add api/saga/reducer to fetch/load user notifications

---

src/amo/api/collections.js
src/amo/components/AddonsCard/index.js
src/amo/components/Collection/index.js
src/amo/components/EditableCollectionAddon/index.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
src/core/api/index.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/components/TestAddonsCard.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/components/TestEditableCollectionAddon.js
tests/unit/amo/sagas/test_collections.js
tests/unit/core/api/test_index.js

Fixes #4577 
This is pretty much complete, except that I couldn't figure out a good way to test the code that lives in `removeAddon` in the `Collection` component. Ideally we'd check that it dispatches a `deleteCollectionAddon` call, but the problem is that it's triggered by a button in a component a could of levels down. I guess we could do it by fully rendering the component, rather than doing a shallow render, but it bothers me that we need to interact with a different component in order to test this one. Any suggestions you have would be appreciated.

Delete a add-on from a collection

---

src/amo/components/UserProfileEdit/index.js
src/amo/components/UserProfileEdit/styles.scss
src/amo/components/UserProfileEditNotifications/index.js
src/amo/components/UserProfileEditNotifications/styles.scss
tests/unit/amo/components/TestUserProfileEdit.js
tests/unit/amo/components/TestUserProfileEditNotifications.js
tests/unit/helpers.js

Fix #5127 – Refs #5000 – ~~Depends on #5071~~
---
It is read-only for now.
Loading state: I chose to display only two notifications because that's what users who are not developers will see anyway.
List of all the notifications returned by the API:
Small screens:
RTL:

UI for user notifications (readonly)

---

src/amo/css/ScreenShots.scss

Changed the display of the ScreenShots by extending the height of the psw-thumbnails section to 220px and same for the viewport height as recommended by @rebmullin . This is related to issue #4887. 
More details regarding the fix:
After testing I realized the two suggestions work hand in hand. They are both based on the height variable defined earlier in that file as 200px. So changing this to 220px changes both values and this resolves the display issue. However, the screenshot image's height is also reliant on this variable so when this value is changed to 220px it does not fix the issue. So the suggested fix is to make this image's height be 20px less of the variable's height and change the variable value to 220px. This 20px less fix is calculated at runtime by performing this …

Fixed height issues with Screenshots section

---

src/amo/components/CollectionManager/index.js
src/amo/components/CollectionManager/styles.scss
tests/unit/amo/components/TestCollectionManager.js

fixes #5011 
video
https://monosnap.com/image/52gnX55LZiRElcneQSKGCGWiJAHHwN.png
I feel like we should add some transition effect here too...

I5011 improve collection success msg appearance

---

src/amo/components/SearchResult/styles.scss

fixes #5173 
for persona theme images, i am reverting back to `top right` styles so nothing is cut off and to give better sense of the theme style

I5173 static theme persona style fix

---

src/amo/api/collections.js
src/amo/components/AddAddonToCollection/index.js
src/amo/components/CollectionManager/index.js
src/amo/reducers/collections.js
src/amo/sagas/collections.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/components/TestAddAddonToCollection.js
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js

Fixes #5164 
Note that this patch is pretty much all just renames. I don't believe any logic had to change anywhere to make this work.

Use slug instead of collectionSlug everywhere except for modifying a collection

---

src/amo/components/UserProfileEditPicture/index.js
src/amo/components/UserProfileEditPicture/styles.scss
src/ui/components/ConfirmButton/index.js
src/ui/components/ConfirmButton/styles.scss
tests/unit/amo/components/TestUserProfileEditPicture.js
tests/unit/ui/components/TestConfirmButton.js

Fix #5151
---
Notes:
- I chose to hide this action on small screens. I am not sure we really need it on a smartphone...
- The "cancel" style for the button is fixed in another PR (#5140)

Add a ConfirmButton and use it to delete a profile picture

---

src/amo/components/Addon/styles.scss

fixes #5181 
before - left aligned (mobile)        |  after - right aligned (mobile)
:-------------------------:|:-------------------------:

I5181 persona style fix in header

---

src/amo/api/collections.js
src/amo/components/AddAddonToCollection/index.js
src/amo/components/Collection/index.js
src/amo/components/CollectionManager/index.js
src/amo/components/Home/index.js
src/amo/reducers/collections.js
src/amo/routes.js
src/amo/sagas/collections.js
src/amo/sagas/home.js
tests/unit/amo/api/test_collections.js
tests/unit/amo/components/TestAddAddonToCollection.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/containers/TestHome.js
tests/unit/amo/reducers/test_collections.js
tests/unit/amo/sagas/test_collections.js
tests/unit/amo/sagas/test_home.js

Fixes #5142 
I decided to use the string `username` as the identifier in all cases, rather than the numeric `userId`, mainly because of this [comment](https://github.com/mozilla/addons-frontend/blob/38c186ed9a33f950db1ebbeb09b6cb386fd9d1fd/src/amo/api/collections.js#L133), which has to do with the fact that we sometimes redirect to a URL and want that URL to be username-based.
Sorry for the large PR. It's *mostly* just direct changes from `userId` to `user` in a lot of places, but there are a few places I had to change some logic as well, mostly in the components.

Consistently use username as the user identifier in collections reducers and sagas

---

src/amo/components/Addon/styles.scss
src/core/css/inc/vars.scss

fixes #5176 - fixes style issue seen when theme has a badge associated with it
before (badge text wraps here):
after (no wrapping badge text):

I5176 badge in header style fix

---

src/amo/components/UserProfileEditPicture/styles.scss

Fix #5189
---
I made the button larger and centered under the picture + "upload" button.

Fix delete picture button style

---

src/ui/components/Card/styles.scss

Fix https://github.com/mozilla/addons-frontend/issues/5199
---
The reverted commit creates another bug on some cards (see the corners below the grey button):
The UI bug fixed by the reverted commit was almost invisible whereas this one is quite visible... That's why I think it makes sense to revert the patch and work on the original issue later.
Original issue is: https://github.com/mozilla/addons-frontend/issues/4884

Revert "Fix border radius in the about this extension card (#5050)"

---

src/amo/api/users.js
tests/unit/amo/api/test_users.js

Fix #5190 
---
This is needed to configure `fetch` to send credentials (`include`) so that cookies can be set. We want this because the API sets new (empty) cookies when the current logged-in user deletes their profile in order to log out this user successfully.

Send credentials when deleting user account

---

src/amo/components/UserProfileEdit/index.js
src/amo/reducers/users.js
tests/unit/amo/components/TestUserProfileEdit.js
tests/unit/amo/reducers/test_users.js
tests/unit/helpers.js

Fix #5206
---
This PR introduces a `isDeveloper()` selector to quickly determine
whether a user is an artist or add-on developer.
Before:
After:

Hide notifications information for non-developer users

---

src/amo/components/UserProfileEdit/index.js
tests/unit/amo/components/TestUserProfileEdit.js

Fix #5207
Fix #5211
---
This PR disables the confirm button to avoid a user or admin to delete a
user profile that owns add-ons.
regular user:
admin:

Disable confirm button when user to delete has add-ons

---

src/amo/api/users.js
src/amo/components/UserProfileEdit/index.js
tests/unit/amo/api/test_users.js
tests/unit/amo/components/TestUserProfileEdit.js

Fix #5212
---
This PR fixes an issue caused by a `textarea` component, which does not
accept `null` as a valid value. It outputs a warning in the dev tools
but also converts `null` to `"null"` (string) on submit, causing the
issue reported in #5212.

Make sure we never pass null to a textarea

---

src/amo/components/Addon/styles.scss

Fix #5226
---
The PR sets the `max-width` to the theme image header container so that all other elements are still contained inside (especially the install button that goes out of the container in RTL mode, sometimes).

Set max-width to the parent container (theme header)

---

src/disco/constants.js

identified via https://ftp.mozilla.org/pub/system-addons/

add 2 new system extensions

---

src/amo/components/Collection/index.js
src/amo/components/Collection/styles.scss
src/amo/sagas/collections.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/sagas/test_collections.js

Fixes #4195 
Depends on #5161 
This adds a "Delete this collection" button to the Collection screen, both in display and edit mode, which only appears if the user has access to delete the collection. For now I have styled it similar to the "Delete this picture" button on the User Profile.
Detail screen:
With confirmation:
Edit screen:
With confirmation:

Delete a collection - UI portion

---

src/amo/components/UserProfile/styles.scss

Fixing Word break in Biography section 

---

src/amo/reducers/users.js
tests/unit/amo/reducers/test_users.js

Fix #5214
---
By not resetting the `notifications` property of a user when updating
this user in the state, we don't have to reload the notifications for
this user and there is no problem of notifications being stuck in a
loading state as described in #5214.

Do not reset notifications in users reducer

---

package.json
tests/unit/amo/components/TestAddAddonToCollection.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonRecommendations.js
tests/unit/amo/components/TestAddonReviewList.js
tests/unit/amo/components/TestAddonsByAuthorsCard.js
tests/unit/amo/components/TestCategories.js
tests/unit/amo/components/TestCategory.js
tests/unit/amo/components/TestCollection.js
tests/unit/amo/components/TestCollectionManager.js
tests/unit/amo/components/TestLandingPage.js
tests/unit/amo/components/TestReportAbuseButton.js
tests/unit/amo/components/TestReportUserAbuse.js
tests/unit/amo/components/TestUserProfile.js
tests/unit/amo/components/TestUserProfileEdit.js
tests/unit/core/TestInstallAddon.js
tests/unit/core/components/TestInstallButton.js
tests/unit/core/test_tracking.js
tests/unit/ui/components/TestExpandableCard.js
yarn.lock

Closes #5265
I had to replace calls to spy.reset() with calls to spy.resetHistory(), which is a bit odd, because apparently spy.reset() was removed in version 5, which we were previously on. Maybe it was just deprecated in version 5, and removed entirely in version 6. In any case this fixes the test failures for me locally.

update sinon to version 6.0.0

---

src/amo/components/UserProfileEdit/index.js
tests/unit/amo/components/TestUserProfileEdit.js

Fix #5250
---
This PR reduces the number calls to `window.scroll`: it is not called
when we re-render because of a new error or a success message, but only
the first time!

Only scroll the first time we render an error or message

---

src/amo/components/Header/styles.scss

Fixes https://github.com/mozilla/addons-frontend/issues/5306
Autocomplete search results on mobile are too small. This maximizes them in the current layout as a simple solution. A more complex solution would be to make the search box go full width when you focus on it (and hide the login button) but that requires a lot of new state management logic (I think).
This improvement will look more dramatic on wider screen devices, such as Android Pixels.

Make the search box bigger on small mobile screens

---

src/core/components/ErrorPage/index.js
src/core/containers/error-simulation/SimulateClientError.js
src/core/containers/error-simulation/SimulateClientError.scss
src/core/reducers/errorPage.js
tests/unit/core/containers/error-simulation/TestSimulateClientError.js

Fix #5278 
---
This PR adds a new button to the `SimulateClientError` that throws an error in the `render()` method, in order to test our integration with Sentry (and `componentDidCatch()` in `ErrorPage`). It also adds more Flow coverage.

Update SimulateClientError to trigger render errors

---

src/amo/components/ScreenShots.js
src/amo/css/ScreenShots.scss
tests/unit/amo/components/TestScreenShots.js
tests/unit/amo/helpers.js

fixes #4197 - 
instead of scaling up we are now we are using the actual image size. My understanding is that eventually we want to use srcset when the images are all set up (let me know if this assumption is not correct)
With the smaller image it looks a little odd so I have also centered the caption a bit more (it was left aligned in it's container which was centered). 
before:
after:

I4917 screenshot size fix

---

src/amo/components/UserProfileEdit/index.js
src/amo/components/UserProfileEdit/styles.scss

Fix #5314
---
This PR fixes a CSS mistake that hides the Authenticate button on small screens.
Before:
After:

Always show the authenticate button

---

src/amo/components/AddAddonToCollection/index.js
src/amo/components/AddonBadges/index.js
src/amo/components/AddonMeta/index.js
src/amo/components/AddonMoreInfo/index.js
src/amo/components/AddonRecommendations/index.js
src/amo/components/AddonReviewList/index.js
src/amo/components/App/index.js
src/amo/components/CategoriesPage/index.js
src/amo/components/Collection/index.js
src/amo/components/ContributeCard/index.js
src/amo/components/DownloadFirefoxButton/index.js
src/amo/components/ErrorPage/NotAuthorized/index.js
src/amo/components/FlagReviewMenu/index.js
src/amo/components/HomeHeroBanner/index.js
src/amo/components/LanguageTools/index.js
src/amo/components/PermissionsCard/index.js
src/amo/components/SearchForm/index.js
src/amo/components/SearchPage/index.js
src/amo/components/SearchResults/index.js
src/amo/components/SearchTools/index.js
src/amo/components/SectionLinks/index.js
src/amo/components/UserProfile/index.js
src/amo/components/UserProfileEdit/index.js
src/amo/components/UserProfileEditNotifications/index.js
src/amo/components/UserProfileEditPicture/index.js
src/ui/components/FormOverlay/index.js
src/ui/components/UserRating/index.js

Fixes https://github.com/mozilla/addons-frontend/issues/5340
This approach to preventing misuse of Props is a bit of a hack. What it does is *declare* a typehint for what the final component would be. I attempted to do it the right way by adding types for all of our HOC's but that's an uphill battle. This approach works! It produces the Flow errors that I want to see.
The pattern consists of:
* You define the type of your exported component by re-using the `Props` object
* In most cases, you have to make a separation of props that should be regarded as *public* (those that other components will set) and those that are *private* (those used internally which are typically injected by other HOCs). For example, the *i18n* prop is injected by an HOC and never needs to be set by another …

Flow types to prevent misuse of component props, part 1

---

src/core/components/Paginate/styles.scss

Fix paginate width

---

src/amo/components/AddonsByAuthorsCard/index.js
src/amo/reducers/addonsByAuthors.js
src/amo/sagas/addonsByAuthors.js
tests/unit/amo/components/TestAddon.js
tests/unit/amo/components/TestAddonsByAuthorsCard.js
tests/unit/amo/helpers.js
tests/unit/amo/reducers/test_addonsByAuthors.js
tests/unit/amo/sagas/test_addonsByAuthors.js

Fix #5353 
---
This PR:
- removes unused code (`byAuthorNamesAndAddonType`) in the `addonsByAuthors` reducer
- adds `pageSize` as a required argument to `fetchAddonsByAuthors()` in order to pass this value from the UI
- adds `page` and `sort` arguments (optional) to `fetchAddonsByAuthors()` to be able to paginate the add-ons related to a user
- adds `countFor` attribute to the state, which is designed like `loadingFor`
- passes `count` and `pageSize` to `loadAddonsByAuthors()`, `pageSize` was computed two times before, now this value is defined once in the UI and passed everywhere
- adds a `getCountForAuthorNames()` selector, similar to `getLoadingForAuthorNames()`

Enhance the addonsByAuthors reducer and saga
