src/core/components/Paginate/styles.scss
In #5350, I fixed a CSS bug and thought that it would be OK on small
screens but I tested in real life today and we can do better.
Before:
After:
=> Better pagination buttons on small screens

src/amo/components/UserProfileEdit/index.js, tests/unit/amo/components/TestUserProfileEdit.js
Fix #5327
---
When we navigate to another page, the component is unmounted, hence it
seems like a good idea to clear the error handler in this lifecycle
method.
=> Clear error handler when unmounting UserProfileEdit component

src/amo/components/UserProfileEdit/index.js, tests/unit/amo/components/TestUserProfileEdit.js
fixes #5146 
Added manage firefox account link and aside description as detailed in the mockup by @willdurand.
=> Add missing Manage FireFox Account link and aside description

src/amo/components/App/styles.scss
=> fixing broken text wrapping in notes

src/amo/components/Header/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/5371
Before
After
=> Fix Download Firefox button text on mobile screens

src/amo/components/UserProfileEdit/index.js, tests/unit/amo/components/TestUserProfileEdit.js
Fix #5391 
---
This PR moves the title to the field (instead of the parent div).
=> Fix tooltip for email field

README.md, src/amo/components/AddonReview/index.js, src/amo/components/AddonReviewListItem/index.js, src/amo/components/AddonsByAuthorsCard/index.js, src/amo/components/AutoSearchInput/index.js, src/amo/components/Categories/index.js, src/amo/components/CollectionManager/index.js, src/amo/components/EditableCollectionAddon/index.js, src/amo/components/ErrorPage/NotFound/index.js, src/amo/components/FlagReview/index.js, src/amo/components/FlagReviewMenu/index.js, src/amo/components/RatingManager/index.js, src/amo/components/ReportAbuseButton/index.js, src/amo/components/ReportUserAbuse/index.js, src/amo/components/SearchResult/index.js, src/amo/components/UserProfileEditNotifications/index.js, src/amo/components/UserProfileEditPicture/index.js, src/core/components/AuthenticateButton/index.js, src/core/components/ErrorPage/index.js, src/ui/components/ConfirmButton/index.js, src/ui/components/DismissibleTextForm/index.js, src/ui/components/Hero/index.js, src/ui/components/HostPermissions/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/5398
* When coming back after the weekend and looking at this code I realized that `InjectedProps` is unecessary. We can just use `Props` and `InternalProps`. I updated all the code so that no one copies/pastes the wrong thing for future code.
* After understanding https://github.com/facebook/flow/issues/6502 a bit more, I moved some default prop types to `InternalProps`. This is only possible for props that are solely used for testing since we don't have Flow coverage for tests. I think it's nicer this way, though, because we won't have to add a bunch of invariant checks for the default props.
=> Express external/internal props more concisely

src/amo/components/AddonsByAuthorsCard/index.js, src/amo/components/AddonsByAuthorsCard/styles.scss, src/amo/components/AddonsCard/styles.scss, src/amo/components/UserProfile/index.js, src/amo/reducers/addonsByAuthors.js, src/core/components/Paginate/index.js, src/core/components/PaginatorLink/index.js, src/core/types/addons.js, tests/unit/amo/components/TestAddonsByAuthorsCard.js, tests/unit/amo/components/TestUserProfile.js, tests/unit/amo/reducers/test_addonsByAuthors.js, tests/unit/core/components/TestPaginate.js, tests/unit/core/components/TestPaginatorLink.js
Fix #4809 
~~⚠️ Depends on #5352~~
---
This PR allows to paginate extensions and/or themes of a given user, on their profile page. Pagination is per card, so that we can paginate extensions and themes independently (two different query parameters).
A good user to try this PR: https://addons-dev.allizom.org/en-US/firefox/user/l4/
~~TODO: more tests~~
=> Paginate user extensions and themes

src/amo/components/AddonsByAuthorsCard/styles.scss
Fix #5382
---
Before:
After:
Before:
After:
=> Fix AddonsByAuthorsCard on small screens

src/amo/components/AutoSearchInput/index.js, tests/unit/amo/components/TestAutoSearchInput.js
Supports #3991
I need to be able to prevent the AutoSearchInput component from automatically creating filters based on the location query parameters for my changes to the CollectionManager to support sorting add-ons in a collection, and this seems like a simple way of doing that.
=> Allow AutoSearchInput to be called without a location property

src/amo/api/users.js, src/amo/components/UserProfileEdit/index.js, src/amo/reducers/users.js, src/amo/sagas/users.js, tests/unit/amo/api/test_users.js, tests/unit/amo/components/TestUserProfileEdit.js, tests/unit/amo/reducers/test_users.js, tests/unit/amo/sagas/test_users.js
Fixes #5195 
changes `editUserAccount` to `updateUserAccount` in all files and tests.
changes all functions and tests that match with `editUser` to `updateUser`
PRs open for the same issue.
Cheers!
=> changes editUserAccount to updateUserAccount

src/amo/components/AddonsByAuthorsCard/index.js, src/amo/components/UserProfile/index.js, tests/unit/amo/components/TestAddonsByAuthorsCard.js, tests/unit/amo/components/TestUserProfile.js
Fix #5442
---
This PR allows to return a 404 when extensions and/or themes on a user
profile cannot be loaded (and the API returns a 404 when trying to fetch
these add-ons), likely due to an invalid query parameter value.
Passing the `errorHandler` from the `UserProfile` component to the
`AddonsByAuthorsCard` components is required to make sure we return a
`NotFound` component on the server, thus returning a real `404` HTTP
response.
I also decided to hide the `AddonsByAuthorsCard` when an error occurs,
because it is better than being stuck in a loading state. On an add-on
detail page, it is "secondary data" so does not matter much I guess,
and on the user profile, the `UserProfile` will display the error.
I don't know if the added tests are enough or if we could find a better
patch, but …
=> Pass errorHandler from UserProfile to AddonsByAuthorsCards

src/amo/components/UserProfileEdit/index.js, src/amo/components/UserProfileEditPicture/index.js, tests/unit/amo/components/TestUserProfileEdit.js, tests/unit/amo/components/TestUserProfileEditPicture.js
Fix #5184 
---
Google doc: https://docs.google.com/document/d/1nnv1gwiQe5K3tvYXdsA2QmtWKO6XD75aD31V0hoyI_k/edit?ts=5b3679d3
This PR updates the copy for the user ~~profile~~ account deletion according to the Google doc above. It also slightly improves some other texts on this edit page thanks to the comments in the Google doc.
**Why WIP?** We still need a final decision about some red color on the "important" and "notes" words (again, please see the Google doc).
Regular user:
Admin:
Other fixes: buttons at the bottom
Other fixes: upload buttons
=> Update profile deletion copy

src/amo/components/AddonRecommendations/index.js, src/amo/reducers/recommendations.js, src/amo/sagas/recommendations.js, tests/unit/amo/components/TestAddonRecommendations.js, tests/unit/amo/sagas/test_recommendations.js
Fixes #5408 
This ensures that 100% of users will request actual recommendations from TADAr. As per the comment at https://github.com/mozilla/addons-frontend/issues/5408#issuecomment-400971189 we will not be making any changes to the data sent to GA at this time.
These changes are currently isolated to the `AddonRecommendations` component. Although we could potentially make these changes at a lower level, removing the `recommended` property from `FetchRecommendationsParams`, I think it's best to just leave that as is for now, as there is a suggestion we may be doing further experiments with this feature in the future.
=> Remove the A/B test from the TADAr so that recommendations are 100% of traffic

src/amo/components/UserProfileEdit/index.js, src/amo/reducers/users.js, src/amo/sagas/users.js, tests/unit/amo/components/TestUserProfileEdit.js, tests/unit/amo/sagas/test_users.js
Fix #5252
Fix #5219
---
The idea is: because we have the uploaded file and we are able to display this picture in the edit page, why not using it after having successfully submitted the form?
Same for the Basket integration issue: we now what the user has chosen, so let's use it. Because it is only overridden in the `edit` saga, I believe it is quite safe.
---
TODO:
=> Use user data when the API does not return the updated data right away after a user profile update

src/amo/components/CollectionList/index.js
I noticed in the console that I hadn't added keys to the `UserCollection` items that are generated in `CollectionList`. This fixes that.
I thought it unnecessary to open an issue for this little fix.
=> Ensure that UserCollection items in CollectionList have keys

src/amo/components/SearchResult/styles.scss, src/amo/components/UserProfile/styles.scss
=> Fix display issues with long displayName on UserProfile page

src/amo/components/Addon/index.js, src/amo/components/AddonsCard/index.js
fixes #4744 
if the theme has a description/summary, the ShowMoreCard would be displayed which uses the Card component. I think b/c there were no keys here it was not acting in an unexpected way.  By adding a varying key value, this looks to be fixed..
Both screenshots are after refreshing the page (SSR bug)
Before (everything looks like it's using AddsonByAuthorsCard except the section classes are wrong):
After:
*Note*: i wasn't loving this key name but i didn't see a lot of options here. We might need to find a more unique name..
=> I4744 adding key fixes ssr bug (seen on addon detail in AddonsByAuthorsCard)

src/amo/sagas/reviews.js, tests/unit/amo/sagas/testReviews.js
Fix #5474
---
This PR removes the filter to retrieve ALL reviews of a user.
=> Show empty reviews in user profile

src/amo/components/CollectionList/styles.scss, src/ui/components/UserCollection/styles.scss
=> Reduce spacing between collections on the CollectionList component

src/amo/components/Collection/index.js, src/amo/reducers/collections.js, src/amo/sagas/collections.js, tests/unit/amo/components/TestCollection.js, tests/unit/amo/reducers/test_collections.js, tests/unit/amo/sagas/test_collections.js
Fixes #5425 
This fixes both issues as reported at #5425.
It updates the list of user collections after one is saved, which will then allow it to appear immediately on the My Collections screen, and it also doesn't use the currently loaded collection when rendering the Create Collection form, so we don't end up with pre-populated fields.
=> Refresh user collections when a collection is saved, and don't use the current collection when editing

src/amo/components/AddonBadges/index.js, src/amo/components/AddonBadges/styles.scss, src/ui/components/Badge/styles.scss, tests/unit/amo/components/TestAddonBadges.js
fixes #5417 
this PR addresses the text (from `Featured Add-on` -> to `Featured Theme`) and addresses styles noted in the issue...
Regarding the style updates, do you prefer to override these in 1 place or is how I have it here okay?
=> I5417 static theme badge

src/core/utils/index.js, tests/unit/core/utils/test_index.js
Fix #5473
---
This PR removes `<br />` occurences between HTML tags.
=> Do not add br between html tags

src/core/constants.js
fixes #5578 
notice eventAction is now just `statictheme`
=> I5578-updating static theme tracking info

src/amo/components/UserProfile/index.js, tests/unit/amo/components/TestUserProfile.js
Fix #5587
---
I believe the browser changes the HTML in the DOM to be valid. React
does not find what the server has sent in the `dangerouslySetInnerHTML`
when introspecting the DOM, hence the warning (locally) about the
`dangerouslySetInnerHTML` mismatch (see issue).
React 16 is weird when a difference between server and client occurs.
=> Set dangerouslySetInnerHTML on a div

src/amo/components/SearchResult/styles.scss, src/amo/components/UserProfile/styles.scss
This is a slightly better fix for #5494 that avoids a scroll bar to be displayed.
=> Avoid scrollbar in user profile name

config/default-disco.js, config/default.js, config/dev.js, config/development.js, package.json, src/core/store.js, tests/unit/core/test_store.js, yarn.lock
Fix #5622
---
This PR introduces a new config paramter `enableDevTools` that can be
use to enable devtools in any environment.
I'd like to debug #5608 in -dev and I think it would be useful to have
the Redux devtools available in this environment. FWIW, Airbnb has the
Redux devtools in all envs, including -prod, which is super great.
As a first step, we can enable the devtools in -dev, and see if we need
to turn them on for -stage and/or -prod later.
I also removed a package that we are not using at all. We use the
following Redux devtools:
https://github.com/zalmoxisus/redux-devtools-extension, which does not
need any extra dependency. It is only enabled if the browser extension
is installed and opened.
=> Enable redux-devtools in -dev

src/disco/components/DiscoPane/styles.scss
Fix #5323 (see comments)
---
Before:
After:
=> Fix discopane css

src/ui/components/ConfirmButton/index.js, tests/unit/ui/components/TestConfirmButton.js
fixes #5550 
I wasn't totally clear if I need to do anything to the HOC. I saw this component in 2 places - the collections and the user profile - and it looks like it works with the changes in both places still. 
let me know what you think : )
=> I5550 converting confirm btn to use setUIState

tests/unit/amo/components/TestApp.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/core/TestAddonManager.js, tests/unit/core/TestInstallAddon.js, tests/unit/core/TestThemeInstall.js, tests/unit/core/api/test_index.js, tests/unit/core/client/test_logger.js, tests/unit/core/components/TestInfoDialog.js, tests/unit/core/components/TestInstallSwitch.js, tests/unit/core/i18n/TestI18nProvider.js, tests/unit/core/i18n/test_translate.js, tests/unit/core/i18n/test_utils.js, tests/unit/core/middleware/test_HstsMiddleware.js, tests/unit/core/middleware/test_cspMiddleware.js, tests/unit/core/middleware/test_frameguardMiddleware.js, tests/unit/core/middleware/test_logRequests.js, tests/unit/core/middleware/test_trailingSlashMiddleware.js, tests/unit/core/testErrorHandler.js, tests/unit/core/utils/test_index.js, tests/unit/ui/components/TestRating.js, tests/unit/ui/components/TestSwitch.js
Fix #2437 
---
- use `sinon.assert` everywhere
- remove more unused code
=> use sinon.assert everywhere

package.json, yarn.lock
Fix #4264
---
- Requiring `history` directly is needed because it is a transitive dependency (_via_ `react-router`) but there is no guarantee that it will be always there (in reality, it should but... we would not get rid of the warning, because Yarn does not look at transitive deps apparently)
- I think #4688 was too bold, because `webpack-dev-server` v3 does not support webpack < 4
=> Fix peer deps warnings

src/core/components/SurveyNotice/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/5653
Before:
After:
=> Improve contrast of survey notice box

src/amo/components/AddonReviewList/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/5655
Before
After
=> Fix page padding for add-on review listing

src/amo/components/EditableCollectionAddon/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/5658
Before
After
=> Fix layout issue with Remove button

src/amo/components/Collection/index.js, tests/unit/amo/components/TestCollection.js
Fixes https://github.com/mozilla/addons-frontend/issues/5672
I noticed this while testing out the spiffy new collections and it bugged me. I thought it was easy to fix and it totally wasn't! But I started it towards the end of the day anyway. Sigh.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> A less jarring loading screen while editing a collection

src/amo/sagas/collections.js, tests/unit/amo/sagas/test_collections.js
=> Redirect to the slug that is returned by the API call when creating or editing a collection

package.json, yarn.lock
Removing this dev dependency as we are not using it, we use middleware instead.
=> Remove unused webpack-dev-server dep

src/amo/components/UserProfile/index.js, tests/unit/amo/components/TestUserProfile.js
Fix #5594 
---
I had this fix in one of my local branches... This PR allows a user profile page to be shown when using a user ID in the URL (for backward compatibility purpose).
=> Accept numeric IDs to browse a user profile page

src/amo/components/CollectionSort/index.js, src/core/constants.js
Fixes #5581 
Note that I looked for an opportunity to test this change, but as all we're doing is changing the value of a constant, there isn't really anything to test. We don't generally test values of constants.
=> Sort by popularity should use descending order

src/amo/components/CollectionAddAddon/index.js
This change was accidentally committed.
We should cherry-pick this for this week's tag.
=> Revert add-on added message timeout to 5 seconds

src/amo/components/Collection/index.js, src/amo/components/CollectionAddAddon/styles.scss, src/amo/components/CollectionControls/index.js, src/amo/components/CollectionControls/styles.scss, src/amo/components/CollectionManager/index.js, src/amo/components/CollectionSort/index.js, src/amo/components/CollectionSort/styles.scss, tests/unit/amo/components/TestCollection.js, tests/unit/amo/components/TestCollectionControls.js, tests/unit/amo/components/TestCollectionManager.js
Fixes #5675 
Fixes #5286
Fixes #4617
Depends on #5669 
There is one UX quirk that may be an issue. When you add an add-on to a collection, the card increases in size to show the "Added to collection" notice, and then, when the notice fades away, the card reduces in size. The fact that it changes its size to show the notice is consistent with what we do when there's an error, but it's a bit odd because of the notice disappearing and the card shrinking. See the screenshot as an example:
The only option I can think of to mitigate this is to reserve enough blank space at the top of the card for the message, but then that looks bad whenever the message is not visible, which is why I wrote it the way it currently is. Do you have an opinion @pwalm?
Before:
After:
=>  Move the select which is used to add an add-on to a collection out of the edit form

src/core/tracking.js, tests/unit/core/test_tracking.js
fixes #5707 
So it looks like we using extension tracking for install as a catchall if it wasn’t a lightweight theme or open search type.  
Earlier we were not using `getAddonTypeForTracking` (previously called `getAction`) for install, only uninstalls it seems. So on a side but related note I think you should probably see invalid coming up on uninstalls..
Anyway, I’ve added all the missing types so in theory we shouldn’t see invalid anymore if it’s one of these types. Just a note, I am still tracking these with the extension tracking type - is that what we want? Or should each addon type have their very own tracking type?
These are currently the tracking types that are set up:
```javascript
// Tracking add-on types
export const TRACKING_TYPE_EXTENSION = 'addon';
export const …
```
=> I5707 adding all addon types to action list for GA

src/amo/components/Addon/styles.scss, src/amo/components/AddonsByAuthorsCard/styles.scss, src/core/css/inc/vars.scss
fixes #5703 
I did not see this issue consistently and I am not sure if this will be the end all solution but it does  seem to minimize the icon size at least. I believe this icon should be appearing as a placeholder while the we are waiting for the addon to load (right?). So this just gives a max height to make it look a little nicer. Note that I am going by lwt's height since it is a little bigger and for now since it's it should I think it should work for both.
=> I5703 adjusting styles to minimize big icon while waiting for addon

.gitignore, .travis.yml
Refs #5781 
---
This PR changes the Firefox version from nightly to dev edition in order
to get a green feedback again. The issue is related to a "menu" button
not being found anymore. All FF versions < 63 are not affected.
I added a job for nightly so that we can keep an eye on it, but this job
won't fail the build at least.
=> Switch to firefox dev edition

tests/setup.js, tests/unit/amo/sagas/test_collections.js, tests/unit/testSetup.js
Fix #1138
---
I tested by removing all the "mock" code of a saga test suite and in
some API test cases in the disco test suite.
=> Prevent the test suite from ever calling a real API

webpack.dev.config.babel.js
Fix #4508
---
This `devtool` value is the recommended one, and it is faster than the
previous one: https://webpack.js.org/configuration/devtool/.
From what I know, the main difference is that it does not link to the
column, only to the line (where an error has occurred for instance). I
don't think it really matters because we only have 80 columns anyway.
=> Use cheap-module-eval-source-map in webpack dev

src/amo/components/App/index.js, src/disco/components/App/index.js
Fix #3565
---
Please read: https://github.com/mozilla/addons-frontend/issues/3565#issuecomment-409204307
=> Fix CSS order

jest.config.js
Fix #2639
---
I find this behavior annoying and found the GH issue last night, so here is a patch.
I hooked into the Jest process to see which files were triggering a re-run.
=> Do not run tests twice after editing a file

src/ui/components/Button/styles.scss
Fix #5789
---
According to the spec, the primary buttons (called "action" in our code
base) should have such colors:
- blue 60
- blue 70 for hover
- blue 80 for active
See: https://design.firefox.com/photon/components/buttons.html#behaviours
I also updated the error colors according to this section: https://design.firefox.com/photon/patterns/errors.html#colors
=> Fix button colors according to Photon spec

src/amo/components/Addon/index.js, src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss, tests/unit/amo/components/TestAddon.js, tests/unit/amo/components/TestSearchResult.js
fixes #5703 
From what I could tell the url was changed in the src *after* the classname was updated and for a split second you see the icon large b/c it takes on the new classname styles:
In the header, the only way that I found that fixes this is to change the html structure or to use a key on the image/wrapping div. This might be another reconciliation issue (?). I decided to go the html approach - changing out a div for a span. let me know what you think..
note: i did a little bit of clean up too : )
=> I5703 fixing scaled icon flash

src/amo/components/EditableCollectionAddon/index.js, src/core/reducers/uiState.js, src/core/withUIState.js, src/ui/components/ConfirmButton/index.js, tests/unit/amo/components/TestEditableCollectionAddon.js, tests/unit/core/testWithUIState.js, tests/unit/helpers.js, tests/unit/ui/components/TestConfirmButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/5764
After thinking more about the problem (see https://github.com/mozilla/addons-frontend/issues/5764), I'm convinced that `withUIState()` components should be persistent by default. If--and only if--we run into problems, we can fall back to the `setState()` behavior which is to reset state for new component instances.
=> Make withUIState() components use persistent state

src/amo/components/SearchFilters/index.js, tests/unit/amo/components/TestSearchFilters.js
Fix #5822
---
I reverted some changes made in #5652 (RRv4 upgrade) because that's the
root cause of #5822. The `SearchFilters` must navigate to the search
page from the "search tools" page.
=> Fix pathname in SearchFilters

.travis.yml, README.md
Fix #5819
---
We do not run the `snyk` job when the PR comes from a fork:
- The build for this PR does not have it: https://travis-ci.org/mozilla/addons-frontend/builds/411224682?utm_source=github_status&utm_medium=notification
- The build for the branch pushed directly on this repo has it: https://travis-ci.org/mozilla/addons-frontend/builds/411227047?utm_source=github_status&utm_medium=notification
=> Do not run snyk on forks

bin/build-locales, package.json, webpack.prod.config.babel.js, yarn.lock
Fix #5796
---
I tried to build the `amo` app and could not get the same hashes when
introducing a change in the source code. I was not able to reproduce
the original issue, but I am optimistic :smile:
This PR will allow us to compile not-only-ES5 code!
=> Use uglifyjs-webpack-plugin

src/amo/components/AddonReview/index.js, src/amo/components/AddonReview/styles.scss, src/amo/components/UserProfileEdit/index.js, src/ui/components/Overlay/index.js, src/ui/components/OverlayCard/index.js, tests/unit/ui/components/TestOverlay.js, tests/unit/ui/components/TestOverlayCard.js
fixes #5555 (wip)
I had few follow up questions maybe before the official review:
Should I use update `Overlay` to use flow or is this okay how I have it?
I’ve updated the tests in the `TestOverlay` to use enzyme - that’s ideally what we want, right?  
I see that `TestOverlayCard` is using `renderIntoDocument` too and since updating `TestOverlay` actually took a bit of time for me to change I wanted to make sure before I did any more work that this is something we want.
Clicking the background in the overlay, as far as I can tell, doesn’t work :/ 
Should it? I checked dev and it didn't work for me either. On stage, it seems to work if I click in the header..? :/
=> I5555 overlay convert setstate to set ui state

src/core/searchUtils.js, tests/unit/core/test_searchUtils.js
Fix #5845
---
This PR makes sure we only fetch lightweight themes on Android.
=> Fetch only lightweight themes on Android

.travis.yml, README.md, bin/build-checks.js, bin/build-locales, package.json, yarn.lock
Fix #2923
Fix #2691
---
I was curious to see what [bundlesize](https://github.com/siddharthkp/bundlesize) could do.
This PR updates the `build` commands and removes the undocumented
`ADDONS_FRONTEND_BUILD_ALL` environment variable.
Bundlesize checks both amo and disco apps. I also added `FORCE_COLOR=0`
to remove some colors in the logs (bundlesize and chalk calls), since
logs are big and we need the raw output every time.
<details>
<summary>Output on Travis-CI</summary>
```
> mozilla-addons-frontend@0.0.1 bundlesize /home/travis/build/mozilla/addons-frontend
> bundlesize
WARN  github token not found
You are missing out on some cool features.
Read more here: https://github.com/siddharthkp/bundlesize#2-build-status
PASS  ./dist/amo-009847d7cf65fb8e5c9c.js: 390.8KB < maxSize 400KB (gzip) …
```
=> Add bundlesize

config/test.js, src/core/logger.js
Fix #5869
---
The alternative option would be to use the following Jest option: `--browser`, but that would mean enabling this feature for everything.
=> Use pino/browser in test env

src/amo/sagas/collections.js, tests/unit/amo/sagas/test_collections.js
=> changing the order of calls of unloadCollectionBySlug & pushLocation

package.json, yarn.lock
Fix #4041
---
This PR uses [pino-devtools](https://github.com/willdurand/pino-devtools) to view the server logs:
=> Use pino-devtools to view the server logs

package.json
Fix #5886
---
We don't need to kill all processes when an error occurs.
The issue was that the server code could not be reloaded because of a
syntax error, thus exiting with a non-zero code. `concurrently` then
killed the proxy. Once you fix the syntax error, the server code
restarts correctly, but proxy is not available anymore...
=> Do not kill everyone in development

src/amo/components/Addon/index.js, src/amo/components/LandingPage/index.js, src/amo/components/LanguageTools/index.js, src/core/components/InstallButton/index.js, src/core/components/InstallSwitch/index.js, src/core/installAddon.js, src/core/middleware/security.js
Fix #5860 
---
This PR aims at fixing most of the issues displayed when running `yarn amo:dev`.
The `InfoDialog` warnings are fixed in #5880
=> Fix some react warnings

src/amo/components/AddonReviewListItem/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/5926
**Before**
**After**
=> Don't break words in review control links

src/amo/components/AddonReviewListItem/index.js, src/amo/components/AddonReviewListItem/styles.scss, src/ui/components/Icon/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/3424 by flex-wrapping controls to a new line (this works better than the grid approach in https://github.com/mozilla/addons-frontend/pull/5951). The idea of pushing controls to a new line has come up before so it will solve a few problems.
<hr>
Here is how it looked **before**. Notice that it's not as bad as the original screenshot in the issue, thanks to https://github.com/mozilla/addons-frontend/issues/5926
<hr>
Here's how that screen looks **after**
<hr>
Here are some other mobile views
<hr>
Larger screens:
=> Push review controls to a new line when out of space (fixes Reply to Review layout issues)

src/amo/components/AddonMeta/styles.scss
Fixes #5952 
Before:
Note that hovering over the number "153" in the *before* version does not change the color of the number to blue.
After:
After, while hovering over the number of reviews:
Note also that hovering over the text "Reviews" changes the color to blue in both the before and after versions.
=> Add an underline to the links to "all reviews" from the AddonMeta component

src/ui/components/DismissibleTextForm/index.js, tests/unit/ui/components/TestDismissibleTextForm.js
Fixes https://github.com/mozilla/addons-frontend/issues/5976
I need to hide the cancel / dismiss button and make the submit button puffy.
=> Configure DismissibleTextForm for inline add-on reviews

src/amo/components/Addon/index.js, src/amo/components/Addon/styles.scss
Fixes #5388 
Image used - size: 1.96 MB (JPEG), dimensions: 1980 × 1289
- Wrapped the custom icon image inside a div `Addon-img-wrapper` and imposed the restriction of `height` and `width` acc to screen size. And, changed styles for class `Addon-icon-image` to `height:auto;` and `width:100%` thus resolving the squashing problem. 
- By the following changes, horizontal images do not squash anymore but if the height of image is greater than 64px(potrait images) its cropped from bottom (not squashed), which should be the desired behaviour as read in the #4629. Please confirm this? 
- Do I need to write tests for the same?
Thank you for all the help, please review this @willdurand  @ioanarusiczki
=> Fixes #5388 resolves addon custom icon squashing

src/amo/components/CollectionManager/styles.scss
Fixes: #5627  
Bug: 
Result:The text-area has resize vertical, so only vertical expansion can occur
=> [Fixes]#5627: Description text box should have only a vertical expansion

src/amo/components/UserProfileEditPicture/index.js
Fix #6006
---
To get rid of ESLint errors, I added `htmlFor` but `id` was missing on
the `input`, causing a mismatch leading to the (fake) button never
calling the underlying input file anymore.
=> Add missing id to input file

jest.config.js, tests/jest-reporters/summary.js
Fix #5956 
---
We cannot specify `summary` only, we have to import this reporter in our code to use it. I decided to do this because it works, and it is simple. Maybe we should look into writing a better reporter, but that works now so...
=> Add jest summary reporter

src/amo/components/UserProfile/index.js, tests/unit/amo/components/TestUserProfile.js
Fixes https://github.com/mozilla/addons-frontend/issues/6007
I checked all other usage of `parseInt()` and I don't think we need to fix anything else. It's surprising that `parseInt('0something', 10)` returns `0` 🤡 👯
=> Handle zero-prefixed usernames in UserProfile

package.json, src/core/client/base.js, yarn.lock
`pino-devtools` 2.0 introduces a new mode to output the logs in the same console as the application (buffer mode), which is now used here.
=> Upgrade to pino-devtools 2

src/amo/api/reviews.js
`Fixes #6055`
- Initial fix for apiState should not be optional in api/reviews.js
- All tests are successful.
=> apiState should not be optional in api/reviews.js - 6055

src/core/addonManager.js, src/core/components/InstallButton/index.js, src/disco/components/Addon/index.js, src/disco/components/DiscoPane/index.js, tests/unit/core/components/TestInstallButton.js, tests/unit/core/test_addonManager.js, tests/unit/disco/components/TestDiscoPane.js
Fix #6059
---
This PR removes react warnings in the disco app, mostly by fixing invalid prop types.
=> Remove disco react warnings

src/ui/components/Rating/index.js, tests/unit/ui/components/TestRating.js
Fixes #4955 - We should show a more appropriate tooltip for the respective star if a rating is present.
See below for two GIFs that showcase the updates:
=> Show a more appropriate tooltip for current rating

src/ui/components/Overlay/styles.scss
Fix #5851
---
I refactored the CSS to reduce the `.Overlay-contents` area so that we
can click anywhere around the modal to close it.
=> Refactor Overlay CSS to allow click everywhere

package.json
I forgot to add this in a previous PR. Running `yarn disco` should continue to work but we'll have the server logs in the console now :)
=> Add buffer mode to pino-devtools for disco

src/core/components/AMInstallButton/index.js, src/core/constants.js, src/core/installAddon.js, tests/unit/core/components/TestAMInstallButton.js, tests/unit/core/test_installAddon.js
Partially fix #5929
---
I said "partially" because there is some work to do on the browser side. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1477155#c1.
This allows to get a "Add to Firefox" button when an **extension** has been removed from "about:addons". It does not work for themes, though. 
I also fixed the test cases because `getAddonById` clearly does not return `type` as we are used to use: it is either `extension` or `theme`, not `persona`, `statictheme`, etc.
=> Add INACTIVE status for extensions

config/development.js, package.json, src/core/middleware/security.js, tests/unit/core/middleware/test_cspMiddleware.js, webpack.dev.config.babel.js
Fix #2984
---
Explanations in comments.
I got a lot of CSP issues in the disco app locally, so I investigated a bit. It turned out that amo had CSP disabled locally but not disco. I tried to fix the CSP errors for disco and tried to enable CSP on amo, which actually worked.
=> Fix CSP for disco and amo locally

src/amo/components/Addon/styles.scss
=> Fix AMInstallButton alignment on addon detail page

src/amo/actions/reviews.js, src/amo/components/AddonReviewListItem/index.js, src/amo/components/AddonReviewListItem/styles.scss, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, tests/unit/amo/components/TestAddonReviewListItem.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/helpers.js, tests/unit/test_helpers.js, tests/unit/ui/components/TestConfirmButton.js
Fixes #3075 
This adds a "Delete my review" link to reviews that are deletable by the current user, and a "Delete my reply" link to replies that are deletable by the current user. Clicking the link deletes the review/reply immediately and refreshes the list of reviews.
I considered using the `ConfirmButton` as we've used for deleting a collection and a user profile, but I think that's probably unnecessary for deleting a review/reply.
A user's review:
A developer's response:
=> Enable deleting a review from the review listing page

src/amo/components/AddonReviewListItem/styles.scss
Fixes #6112 
This fixes it for me on Chrome.
Before:
After:
=> Fix style of the "Delete my review" link

package.json, yarn.lock
Fixes #6111 by forcing the use of `fbjs@0.8.17`
=> Use resolution to fix version of fbjs

src/amo/components/Addon/index.js, src/amo/components/Addon/styles.scss, tests/unit/amo/components/TestAddon.js
Fixes #6058 - When there is no description present for an add-on, show nothing instead of showing an exact duplicate of the add-ons summary.
=> Display nothing when there is no addon description

src/amo/components/AddonReview/index.js, src/core/api/index.js, src/core/polyfill.js, src/core/sagas/addons.js, src/core/utils/index.js, tests/setup.js, tests/unit/amo/components/TestAddonReview.js, tests/unit/core/api/test_index.js, tests/unit/core/utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/4935
~~In the interest of time and simplicity, I did not actually test this by setting up multiple versions of language packs.~~ I was able to test this with http://localhost:3000/en-US/firefox/addon/finn-language-pack/ (see https://github.com/mozilla/addons-server/issues/8180#issuecomment-418687835)
Also, I opened up a can of worms here. The moving of `refreshAddon` was to fix a circular dependency and the new polyfill code was probably always a bug but I think moving `refreshAddon` made it worse.
=> Show compatible langpacks based on app version when possible

config/default-disco.js, config/default.js, src/core/api/index.js, src/core/server/base.js, tests/unit/core/api/test_index.js
Refs #5527 
---
This PR adds a `version` parameter to the `callApi` function, used by most higher-level API calls, along with a `apiVersion` config parameter. This will ease the API version upgrade described in #5527.
=> Add version param to callApi

src/amo/components/AddonReviewCard/index.js, src/amo/components/RatingManager/index.js, src/amo/components/RatingManager/styles.scss, src/ui/components/UserReview/index.js, src/ui/components/UserReview/styles.scss, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/ui/components/TestUserReview.js
Fixes https://github.com/mozilla/addons-frontend/issues/6178
**Before**
**After**
=> Simplify how saved ratings are rendered

.travis.yml, Dockerfile
=> use yarn.lock when building the apps

package.json
I don't have a better solution right now.
~~I'll file an issue to explore ways to reduce the bundlesize of `amo` JS.~~ See: https://github.com/mozilla/addons-frontend/issues/6192
=> Increase bundlesize JS threshold

src/amo/components/Addon/index.js, src/amo/components/AddonReviewList/index.js, src/amo/components/AddonsByAuthorsCard/index.js, src/amo/components/Categories/index.js, src/amo/components/Category/index.js, src/amo/components/Collection/index.js, src/amo/components/Home/index.js, src/amo/components/LandingPage/index.js, src/amo/components/LanguageTools/index.js, src/amo/components/RatingsByStar/index.js, src/amo/components/Search/index.js, src/amo/components/SearchPage/index.js, src/amo/components/UserProfile/index.js, src/amo/components/UserProfileEdit/index.js, src/ui/components/Hero/index.js, tests/unit/core/server/test_server.js
Fix #6186
---
This PR updates our codebase to get rid of the `componentWillMount()` calls and use the `constructor()` instead, as specified [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data):
> When supporting server rendering, it’s currently necessary to provide the data synchronously – componentWillMount was often used for this purpose but the constructor can be used as a replacement. The upcoming suspense APIs will make async data fetching cleanly possible for both client and server rendering.
=> Remove componentWillMount() calls

src/core/components/AMInstallButton/index.js, src/core/components/AMInstallButton/styles.scss, tests/unit/core/components/TestAMInstallButton.js
Fix #6165  – ~~⚠️ depends on #6170~~
---
This PR adds a short CSS transition on the `AMInstallButton`.
=>  Add transition on AMInstallButton 

src/amo/components/Header/index.js
Fix #6125
---
This PR does not technically fix #6125 but it prevents the issue to be reproducible :wink:
Here is why the issue occurs: https://github.com/mozilla/addons-frontend/issues/6125#issuecomment-418764981, I don't have a fix in mind because it is related to the browser cache and we do not have control over that.
=> Open dev hub link in another tab

src/core/server/base.js, tests/unit/core/server/test_server.js
Fixes https://github.com/mozilla/addons-frontend/issues/6217
It looks like there are other headers we need for older browsers but I'm not sure it's worth it.
=> Cache-Control=no-store to make auth tokens really go away

README.md, bin/local-dev-server-certs/index.js, bin/proxy.js, bin/server.js, bin/webpack-dev-server.js, config/development.js, docs/moz-addon-manager.md, package.json
Fix #6143
---
~~This setup works at 99%. I am not able to install extensions though~~ (edit: it works with Nightly), but the rest looks good. CSP complains about sha1 signatures too, but this is not related.
All you need to get started is to import [the CA certificate](https://github.com/mozilla/addons-frontend/blob/14624803fc0d8db424cb2da471f68911163c6253/bin/local-dev-server-certs/example.com.ca.crt.pem) in Firefox:
=> Add new amo:dev-https command

src/amo/reducers/collections.js, tests/unit/amo/reducers/test_collections.js
Fixes #5930 
When users go from collection A page(after refresh) to collections and back to collection A page, if addons number over 25, the pagination is disappeared.
The initial pageSize send from `LOAD_USER_COLLECTIONS` to `loadCollectionIntoState` is always null. So if the `existingCollection` is stored to collections, it can have all the existing data, including `pageSize`.
=> Put existing visited collection in collections

src/amo/components/AddonReviewCard/index.js, src/amo/components/AddonReviewCard/styles.scss, src/amo/components/AddonReviewManager/index.js, src/amo/components/RatingManager/index.js, src/amo/components/RatingManager/styles.scss, src/ui/components/DismissibleTextForm/index.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestAddonReviewManager.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/ui/components/TestDismissibleTextForm.js
~~**This patch depends on** https://github.com/mozilla/addons-frontend/pull/6220~~
<hr>
- Fixes https://github.com/mozilla/addons-frontend/issues/6163 by hooking up the edit button. This involved moving a bunch of code from `RatingManager` to `AddonReviewCard` which makes more sense now.
- Fixes https://github.com/mozilla/addons-frontend/issues/6162 by magic (it just fell into place)
Behold! We now have a complete inline review flow, minus notifications (https://github.com/mozilla/addons-frontend/pull/6213).
<details>
<summary>Screencast</summary>
</details>
<hr>
I adjusted the buttons on a few other screens for consistency:
=> Hook up edit button for inline reviews

config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/components/HomeHeroBanner/index.js, src/core/withExperiment.js, tests/unit/amo/components/TestHomeHeroBanner.js, tests/unit/core/test_withExperiment.js
Fixes #6274
---
This PR adds two features:
1. make the `witExperiment` HOC config-aware in a generic way
2. disable the home hero experiment by default, and enable it in -dev only
=> Add config for withExperiment HOC

src/core/utils/compatibility.js, tests/unit/core/utils/test_compatibility.js, tests/unit/helpers.js
Fix #6240 
---
~~I think we still need to know when non-restartless add-on support has been dropped because the current patch makes all non-restartless add-ons incompatible.~~ FF 61 is the answer.
=> Add a check for non-restartless add-ons

src/amo/actions/reviews.js, src/amo/api/reviews.js, src/amo/components/AddonReviewCard/index.js, src/amo/components/FeaturedAddonReview/index.js, src/amo/components/FeaturedAddonReview/styles.scss, src/amo/components/Routes/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/UserProfile/index.js, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, src/ui/components/UserReview/styles.scss, tests/unit/amo/api/test_reviews.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestFeaturedAddonReview.js, tests/unit/amo/components/TestRoutes.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js
Fixes #2771 
There are (at least) a couple of issues:
1. I'm having the same problem I had with recommendations and SSR where the sagas do not finish in time and the page is broken for SSR, unless I move the processing to `componentDidMount`. This does cause a noticeable delay in all the content appearing on the page, so we may want to find another way of dealing with this. I've added a comment to the code about this as well.
2. I had trouble coming up with a good way to test that a particular action was not dispatched. I have also added a comment to the code about this and welcome any suggestions.
The new version of the All Reviews page is located at `/review/[reviewId]/`, e.g., http://localhost:3000/en-US/firefox/review/563237/, and currently looks like this:
Here's what it looks like …
=> Allow for a review to be featured at the top of the All Reviews page

src/core/addonManager.js, src/core/constants.js, tests/unit/core/test_addonManager.js, tests/unit/disco/pages/TestDiscoPane.js
Fix #6164
Fix #562
Fix #6227
~~⚠️ depends on #6237~~
---
The `onOperationCancelled` event is fired when a user clicks the "undo"
button in `about:addons` (after having removed an add-on from this
panel). This fixes a bug where the install button state was still
"pending" on the AMO side.
Update: this `onOperationCancelled` event seems to be only sent for extensions.
=> Listen to onOperationCancelled to fix the install status

src/amo/components/AddonReviewManager/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/6272
<hr/>
**Before**
<hr/>
**After**
<hr/>
In other locales:
On larger screens it's the same as before:
=> Bigger rating stars on small screens when editing a review

src/core/reducers/addons.js, tests/unit/core/reducers/test_addons.js
This fixes https://github.com/mozilla/addons-frontend/issues/6265 because `addon.ratings.count` was used by `<RatingsByStar>` to set the width of the bar. This patch fixes a couple other issues where `addon` was used in that same component.
=> Unload related add-on for set-review actions

src/amo/components/AddonReviewCard/index.js, src/amo/components/AddonReviewCard/styles.scss, src/amo/components/FeaturedAddonReview/index.js, src/amo/components/RatingManager/index.js, src/amo/components/RatingManager/styles.scss, src/amo/pages/UserProfile/index.js, src/amo/pages/UserProfile/styles.scss, src/ui/components/UserReview/index.js, src/ui/components/UserReview/styles.scss, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/ui/components/TestUserReview.js
Fixes #6104 
Also fixes #5495 
As discussed in the issue, this does not add the new information to the User Profile page, such as add-on name and icon, but it does use the same component on both the Add-on Review Listing and User Profile pages so there are now links available on the User Profile to edit and delete a review or reply, as well as to delete a rating.
Before:
After:
=> Make user profile reviews look like add-on reviews (mostly) 

src/core/api/index.js, tests/unit/core/api/test_index.js
Fix #6370
---
This PR should avoid HUGE log entries.
=> Do not log full response object in callApi

src/core/reducers/addons.js, tests/unit/core/reducers/test_addons.js
This reverts commit 40d1ba4e8fe83bfdcf4bc44ba3854a5ba8a4ea61 and will close https://github.com/mozilla/addons-frontend/issues/6372
The patch I'm reverting was causing https://github.com/mozilla/addons-frontend/issues/6381 ; we need to fix the original bug in a different way. I have a new patch but it might not be ready before today's tag.
=> Revert "Unload related add-on for set-review actions (#6335)"

src/amo/pages/LanguageTools/index.js, src/core/languages.js, tests/unit/amo/pages/TestLanguageTools.js
Fixes #6145
---
This PR fixes #6145 in two ways:
- it adds `fa-IR` (Persian for Iran) in the list of supported languages,
which creates a new row for the related language tools
- it lists more add-ons by adding the add-ons with a long locale (e.g.,
`az-IR`) in the sets of add-ons (dict or lang pack) of the
corresponding short locale (e.g., `az`), but only if this long locale
is not supported (otherwise there would be add-ons listed multiple
times (e.g., the Austrian German would be listed in "German" `de` and
"German (Austria)" `de-AT`).
=> Fix language tools listing

src/amo/components/AddonReviewCard/index.js, src/amo/components/RatingManager/index.js, src/amo/components/RatingManagerNotice/index.js, src/amo/components/RatingManagerNotice/styles.scss, src/ui/components/Notice/index.js, src/ui/components/Notice/styles.scss, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/ui/components/TestNotice.js
Fixes #6345 
New "saving" message:
New "saved" message:
=> Simplify the 'rating saved' notification

config/default-amo.js, config/default.js, src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
Removed All occurrences of enableFeatureAddonRecommendations from the following 4 files as the feature has been adopted.
1. config/default-amo.js
2. config/default.js
3. tests/unit/amo/pages/TestAddon.js
4. src/amo/pages/Addon/index.js
=> Fixes #6374: Removed All occurences of enableFeatureAddonRecommendations

src/core/components/PaginatorLink/index.js, tests/unit/core/components/TestPaginatorLink.js
Fix #5757
---
This PR adds new `rel` attributes to paginator links.
=> Add prev/next rel attributes to paginator links

src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
Fixes #5766 
---
I did not provide a fallback in case the summary is not available since the content should be truncated if we use the full description (and that might lead to a weird content).
Because the name of the add-on is part of the content, there is no risk of similar content if we don't have a summary (content will still be unique).
=> Add description meta tag on add-on detail pages

src/amo/components/AddonReviewCard/index.js, src/amo/components/AddonReviewCard/styles.scss, src/amo/components/RatingManager/styles.scss, src/core/css/inc/vars.scss, src/ui/components/Button/styles.scss, src/ui/components/ConfirmButton/index.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/ui/components/TestConfirmButton.js
Fixes #6454 
Note that this looks a bit odd when rendered for a review as opposed to a rating, but I think that's okay as a short-term issue until #6347 is fixed entirely.
Deleting a rating (before):
Deleting a rating (after):
Deleting a review (before):
Deleting a review (after):
=> Adjust the appearance of the confirmation buttons when deleting a review/reply

src/amo/pages/Addon/styles.scss
Fixes #6482
---
Before:
After:
=> Fix install button width on medium+ screens

src/core/addonManager.js, src/core/components/InstallButton/index.js, src/core/installAddon.js, src/core/utils/addons.js, tests/unit/core/components/TestInstallButton.js, tests/unit/core/test_addonManager.js, tests/unit/core/test_installAddon.js, tests/unit/core/utils/test_addons.js
Fixes #1208 
---
I reused an existing function (moved to `core/utils/addons`), so the diff looks big but it is not. The main part is calling `getFileHash` in the `install()` method of the HOC.
=> Use getFileHash in installAddon HOC

tests/ui/requirements/requirements.txt
Fixes https://github.com/mozilla/addons-frontend/issues/6503 by supporting Python 2 in addition to Python 3. For some reason, my tox is still linked to Python 2 even though I have Python 3 installed.
=> Fix import errors when running tox with Python 2

src/amo/components/AddonAdminLinks/index.js, src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonAdminLinks.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes #4632 
Here's an example for an extension for a user with all of the permissions:
=> Add admin and review links for add-on details page

package.json
This is to address failures like https://travis-ci.org/mozilla/addons-frontend/jobs/437296070
The [last time we did this](https://github.com/mozilla/addons-frontend/commit/c64bbcbfe14fd59b5a7203b6a02662dba9c1a0e5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), we increased it from 400kB to 410kB.
=> Increase the bundlesize to address build-ci failure

src/amo/components/AddonReviewCard/index.js, tests/unit/amo/components/TestAddonReviewCard.js
Fixes https://github.com/mozilla/addons-frontend/issues/6491
I told Jorge on IRC that this would be a one line change 😞 
It seems important, though. The API definitely supports multiple developers editing each other's responses.
=> Allow developer response collaboration among authors

src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
Fixes #3969 
---
This PR adds OpenGraph meta tags. It is useful for Facebook, Twitter, etc. In order to verify it, one can use:
- https://cards-dev.twitter.com/validator
- https://iframely.com/embed (sometimes fails for no reason)
- https://developers.facebook.com/tools/debug/ (requires a FB account, which I don't have..)
In order to use those tools, you need to proxy your local env to the outside world with `ngrok` or http://serveo.net/.
=> Add Open Graph meta tags

config/default.js, config/dev-amo.js, config/development-amo.js, config/lib/shared.js, config/stage-amo.js, src/amo/pages/Addon/index.js, src/amo/pages/Category/index.js, src/amo/pages/Home/index.js, src/amo/pages/LandingPage/index.js, src/amo/pages/LanguageTools/index.js, src/amo/pages/StaticPages/About/index.js, src/amo/pages/StaticPages/ReviewGuide/index.js, src/amo/store.js, src/amo/utils.js, src/core/components/ServerHtml/index.js, src/core/types/router.js, tests/unit/amo/helpers.js, tests/unit/amo/pages/StaticPages/TestAbout.js, tests/unit/amo/pages/StaticPages/TestReviewGuide.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestCategory.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/pages/TestLandingPage.js, tests/unit/amo/pages/TestLanguageTools.js, tests/unit/amo/test_utils.js, tests/unit/core/components/TestServerHtml.js, tests/unit/core/server/fakeApp.js
Fixes #5755
---
This PR adds canonical link tags to the following pages:
⚠️ in order to avoid hardcoded URLs, I read the router config (`pathname`) from the redux state. It ensures that our canonical URLs are in sync with the router config, but that's why test cases don't have the "production" values. It also avoids issues with trailing slashes (because we can trust the middleware and we don't have to think about them).
=> Add canonical link tags

locale/hsb/LC_MESSAGES/amo.po
This reapplies the commit from https://github.com/mozilla/addons-frontend/commit/940b1aae3313c3e30ef7019dd216ccee623bfe93
=> Update Sorbian, Upper (hsb) localization of AMO Frontend

locale/da/LC_MESSAGES/amo.po
This reapplies the commit from https://github.com/mozilla/addons-frontend/commit/503df3533359004ad245f9eea24efd0900be31b8
This is mostly formatting churn but I do see some fuzzy strings that got fixed.
=> Update Danish (da) localization of AMO Frontend

src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
Fixes #6587
---
I check `themeData` because the reducer ensures `themeData` is only available for LWT.
Note: `ngrok` + slack (pasting the URL in DM to the `slackbot`) is a nice way to try this PR.
=> Expose "og:image" meta property for lw themes

src/amo/pages/Home/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/6588
I checked other locales but here are screenshots in `es`.
**Before**
**After**
**Before**
**After**
**No changes**
=> Don't center shelf descriptions on smaller screens

src/amo/pages/Addon/index.js, src/core/components/ServerHtml/index.js, src/core/reducers/addons.js, src/core/utils/addons.js, tests/unit/amo/pages/TestAddon.js, tests/unit/core/components/TestServerHtml.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/server/fakeApp.js, tests/unit/core/utils/test_addons.js
Fixes #4129
---
You can use this tool to verify the structured data: https://search.google.com/structured-data/testing-tool
~~I do not yet expose the number of downloads (as mentioned in #4129) because we don't know if we want to expose it. It can be added later in any case.~~
=> Expose JSON linked data on amo detail pages

README.md, jest.config.js, package.json, tests/jest-reporters/flow-check.js
This adds a custom Jest reporter that shows Flow errors in our test output. 
In practical usage, I don't think there will be any impact to speed. There might be a couple seconds of delay when the server starts for the first time but that happens in parallel to the tests anyway.
This fixes https://github.com/mozilla/addons-frontend/issues/6550 by removing the need to run `yarn flow:dev`. It even implements part of https://github.com/mozilla/addons-frontend/issues/2281 🍰 
I've actually wanted to see Flow errors in test output for a while but for some reason it never struck me to create a reporter! It also seems like a decent workaround to https://github.com/facebook/jest/issues/7124
Some examples:
<details>
<summary>Flow failures</summary>
</details>
<details>
<summary>No Flow …
=> Show Flow errors in `yarn test` (as a Jest reporter)

src/amo/components/AddonReviewCard/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/6612 with a more direct margin approach because [can I use `row-gap`](https://caniuse.com/#feat=multicolumn) is full of lies! Browsers are hard.
**Before**
**After**
=> Use plain ol' margin-ing instead of row-gap

tests/unit/helpers.js, tests/unit/test_helpers.js
Fixes #6560
---
This test case makes sure our helper function is always in sync with the
upstream lib.
=> Add a test case for `onLocationChanged`

src/amo/components/AddonReviewCard/styles.scss, src/ui/components/TooltipMenu/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/6656
**Before**
**After**
I also made sure the review control links still look the same.
=> Fix regression in flag menu log in button styles

src/amo/components/AddonTitle/index.js, tests/unit/amo/components/TestAddonTitle.js
Fixes #6628
---
This PR brings react router into the URLs of each author of an add-on, on the add-on detail pages. The list of authors is now fully translatable!
=> Use Link component in AddonTitle

src/amo/components/AddonTitle/index.js, tests/unit/amo/components/TestAddonTitle.js
Fixes #6631
---
This PR adds a new prop to the `AddonTitle` component that adds a link
to the detail page on the add-on name, when the prop is set to `true`.
=> Allow to link back to the add-on detail page from the `AddonTitle` component

src/core/components/AMInstallButton/index.js, src/core/components/InstallButton/index.js, src/core/components/InstallSwitch/index.js, src/core/reducers/addons.js, src/core/themeInstall.js, src/core/types/addons.js, src/disco/components/Addon/index.js, src/ui/components/ThemeImage/index.js, tests/unit/core/components/TestAMInstallButton.js, tests/unit/core/components/TestInstallButton.js, tests/unit/core/components/TestInstallSwitch.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/test_themeInstall.js
Fixes #3892
---
This PR removes a bunch of code related to `theme_data`. I am confident now that
- the `AMInstallButton` is used on AMO and soon on Disco Pane
- flow coverage on Disco Pane is good
- old `InstallSwitch`/`InstallButton` components are scheduled for deletion
This actually fixes a small issue.
In order to test the old code (not for QA but for reviewers):
- make sure to disable the `enableFeatureAMInstallButton` flag in `config/development-disco.js`
- make sure you have the prefs `xpinstall.signatures.dev-root` and `extensions.webapi.testing` set to `true` too
- you should see the switch buttons with `yarn disco:https`
Installing a LW theme should work. Once done, go to `about:addons` and make sure there is your theme listed as installed (with a description) in the `themes` …
=> Refactor theme data

src/amo/components/AddonReviewCard/index.js, tests/unit/amo/components/TestAddonReviewCard.js
Fixes #6416: "Flag" should be removed from the profile page
This PR prevents the "flag" button from being rendered for reviews made by the current user. Essentially, if Sean leaves a review, he should not be allowed to flag his own comment.
**Before:**
**After:**
=> Do not render report flag for reviews by the current user

src/amo/components/AddonReviewCard/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/6613
**Before**
<hr/>
**After**
=> More space between review controls on small screen

src/amo/reducers/versions.js, src/amo/store.js, src/core/reducers/addons.js, src/core/types/addons.js, tests/unit/amo/reducers/test_versions.js, tests/unit/core/reducers/test_addons.js
Fixes #6634 
This stores the `versionId` of the `current_version` in the `addon` object. It also updates the versions reducer so that every time an add-on is loaded we also load data for the add-on's `current_version` in the versions redux state.
This does not remove `current_version` from `addon` nor does it update any components to access the version via `currentVersionId`. That will be done in small pieces in separate PRs after this change lands.
=> Store the versionId of the current version in addon

config/default-disco.js, config/default.js, src/amo/components/AddonHead/index.js, src/core/languages.js, tests/unit/amo/components/TestAddonHead.js
Fixes #6644
~~⚠️ depends on #6649~~
---
This PR adds new `link` tags in the add-on detail pages.
You can try it by using https://app.hreflang.org/, which requires three steps:
1. Install `localtunnel`: https://localtunnel.github.io/www/
2. Run it: `lt --port 3000`
3. Update this line to add `xxx.localtunnel.me` instead of `${_config.get('baseURL')}`: https://github.com/mozilla/addons-frontend/blob/7a6dd48ee5050cc863d6fdefff2dd24eafbe24b4/src/amo/utils.js#L64
4. Browse an add-on detail page like: `xxx.localtunnel.me/en-US/firefox/addon/awesome-screenshot-plus-/?`
5. Paste this URL into https://app.hreflang.org/ and click the "test" button
=> Add alternate links to add-on detail pages

src/amo/pages/Collection/index.js, tests/unit/amo/pages/TestCollection.js
Fixes #5893 
The sort filter should be hidden when creating a collection.
Before:
After:
=> I5893 hide sort filter on collection creation

src/core/components/ServerHtml/index.js, src/core/server/base.js, tests/unit/core/components/TestServerHtml.js
Fixes https://github.com/mozilla/addons-frontend/issues/6729 by serializing the application state immediately after all sagas have finished and *before* the final application component begins rendering. 
This ensures that the client always has a predictable app state. In other words, we already know that we only get *one* chance to load data: the first render and any saga that was triggered by it. This patch makes that implementation detail predictable. 
Before this patch, the constructors of components in the *second* render might have been able to modify the initial state, depending on timing. I don't know if any page was relying on that buggy behavior but I tested cold loads of many pages with this patch and they seem to work.
The steps in …
=> Initialize the client with a predictable app state

src/amo/pages/Home/index.js, src/amo/pages/LandingPage/index.js, src/amo/pages/LanguageTools/index.js, src/amo/pages/SearchTools/index.js, src/amo/pages/StaticPages/About/index.js, tests/unit/amo/pages/StaticPages/TestAbout.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/pages/TestLandingPage.js, tests/unit/amo/pages/TestLanguageTools.js, tests/unit/amo/pages/TestSearchTools.js
Refs #5767
---
Please see this doc for the content: https://docs.google.com/document/d/1jCkeuyCuLpcwAVIXnqpYKgqnHnV0y1OkuQ1WHUc-ftI/edit?usp=sharing
This is the batch #1, I'll open another PR for the categories and yet another one for the more "dynamic" descriptions (reviews, user profiles, etc.)
=> Add "description" meta tags on landing, home, about, lang packs and search tools pages

src/amo/components/AddonHead/index.js, src/amo/components/App/index.js, tests/unit/amo/components/TestAddonHead.js, tests/unit/amo/components/TestApp.js
Fixes #6648
---
Update the page titles for Android, according to this comment: https://github.com/mozilla/addons-frontend/issues/6648#issuecomment-432236938
=> Update page titles for Android

src/amo/pages/AddonReviewList/index.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_versions.js
Refs #5767
---
This PR adds `description` meta tags on review pages.
Please see this doc for the content: https://docs.google.com/document/d/1jCkeuyCuLpcwAVIXnqpYKgqnHnV0y1OkuQ1WHUc-ftI/edit?usp=sharing
=> Add description meta tag on review pages

config/default-amo.js, config/default-disco.js, config/default.js, config/dev-disco.js, config/development-disco.js, src/amo/pages/Addon/index.js, src/disco/components/Addon/index.js, tests/ui/pages/discopane.py, tests/unit/amo/pages/TestAddon.js, tests/unit/disco/components/TestAddon.js
Fixes #6539
---
Given that the `AMInstallButton` has been in-use for a while on AMO, I decided to remove the feature flag and make it the only button on both AMO and Disco Pane.
=> Remove AMInstallButton config, use it everywhere

mkdocs.yml
Old builds were passing this config as command line arguments: https://readthedocs.org/projects/addons-frontend/builds/7827080/.
Things have changed a month ago though... https://readthedocs.org/projects/addons-frontend/builds/8004689/
=> Add mkdocs.yml

src/amo/components/CategoryHead/index.js, src/amo/types/categories.js, tests/unit/amo/components/TestCategoryHead.js
Refs #5767
~~:warning: depends on #6739~~
---
The categories API now exposes the descriptions, so we can just use them in the frontend.
=> Add description meta tag on category pages

src/amo/components/CollectionManager/index.js, tests/unit/amo/components/TestCollectionManager.js
Fixes #5234
---
We need empty strings because controlled inputs in React don't accept `null`.
=> Fix react warning in CollectionManager

src/ui/components/Rating/styles.scss
Fixes #6755. This PR removes outline from rating star when selecting/unselecting the star on Chrome.  CSS property "outline" with value "none" fixes it. Below is screenshot comparison before and after the change.
**Before**:
**After**:
=> Fixes #6755: Remove outline from a Rating Star

package.json, src/core/i18n/utils.js, yarn.lock
Fixes #6457
---
I manually verified this PR by:
- looking at the fork and upstream libs to make sure all changes in the fork have been added to the upstream/original lib
- extracting/merging the locales for `amo` on `master` and on this PR and compared both results (changes are similar, so that looks good)
=> Use official babel-gettext-extractor

src/amo/components/AddonReviewCard/index.js, src/amo/components/FeaturedAddonReview/index.js, src/amo/components/RatingManager/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/UserProfile/index.js, src/amo/reducers/reviews.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestFeaturedAddonReview.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_reviews.js
Fixes https://github.com/mozilla/addons/issues/526
Originally I wanted to modify the current [`fetchReviews`](https://github.com/mozilla/addons-frontend/blob/12ad39894c60fa462ce06edb8b60029d8e029d5a/src/amo/pages/AddonReviewList/index.js#L128-L137) call but this is complicated because I can't depend on `siteUser` (https://github.com/mozilla/addons-frontend/issues/6717). My current patch just introduces a separate dispatch which is fine, I guess. We could fix it up later.
=> Let unlisted add-on owners/developers reply to reviews

src/amo/components/AddonsByAuthorsCard/index.js, src/amo/pages/UserProfile/index.js, src/amo/reducers/addonsByAuthors.js, src/core/types/addons.js, tests/unit/amo/components/TestAddonsByAuthorsCard.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/reducers/test_addonsByAuthors.js
Fixes #6775
~~:warning: depends on #6684~~
---
This PR changes the way we use the `AddonsByAuthorsCard` and adds a
better "loading" state to it. Now, we can render the component all the
time.
The `AddonsByAuthorsCard` is rendered with loading animations on first
render (from the server) and it does not shake.
=> Always render AddonsByAuthorsCard in user profile pages

src/amo/components/AddonRecommendations/index.js, tests/unit/amo/components/TestAddonRecommendations.js
Fixes #6805 
This was happening because in `componentDidUpdate` we were checking `oldAddon !== newAddon` and although the contents of the objects are identical, they are not the same object, so that statement was evaluating to `true`. I changed it to check `oldAddon.guid !== newAddon.guid`, which works in this case. I wonder how many other places in our code base we've done this same thing? Perhaps it would be worth opening a code quality issue to audit for that?
=> Prevent AddonRecommendations from dispatching fetchRecommendations unless the add-on is actually changed

tests/unit/amo/components/TestAddonCompatibilityError.js, tests/unit/core/api/test_index.js, tests/unit/core/components/TestAMInstallButton.js, tests/unit/core/i18n/test_utils.js, tests/unit/core/middleware/test_datadogTiming.js, tests/unit/core/sagas/test_utils.js, tests/unit/core/test_addonManager.js, tests/unit/core/test_tracking.js, tests/unit/core/utils/test_compatibility.js, tests/unit/core/utils/test_server.js
Fixes #6413.
All the test ran successfully after these changes.
=> Fixes #6413. Use `getFakeLogger()` everywhere in test suite

tests/ui/README.md, tests/ui/run-functional-tests.sh
Geckodriver 0.21.0 is required now. With anything less, all the UI tests fail.
=> Update Geckodriver requirement

bin/start-func-test-server.js, config/uitests-disco.js, tests/ui/conftest.py, tests/ui/tests/test_discopane.py
Fixes #6836
---
This PR changes the `uitests` config to use the -dev API instead of -prod.
It fixes the test case that installs an extension, ~~but not (yet) the theme install one.~~ Fixed by installing a LWT and not a static theme.
=> Use -dev API for ui tests

src/amo/actions/reviews.js, src/amo/api/reviews.js, src/amo/components/RatingManager/index.js, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, src/core/types/sagas.js, tests/unit/amo/api/test_reviews.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/helpers.js, tests/unit/test_helpers.js
This fixes https://github.com/mozilla/addons-frontend/issues/4529 by removing the `versionId` parameter when looking for saved reviews. I confirmed that when omitting this parameter, the API returns the latest saved review for the add-on, regardless of version. I also verified that no errors are thrown if the user had reviewed an add-on multiple times at different versions.
As part of this patch, I moved the old review fetching logic to a saga.
=> Always load the latest saved review, regardless of version

src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
Fixes #6735 
Trims the trailing spaces of `slug` in `match.params`. This triggers 301 redirect to and hence removes loading state.
=> Fixes 6735 | Blank space in URLs redirect

src/amo/components/AddonHead/index.js, src/amo/components/CategoryHead/index.js, src/amo/components/HeadLinks/index.js, src/amo/pages/CategoriesPage/index.js, src/amo/pages/Category/index.js, src/amo/pages/Home/index.js, src/amo/pages/LandingPage/index.js, src/amo/pages/LanguageTools/index.js, src/amo/pages/SearchTools/index.js, src/amo/pages/StaticPages/About/index.js, src/amo/pages/StaticPages/ReviewGuide/index.js, tests/unit/amo/components/TestAddonHead.js, tests/unit/amo/components/TestCategoryHead.js, tests/unit/amo/components/TestHeadLinks.js, tests/unit/amo/pages/StaticPages/TestAbout.js, tests/unit/amo/pages/StaticPages/TestReviewGuide.js, tests/unit/amo/pages/TestCategoriesPage.js, tests/unit/amo/pages/TestCategory.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/pages/TestLandingPage.js, tests/unit/amo/pages/TestLanguageTools.js, tests/unit/amo/pages/TestSearchTools.js, tests/unit/helpers.js
Fixes #6774
Fixes #6841
~~:warning: depends on #6794~~
---
Alternate links have been added to all pages containing a `canonical` link. I also added the canonical link to the `SearchTools` component (search tools page) because it was missing. => This PR uses the new `HeadLinks` component, which renders both `canonical` and `alternate` links.
=> Add `hrefLang` on other pages (not add-on detail pages)

src/amo/components/AddonHead/index.js, src/amo/components/HeadMetaTags/index.js, tests/unit/amo/components/TestAddonHead.js, tests/unit/amo/components/TestHeadMetaTags.js
Refs #6555
~~⚠️ depends on #6865~~
---
Changes made to `HeadMetaTags` here:
- added a `appendDefaultTitle` boolean prop: this is required because other pages should have an additional title (not just "Themes" for the "themes" landing page for example) while add-ons have great titles already
- `title` prop becomes optional: the homepage does not have a specific `title`
- `description` prop becomes optional: categories may not have a `description`
The `appendDefaultTitle` prop has been added to the `HeadMetaTags` used in `AddonHead` component.
=> Head meta tags tweaks

src/amo/components/RatingManager/styles.scss
#6357: Force Login rate element to be center of parent.
=> Fix: #6357, Force Login rate element to be center of parent

src/amo/components/AddonReviewCard/index.js, src/amo/components/AddonReviewCard/styles.scss, src/amo/components/AddonReviewManager/index.js, src/ui/components/DismissibleTextForm/index.js, src/ui/components/DismissibleTextForm/styles.scss, tests/unit/ui/components/TestDismissibleTextForm.js
Fixes https://github.com/mozilla/addons-frontend/issues/6579 and fixes https://github.com/mozilla/addons-frontend/issues/6246 by using buttons instead of anchors.
There is some code lore about how we switched from buttons to links in order to workaround a bug in Firefox for Android that triggered hover styles on the first tap (see https://github.com/mozilla/addons-frontend/issues/3458). It would require two taps to trigger the button but the problem went away with an anchor tag. That original problem affected Firefox 58. I tested today with Firefox 62 (release) on Android and I no longer see the problem. I'm not sure when it was fixed but I think it's safe to proceed here.
This patch fixes the same problem for all instances of `<DismissibleText>`. I have manually tested those for …
=> Improve keyboard accessibility for review flow and other forms

src/amo/components/CategoryHead/index.js, src/amo/pages/CategoriesPage/index.js, src/amo/pages/Home/index.js, src/amo/pages/LandingPage/index.js, src/amo/pages/LanguageTools/index.js, src/amo/pages/SearchTools/index.js, src/amo/pages/StaticPages/About/index.js, src/amo/pages/StaticPages/ReviewGuide/index.js, tests/unit/amo/components/TestCategoryHead.js, tests/unit/amo/pages/StaticPages/TestAbout.js, tests/unit/amo/pages/StaticPages/TestReviewGuide.js, tests/unit/amo/pages/TestCategoriesPage.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/pages/TestLandingPage.js, tests/unit/amo/pages/TestLanguageTools.js, tests/unit/amo/pages/TestSearchTools.js
Fixes #6555
~~⚠️ depends on #6868~~
---
**Important:** there is no `image` yet (as described in the original issue) because we don't have an image :D
=> Add OpenGraph tags on other pages (not add-on detail pages)

config/development-disco.js, docs/index.md, docs/telemetry.md, src/core/constants.js, src/core/tracking.js, src/disco/constants.js, src/disco/pages/DiscoPane/index.js, tests/unit/core/test_tracking.js, tests/unit/disco/pages/TestDiscoPane.js, tests/unit/test_tracking_docs.js, yarn.lock
Fixes #6867 
Fixes #6866 
This patch cleans-up the strings used for HCT - because an issue with filtering strings is that it was causing the strings to be truncated which in some cases hid their meaning. 
To fix this I've removed the previous filtering in favour of a fixed mapping for the methods so readability is ensured. The tests check that the mapping text meets the [HCT requirements](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html#limits).
At the same time as implementing better strings, I've also documented the data collection and added a test to ensure we always document any additional methods.
Results now look like this:
=> Fix telemetry method and object strings

src/amo/pages/Addon/index.js, src/core/installAddon.js, src/core/reducers/addons.js, src/core/reducers/versions.js, src/core/types/addons.js, tests/unit/amo/components/TestPermissionUtils.js, tests/unit/amo/pages/TestAddon.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/reducers/test_versions.js, tests/unit/core/test_installAddon.js, tests/unit/core/utils/test_compatibility.js, tests/unit/core/utils/test_index.js
Fixes #6727 
Note that there is one test that is failing that I cannot seem to figure out. It's `sets the current status in componentDidMount with an addonManager` and it's failing because `mapStateToProps` is not being called so the component doesn't end up with a `currentVersion`. I assume this has to do with the way the test is set up, using 
`mount(<WithInstallHelpers {...props} WrappedComponent={() => <div />} />);`
as opposed to
`mount(<Component {...props} />);`
which many of the other tests do.
Any advice anyone can provide on how to fix this test would be appreciated.
Also note that `LanguageToolType` still uses `current_version` and the reducer just stores the raw data returned from the API in state. I don't think this `current_version` is ever accessed, but I will check and …
=> Finish removing current_version and platformFiles from AddonType

src/amo/pages/Addon/index.js, src/core/installAddon.js, src/disco/components/Addon/index.js, tests/unit/core/test_installAddon.js
Fixes #6878
---
Not only this patch moves `userAgentInfo` into `mapStateToProps` but it also completely removes the weird logic around `mapDispatchToProps`. The logger is injected via a prop too and Flow types have been updated to reflect the reality: the `addon` prop is nullable.
=> Move userAgentInfo into mapStateToProps in withInstallHelpers and remove `mapDispatchToProps` stuff

src/amo/components/App/index.js, src/core/actions/index.js, src/core/client/base.js, src/core/constants.js, src/core/middleware/requestId.js, src/core/pages/error-simulation/SimulateClientError/styles.scss, src/core/reducers/api.js, src/core/server/base.js, tests/unit/core/client/test_base.js, tests/unit/core/middleware/test_requestId.js, tests/unit/core/reducers/test_api.js, tests/unit/core/server/test_server.js
Fixes https://github.com/mozilla/addons-frontend/issues/6908 and fixes some style issues on error pages.
The client side Sentry reporter will contain a request ID tag now:
I couldn't think of a way to add this tag to the server side reporter. The best idea I had was to ensure that a request header is set. It seems to work:
The downside is that we'd have to remember to check the request header (not the tag) when viewing server errors.
=> Add request ID to Sentry errors

tests/unit/amo/pages/TestAddon.js
I realized that the test I wrote originally for #6944 was not accurate and would always pass. I committed the cardinal sin of not seeing the test fail, which I try to always do, but in this case I was in a hurry to fix the bug. My apologies. This should fix it.
It doesn't help that the tests for `Addon` are pretty crazy and all over the place, but that's a different issue.
=> Fix the test that was written for an add-on without a version

src/core/components/AMInstallButton/index.js, tests/unit/core/components/TestAMInstallButton.js
Fixes #6964
Fixes #6962
---
I believe we missed this use case because we do not test with all cookies disabled.
In addition, I think Flow coverage in `tracking` would have helped. I filed #6968.
=> Do not send a tracking event when variant is null

README.md, jest.config.js, package.json, tests/jest-reporters/eslint-check.js, tests/jest-reporters/utils.js, tests/unit/jest-reporters/test_utils.js
Fixes https://github.com/mozilla/addons-frontend/issues/2281
---
I tried to use an existing lib but it was super slow and I hate when things are super slow. I wrote another reporter, taking inspiration from the excellent Flow reporter and I added a nice trick to make Eslint report blazing fast ⚡️ 
The trick is to leverage `git` to find the modified files (newly created or modified, not deleted) and to pass this list to ESLint.
=> Create an Eslint reporter

src/amo/components/GuidesAddonCard/index.js, src/amo/components/GuidesAddonCard/styles.scss, tests/unit/amo/components/TestGuidesAddonCard.js
=> I6916 updates to get firefox btn on non firefox client (on guides pages)

src/amo/api/users.js, src/amo/components/AddonTitle/index.js, src/amo/components/Header/index.js, src/amo/components/Routes/index.js, src/amo/pages/UserProfile/index.js, src/amo/pages/UserProfileEdit/index.js, src/amo/reducers/users.js, src/amo/sagas/users.js, tests/unit/amo/api/test_users.js, tests/unit/amo/components/TestAddonTitle.js, tests/unit/amo/components/TestHeader.js, tests/unit/amo/components/TestUserProfileEditNotifications.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/pages/TestUserProfileEdit.js, tests/unit/amo/reducers/test_users.js, tests/unit/amo/sagas/test_users.js
Fixes #6526 
---
⚠️ ⚠️ ⚠️ This PR does NOT add a server redirect when a user profile page is accessed using a `username` in the URL (i.e. `/user/willdurand/`). We should add a server redirect to load a user profile page by `username` and `301` to the URL with the user ID. I have a patch locally, but this PR is big enough. I filed #6915 for that.
=> Use `userId` in user profile pages

src/amo/pages/UserProfile/index.js, src/amo/pages/UserProfileEdit/index.js, src/amo/reducers/users.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/reducers/test_users.js
Fixes #6915
~~:warning: depends on #6904~~
---
This PR allows to keep backward compatibility with the previous URL scheme. User profiles loaded _via_ the `username` in the URL will be redirected to the URL with the user ID.
I double checked with product: we do not need to setup a redirect for the "edit" pages (private pages).
I also inlined a few comments for context. There is #6769 for the `componentWillReceiveProps()` but the logic in this component is tough...
=> Redirect user profile pages

docs/telemetry.md
- Read The Docs has layout issues with the two JS snippets
- Replacing the `const` by `let` allows to override `hostURI`
=> Fix telemetry doc (formatting + js)

src/amo/components/PermissionsCard/permissions.js, src/core/api/versions.js, src/core/installAddon.js, src/core/reducers/versions.js, src/core/types/addons.js, tests/unit/core/reducers/test_versions.js, tests/unit/helpers.js
Fixes #7015 
Note that this also adds the `isCustom` property to `VersionLicenseType`.
=> Move version-related types into versions reducer

config/default-disco.js, config/dev-disco.js, config/development-disco.js
This reverts commit 9490af7e3f4274dcc4a9a2ccd3a693e131711994.
see https://github.com/mozilla/addons-frontend/issues/6797#issuecomment-440985010 for more details.
Fixes #7025
=> Revert "Enable HCT in production (#6994)"

src/amo/components/Header/styles.scss
Fixes #7020
---
See before here: https://github.com/mozilla/addons-frontend/issues/7020#issuecomment-440957324
After:
=> Fix download button width

src/amo/components/HeadLinks/index.js, src/amo/components/HeadMetaTags/index.js, src/amo/components/UserProfileHead/index.js, src/amo/pages/UserProfile/index.js, tests/unit/amo/components/TestHeadLinks.js, tests/unit/amo/components/TestUserProfileHead.js, tests/unit/amo/pages/TestUserProfile.js
Fixes #6527
~~:warning: depends on #6937~~
---
This PR adds a `UserProfileHead` component, similar to the `AddonHead` and `CategoryHead` components. It allows to configure SEO metadata for the user profile pages (not the edit pages). It reuses the `HeadLinks` and `HeadMetaTags` comoponents, but it has some logic to compute a sort of "canonical query string" as defined here: https://github.com/mozilla/addons-frontend/issues/6527#issuecomment-436243834.
=> Create and use a `UserProfileHead` component

src/amo/pages/Guides/index.js, src/amo/reducers/guides.js, tests/unit/amo/pages/TestGuides.js, tests/unit/amo/reducers/test_guides.js, tests/unit/amo/sagas/test_guides.js
Fixes #7019
---
I changed the shape of the state to use a map <slug, Array<GUID>> so that we can load other add-ons for another guide page, while keeping our strategy to avoid double-fetch. I also cleaned up the test file for the `Guides` component.
=> Fix how we fetch add-ons for a guide page

tests/unit/test_sriDataPlugin.js
Fixes #7031
---
~~According to https://github.com/facebook/jest/issues/1909, we should use `node` as the test environment. I am not sure what the implications are, but if the test suite passes with that, I guess it is alright.~~
~~I saw a similar patch related to webpack 4 too: https://github.com/mxmul/closure-loader/pull/40~~
I marked the test file for the `sriDataPlugin` as "requires node", see also: https://github.com/mozilla/addons-frontend/issues/2445
=> Use node env in Jest

src/core/languages.js
Fixes https://github.com/mozilla/addons/issues/839
---
Please read the original issue.
You will need this patch to test properly, because the add-on is only available in -prod. It must be applied to `config/development-amo.js`:
```diff
diff --git a/config/development-amo.js b/config/development-amo.js
index 452283939..24fc8134e 100644
--- a/config/development-amo.js
+++ b/config/development-amo.js
@@ -3,6 +3,8 @@ module.exports = {
baseURL: 'http://localhost:3000',
+  apiHost: 'https://addons.mozilla.org',
+
proxyApiHost: 'http://olympia.test',
proxyPort: 3000,
proxyEnabled: true,
```
Before:
After:
=> Add Venetan lang

src/amo/components/UserProfileHead/index.js, src/core/types/router.js, tests/unit/amo/components/TestUserProfileHead.js, tests/unit/helpers.js, tests/unit/test_helpers.js
Fixes #7038 
---
I am not sure why this issue mainly occurs in the hosted envs, but it was tricky to reproduce locally.. This patch *should* fix the issue because the error message mentions the routing layer, and I don't see what else could go wrong anyway.
I access the `router` data _via_ Redux and not _via_ the HOC, the rest is similar as before. With this patch applied locally, I could not reproduce the issue at all, so I am a bit hopeful.
=> Fix UserProfileHead component

src/amo/actions/reviews.js, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, src/core/types/addons.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/5986 by directly adjusting star rating counts after creating / editing a review instead of relying on the API response to adjust those values. We can't rely on the immediate API response because star rating counts are recalculated on the server in a background task. The server is eventually consistent.
=> Optimistically update star breakdown for ratings

src/amo/sagas/reviews.js, src/core/reducers/addons.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/core/reducers/test_addons.js
~~⚠️ Depends on https://github.com/mozilla/addons-frontend/pull/6957~~
<hr>
Fixes https://github.com/mozilla/addons-frontend/issues/6958 by optimistically recalculating average ratings for an add-on after adding / updating a rating.
=> Optimistically recalculate the average rating for an add-on

src/amo/pages/AddonReviewList/index.js, tests/unit/amo/pages/TestAddonReviewList.js
Fixes #2664: When pre-loading reviews, create only the number of reviews that the page will load
This patch will now render the respective amount of `LoadingText`, ie. placeholders, when a user navigates to an addons reviews page, replacing the current implementation of 4 placeholders.
The new criterion is as follows:
1. If the addon has **between 1 and 25 reviews**, render the exact amount (ex. 3 `LoadingText` placeholders for 3 reviews):
<details>
<summary>🎥 Between 1 and 25 reviews (inclusive)</summary>
</details>
2. If the addon has **more than 25 reviews**, render 25 `LoadingText` placeholders (as per the [pagination limit](https://github.com/mozilla/addons-frontend/blob/fda47b4842a7066ce989a7e5a6ec1a84ecd479fc/src/core/api/index.js#L24)):
<details>
<summary>🎥 25+ reviews</summary> …
=> I2664 - When pre-loading reviews, create the respective amount placeholders for reviews

src/amo/sagas/reviews.js, tests/unit/amo/sagas/test_reviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/6958 (again). The symptom was that when you rated an add-on, the star count incremented by two instead of one.
The call to `updateRatingCounts()` was first added in https://github.com/mozilla/addons-frontend/commit/d4c2a0ddbf#diff-170eeec007168b88041e21f7420f424aR350 for https://github.com/mozilla/addons-frontend/pull/6957
A follow-up patch was originally based on that branch and then rebased on master. This follow-up landed in https://github.com/mozilla/addons-frontend/commit/4a81aae5e9#diff-170eeec007168b88041e21f7420f424aR344 but, as you can see from diff, git automerged the code incorrectly. This resulted in a duplicate call to `updateRatingCounts()`.
=> Remove duplicate call to updateRatingCounts()

src/amo/api/collections.js, src/amo/components/AddAddonToCollection/index.js, src/amo/components/CollectionAddAddon/index.js, src/amo/components/CollectionManager/index.js, src/amo/pages/Collection/index.js, src/amo/pages/CollectionList/index.js, src/amo/reducers/collections.js, src/amo/sagas/collections.js, src/amo/sagas/home.js, tests/unit/amo/api/test_collections.js, tests/unit/amo/components/TestAddAddonToCollection.js, tests/unit/amo/components/TestCollectionAddAddon.js, tests/unit/amo/components/TestCollectionManager.js, tests/unit/amo/pages/TestCollection.js, tests/unit/amo/pages/TestCollectionList.js, tests/unit/amo/reducers/test_collections.js, tests/unit/amo/sagas/test_collections.js, tests/unit/amo/sagas/test_home.js
Fixes #7135 
---
It is a bit weird to see `userId: username` in some component codes but that will be removed very soon.
It is a small step to fix #6609. I removed test cases that covered the `throw Error()` statements that I removed too (replaced with `invariant` calls instead).
=> Rename "username" to "userId" in collection saga/api/reducer

src/core/css/inc/mixins.scss, src/core/css/inc/vars.scss, src/ui/css/vars.scss
This PR makes sure we only use one `$link-color` variable in our SCSS code.
`$blue-60` is the Photon color to use for links: https://design.firefox.com/photon/components/links.html.
=> Only use on link-color var in SCSS

src/amo/components/HomeHeroGuides/styles.scss
fixes #7138 
it seems that there are 2 link-colors (the one referenced in the issue looks more like the one set in ui but I am using the one in core). let me know if this is an issue.
hover on "Organize Tabs & Bookmarks" card:
=> I7138-updating guides link hover color

src/amo/actions/reviews.js, src/amo/api/reviews.js, src/amo/components/AddonMeta/index.js, src/amo/components/AddonReviewCard/index.js, src/amo/components/RatingsByStar/index.js, src/amo/components/RatingsByStar/styles.scss, src/amo/pages/Addon/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/AddonReviewList/styles.scss, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, src/core/components/PaginatorLink/index.js, src/core/components/SurveyNotice/index.js, src/core/components/SurveyNotice/styles.scss, src/ui/components/Notice/index.js, src/ui/components/Notice/styles.scss, tests/unit/amo/api/test_reviews.js, tests/unit/amo/components/TestAddonMeta.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestRatingsByStar.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/core/components/TestPaginatorLink.js, tests/unit/ui/components/TestNotice.js
* Fixes https://github.com/mozilla/addons-frontend/issues/5923 by adding links to the rating graph.
* Fixes https://github.com/mozilla/addons-frontend/issues/4549 by making notice buttons gray.
New screen for viewing filtered reviews:
For stars that have no reviews, it shows a new empty screen:
=> Link the rating graph to reviews filtered by star

.snyk
We only use `chokidar` in `bin/server.js` for development (file watching)
=> Ignore chokidar / chownr security warnings

src/amo/components/AddonMeta/index.js, src/amo/components/AddonReviewCard/index.js, src/amo/pages/Addon/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/sagas/reviews.js, tests/unit/amo/components/TestAddonMeta.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/sagas/test_reviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/7200
**Before**
**After**
<hr>
This new approach will always show rating-only reviews which will make the number of ratings always match the number of results.
Here are a few other changes:
* On the add-on detail page, The metadata count in the star breakdown of "reviews" now includes a count of ratings. This should make the number less confusing as it will now add up to the number of stars.
* The add-on detail page has a link to the review list saying *Read N reviews* where *N* now includes the number of ratings, too. This is because the review list will also show ratings. This will clear up confusion when an add-on has star ratings but no written reviews.
=> Show rating-only reviews to avoid confusing counts

src/amo/components/PermissionsCard/permissions.js, src/ui/components/HostPermissions/index.js
Small change to fix the spelling of `webextension`
Fixes #7265
=> Fixes Spelling of webextension

src/amo/components/CollectionManager/index.js, src/amo/components/CollectionManager/styles.scss
Fixes #5081
I added extra `<div></div>`  and changed styles to make html text had `direction:rtl` while tooltip text has `direction:ltr`.
Before:
After:
=> Fix #5081, ToolTip display in CollectionManager

src/amo/components/GuidesAddonCard/styles.scss
fixes #7205 
I played with this for a bit and the only way I could make it show only 2 lines across the different browsers was with this approach. It does it break it differently (than what was seen on chrome) but hopefully this is okay.
=> I7205 style tweak for non firefox button

src/disco/pages/DiscoPane/styles.scss
=> I6486 removing style to left align disco pane

src/amo/pages/UserProfileEdit/index.js, src/amo/pages/UserProfileEdit/styles.scss, tests/unit/amo/pages/TestUserProfileEdit.js
Fixes #7166
---
This PR removes the "username" field in the user profile edit page.
=> Remove `username` field in `UserProfileEdit` page/component

src/amo/components/CollectionManager/index.js, src/amo/pages/Collection/index.js, src/amo/pages/CollectionList/index.js, src/amo/reducers/collections.js, src/ui/components/UserCollection/index.js, tests/unit/amo/components/TestCollectionManager.js, tests/unit/amo/components/TestCollectionSort.js, tests/unit/amo/pages/TestCollection.js, tests/unit/amo/pages/TestCollectionList.js, tests/unit/amo/reducers/test_collections.js, tests/unit/ui/components/TestUserCollection.js
Fixes #6609
---
This PR updates the collection code to deal with user IDs instead of usernames. It handles the case when a collection is loaded by username and not user ID for backward compatibility.
I filed #7297 to fix the hardcoded collection URLs in the homepage.
=> User ID in collection URLs

src/amo/pages/AddonReviewList/index.js, tests/unit/amo/pages/TestAddonReviewList.js
Fixes #7311
---
This PR makes sure permissions are not fetched when there is an error in the review list page.
=> Do not dispatch action when an error has occured

src/amo/pages/Home/index.js, src/amo/reducers/home.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/reducers/test_home.js
Fixes #6650
---
This PR changes the `home` reducer and `Home` component to re-fetch the
homepage data when the `clientApp` changes.
=> Re-fetch home data when clientApp changes

src/amo/components/AddonVersionCard/styles.scss
=> fixing position of add to FF button to center at version page

src/amo/pages/Guides/index.js
Fixes #7344
---
This PR updates the mozilla collection URLs used in the guide pages to use `userId` instead of `username` values. I did not use a variable because URLs are hardcoded anyway.
=> Fix collections URLs for guide pages

src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes #7352
---
This PR changes the link to "see all versions" of an add-on to use
client-side navigation and react-router.
=> Use react-router for "all versions" link

src/amo/components/AddonVersionCard/index.js, tests/unit/amo/components/TestAddonVersionCard.js
Fixes #7348
---
This PR allows licenses without URL to be displayed in an `AddonVersionCard`.
=> Render a license without URL in AddonVersionCard

src/amo/pages/AddonVersions/index.js, src/amo/pages/AddonVersions/styles.scss, tests/unit/amo/pages/TestAddonVersions.js
Fixes #7343
---
This PR does a few things to improve error handling of the "All versions" pages:
- return a `NotFound` component for 401, 403 and 404 API responses
(similar to the add-on detail page)
- fix style so that errors are more readable
=> Return a NotFound page when add-on does not exist

src/core/installAddon.js, tests/unit/core/test_installAddon.js
Fixes #7332 
Note that this only addresses the issue where the current version is installed no matter which button is clicked. It does not address the issue of the behaviour of all of the buttons (i.e., they all show install status, they all say "Remove" and they all say "Enable", in different scenarios). That may or may not be addressed via a separate issue.
=> Install the correct version when a specific version is set for installAddon

src/core/utils/index.js, tests/unit/core/utils/test_index.js
Fixes #6129
---
Using this content in the edit page of [my user in -dev](https://addons-dev.allizom.org/en-US/firefox/user/10641627/):
=> Update regex in `nl2br`

src/amo/actions/reviews.js, src/amo/pages/AddonReviewList/index.js, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js
Fixes https://github.com/mozilla/addons-frontend/issues/7206 by adding `score` as a dimension to the stored reviews data.
I discovered a new bug while working on this one: https://github.com/mozilla/addons-frontend/issues/7376 It will be fixed in a follow-up patch.
=> Store reviews data with a score

src/amo/components/AddonVersionCard/index.js, src/amo/components/AddonVersionCard/styles.scss, src/amo/pages/AddonVersions/index.js, src/amo/pages/AddonVersions/styles.scss
Fixes #7245 
Also fixes #7350
I believe this fixes all of the items mentioned in #7245.
Before (desktop):
After (desktop):
Before (mobile): 
After (mobile):
=> Fix inconsistencies between the All Versions page and the mocks

src/amo/actions/reviews.js, src/amo/pages/AddonReviewList/index.js, src/amo/reducers/reviews.js, src/amo/sagas/reviews.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_reviews.js
~~⚠️  Depends on https://github.com/mozilla/addons-frontend/pull/7374~~
<hr>
This patch fixes https://github.com/mozilla/addons-frontend/issues/7376 by adding `page` to the reducer data. Because this implements more natural pagination, it also magically fixes https://github.com/mozilla/addons-frontend/issues/3759
=> Store page as part of review listing data

webpack.prod.config.babel.js
Fixes https://github.com/mozilla/addons-frontend/issues/7191 by disabling one of our SVG optimizations.
I couldn't figure out how to apply SVG optimizations to `yarn amo:dev` so I was testing with a [production build](https://github.com/mozilla/addons-frontend/#building-and-running-services) which allowed me to reproduce the bug.
Here are the stars before my patch:
Here are the stars after:
=> Workaround bug in svgo causing glitchy stars

Dockerfile
Fixes #7418
---
As discussed in the weekly, this upgrades node to v10.
Need to add python and build-essential packages or the `yarn install --pure-lockfile`
fails while trying to invoke `detect-libc prebuild-install || node-gyp rebuild`.
=> Upgrade to node v10

src/amo/components/ReportAbuseButton/index.js, src/amo/components/ReportAbuseButton/styles.scss, src/core/reducers/abuse.js, tests/unit/amo/components/TestReportAbuseButton.js, tests/unit/core/reducers/test_abuse.js
Fixes #3279 
Botton styles changes.
I also removed relevant part of  `disableAbuseButtonUI` and  `enableAbuseButtonUI` in "core/reducers/abuse.js" since they are not used any more.
Before,
After,
=> Refactor ReportAbuseButton to use DismissibleTextForm

src/amo/pages/AddonReviewList/index.js, tests/unit/amo/pages/TestAddonReviewList.js
Fixes #7436
Fixes #7452
---
Before:
After:
=> Show dropdown filter in header when there is 0 review

src/amo/reducers/collections.js, tests/unit/amo/reducers/test_collections.js
Fixes #7412
---
By resetting this part of the state on `LOCATION_CHANGE` (i.e. when the
user navigates to another page), the displayed messages that were
persistent are now hidden when the user navigates back to the add-on
detail page.
=> Hide persistent messages in AddAddonToCollection

src/amo/components/EditableCollectionAddon/index.js, tests/unit/amo/components/TestEditableCollectionAddon.js
=> Make url clickable in add-on notes I7444

.travis.yml, package.json
Fixes https://github.com/mozilla/addons-frontend/issues/7491
I checked out the code before https://github.com/mozilla/addons-frontend/pull/7469 and verified that `yarn storybook-smoke-test` failed. It succeeds on master.
=> Ensure that storybook doesn't break again

src/amo/pages/UserProfileEdit/index.js, tests/unit/amo/pages/TestUserProfileEdit.js
Fixes #7301 
Indicating mandatory display name field.
Put a mandatory sign `*` next to display name label, so as to make it look mandatory
**Before:**
**After:**
Hope it works simply with a `*`
=> I7301 - Indicating mandatory display name field

src/amo/components/AddonRecommendations/index.js, src/disco/components/App/index.js, src/disco/components/App/styles.scss, src/disco/pages/DiscoPane/index.js, src/disco/pages/DiscoPane/styles.scss, src/disco/reducers/discoResults.js, src/ui/components/Notice/index.js, tests/ui/pages/discopane.py, tests/unit/disco/components/TestApp.js, tests/unit/disco/pages/TestDiscoPane.js, tests/unit/disco/reducers/test_discoResults.js
Fixes #7494 
---
This PR mainly adds a `Notice` component to the Disco Pane when there are "recommended results" listed, i.e. **some** of the API results come from the recommendation service (TAAR) and not from the static curated content.
Because following the CSS was tricky, I also refactored some of the CSS in the disco app by:
- moving CSS code to the right file
- renaming some CSS class names
When there are no recommended results, there is no notice:
But when there is at least one recommended result, a notice is displayed with a parametrized "learn more" link:
=> Recommendation disco UI

jest.config.js
=> Use setupFilesAfterEnv instead of setupTestFrameworkScriptFile

src/ui/components/DropdownMenu/styles.scss
Fixes #7389: Dotted Line Border Will not show up on Android & Desktop
Bugs Remaining:
1. Pressing Ctrl brings up the Dotted Line on Dropdown Menu
2. Dev Hub still showing dotted Line(Need Help in this)
=> Dotted Line Border Will not show up on Android & Desktop

src/disco/pages/DiscoPane/styles.scss
Fixes #7520
---
Before:
After:
=> Fix notice in disco pane

src/amo/pages/AddonReviewList/index.js, tests/unit/amo/pages/TestAddonReviewList.js
Fixes #6827 
The reply button is disappeared because `permissions` is undefined after the reply is deleted.
This situation only happens when the reply is featured, by clicking the time permalink.
This is because only the featured reply will be set to [byId](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/reviews.js#L705), it will then go into the `if` condition and set the permission to undefined. 
I then check the action after reload, it calls `fetchReviewPermissions`. Thus, I move `fetchReviewPermissions` from `componentDidMount` to `componentDidUpdate`.
But I am not sure it is a good solution, if you find out a better way, please comment.
=> I-6827 Display reply button of a comment after deleting the reply

src/amo/components/SearchContextCard/styles.scss
=> Discrete styling for search results on small screens

src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss, src/amo/pages/Addon/index.js, src/core/css/inc/vars.scss, src/core/imageUtils.js, src/disco/components/Addon/index.js, src/ui/components/ThemeImage/index.js, tests/unit/core/test_imageUtils.js, tests/unit/disco/components/TestAddon.js, tests/unit/ui/components/TestThemeImage.js
fixes #6507
This updates the header in the product detail and search results. 
Note: I created a method so it would be more dynamic since there is [discussion](https://github.com/mozilla/addons-server/issues/9419#issuecomment-424329033) of removing the other previews sizes.
some static themes (eg: eco theme) don't have the 720 sizes so it should default to using the first image in the previews array
EDIT
NOTE: I do have a follow up question to see if we should be updating this on disco too: See https://github.com/mozilla/addons-frontend/issues/6507#issuecomment-460373429
maybe that could be a follow up issue tho?
=> I6507 updating preview size

src/amo/components/Search/index.js, src/amo/components/SearchContextCard/index.js, src/amo/components/SearchResults/index.js, src/core/reducers/search.js, src/core/searchUtils.js, tests/unit/amo/components/TestSearch.js, tests/unit/amo/components/TestSearchResults.js, tests/unit/core/reducers/test_search.js
Fixes #6117
---
We do not reset filters anymore and we show all the results coming from the API, with or without filters.
In order to make sure a fresh call to `/search/` shows all the results, I changed the initial state from `filters: {}` to `filters: null` so that we call the API the very first time only.
=> Show all search results by default

src/disco/components/Addon/styles.scss
Fixes #7580 
Replaced break-all with break-word in src/disco/components/Addon/styles.scss file at L23
=> Fixes #7580: Replaced break-all with break-word

src/amo/pages/Home/styles.scss
Fixes #6376
`.Home-SubjectShelf-list` should ideally never have overflow, so `overflow:auto` is kinda removable. `overflow: auto` causes this issue, adding 1px to top and bottom would have also helped, but I preferred removing `overflow`
=> I6376: show focus rectangles rectangles at home page

src/amo/components/AddonReviewManagerRating/styles.scss, src/ui/components/Rating/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/7581
Some screenshots of the components that this will apply to:
=> Fix rating stars in edit mode on mobile

src/amo/components/Footer/styles.scss
Fixes #7579: Choose Language Select BG is always White
=> Fixes #7579: Choose Language Select BG is always White

src/core/constants.js, tests/unit/amo/components/TestAddonsByAuthorsCard.js, tests/unit/amo/reducers/test_addonsByAuthors.js
Fixes https://github.com/mozilla/addons-frontend/issues/7584
I was able to reproduce the bug locally before fixing it.
I don't really know what I'm doing here TBH. Lightweight themes have been removed entirely, correct? I deleted some tests which were only related to lightweight themes. Each one had a complimentary test using a static theme and those are still passing.
=> Stop searching for lightweight themes to prevent an API error

src/amo/pages/Home/index.js, tests/unit/amo/pages/TestHome.js
Fixes #7746
---
It turns out that `isTheme` was more useful than expected 😓 
Before:
After:
=> Fix themes on homepage

src/amo/pages/AddonVersions/styles.scss
Fix #7732 
I cannot find addon release notes with `ul` tag for test. So I only manually add `ul` into `<div class="AddonVersionCard-releaseNotes"></div>` and it looks ok.
=> Fix list padding in release notes I7732

src/amo/pages/AddonVersions/index.js, tests/unit/amo/pages/TestAddonVersions.js
Fixes https://github.com/mozilla/addons-frontend/issues/7825
Description:
This fixes a capitalization issue with the version history page.
Before:
After:
=> Correct version history page capitalization

src/amo/components/Routes/index.js, src/amo/components/UserProfileEditNotifications/index.js, src/amo/pages/UsersUnsubscribe/index.js, src/amo/pages/UsersUnsubscribe/styles.scss, src/amo/utils/notifications.js, tests/unit/amo/components/TestRoutes.js, tests/unit/amo/components/TestUserProfileEditNotifications.js, tests/unit/amo/pages/TestUsersUnsubscribe.js
Fixes #7840
---
This patch adds a new `UsersUnsubscribe` page component. It won't be enabled in -dev because the route is redirected to addons-server at the nginx level. This patch supports #7656. It does NOT perform any action yet.
Being logged in or out does not matter because we'll use the hash/token in the URL. That's why the two screenshots thereafter are the same. The UI is similar to the old one but I did not add two links to edit the notification settings/profile. It's the same page, so I added a sentence that explains what a user can do after having landed to this page. That's what I'd expect when landing to this page. 
User is logged in:
User is not logged in:
=> Add basic UsersUnsubscribe page

package.json, src/amo/api/users.js, src/core/api/index.js, tests/unit/amo/api/test_users.js, tests/unit/core/api/test_index.js, tests/unit/core/api/test_index_node.js, yarn.lock
Fixes #7843
---
This patch fixes an issue with `FormData` being not defined on the server. The fact that it still works without having to change any test case is a good sign. I added two smoke tests to make sure we use the right `FormData` in each context.
=> Use an isomorphic lib for FormData

src/amo/api/users.js, tests/unit/amo/api/test_users.js
Fixes #7842
---
This patch only adds a new API function to reduce the diff of the patch needed for #7853.
=> Add API function to unsubscribe a user from a notification

src/amo/components/Header/index.js
Fixes [#7831](https://github.com/mozilla/addons-frontend/issues/7831)
Add tooltips to the Extension Workshop and DevHub header links:
- Extension Workshop: "Learn how to create extensions and themes"
- Developer Hub: "Submit and manage extensions and themes"
=> Added tooltips to Extension Workshop and DevHub header links

src/amo/pages/StaticPages/About/index.js
Fixes #7838
---
Under Get Involved, Added new line :
Want to interact with addons.mozilla.org (AMO) programmatically? Check out the documentation for the Add-ons Servers documentation for details about the AMO APIs, the APIs used by the Add-ons Manager.
=> Added new line under Get Involved

bin/.gitattributes, config/dev-amo.js, config/development-amo.js
Fix #7830
---
When running `yarn dev:amo`, the link to extension workshop in footer now point at ttps://extensionworkshop-dev.allizom.org.
Please note the url is not available :cry: 
~I've also added `.gitattribute` file to force LF end of lines on checkout. Developers with `auto.crlf=true` in their global git configuration. One cannot run the app with CLRF in script files.~
=> Change extension workshop urls when running dev

src/amo/pages/UsersUnsubscribe/index.js, tests/unit/amo/pages/TestUsersUnsubscribe.js
Fixes #7656
~~⚠️ depends on #7855~~
---
**Only the last commit is relevant.**
This is the last iteration to ship a new unsubscribe page.
Happy path:
Loading state:
Token is invalid:
Hash is invalid:
Notification name is invalid:
=> Connect `UsersUnsubscribe` component

src/amo/pages/UserProfileEdit/index.js
Fixes #6769 
---
This is similar to [other](https://github.com/mozilla/addons-frontend/issues/6770) [patches](https://github.com/mozilla/addons-frontend/issues/6771).
It is needed to [upgrade Enzyme to 3.9.0](https://github.com/mozilla/addons-frontend/pull/7606) which, in turn, should allow us to use `getDerivedStateFromProps()` in this component to get rid of the `setState` calls in `componentDidUpdate()` (there is [a known Enzyme issue about that](https://github.com/airbnb/enzyme/issues/2020)).
It is not recommended to use `setState` in `componentDidUpdate()` but it is possible. The only potential problem is infinite loops but we have enough guards in place to avoid that, so I don't think we'll run into issues. That being said, once this patch lands and we upgrade to Enzyme 3.9.0, I'll …
=> Remove use of componentWillReceiveProps() in UserProfileEdit

src/amo/components/AddonReviewCard/index.js, tests/unit/amo/components/TestAddonReviewCard.js
=> Add tooltip to review time I7849

src/amo/components/AddonVersionCard/index.js, tests/unit/amo/components/TestAddonVersionCard.js
Fixes #7913 
Rename unidentified license to Custom License in `AddonVersionCard`.
Also, I find the translation doesn't work properly, so I change the condition a little bit.
Please check if it is appropriate.
Before: 
After
=> Rename unidentified license to Custom License in AddonVersionCard

src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes #7912
---
Before:
After:
=> Set a default name for license when name is `null`

config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/components/AddonBadges/index.js, src/core/reducers/addons.js, src/core/types/addons.js, tests/unit/amo/components/TestAddonBadges.js, tests/unit/helpers.js
~~Depends on #7958~~
Fixes #7794 
Large screen:
Small screen:
I know there are some issues with the small screen, but I think I'll be able to address them once I have the correct icon.
@jvillalobos & @brassy- Do we want the Recommended badge to appear lower down on the small version of the screen, as it does in my screenshot above? I've simply put it above all the other badges on both the large and small screens. But maybe we want this new Recommended badge to show up in the upper right-hand corner even on smaller screens?
=> Show recommended badge on details page

src/ui/components/RecommendedBadge/styles.scss
Fixes #7986 
Default:
Hovered:
=> Update recommended badge colors

src/amo/pages/UserProfile/index.js, tests/unit/amo/pages/TestUserProfile.js
Fixes #4916 
Profile homepage ref now looks like this.
Kept the lightgray 'Homepage' label, as discussed in #4916
=> replacing the profile url with "Homepage" (#4916)

src/core/languages.js
We need to support Bengali (bn) from 68. 
https://addons.mozilla.org/it/firefox/addon/bengali-language-pack/
Without the language listed here, the language pack won't be available in 
https://addons.mozilla.org/firefox/language-tools/
=> Add Bengali (bn) to list of languages

.travis.yml, tests/unit/amo/components/TestSearchResult.js, tests/unit/core/i18n/test_utils.js
Fixes #8100
---
- Use a narrow space (`\u202F`) in the expected formatted strings.
- Upgrade to Node 12 because Node 11 was set before Node 12 was available (and Node LTS are only even numbers)
=> Fix test suite

src/amo/components/SearchFilters/index.js, tests/unit/amo/components/TestSearchFilters.js
=> Force recommended results to the top when sorting from a Category page

src/amo/components/EditableCollectionAddon/styles.scss, src/ui/components/Button/styles.scss
Fixes #5575 
Updated style for buttons to remove `text-shadow` for `Buttons` on CollectionEdit.
=> Remove text shadow for collection action buttons

src/core/middleware/prefixMiddleware.js, tests/unit/core/middleware/test_prefixMiddleware.js
Fixes #8059
From local testing (to exercise both the prefix and the trailing slash middleware) this results in the following:
`/android?foo=1` => `/en-US/android/?foo=1`
`/en-US/android?foo=1` => `/en-US/android/?foo=1`
`/en-US?foo=1` => `/en-US/firefox/?foo=1`
=> Handle query params correctly for client app urls with no trailing slash

src/amo/pages/Guides/index.js
Fixes #8131 
Note that I thought about using [`categoryResultsLinkTo`](https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/amo/components/Categories/index.js#L59-L70) to build the link, but `exploreUrl` in the Guides page expects a string, which it uses in a couple of places, whereas `categoryResultsLinkTo` returns an object which we'd have to unpack and manipulate. Seeing as this page is always going to be manually edited whenever changes are required, and all the other values of `exploreUrl` are strings, I kept it simple and just included an explicit link.
=> Fix the link to photos-music-videos from the Guides page

PULL_REQUEST_TEMPLATE.md
The last sentence of the old template explained how to finalize the PR but no one did that. This tells me that we should guide them towards the final state rather than explain how to do it. If someone doesn't read this new template at all, their PR description will at least look close to finalized.
=> Make the PR template easier to edit and understand

src/amo/components/AddonRecommendations/styles.scss, src/amo/components/AddonsCard/styles.scss, src/amo/components/SearchResult/index.js
Fixes #8154 
Note that this is a quick fix which simply replaces the `<a>` wrapper that was removed with a `<div>` wrapper. This works and seems to now render the site the same as what's on stage.
We may want to reevaluate how we're assigning these styles in a follow-up, as I'm not sure if we need this wrapper or if we could just assign the styles directly to the `SearchResult-result` `div`, but we need a fix to land in time for today's tag, so I think we should deal with that in a follow-up.
Before:
After:
=> Fix search result styles

src/core/searchUtils.js, tests/unit/core/test_searchUtils.js
Fixes #8177 
Note that this error is triggered by having multiple `sort` query parameters, which results in `filters.sort` being an array rather than a string.
We discussed this in IRC and we cannot really properly support multiple instances of query parameters for a number of reasons including:
- The APIs do not support it (they take the last instance of multiple params passed)
- Our UI generally does not support it (for things like search params, where we only allow the user to choose a single value)
My solution to this is to just take the first instance of multiple query params and use that. There is no reason for a user to expect to be able to manually add multiple instances of a query param to the URL and expect the application to be smart enough to know what to do with them.
=> Only use the first instance of multiple query parameters

src/amo/components/AddonsByAuthorsCard/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/8161
Before:
After:
The wide-screen search results remain the same:
=> Tighten up recommended styles (add-ons by authors)

src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes #3900 
This patch adds file size information to "More Info" section on addon's page.
Before:
After:
=> Fixes #3900: Add file size info to addon's "More Info" section

.snyk
I reviewed the use of the `defaultsDeep`, `mergeWith` and `merge` functions and they are not used in our code base. There are occurrences in the node modules but not in libs we are directly using (only build tools).
=> Temporarily ignore lodash prototype pollution

src/amo/components/SearchResult/styles.scss
Fixes #8254 
Note that the only css rule I could get to work is `word-wrap: anywhere;`, which seems odd as we use `word-wrap: break-word;` everywhere else, but for some reason that isn't working in this case. I'm not sure why.
Before:
After:
=> Wrap unbreaking words in add-on name in search results

src/amo/components/LandingAddonsCard/index.js, src/amo/components/LandingAddonsCard/styles.scss, src/amo/pages/Home/index.js, src/amo/pages/Home/styles.scss, src/amo/sagas/home.js, tests/unit/amo/sagas/test_home.js
Fixes #8278 
This fixes the issue, but it's causing a css problem that I can't seem to track down. I've compared the style rules using Firefox's dev tools for all of the elements that make up both the Recommended Themes shelf (which looks fine) and the Popular Themes shelf (which is way too high) and they all seem identical. I could use some help debugging this css issue.
=> Display only 3 themes for all home page shelves that include themes

src/amo/pages/Addon/index.js
Fixes #7624
This patch moves `<PermissionsCard />` further up on addon page.
Change works locally. Tests pass. I didn't add new tests - order of components was not tested previously.
Before:
After:
=> Move PermissionsCard further up on addon page

src/amo/sagas/home.js, tests/unit/amo/sagas/test_home.js
Fixes https://github.com/mozilla/addons-frontend/issues/8294
---
To ease the review, you can edit `src/amo/pages/Home/index.js` and
change the `userId` to `10641627` as shown below. I made a private
collection with the `password-maangers` slug. Be sure to be logged in
and you should see that the collection is hidden with the patch and
everything is broken without it.
```diff
diff --git a/src/amo/pages/Home/index.js b/src/amo/pages/Home/index.js
index 9e2b538f8..d317fec64 100644
--- a/src/amo/pages/Home/index.js
+++ b/src/amo/pages/Home/index.js
@@ -34,7 +34,7 @@ export const MOZILLA_USER_ID = config.get('mozillaUserId');
export const FEATURED_COLLECTIONS = [
{ slug: 'privacy-matters', userId: MOZILLA_USER_ID },
-  { slug: 'password-managers', userId: MOZILLA_USER_ID },
+  { slug: …
```
=> Do not indefinitely reload homepage collections on 403

tests/ui/run-functional-tests.sh
This disables the devhub and install tests within this repo. See https://github.com/mozilla/addons-server/issues/11691 for more details.
Fixes #8323
=> Change integration-test job to only run specific tests.

src/amo/components/GuidesAddonCard/index.js, src/amo/components/GuidesAddonCard/styles.scss
Fixes #8284 
I got this working pretty much exactly how I wanted, with one exception. When the description of the add-on is only on one line, the Install Button looks too close to the bottom of the card (to me, anyway). That's because it is center aligned with the description. To fix this I added some padding to the bottom of the button, which gives it a decent amount of space in this scenario, but it does mean that when there is more than one line of add-on description, the button is not 100% center aligned with the description, but is above center by a very small amount. The longer the description, the less of a difference this makes. 
Perhaps there's something else I can do to fix this without affecting the centering of the button for longer descriptions?
Here's an example of the …
=> Fix display issue with Recommended Badge on Guides pages

src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/8330
🤷‍♂ 
Before:
After:
=> Use a spacer (I'm serious) to fix badge wrapping

src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss
This fixes https://github.com/mozilla/addons-frontend/issues/8330 and reverts the previous attempt at a fix, too (https://github.com/mozilla/addons-frontend/pull/8335)
Before:
After:
=> Recommended badges: replace spacer with a margin

tests/unit/amo/components/TestSearchResult.js
Fixes https://github.com/mozilla/addons-frontend/issues/8379
I also updated the localization tests to rely on explicit input rather than implicit (default) input.
=> Make the non-breaking space test less flaky

.circleci/config.yml, tests/smoke/README.md, tests/smoke/setup_docker.sh, tests/smoke/test_homepage.py, tests/ui/docker-compose.functional-tests.yml, tox.ini
More fixes for the smoke test suite. This adds a selenium-firefox docker image that the tests can run in.
=> Update smoke tests to use requests instead of seleium.

src/amo/components/HeroRecommendation/styles.scss
This fixes https://github.com/mozilla/addons-frontend/issues/8426 with a workaround.
**Before** (the SVG shape overlaps its container just slightly at the bottom):
**After**:
=> Work around layout bug for hero promo SVG

src/amo/components/AddonSummaryCard/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/8437
**Before** (in iPhone 6/7/8)
**After**
=> Fix rating star alignment in mobile view

src/amo/components/RatingManager/index.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/pages/TestAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/8450
This isn't the first one we've had to fix. D'oh. I have a feeling hooks would make it easier to write a wrapper around our loaders to automatically prevent execution on error. We need some kind of abstraction like that but it's not really possible with `componentDidMount()`.
=> Do not enter a fetch loop on error

src/core/withExperiment.js, tests/unit/core/test_withExperiment.js
Fixes #8515 
This makes the default expiry date of a cookie created via `withExperiment` 30 days in the future (2592000 seconds, to be exact). This can be overridden for a particular experiment by passing a `cookieConfig` property into the call to `withExperiment`, which can then specify a different expiry date.
=> Default the expiry date for cookies created by withExperiment to 30 days

src/core/components/SiteNotices/index.js, tests/unit/core/components/TestSiteNotices.js
Fixes https://github.com/mozilla/addons-frontend/issues/8599
---
Before:
After:
=> Allow some HTML tags in SiteNotices

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, tests/unit/amo/components/TestHeroRecommendation.js
=> Do not display author names in Primary Hero shelf

src/core/languages.js
Fixes https://github.com/mozilla/addons-frontend/issues/8613
---
We're in the process of adding trs and ca-valencia to Firefox 71, we need trs added in order to show the language pack on the page.
The decode name is `Nánj nï'ïn`.
=> Add Triqui (trs), update name for ca-valencia

src/amo/components/AddonHead/index.js, src/amo/components/HeadMetaTags/index.js, src/amo/pages/Home/index.js, tests/unit/amo/components/TestAddonHead.js, tests/unit/amo/components/TestHeadMetaTags.js
Fixes #8066
This patch adds missed Twitter meta tags into html head.
According to ["Twitter Cards and Open Graph"](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html) documentation -
> When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property. This allows for both to be defined on the page independently, and minimizes the amount of duplicate markup required to describe content and experience.
Also this line from ["Overview of all Twitter Card Tags"](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup) explains the current behavior -
> If an og:type, og:title and og:description exist in the markup but …
=> Fixes #8066: Add twitter meta tags to head

src/amo/reducers/users.js, tests/unit/amo/reducers/test_users.js
Fixes https://github.com/mozilla/addons-frontend/issues/8575
=> Support wildcards in `hasPermission()`

src/core/components/SiteNotices/index.js, tests/unit/core/components/TestSiteNotices.js
Fixes #8616
---
We need to use a new sanitize function so that we can use a `<span />`.
We have an [ESLint rule](https://github.com/mozilla/eslint-plugin-amo#dangerously-set-inner-html) to prevent the use of `sanitizeUserHTML()` with a tag that is not `<div />`.
`<span />` should only have [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) as children, which is why we need a new sanitize function. `<a />` is allowed "if it contains only phrasing content", which should be fine here.
=> Fix UI glitch on SiteNotices by adding a new sanitize function

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, src/amo/reducers/home.js, stories/amo/HeroRecommendation.js, tests/unit/amo/components/TestHeroRecommendation.js, tests/unit/helpers.js
~~Depends on #8615~~
Fixes #8629 
With and without image screenshots, from Storybook:
=> Different layout for primary hero based on primary image

src/ui/components/Notice/styles.scss, src/ui/css/vars.scss
fixes #8632
@willdurand I ran it locally and both desktop and android links are black. The links change color when they are clicked and you return the page once again. If you clear the browsing data, the color is back to black. Located class Notice-text, and change the link color.
=> Issue #8632, Change link color

src/amo/components/Footer/index.js
Fixes #8465 
`Footer` passes a ref to `LanguagePicker` which is a class component but it's wrapped in HOCs.
`this.languagePicker` is dead code so it is removed.
=> Remove language picker ref

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, src/amo/components/SecondaryHero/index.js, src/amo/components/SecondaryHero/styles.scss, src/amo/pages/Home/index.js, stories/amo/HeroRecommendation.js, tests/unit/amo/components/TestHeroRecommendation.js, tests/unit/amo/components/TestSecondaryHero.js, tests/unit/amo/pages/TestHome.js
~~Depends on #8662~~
Fixes #8619 
This is my first take at solving this issue. It basically works, but as discussed in the front-end meeting, it's virtually impossible to make sure the `min-height` always works, because sometimes the content can make the hero bigger, and at the same time we don't want to make the standard `min-height` too big or the hero will take up an unnecessary amount of space. I came up with the numbers in this PR by taking what looked to me that an average amount of content for a hero (both the Primary and Secondary) and then observing the sizes at different viewport sizes.
The positioning of the `LoadingText` elements are not very exact, but I'm not sure how important that is. I think it's more important to try to get the overall sizes of the elements as close as …
=> Create loading skeleton for hero shelves

src/amo/components/HeroRecommendation/styles.scss
Fixes #8742 
Before, with image (however image is hidden):
After, with image:
Before, no image:
After, no image:
=> Layout fixes for Primary Hero element on mobile

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, src/amo/components/Page/index.js, src/amo/components/Page/styles.scss, src/amo/pages/Home/index.js, src/amo/pages/Home/styles.scss, stories/amo/HeroRecommendation.js, tests/unit/amo/components/TestHeroRecommendation.js, tests/unit/amo/components/TestPage.js, tests/unit/amo/pages/TestHome.js
Fixes #8750 
Fixes #8756
Before (#8750):
After (#8750):
Before (#8756):
After (#8756):
=> Fix width of site notices and error messages on home page

src/amo/components/SecondaryHero/styles.scss
=> Fix overflow issue with long words on Secondary Hero

src/amo/components/Page/index.js, tests/unit/amo/components/TestPage.js
~~Depends on #8753~~
Fixes #8757 
I could easily combine this into the patch for #8753 if that would be preferred.
Before:
After:
=> Fix site banner and error messages on Android home page

src/amo/components/HeroRecommendation/styles.scss
=> Fix primary hero loading skeleton on mobile

src/amo/components/HeroRecommendation/styles.scss
=> Fix the "Get the extension" button in the primary hero shelf

src/amo/components/Header/index.js, src/core/components/AuthenticateButton/index.js, src/ui/components/Button/index.js, src/ui/components/DropdownMenuItem/index.js, src/ui/components/DropdownMenuItem/styles.scss, tests/unit/amo/components/TestHeader.js, tests/unit/core/components/TestAuthenticateButton.js, tests/unit/ui/components/TestButton.js, tests/unit/ui/components/TestDropdownMenuItem.js
Fixes https://github.com/mozilla/addons-frontend/issues/7636
---
Given that we have a banner on every page, we can disable the login/logout buttons to avoid weird behaviors. Hopefully this is all we need. I could not think of any other buttons we'd need to "fix".
Authenticate button:
Logout button/link in the dropdown:
A login button in a page (+ HTML title):
=> Disable login/logout buttons

src/amo/components/AddonsCard/index.js, src/amo/components/LandingAddonsCard/index.js, src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss, tests/unit/amo/components/TestAddonsCard.js, tests/unit/amo/components/TestLandingAddonsCard.js, tests/unit/amo/components/TestSearchResult.js
Fixes https://github.com/mozilla/addons-frontend/issues/3134
---
This is a small improvement to the loading state for theme pages. This patch will allow us to do the same thing for search results pages when we are sure that it will only contain themes (but that would be too much work here).
I also improved the contrast of the "notheme" placeholder as seen below (text was white before):
=> Fix theme shelves UI when loading

src/amo/components/SecondaryHero/styles.scss
=> Improve padding on Secondary Hero message

src/amo/components/Categories/index.js, src/core/constants.js, src/core/utils/index.js, src/ui/css/vars.scss, tests/unit/amo/components/TestCategories.js, tests/unit/core/utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/8180
---
Now that we are only using colors for the buttons, we don't need the complicated function to return a color. We can simply have 12 fixed colors and iterate over them.
Colors are now Photon colors.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> Fix category colors

src/amo/components/Categories/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/8823
This is a simple fix to make the list wrapping a bit better.
**Before**
<details>
<summary>Screenshots</summary>
</details>
**After**
<details>
<summary>Screenshots</summary>
</details>
Here are some more examples of wrapping scenarios with the new approach:
<details>
<summary>Screenshots</summary>
</details>
=> Make wrapping category lists look more even

src/amo/components/Categories/styles.scss, src/amo/components/CategoryIcon/styles.scss, src/amo/pages/Home/index.js
fixes https://github.com/mozilla/addons-frontend/issues/8835
---
I updated each `color` attribute instead of using the `index` because I
did not want to introduce a complicated logic to make sure we only use
one of the 12 allowed colors (with `% 12`).
I don't think I precisely reused the colors in the landing pages either.
Does it really matter now that we don't have dedicated pages?
Before:
After:
=> Change the colors for the themes shelf on homepage

src/amo/components/ErrorPage/NotAuthorized/index.js, src/amo/components/ErrorPage/NotFound/index.js, src/amo/components/ErrorPage/ServerError/index.js, src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, src/amo/components/Page/index.js, src/amo/components/Routes/index.js, src/amo/components/StaticPage/index.js, src/amo/components/WrongPlatformWarning/index.js, src/amo/components/WrongPlatformWarning/styles.scss, src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss, src/amo/pages/Home/index.js, src/core/constants.js, src/core/reducers/api.js, src/core/utils/compatibility.js, src/ui/components/Notice/index.js, src/ui/components/Notice/styles.scss, tests/unit/amo/components/TestWrongPlatformWarning.js, tests/unit/amo/pages/TestAddon.js, tests/unit/core/utils/test_compatibility.js
Fixes #8701 
Screenshots:
<details>
<summary>When mistakenly on /android/</summary>
</details>
<details>
<summary>When mistakenly on /firefox/</summary>
</details>
=> Warn AMO users when visiting wrong platform site

package.json, yarn.lock
Reverts mozilla/addons-frontend#8856
Reverting this temporarily because of https://github.com/andreypopp/react-textarea-autosize/issues/253
This breaks the webpack build and thus breaks local development on addons-server
=> Revert "Update dependency react-textarea-autosize to v7.1.1"

src/amo/components/HeroRecommendation/styles.scss
=> Fix site banner alignment with no-image primary hero

src/amo/components/HeroRecommendation/styles.scss, src/amo/components/SecondaryHero/styles.scss, src/core/css/inc/vars.scss
Fixes #8837 
Note that I didn't create new variables in `core/css/inc/vars.scss` for all of the new font sizes because:
1. They are specific sizes currently just being used for these hero elements.
2. They don't necessarily conform with other common sizes on the site, but I believe it is intentional that the home page is starting to diverge from the rest of the site, and that we will eventually update the fonts on the rest of the site to be more in line with Skyline branding.
My thought is that when we undertake more branding work which affects fonts that we might at that time make things more consistent, at which point these sizes might also apply to other elements on the site.
Before:
After:
=> Adjust font sizes, weights and spacing on hero elements

config/dev-amo.js, config/development-amo.js, src/amo/components/InstallWarning/index.js, src/core/components/AMInstallButton/index.js, src/ui/components/Notice/index.js, src/ui/components/Notice/styles.scss, tests/unit/amo/components/TestInstallWarning.js, tests/unit/core/components/TestAMInstallButton.js
Fixes #8760 
~~Depends on #8869~~
Screenshots:
<details>
<summary>For users who will see the "old" warning:</summary>
</details>
<details>
<summary>For users who will see the "new" warning:</summary>
</details>
<details>
<summary>When the "wrong platform warning" would be displayed:</summary>
</details>
=> New A/B test for non-recommended warning

src/amo/components/AddAddonToCollection/styles.scss
fixes #4184
should we be limiting the length of a collection name too?
=> added word-break property to the AddAddonToCollection-added div

src/amo/components/ReportAbuseButton/index.js, tests/unit/amo/components/TestReportAbuseButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/8929
---
This would be a good candidate for cherry-picking.
=> Use FF abuse report panel for extensions and static themes only

config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/components/SearchFilters/index.js, src/amo/components/SectionLinks/index.js, src/amo/pages/SearchTools/index.js, tests/unit/amo/components/TestSearchFilters.js, tests/unit/amo/components/TestSectionLinks.js, tests/unit/amo/pages/TestSearchTools.js
Fixes https://github.com/mozilla/addons-frontend/issues/8679
Fixes https://github.com/mozilla/addons-frontend/issues/8680
---
This patch adds a new feature flag to remove the main access points to the search tools. It also adds a server redirect to handle requests to `/search-tools/`. The `/search-engines/` is handled at the [nginx level](https://github.com/mozilla-services/cloudops-deployment/blob/be40e0b13a1c2a9d4322027e8955647a74753e8e/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L382-L385).
The feature flag is active for local dev and -dev for QA.
=> Remove the main access points to the search tools behind a flag

.circleci/config.yml
The integration-test job runs out of memory, this should help with that.
=> Add circleci config for more memory in containers.

src/amo/components/SectionLinks/index.js, tests/unit/amo/components/TestSectionLinks.js
Fixes https://github.com/mozilla/addons-frontend/issues/8940
---
Before:
After:
=> Do not render 'for Android' section when there is no link

src/amo/components/ReportAbuseButton/index.js, tests/unit/amo/components/TestReportAbuseButton.js
=> Enable abuse reporting via Firefox for static themes

src/core/client/base.js, src/core/tracking.js, tests/unit/core/client/test_base.js, tests/unit/core/test_tracking.js, tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/8647
---
I don't know if we need more but it seems to work locally for me so.. I
looked at various options and it looks like `history.listen()` is both
simple and functional.
=> Log page views for client-side navigation

webpack-common.js
Fixes https://github.com/mozilla/addons-frontend/issues/9000
=> Do not generate es modules by default in file/url loaders

package.json, yarn.lock
This is needed as the `esModule` option has been introduced in version 5.0.2 (5.0.0 used `esModules`).
=> Update file-loader to 5.0.2

src/core/withExperiment.js
Fixes #8957 by making the cookie secure. @psiinon is going to whitelist the cookie to allow it to remain non-httpOnly.
=> Default experiment cookies to secure cookies

tests/ui/tests/test_discopane.py
Fixes #9030
---
Although I am not sure why this test is failing precisely (I did not look at the latest FF changes), I think it does not make much sense to test the discopane built in FF. Before the FF discopane, we were loading an iframe. When this iframe was not present, we displayed a message. I think this is what this test case covers.
=> do not test built-in discopane

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9034 (maybe)
---
I had to re-read https://github.com/mozilla/addons-frontend/issues/8949 to
understand the previous changes, which I reverted because it was hard to
follow. I tried something without really believing in it (the `max-width`
thingy) but it seems to fix both issues so maybe that's what we want? WDYT?
=> Bring back primary hero loading indicators

Dockerfile
Fixes #9074 
---
This patch re-adds two dependencies we need to be able to install Yarn in our Docker images. It needs both dependencies, adding `gnupg` only leads to the following error:
```
Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages
```
Both dependencies were present before the update on the base image so I assume this patch only brings the old behavior back. At least it works..
=> Add gnupg in Dockerfile

src/core/utils/compatibility.js, tests/unit/core/utils/test_compatibility.js, tests/unit/helpers.js
Fixes #9069 
This introduces a helper that identifies Fenix, based on an OS of Android, browser of Firefox, and version of 69 or higher.
It also replaces the logic that previously existed inside `isCompatibleWithUserAgent` with a call to the new `isFenix` function.
=> Create a helper to identify Fenix

src/amo/components/AddonCompatibilityError/index.js, src/amo/components/WrongPlatformWarning/index.js, src/amo/pages/Addon/index.js, tests/unit/amo/components/TestAddonCompatibilityError.js, tests/unit/amo/components/TestWrongPlatformWarning.js
Fixes #9068 
This PR introduces a few changes:
1. The `AddonCompatibilityError`, which is the red warning near the top of the add-on detail card, will no longer be displayed when a user visits the site with Fenix. This is because that warning is being replaced by the `WrongPlatformWarning`. Before screenshot:
2. When visiting the site with Fenix, the `WrongPlatformWarning` will be displayed with a message. This will either be displayed under the install button (on the add-on detail page):
or at the top of the screen:
3. Similar to 2, above, the standard `WrongPlatformWarning`, which displays a warning if you visit the `/android` site with desktop, or the `/firefox` site with Android, will *not* be displayed for Fenix users, as it will be replaced by the new `WrongPlatformWarning` as …
=> Warn AMO users when visiting the site with Fenix

src/ui/components/DropdownMenu/index.js, tests/unit/ui/components/TestDropdownMenu.js
Fixes #8424 
Replace this sentence with a description of how your patch fixes the issue.
The handleClick function is checking if the element is in hover state or not. If it's in hover state and clicked then it set hover state to be `false` and return. Then we again clicked then it then it's checking that state is `false` then drop down state change and hide. That's the reason every time the mouse enters the element and has to clicked twice to close the dropdown.
```
if (this.state.setByHover) {
this.setState({ setByHover: false });
return;
}
```
Just by removing this if condition dropdown works as expected.
=> Fix Dropdown mouse click

src/amo/components/AddonRecommendations/index.js, tests/unit/amo/components/TestAddonRecommendations.js
Fixes #6001
Changes inside?
1. In `ComponentDidUpdate` check, if there is an error then return.
2. In `render` check, if there is an error then render nothing.
=> handled error when recommendation service down

src/amo/components/AddonsCard/styles.scss, src/amo/components/SearchResult/index.js, src/amo/components/SearchResult/styles.scss, tests/unit/amo/components/TestSearchResult.js
Fixes #8724 
Changes inside:
1. Remove Link tag from the title.
2. Change extension-title className from `SearchResult-link` to `SearchResult-title`.
3. Replace className `SearchResult-wrapper` element `div` to `Link` tag.
4.Remove onClick Function on `li` element.
5.Update test cases.
=> Right-click on the extension card area opens the extension page in a new tab

src/amo/components/SearchResult/styles.scss
Fixes #9144 
I also added the dotted outline back (the same as the AMO stage shown in https://github.com/mozilla/addons-frontend/issues/9144#issue-561631860), but not exactly sure if we need that.
Sceenshot
=> Highlight the addon title when focused

src/ui/components/ShowMoreCard/index.js, src/ui/components/UserReview/index.js, src/ui/components/UserReview/styles.scss, tests/unit/ui/components/TestShowMoreCard.js, tests/unit/ui/components/TestUserReview.js
Fixes #6242 
Replace`div` with `ShowMoreCard` inside `UserReview`.
Before:
<div
className={makeClassName('UserReview-body', {
// Add an extra class if the content is an empty string.
'UserReview-emptyBody': !content && !html,
})}
>
{...bodyAttr}
</div>
After:
<ShowMoreCard
id={id}
className={makeClassName('UserReview-body', {
// Add an extra class if the content is an empty string.
'UserReview-emptyBody': !content && !html,
})}
>
<div {...bodyAttr} />
</ShowMoreCard>
=> add collapse text in long add-on reviews

src/amo/components/Footer/styles.scss
Fixes #9197 
This PR fixes the issue #9197. Now all the footer links headers have the same font size. 
_Before:_
_After:_
=> Update footer links headers font-size

src/amo/pages/UserProfile/index.js, tests/unit/amo/pages/TestUserProfile.js
Fixes https://github.com/mozilla/addons-frontend/issues/9203
---
We shouldn't be using the `display_name` attribute so that is why I replaced it with `name`.
=> Fix user name in og:description meta

src/amo/components/AddonAdminLinks/index.js, src/amo/reducers/users.js, src/core/constants.js, tests/unit/amo/components/TestAddonAdminLinks.js, tests/unit/amo/pages/TestUserProfileEdit.js, tests/unit/amo/reducers/test_users.js
Should fix https://github.com/mozilla/addons-frontend/issues/9217
Fixes https://github.com/mozilla/addons-frontend/issues/9219
---
I added two new permissions to make sure we display the reviewer name field for
users with these permissions. Our function to check reviewer permissions is
closer to the one used in addons-server (I believe `STATIC_THEMES_REVIEW` and
`THEMES_REVIEW` are equivalent).
=> Add new reviewer permissions

src/core/addonManager.js, src/core/installAddon.js, tests/unit/core/test_addonManager.js, tests/unit/core/test_installAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/9202
---
It turns out that the `mozAddonManager` never used the `src` query parameter passed in the install URL. Instead, it was always overriding it with the default install source. This patch changes that so that we pass the correct install URL with the right `src` value to the `mozAddonManager`.
=> Make sure mozAddonManager uses the right src query parameter

src/amo/api/blocks.js, src/amo/reducers/blocks.js, tests/unit/amo/api/test_blocks.js
Fixes https://github.com/mozilla/addons-frontend/issues/9231
---
Breaking down things in small pieces to ease the review process. The full branch is [here](https://github.com/mozilla/addons-frontend/tree/blocklist) (if needed). This does not do much yet but it will be used in the next patch.
=> Add api logic to call the blocklist endpoint

src/amo/reducers/blocks.js, src/amo/sagas/blocks.js, src/amo/sagas/index.js, src/amo/store.js, tests/unit/amo/reducers/test_blocks.js, tests/unit/amo/sagas/test_blocks.js, tests/unit/helpers.js
~~:warning: depends on https://github.com/mozilla/addons-frontend/pull/9232~~
Fixes https://github.com/mozilla/addons-frontend/issues/9233
---
Breaking down things in small pieces to ease the review process. The full branch is [here](https://github.com/mozilla/addons-frontend/tree/blocklist) (if needed). This does nothing unless we explicitely call the actions. The UI part (next patch) will rely on this patch.
=> Add reducer and saga to fetch blocks

config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/components/Routes/index.js, src/amo/pages/Block/index.js, src/amo/pages/Block/styles.scss, tests/unit/amo/components/TestRoutes.js, tests/unit/amo/pages/TestBlock.js, tests/unit/helpers.js
~~:warning: depends on https://github.com/mozilla/addons-frontend/pull/9235~~
Fixes https://github.com/mozilla/addons-frontend/issues/9216
---
This patch introduces a new patch to show blocked add-ons (blocks). It is behind a feature flag, only enabled in -dev/local dev.
Screenshots:
=> Add new Block page

src/amo/pages/Block/index.js, src/amo/reducers/blocks.js, tests/unit/amo/pages/TestBlock.js, tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/9249
---
Screenshot:
=> Add add-on name to the `Block` page

src/amo/pages/Block/index.js, tests/unit/amo/pages/TestBlock.js
Fixes #9250 
Changed the text of versions when `min_version` is `0` and `max_version` is `*`.
=> Show "all versions" when a block has min = 0 and max = *

src/ui/components/Notice/styles.scss
Fixes #9281
Fixed the overflow of the text by adding `word-break: break-word` as suggested in the issue.
=> Add style for fixing site notice text overflow

src/amo/components/AddonAuthorLinks/index.js, src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonAuthorLinks.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes:https://github.com/mozilla/addons-frontend/issues/2756
Add contextual link for a developer to manage their add-on
Before:
After:
=> Add contextual link for a developer to manage their add-on

src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9273
---
Before:
After:
=> Fix max content width for the new dev comments card

src/amo/components/SearchForm/index.js, tests/unit/amo/components/TestSearchForm.js
Fixes #9284 
- Updated the SearchForm component by removing the locales in the openSearchTitle localization strings
- Revised test file by removing the expectations that the link titles include the locales
Before:
After:
=> Fix OpenSearch title

src/core/components/AuthenticateButton/index.js, tests/unit/core/components/TestAuthenticateButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/9260
---
This patch slightly changes the behavior of the logout function: before this patch, an error returned by the API would prevent the user to be logged out. Now, it appears to be logged out on the client so that the user can authenticate again.
=> Always logout a signed-in user on the client

src/amo/components/AppBanner/styles.scss
Fixes #8827 
Fixed the inconsistency of spacing in the site notice in mobile view.
=> Fix space inconsistency of site notice in mobile view

src/amo/pages/Block/index.js, tests/unit/amo/pages/TestBlock.js
Fixes #9271
This patch removes HTML tags in _reason_.
=> Remove HTML tags in the reason of a block

config/default.js, src/amo/components/Header/index.js, src/core/client/base.js, src/core/reducers/site.js, src/core/server/base.js, tests/unit/amo/components/TestHeader.js, tests/unit/core/client/test_base.js, tests/unit/core/reducers/test_site.js, tests/unit/core/server/test_base.js
Fixes https://github.com/mozilla/addons-frontend/issues/9283
---
This patch introduces a new configuration parameter: `anoynmousPagePatterns`.
It should contain a list of URL patterns that the server side will check before
a lot of code is executed.
On the server, when an URL matches (in the context of the `amo` app), we will
not load the current user. Instead, we will mark the loaded page as "anonymous".
After that, the client loads and looks at the value of a `site` state prop
in the initial state. This can only be set by the server side. This check
allows us to configure the client side navigation (history/router) so that any
link will force a page reload. This is because for other pages we want to load
the current logged-in user (if any).
=> Introduce anonymous pages

src/amo/components/AddonTitle/index.js, tests/unit/amo/components/TestAddonTitle.js
Fixes https://github.com/mozilla/addons-frontend/issues/9309
=> Add whitespace before 'by' in AddonTitle

src/amo/components/Routes/index.js, src/amo/pages/Block/index.js, tests/unit/amo/components/TestRoutes.js
Fixes https://github.com/mozilla/addons-frontend/issues/9324
---
Test URL: http://localhost:3000/en-US/firefox/blocked-addon/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D/
=> Add support for versionId in blocked page path

src/amo/components/PermissionsCard/index.js, src/amo/components/PermissionsCard/permissions.js, src/ui/components/HostPermissions/index.js, src/ui/components/ShowMoreCard/index.js, src/ui/components/ShowMoreCard/styles.scss, tests/unit/amo/components/TestPermissionUtils.js, tests/unit/ui/components/TestHostPermissions.js, tests/unit/ui/components/TestShowMoreCard.js
Fixes #7634
It looks like `ShowMoreCard` is good for this case. Thanks @willdurand for the suggestion.
In this patch, we
- Changed `Card` to `ShowMoreCard` in `PermssionsCard`, and listed all domains.
- moved all of "Access you data for *"(sites/domains) to the end of the list, so that we do not need to scroll down to see other permissions, especially when there are many sites/domains in this list.
New UI: http://localhost:3000/en-US/firefox/addon/all-of-the-permissionss/
=> Show all domains in the permission list

src/core/components/AMInstallButton/styles.scss, src/ui/components/LoadingText/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9351
---
This patch adds some `prefers-reduced-motion` media queries to disable animations for the following components:
- `AMInstallButton`: see #9351
- `LoadingText`: I am not sure we have an issue for that yet but I think if #9351 is a problem then the animation for this component is also a problem
regular install button:
"puffy" install button:
Loading indicator:
regular install button:
"puffy" install button:
Loading indicator:
=> Respect prefers-reduced-motion: reduce

src/core/components/AMInstallButton/index.js, src/core/constants.js, stories/core/AMInstallButton.js, stories/index.js, stories/setup/styles.scss, tests/unit/core/components/TestAMInstallButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/9355
---
This patch adds a new story in our storybook and...
- fixes a duplicate constant entry
- adds support for the `DISABLING` state
You can try this patch by fetching the branch and running `yarn && yarn storybook` locally.
=> Add story for AMInstallButton

src/amo/components/InstallButtonWrapper/index.js, src/core/components/AMInstallButton/index.js, src/core/installAddon.js, src/core/reducers/installations.js, src/disco/components/Addon/index.js, stories/core/AMInstallButton.js, tests/unit/amo/components/TestInstallButtonWrapper.js, tests/unit/core/components/TestAMInstallButton.js, tests/unit/core/reducers/test_installations.js, tests/unit/core/test_installAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/8418
~~⚠️ depends on #9356 so only the third commit is relevant~~
---
In order to test this patch locally, follow these steps (not the usual setup because `mozAddonManager` is required): https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#developing-with-a-local-https-server-recommended, and then follow these other steps to create a `policies.json` file: https://github.com/mozilla/addons-frontend/issues/8418#issuecomment-603903349
It's a bit annoying but you have to restart FF after you created the `policies.json` file... The nice thing is that browsing `about:policies` will tell you if everything works as intended or not.
=> Honor `canUninstall` prop

src/core/addonManager.js, src/core/constants.js, tests/unit/core/test_addonManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/9365
---
We listen to some global FF events to react accordingly when an add-on is installed, enabled, disabled, uninstalled, etc. This is handled in the `App` component [here](https://github.com/mozilla/addons-frontend/blob/f34b0d0efdbca225a07d5ff8e7abdb6cd2b3350e/src/amo/components/App/index.js#L95) and [here](https://github.com/mozilla/addons-frontend/blob/f34b0d0efdbca225a07d5ff8e7abdb6cd2b3350e/src/amo/components/App/index.js#L233-L235). The `_addChangeListeners` function is actually defined [here](https://github.com/mozilla/addons-frontend/blob/f34b0d0efdbca225a07d5ff8e7abdb6cd2b3350e/src/core/addonManager.js#L205).
In this patch, we read the `canUninstall` value of a Firefox add-on when possible so that the install button is …
=> Read canUninstall when we can in global event listener

bin/run-l10n-extraction, docs/i18n.md
Fixes https://github.com/mozilla/addons-frontend/issues/9373
---
The script handles both 'amo' and 'disco' apps. It takes care of ensuring the `master` branch is up-to-date before creating a specific branch for the extraction and it detects no changes. The push hero should only run the script once and it will create between 0 and 2 branches on GitHub. The script gives the links to these branches (if any) to open the pull requests.
=> Add script to do the l10n extraction

bin/run-l10n-extraction
This is a small improvement to be able to run the extraction for both amo and disco, all the time. Previously, no changes for amo would stop the script and skip the extraction of the disco locales.
=> Do not exit when there are no changes

src/core/sagas/site.js, tests/unit/core/sagas/test_site.js, tests/unit/core/server/test_base.js
Refs https://github.com/mozilla/addons-frontend/issues/9419
---
This was not a good idea apparently, and https://redux-saga.js.org/docs/api/ describes why. Site status is useful but not critical I believe so we can simply ignore the error and log it.
There is also this action that has a similar behavior: https://github.com/mozilla/addons-frontend/blob/028800baa6801d39a0d43a7cd580aab0da116cbe/src/amo/sagas/users.js#L43-L59
It is less likely to cause an OOM because it requires authenticated calls. For this one, it is more important to fail for the reasons in the comment.
=> Do not let saga throw

src/amo/components/App/styles.scss, src/amo/components/HeroRecommendation/styles.scss, src/amo/components/SearchResult/styles.scss, src/amo/components/SecondaryHero/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9433
Fixes https://github.com/mozilla/addons-frontend/issues/9432
Fixes https://github.com/mozilla/addons-frontend/issues/9436
---
Given the regressions mentioned in the issues above, I think we should use
`anywhere` all the time because `break-word` seems to only work when the
container has a well-defined width while `anywhere` will work in all cases.
=> Use overflow-wrap: anywhere, everywhere

src/amo/components/AddonSummaryCard/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9436
---
The `min-width` causes the flex layout to "push" the right panel to the right
because `330px` was more than `35%` and the right panel is configured to take
`65%` of the width. It looks good without `min-width` so I guess it's fine.
=> Remove min-width in AddonSummaryCard

src/amo/components/AddonMeta/index.js, src/amo/components/SearchResult/index.js, tests/unit/amo/components/TestAddonMeta.js, tests/unit/amo/components/TestSearchResult.js
Fixes https://github.com/mozilla/addons-frontend/issues/9472
---
I did not use a feature flag because I think we'll make the addons-server changes in the same tag: the only problem if this does not happen is that we'll see "Downloads" for a number of users instead of a number of actual downloads (the addons-server changes being about updating `average_daily_users` with download data instead of usage data)
=> Use the term Downloads instead of Users for dictionaries and langpacks

src/amo/reducers/users.js, src/amo/sagas/users.js, src/core/components/SiteNotices/index.js, src/core/server/base.js, tests/unit/amo/reducers/test_users.js, tests/unit/amo/sagas/test_users.js, tests/unit/core/components/TestSiteNotices.js, tests/unit/core/server/test_base.js
Fixes https://github.com/mozilla/addons-frontend/issues/9482
---
This patch should fix the issue above. In addition, we also show the notice when a user logs out manually. I find this behavior more consistent. It will require two location changes to make the message disappear in this specific case but I think that's fine.
I tried this patch by editing my auth cookie value (putting random chars to make it invalid).
=> Handle 401s on the server and show a message when user is logged out

src/core/server/base.js, tests/unit/core/server/test_base.js
Fixes https://github.com/mozilla/addons-frontend/issues/9490
Fixes https://github.com/mozilla/addons-frontend/issues/9491
---
This should make sure the cookie is deleted in the browser.
It won't fix the 404 I think because in some cases, we send API requests in parallel.
=> Pass options when removing auth cookie

bin/run-l10n-extraction
Fixes https://github.com/mozilla/addons-frontend/issues/9430
---
I slightly changed the approach but the goal remains the same. We see this in the console now:
```
❯ ./bin/run-l10n-extraction
INFO: Starting l10n extraction for: amo
From github.com:mozilla/addons-frontend
* branch                master     -> FETCH_HEAD
Successfully rebased and updated refs/heads/master.
INFO: Creating and switching to branch 'amo-locales'
Switched to a new branch 'amo-locales'
INFO: Extracting locales (this can take several minutes)
INFO: No locale changes for amo, aborting
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1 commit.
(use "git push" to publish your local commits)
Deleted branch amo-locales (was 1cbfce59a).
INFO: Starting l10n extraction for: disco
From …
```
=> Log output to a file, show important information only on the console

src/amo/components/PermissionsCard/index.js, src/amo/components/PermissionsCard/permissions.js, src/amo/components/PermissionsCard/styles.scss, src/core/reducers/versions.js, tests/unit/amo/components/TestPermissionUtils.js, tests/unit/amo/components/TestPermissionsCard.js, tests/unit/helpers.js
Fixes #9542 
Here's what it looks like:
I noticed a visual bug here, but it's not a regression. It seems to exist on prod as well. The bottom of the permissions box doesn't have rounded corners. I'll file a separate issue for that.
=> Display optional permissions

config/default-disco.js, config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/components/AddonMeta/index.js, src/amo/components/AddonMoreInfo/index.js, src/amo/components/AddonReviewCard/index.js, src/amo/components/AddonSummaryCard/index.js, src/amo/components/AddonTitle/index.js, src/amo/components/Footer/index.js, src/amo/components/RatingsByStar/index.js, src/amo/components/SearchResult/index.js, src/amo/pages/Addon/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/reducers/reviews.js, src/amo/utils/index.js, src/core/constants.js, src/core/utils/url.js, tests/unit/amo/components/TestAddonMeta.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/components/TestAddonSummaryCard.js, tests/unit/amo/components/TestAddonTitle.js, tests/unit/amo/components/TestFooter.js, tests/unit/amo/components/TestRatingsByStar.js, tests/unit/amo/components/TestSearchResult.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/core/utils/test_url.js
Fixes https://github.com/mozilla/addons-frontend/issues/9547
---
This patch adds a feature flag to enable two features:
1. replaces `src` query parameter with UTM parameters (two params have a fixed value, and `src` becomes `utm_content`)
2. makes sure to set UTM parameters (when available) to all links for the same add-on, similar to what we do for `src`
It's tricky to split this patch in two because both "features" are interleaved. Most components have full coverage with all possible edge cases I think, but it's possible that some don't have all possible test cases. It's already quite a big patch.
The sooner we land this in -dev, the more time QA will have to verify all possible scenarios (which I'll add in the issue). I checked locally and I could not see any problem with the feature …
=> Replace src query parameter with UTM params (controlled by a feature flag)

renovate.json
I think this would avoid further breakage given that both should be kept in sync (based on the two recent PRs we have).
=> Add a new group for history deps in renovate config

src/amo/components/AddonAdminLinks/index.js, tests/unit/amo/components/TestAddonAdminLinks.js
Fixes #9578 
I have removed the code for this link from the component.
https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94,
=> Link Removed (Fixes #9578)

src/amo/components/AddonBadges/index.js, src/amo/components/AutoSearchInput/index.js, src/amo/components/CollectionAddAddon/index.js, src/amo/components/GuidesAddonCard/index.js, src/amo/components/InstallWarning/index.js, src/amo/components/SearchForm/index.js, src/amo/components/SearchResult/index.js, src/core/constants.js, src/core/reducers/addons.js, src/core/reducers/autocomplete.js, src/core/types/addons.js, tests/unit/amo/components/TestAddonBadges.js, tests/unit/amo/components/TestAutoSearchInput.js, tests/unit/amo/components/TestGuidesAddonCard.js, tests/unit/amo/components/TestInstallWarning.js, tests/unit/amo/components/TestSearchResult.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/reducers/test_autocomplete.js, tests/unit/helpers.js
Fixes #9579 
This removes the use of `is_recommended` from the API response, and uses `promoted` instead. To keep this patch simple, I've kept an internal `isRecommended` property for the `Addon` type, which is now based on the contents of `promoted`. This also makes `promoted` available in the `Addon` object so it can be used in the future when we start to support other categories.
=> Use `promoted` from the API response in place of `is_recommended`

config/default.js, config/dev-amo.js, config/development-amo.js, src/amo/pages/Home/index.js, src/amo/sagas/home.js, src/core/api/search.js, src/core/constants.js, src/core/searchUtils.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/sagas/test_home.js
=> Add the Promoted add-ons shelf to the home page

src/amo/components/AddonVersionCard/index.js, src/amo/components/InstallButtonWrapper/index.js, src/amo/pages/Addon/index.js, src/core/addonManager.js, src/core/components/AMInstallButton/index.js, src/core/installAddon.js, src/core/utils/compatibility.js, src/disco/components/Addon/index.js, src/disco/pages/DiscoPane/index.js, stories/core/AMInstallButton.js, tests/unit/amo/components/TestInstallButtonWrapper.js, tests/unit/core/components/TestAMInstallButton.js, tests/unit/core/test_addonManager.js, tests/unit/core/test_installAddon.js, tests/unit/disco/components/TestAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/9556
---
We don't want to use `?src=` anymore and FF tracks attribution using UTM params in the url of the page itself nowadays.
=> Stop passing an install source/`src` param to Addon Manager

config/default.js, src/amo/pages/Addon/index.js, src/core/utils/compatibility.js, tests/unit/amo/pages/TestAddon.js, tests/unit/core/utils/test_compatibility.js
Fixes #9360 
With an incompatible add-on:
With a compatible add-on:
=> Change mobile compatibility message for add-ons in Fenix collections

src/amo/components/InstallWarning/index.js, src/amo/components/PromotedAddonsCard/index.js, src/amo/constants.js, src/amo/utils/index.js, src/ui/components/PromotedBadge/index.js, tests/unit/amo/components/TestInstallWarning.js, tests/unit/amo/components/TestPromotedAddonsCard.js, tests/unit/amo/utils/test_index.js, tests/unit/ui/components/TestPromotedBadge.js
Fixes #9622 
Also removes the gate for the installWarning new message.
This needs to be cherry-picked for this week's push.
=> Update the URL for the promoted badges/shelf

tests/frontend/ui/pages/desktop/base.py
Seems the search suggestion list loads blank and then loads actual suggestions. This change should make sure the tests wait until the named suggestions load.
=> Change search suggestion locator for integration tests.

src/amo/components/PromotedAddonsCard/index.js, tests/unit/amo/components/TestPromotedAddonsCard.js
=> Hide the promoted add-ons shelf if there are no add-ons

.stylelintrc, src/amo/components/AddonTitle/index.js, src/amo/components/Categories/index.js, src/amo/components/RatingsByStar/index.js, src/amo/components/SearchResult/index.js, src/amo/components/SearchSuggestion/index.js, src/amo/components/SecondaryHero/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/UsersUnsubscribe/index.js, src/ui/components/LoadingText/index.js, src/ui/components/LoadingText/styles.scss, tests/unit/amo/pages/TestAddon.js, tests/unit/ui/components/TestLoadingText.js
Fixes #9511 
This should fix the csp errors by removing the inline styles. It also eliminates the `range` option to `LoadingText`, but I don't think we really needed that. I visually verified the elements that would have been affected, and their loading skeletons seem fine to me.
=> Removing inline styles from LoadingText

src/core/reducers/addons.js, src/core/reducers/versions.js, src/core/sagas/addons.js, src/disco/sagas/disco.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestAddonInfo.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/pages/TestAddonVersions.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/reducers/test_versions.js, tests/unit/core/sagas/test_addons.js, tests/unit/disco/helpers.js, tests/unit/disco/sagas/test_disco.js
This is needed to implement a fix for https://github.com/mozilla/addons-frontend/issues/9692
=> Rename loadAddonResults to loadAddon

src/amo/components/PromotedAddonsCard/index.js, src/amo/pages/Home/index.js, stories/amo/PromotedAddonsCard.js, tests/unit/amo/components/TestPromotedAddonsCard.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/reducers/test_home.js, tests/unit/helpers.js
Fixes #9737 
This prevents the double-render of the `PromotedAddonsCard`, which was causing two sets of events to be dispatched. We're still not sure why this issue only appears with SSR, but this is an acceptable fix for the problem.
I am going to expand on this to move the logic to fetch the `addons` into the `PromotedAddonsCard` as well, but that can be done in a follow-up.
=> Prevent re-render of PromotedAddonsCard

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, tests/unit/amo/components/TestHeroRecommendation.js
Depends on https://github.com/mozilla/addons-server/issues/15741
Fixes #9764 
Note that this mustn't land before https://github.com/mozilla/addons-server/issues/15741 is fixed. I'll mark it as "do not merge".
=> Support non-Recommended extensions in the Primary Hero area

.github/stale.yml
Removes the `contrib:welcome` label from stalebot exclusions.
=> Remove contrib:welcome stalebot exclusion

src/amo/components/AddonAdminLinks/index.js, src/amo/components/AddonReviewCard/index.js, src/amo/pages/UserProfile/index.js, src/amo/reducers/users.js, src/core/constants.js, tests/unit/amo/components/TestAddonAdminLinks.js, tests/unit/amo/components/TestHeader.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/pages/TestUserProfileEdit.js, tests/unit/amo/reducers/test_users.js
Fixes #9788.
This patch removes obsolete permissions and adapts related permission checks.
=> Remove obsolete permissions

tests/smoke/docker-compose.functional-tests.yml, tests/smoke/setup_docker.sh
Looks like a docker file in a different folder was used for the smoke tests. This only runs on circle-ci.
=> Fix smoke tests

src/ui/components/DismissibleTextForm/index.js, tests/unit/ui/components/TestDismissibleTextForm.js
Fixes #9718
Added a simple trim so whitespaces doesn't enable the update button.
=> Disables update button when updated with whitespaces 

.travis.yml, README.md, bin/build-checks.js, bin/build-locales, bin/create-locales, bin/merge-locales, bin/run-l10n-extraction, bin/server.js, config/default.js, config/development.js, config/test.js, docs/i18n.md, docs/index.md, docs/moz-addon-manager.md, package.json, src/core/components/ServerHtml/index.js, src/core/server/base.js, tests/__fixtures__/loadable-stats.json, tests/unit/core/components/TestServerHtml.js, tests/unit/core/middleware/test_cspMiddleware.js, tests/unit/core/middleware/test_frameguardMiddleware.js, tests/unit/core/server/test_base.js, tests/unit/test_frameGuardConfig.js, tests/unit/test_prefixConfig.js, webpack.dev.config.babel.js, webpack.l10n.config.babel.js, webpack.prod.config.babel.js
Fixes #9807 
Depends on ~~https://github.com/mozilla/addons-frontend/issues/9832~~
Something is not quite right with the way the `config` is being built. It looks like, when `amo:dev` is run, it's picking up `development.js` instead of `development-amo.js`, but I can't seem to locate the code that is controlling that.
Other than that I think these changes are working. Note that it's not possible to test `run-l10n-extraction` without first hacking it to prevent it from switching to `master`, because after it switches to master, it runs the wrong versions of the script.
I think more testing is needed, but first I need to figure out how to fix the `config` issue discussed above.
=> Get rid of the `NODE_APP_INSTANCE` env var requirement, and some code that is needed for multiple apps

src/amo/constants.js, src/amo/pages/Home/index.js, src/amo/pages/Home/styles.scss, src/amo/reducers/home.js, src/amo/sagas/home.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/reducers/test_home.js, tests/unit/amo/sagas/test_home.js
Fixes #9863 
This change creates separate logic for retrieving and loading data for the home page for the desktop site vs. the mobile site. This is something we've been thinking about doing, and this was an ideal opportunity to do it. This means that, when visiting the mobile home page, the browser will only make 2 API requests, which is all the data it needs, whereas for the desktop home page it makes several API requests.
This involved adding a new function into the reducer, to load data for the mobile home page, as well as to add a param to indicate if we're fetching data for the desktop or mobile site. I also required changes to the saga to call different APIs for each case.
=> Show more Recommended add-ons in the Android homepage

bin/build-checks.js, bin/build-locales, bin/create-locales, bin/merge-locales, bin/proxy.js, bin/server.js, config/default.js, src/core/client/base.js, src/core/components/ServerHtml/index.js, src/core/constants.js, src/core/logger.js, src/core/server/base.js, src/core/utils/sentry.js, tests/unit/core/client/test_base.js, tests/unit/core/components/TestServerHtml.js, tests/unit/core/utils/test_sentry.js, webpack-common.js, webpack.dev.config.babel.js, webpack.l10n.config.babel.js, webpack.prod.config.babel.js
Fixes #9840 
This is the next step towards eliminating the multiple-app logic for AMO and eventually combining `amo` and `core`. It does away with the `appName` config variable, and replaces it with a constant for now. Eventually we can probably get rid of much of the code that now uses `APP_NAME`, but I wanted to take this in small steps. I've tested locally and everything seem to work.
=> Do away with appName

src/amo/api/hero.js, src/amo/api/shelves.js, src/amo/components/AddonMoreInfo/index.js, src/amo/components/ContributeCard/index.js, src/amo/pages/Block/index.js, src/amo/reducers/blocks.js, src/amo/reducers/home.js, src/core/api/index.js, src/core/reducers/addons.js, src/core/types/addons.js, src/core/types/api.js, src/core/utils/index.js, tests/unit/amo/api/test_hero.js, tests/unit/amo/api/test_shelves.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/components/TestContributeCard.js, tests/unit/amo/components/TestSecondaryHero.js, tests/unit/amo/pages/TestBlock.js, tests/unit/core/api/test_index.js, tests/unit/core/reducers/test_addons.js, tests/unit/core/utils/test_index.js, tests/unit/helpers.js
fixes #9911 - I hope!
Currently we're only using either url _or_ outgoing so I didn't think I needed to add any new tests, but to be able to implement https://github.com/mozilla/addons-frontend/issues/3580 I thought it easiest store both in the internal models now (rather than throw one away in the reducers).
=> handle urls is an object with url & outgoing; drop wrap_outgoing

config/custom-environment-variables.json, config/development-local.js
We're already using 6000 in code-manager, I guess for the same reasons? In short, `4000` is "reserved" for production and configured in our `Dockerfile`. It's annoying because it creates conflicts when we want to use Docker images.
5000 is used by code-manager.
=> Set local ports to 700x because 400x is used for production

src/amo/components/CollectionDetails/index.js, src/ui/components/UserCollection/index.js, tests/unit/amo/components/TestCollectionDetails.js, tests/unit/ui/components/TestUserCollection.js
Fixes #9977
Note that the repetition of the string (in this case "(no name)") in two templates is required to allow for l10n support.
=> Deal with collections with null names

src/amo/components/UserProfileEditPicture/index.js, src/ui/components/Button/index.js, src/ui/components/ConfirmButton/index.js, tests/unit/amo/components/TestUserProfileEditPicture.js, tests/unit/ui/components/TestButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/9493
=> Prevent UserProfileEditPicture to be triggered when submitting the form with enter

src/amo/components/AddAddonToCollection/index.js, src/amo/components/CollectionDetails/index.js, src/amo/components/UserCollection/index.js, src/amo/pages/Collection/index.js, src/amo/reducers/collections.js, tests/unit/amo/components/TestAddAddonToCollection.js, tests/unit/amo/components/TestCollectionDetails.js, tests/unit/amo/components/TestUserCollection.js, tests/unit/amo/pages/TestCollection.js, tests/unit/amo/reducers/test_collections.js
=> Display "(no name)" for collections with missing names in AddAddonToCollection

docs/fenix.md, docs/index.md
Fixes https://github.com/mozilla/addons-frontend/issues/10022
---
I added a new section in our docs to explain how to build a Fenix custom build targetting a specific AMO env.
=> Add docs about Fenix custom builds

package.json, yarn.lock
This reverts commit 169816984c729392fb0ca30026128d8a7aba842a.
Fixes https://github.com/mozilla/addons-frontend/issues/10059
=> Revert "Update dependency @loadable/server to v5.14.2 (#10035)"

src/amo/languages.js
This locale (Silesian, native Ślōnski) is going to ride the trains with Firefox 87 to Beta, so we'll have a language pack for it.
=> Add Silesian (szl) to supported languages

config/default.js, config/dev.js, package.json, src/amo/tracking.js, tests/unit/amo/test_tracking.js, yarn.lock
fixes #10041
---
This patch uses the web-vitals js lib to record the 3 most useful web vitals metrics and push the data to GA.
I used this patch to try it locally (with Chrome):
```diff
diff --git a/config/development.js b/config/development.js
index 2e2b0ea40..9e371b30b 100644
--- a/config/development.js
+++ b/config/development.js
@@ -21,7 +21,8 @@ module.exports = {
restrictSearchResultsToAppVersion: false,
fxaConfig: 'local',
-  trackingEnabled: false,
+  trackingEnabled: true,
+  trackingSendWebVitals: true,
loggingLevel: 'debug',
amoCDN: addonsServerDevCDN,
```
The patch enables this feature for -dev only right now. Once I have some stats collected on -dev (mainly by myself). I'll double check GA, the Web Vitals dashboard and, if everything looks good, I'll update the config to …
=> Collect web-vitals whenever possible

src/amo/pages/LanguageTools/index.js, tests/unit/amo/pages/TestLanguageTools.js
Fixes https://github.com/mozilla/addons-frontend/issues/10071
---
I am not sure we can have locales with more than 3 parts so I kept things quite restricted for now.
=> Allow target locales with 3 parts

config/default.js, config/dev.js
Fixes https://github.com/mozilla/addons-frontend/issues/10070
---
We did collect some data on -dev but it's a bit tricky to make good use of it
because we don't have enough data. Let's enable this feature in all envs and
see what we get on -prod in a week.
=> Enable web vitals collection in all envs

src/amo/actions/reviews.js, src/amo/api/index.js, src/amo/api/reviews.js, src/amo/components/RatingsByStar/index.js, src/amo/pages/Addon/index.js, src/amo/pages/AddonInfo/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/AddonVersions/index.js, src/amo/reducers/addons.js, src/amo/reducers/reviews.js, src/amo/sagas/addons.js, src/amo/sagas/reviews.js, src/amo/types/addons.js, tests/unit/amo/api/test_index.js, tests/unit/amo/api/test_reviews.js, tests/unit/amo/components/TestRatingsByStar.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestAddonInfo.js, tests/unit/amo/pages/TestAddonReviewList.js, tests/unit/amo/pages/TestAddonVersions.js, tests/unit/amo/reducers/test_addons.js, tests/unit/amo/reducers/test_reviews.js, tests/unit/amo/sagas/test_addons.js, tests/unit/amo/sagas/test_reviews.js, tests/unit/helpers.js
Fixes #10074 
This is a bit more involved because we are changing the way we store grouped ratings. Previous to this patch, because we were retrieving them separately from add-on details, we stored the grouped ratings separately, in the `reviews` state. This patch removes all of the code that supported fetching them separately and storing them in the `reviews` state and instead will always retrieve them with the add-on details and store them in the `addons` state with the add-on itself.
=> Fetch grouped ratings along with add-on detail

src/amo/components/AddonsCard/index.js, src/amo/components/SearchResult/index.js, src/amo/components/SearchResults/index.js, src/amo/components/ThemeImage/index.js, src/amo/imageUtils.js, tests/unit/amo/components/TestAddonsCard.js, tests/unit/amo/components/TestSearchResult.js, tests/unit/amo/components/TestSearchResults.js, tests/unit/amo/components/TestThemeImage.js, tests/unit/amo/test_imageUtils.js
fixes #10095 - the saving isn't massive (this is the /themes/ page), but it's something for free.  If we reduce the thumbnail down to the size frontend actually displays we'll save a bit more (that'd be an addons-server change)
=> use thumbnails for small theme previews

.browserslistrc, tests/unit/amo/components/Errors/TestNotAuthorized.js, tests/unit/amo/components/Errors/TestServerError.js, tests/unit/amo/components/TestCategories.js, tests/unit/amo/components/TestSuggestedPages.js
Fixes https://github.com/mozilla/addons-frontend/issues/10171
---
According to bundlesize, js bundle size goes from `435.43KB` to `384.98KB`. IE isn't very used these days (according to various marketshare websites). It's the 18th browser on GA production over the last 12 months (13K users, SeaMonkey had 33K fwiw)
=> Update browserslist config to exclude IE <= 11

src/amo/components/AddonReviewCard/styles.scss, src/amo/components/FlagReviewMenu/index.js, src/amo/components/TooltipMenu/index.js, tests/unit/amo/components/TestFlagReviewMenu.js, tests/unit/amo/components/TestTooltipMenu.js
=> Fix wrapping of Flagged notice

config/default.js, src/amo/middleware/datadogTiming.js, src/amo/middleware/index.js, src/amo/middleware/responseTime.js, src/amo/server/base.js, tests/unit/amo/middleware/test_datadogTiming.js, tests/unit/amo/middleware/test_responseTime.js
Fixes #10202
---
I also renamed the middleware because we aren't using datadog anymore. Config remains the same because it's configured elsewhere.
=> Update timing middleware to output time in logs

src/amo/withExperiment.js, tests/unit/amo/test_withExperiment.js
Fixes #9137 
This fixes #9137 in the most basic way, ensuring that a runtime exception will be thrown if an invalidly formatted `experimentId` is encountered, which is likely good enough, but it won't catch this when the tests are run in development. It also won't catch a case where more than one experiment is defined with the same `experimentId`.
If we want to test for both of those, we could put all `experimentId`s into a single config key, and then we can write a test which checks the config both for formatting and for uniqueness.
@willdurand What do you think of that approach? It could be done as a separate follow-up patch to this.
=> Enforce naming convention for experiment ids

webpack.dev.config.babel.js, webpack.prod.config.babel.js
=> Use webpack's contenthash instead of chunkhash for better long-term caching

src/amo/middleware/responseTime.js
Fixes https://github.com/mozilla/addons-frontend/issues/10235
=> Use .debug() for responseTime log statements

src/amo/components/ScreenShots/index.js, src/amo/components/SearchResult/index.js, tests/unit/amo/components/TestScreenShots.js, tests/unit/amo/components/TestSearchResult.js
Fixes https://github.com/mozilla/addons-frontend/issues/10266
We will investigate a more subtle approach but for now it's not clear it improves things since it delays the initial loading of images that are in the viewport as well.
=> Revert lazy loading of images on extension detail page and theme search results

src/amo/components/Header/index.js, src/amo/components/Header/styles.scss, src/amo/components/SectionLinks/styles.scss, tests/unit/amo/components/TestHeader.js
Fixes #10254 
This fixes the wrapping of the navigation links at `500px` and `900px`, as well as an issue with the "More..." menu.
<details>
<summary>At `500px`</summary>
Before:
After:
</details>
<details>
<summary>At `900px`</summary>
Before:
After:
</details>
=> Make more space for the navigation links at smaller screen resolutions

package.json, webpack-common.js
Fixes #10111
---
Gzipped sizes:
- Before: 62KB
- After: 36KB
There are still a few images inlined (5 I think) because they are under 1KB.
It's probably fine for now, the new CSS bundle size is rather small.
=> Do not inline most of the media files in the CSS bundle

src/amo/api/homeShelves.js, src/amo/components/HomepageShelves/index.js, src/amo/components/LandingAddonsCard/index.js, src/amo/components/SecondaryHero/index.js, src/amo/pages/Collection/index.js, src/amo/pages/Home/index.js, src/amo/reducers/home.js, src/amo/reducers/versions.js, src/amo/sagas/home.js, tests/unit/amo/api/test_homeShelves.js, tests/unit/amo/components/TestHeroRecommendation.js, tests/unit/amo/components/TestHomepageShelves.js, tests/unit/amo/components/TestLandingAddonsCard.js, tests/unit/amo/components/TestSecondaryHero.js, tests/unit/amo/pages/TestCollection.js, tests/unit/amo/pages/TestHome.js, tests/unit/amo/reducers/test_home.js, tests/unit/amo/reducers/test_versions.js, tests/unit/amo/sagas/test_home.js, tests/unit/helpers.js
Fixes #9996 
Per #10065, this pull request was rebased on top of the current master and has the same commits to see what codecov generates.
In addition, this pull request includes the following updates:
- `tests/unit/helpers.js` - adds default value of `[fakeShelf]` to param `resultsProps`
- `tests/unit/amo/sagas/test_home.js` - updates `baseArgs` to `baseApiArgs`
- `components/HomepageShelves/index.js` - updates className from `Home-HomepageShelves` to just `HomepageShelves`, and adds a comment to explain displaying 3 loading shelves
@willdurand, @bobsilverberg - Please review when you have a moment. Thank you!
=> RE: Update - Consolidate API requests for the home page shelves

.circleci/config.yml, README.md, bin/create-package-json-for-blog-utils, package.json, src/blog-utils/index.js, src/blog-utils/styles.scss, src/blog-utils/tracking.js, tests/unit/blog-utils/test_index.js, webpack.blog-utils.config.babel.js
Fixes #10293
---
This is the first step to build the `addons-frontend-blog-utils` library. It
provides the webpack config, the commands, and some tests. Only the code to
build and expose the HTML of the footer is bundled so far since it makes this
patch smaller.
The next steps will be:
1. release npm packages
2. expose a function to render a static add-on card
=> Introduce addons-frontend-blog-utils library

README.md, bin/serve-blog-utils, package.json, src/blog-utils/StaticAddonCard/index.js, src/blog-utils/StaticAddonCard/styles.scss, src/blog-utils/index.html, src/blog-utils/index.js, src/blog-utils/styles.scss, tests/unit/blog-utils/TestStaticAddonCard.js, tests/unit/blog-utils/test_index.js
Fixes #10297 
---
This patch adds a new function to the `blog-utils` library, which allows to build static add-on cards (for the blog). The `dev` command for this library will start a small server to serve an HTML page for development purposes.
I'll add the rest of the UI (ratings, number of users) in a different patch. Same for the cosmetic changes to have the same look&feel as in the mocks (which weren't finalized at the time of writing).
Note: buttons are blue now
=> Add `buildStaticAddonCard()` to `addons-frontend-blog-utils`

src/amo/pages/SearchTools/index.js, tests/unit/amo/pages/TestSearchTools.js
Fixes #9248 
Returns `NotFoundPage` if the server redirect fails in the `SearchToolsBase` constructor. As described in the issue, this is replicated locally when `disableSSR: true` is set in `config/default.js`. 
Before:
After:
=> Update `SearchTools` page component

src/amo/components/Header/styles.scss
Fixes #10328 
I increased the font size and also removed the diminished font-weight, so it now matches the two external links exactly.
Before:
After:
=> Increase font for Register or log in button

src/amo/pages/Collection/index.js, tests/unit/amo/pages/TestCollection.js
Collection page displays add-on results in a wide layout similar to search, so we want the full size theme preview and not the small thumbnail.
Fixes #10326
=> Render full size theme preview in collection page

src/blog-utils/StaticAddonCard/index.js, src/blog-utils/StaticAddonCard/styles.scss, tests/unit/blog-utils/TestStaticAddonCard.js
Fixes #10338
---
Note: some of the style has been updated to look more like the latest mocks. This isn't strictly compliant with the mocks but it is consistent with the AMO frontend.
=> Add ADU + ratings to the StaticAddonCard

src/blog-utils/StaticAddonCard/index.js, src/blog-utils/StaticAddonCard/styles.scss, tests/unit/blog-utils/TestStaticAddonCard.js
=> Use new download button version in StaticAddonCard (blog-utils)

src/amo/components/App/styles.scss
=> Add overflow-wrap: break-word for Safari

src/amo/components/Header/index.js, src/amo/components/SectionLinks/index.js, src/amo/components/SectionLinks/styles.scss, src/blog-utils/index.html, src/blog-utils/index.js, tests/unit/amo/components/TestHeader.js, tests/unit/amo/components/TestSectionLinks.js, tests/unit/blog-utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/10382
---
For some reasons, there is an issue with the "more..." dropdown and I don't know how to fix it. I think it's fine to hide it for now, we'll see with Product/UX later.
The dev page looks like this now:
=> Expose Header in blog-utils library

config/dev.js, src/amo/withExperiment.js, tests/unit/amo/test_withExperiment.js
Fixes #10188 and re-enables the experiment on dev
=> Only set an experiment cookie and send an enrollment event on the client

src/amo/components/GetFirefoxButton/styles.scss
=> Prevent callout icon from being cropped

src/amo/middleware/prefixMiddleware.js, tests/unit/amo/middleware/test_prefixMiddleware.js
fixes #10308 
This is a rewrite of `prefixMiddleware`, mostly, so it's probably easier to compare logically how it works, rather than line by line diff.
The main change is to "fix" the url parts first by _always_ adding the locale and clientApp (e.g. "en-US" and "firefox"), so when when we test the exceptions, and drop locale and/or app as necessary we don't have to worry about what the parts being in the wrong place.
Tests pass (though if you have any ideas for other potential problem urls, I can add new ones) - I changed two because now the code doesn't redirect urls that are external (e.g. addons-server) to add locale or clientApp to the url, it would let them 404 and be dealt with upstream instead.  (to me that seemed to make sense anyway).
=> rewrite prefixMiddleware

src/amo/components/LandingAddonsCard/index.js, tests/unit/amo/components/TestLandingAddonsCard.js
Fixes #9996 
`footer_pathname` supports external URLs, which currently opens in the same tab. However, these URLs should have the same behavior as URLs in the secondary hero shelf (the page opens in a new tab).
This pull request updates the `LandingAddonsCard` component and its test.
@bobsilverberg, please review when you have a moment. Thank you!
=> Open homepage shelf's footer_pathname URLs in a new tab

src/amo/components/Header/index.js, src/amo/components/SectionLinks/index.js, src/blog-utils/index.js, tests/unit/amo/components/TestHeader.js, tests/unit/amo/components/TestSectionLinks.js, tests/unit/blog-utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/10406
---
I renamed the special prop in the first commit because I find it a bit easier to read when used.
=> Do not prepend clientApp/locale in URLs of the Header when rendered for the blog

src/amo/components/SectionLinks/index.js, src/blog-utils/index.html, src/blog-utils/index.js, src/blog-utils/styles.scss, tests/unit/amo/components/TestSectionLinks.js, tests/unit/blog-utils/test_index.js
Fixes #10407 
---
Note: the `buildHeader()` function only returns HTML and we use JS to open/close the dropdown, so this won't work on the dev page. The `blog-utils` library does not provide any "production" JS code, which is why there is no JS in this patch. I have some JS to animate the dropdown in `addons-blog`. Maybe it could be moved in this project in the future but that will require some more webpack config and a few changes. I think this is something we will want to do in the future, if we keep the blog after the pilot.
=> Render 'More...' link (header) for the blog and add link to the blog in the submenu

src/amo/components/InstallButtonWrapper/styles.scss
Fixes #10442
Before: 
After:
Note that the reduced padding for the blue button at this specific resolution is something we're going to live with. It only affects screens from 720px - 730px.
=> Fix new CTA on 720px screen

src/amo/components/SectionLinks/styles.scss
=> Fix wrapping menu items, again

src/amo/pages/AddonVersions/styles.scss
=> Fix padding on versions page

src/amo/components/ServerHtml/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/10492
There's potentially quite a bit of metadata. By putting this blocking resource higher, we increase the chances it will be in the first TCP packet.
=> Put stylesheets top of source order

src/amo/components/Footer/styles.scss
Fixes #10415 
Initially :
Now :
=> Fixed LangPicker Position.

src/amo/api/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/10493
---
This log statement does not seem very useful in production because we call the
API anyway and parsing `appversion` is handled by a 3rd party library.
=> Downgrade a log statement from warn to debug

src/amo/components/SectionLinks/styles.scss
Fixes #10512
---
This css property was added in https://github.com/mozilla/addons-frontend/pull/7338 ...
=> Fix focus styles on 'More...' button

config/default.js, src/amo/components/GetFirefoxBanner/index.js, src/amo/components/GetFirefoxButton/index.js, src/amo/constants.js, src/amo/utils/index.js, tests/unit/amo/components/TestGetFirefoxBanner.js, tests/unit/amo/components/TestGetFirefoxButton.js
=> Use utm_term to pass the addonId and variant to mozilla.org on download URLs

src/blog-utils/StaticAddonCard/index.js, src/blog-utils/StaticAddonCard/styles.scss, src/blog-utils/index.html, tests/unit/blog-utils/TestStaticAddonCard.js
Fixes https://github.com/mozilla/addons-frontend/issues/10525
---
=> Add support for themes in StaticAddonCard

src/amo/components/PermissionsCard/index.js, src/amo/components/PermissionsCard/styles.scss, tests/unit/amo/components/TestPermissionsCard.js
Fixes #9411 
As requested in this [comment](https://github.com/mozilla/addons-frontend/issues/9411#issuecomment-704338725), this PR replaces the button in the PermissionsCard with a link in its header that says 'Learn more'.
Before:
After:
=> Replace 'Learn more about permissions' button with 'Learn more' link

src/amo/components/HomepageShelves/index.js, tests/unit/amo/components/TestHomepageShelves.js, tests/unit/amo/reducers/test_home.js, tests/unit/helpers.js
Fixes #10463
This pull request removes references to the search-themes endpoint from the `HomepageShelves` component, its test, and other test files (reducers, helpers).
@bobsilverberg, please review when you have a moment. Thank you!
=> RE: Remove search-themes endpoint from homepage shelves

src/amo/components/AddonReviewCard/styles.scss, src/amo/components/AddonReviewManagerRating/styles.scss, src/amo/components/AddonSummaryCard/styles.scss, src/amo/components/AddonTitle/styles.scss, src/amo/components/App/styles.scss, src/amo/components/AutoSearchInput/styles.scss, src/amo/components/Badge/styles.scss, src/amo/components/Button/styles.scss, src/amo/components/DropdownMenuItem/styles.scss, src/amo/components/GetFirefoxBanner/styles.scss, src/amo/components/Header/styles.scss, src/amo/components/HeroRecommendation/styles.scss, src/amo/components/LoadingText/styles.scss, src/amo/components/MetadataCard/styles.scss, src/amo/components/Notice/styles.scss, src/amo/components/RatingsByStar/styles.scss, src/amo/components/ScreenShots/styles.scss, src/amo/components/SearchResult/styles.scss, src/amo/components/SecondaryHero/styles.scss, src/amo/components/Select/styles.scss, src/amo/components/TooltipMenu/styles.scss, src/amo/components/UserProfileEditNotifications/styles.scss, src/amo/css/inc/vars.scss, src/amo/pages/AddonReviewList/styles.scss, src/amo/pages/AddonVersions/styles.scss, src/amo/pages/Home/styles.scss, src/amo/pages/LandingPage/styles.scss, src/amo/pages/UserProfile/styles.scss, src/amo/pages/UserProfileEdit/styles.scss
Fixes #10251
This changes the default line-height for body to `1.5` and the line-height used for everything else to `1.2`. I only had to keep once instance of a specific line-height other than those two, and that is for `.RatingsByStar-graph` in order to make the rows the right height.
=> Clean up line-heights

src/amo/components/Badge/styles.scss
Fixes #10547
UI Change: Equal spacing between badges.
**Before**
**After**
=> Fix spacing between badges

src/amo/components/SearchSuggestion/styles.scss
Fixes #10505
UI Change: Will horizontal align the items in autocomplete results.
**Before**  
**After**
=> Align items in autocomplete results

src/amo/components/Header/styles.scss
Fixes #10488 
We already reduced the size of this input on smaller screens, and reducing it a bit more fixes this. It's still a bit tight, as can be seen from the screenshot, but this really only happens on a 500px wide screen. Anything smaller and the input moves to the top of the screen. If we want to make this less "tight", we could reduce the size of the input even more, but that would impact all screens between 500px and 720px, so I think it's better to avoid that.
Before:
After:
=> Prevent More... menu from overlapping search box

src/amo/components/LanguagePicker/styles.scss
Fixes #10524 
This adds `2px` of padding. We can make it even roomier by adding more padding.
Before:
After:
=> Make LanguagePicker less "compact"

src/amo/components/Notice/styles.scss
=> Move the Notice icon down a bit

src/amo/components/Notice/styles.scss
Fixes #10588 
This actually fixes 3 instances where the Notice icon isn't aligned.
Before:
After:
=> Fix issue with notice icon alignment

src/amo/components/SearchResult/styles.scss
Fixes #10590 
Before:
After:
~~Note that this will also add a 6px gap between the name and the badge when the badge does not wrap to the next line, but I think that's a reasonable tradeoff.~~ - fixed by using `row-gap` instead of `gap`.
=> Add gap between promoted badge and add-on name

src/amo/components/InstallButtonWrapper/styles.scss
=> Right align install button when there is no add-on description

src/amo/components/Header/index.js, tests/unit/amo/components/TestHeader.js
Fixes https://github.com/mozilla/addons-frontend/issues/10657
=> Never render the GetFirefoxBanner in the header when forBlog is true

src/amo/server/base.js, tests/unit/amo/server/test_base.js
We don't want browsers to cache our pages at the moment, but sending `Cache-Control: no-store` prevents proxies and upstream caches from caching as well. We override that in nginx at the moment, but the more standards-based approach is to use `max-age` and `s-maxage` instead.
This unlocks the possibility to have a CDN in front of addons-frontend.
Fixes #10678
=> Stop sending Cache-Control: no-store, send max-age and s-maxage

src/blog-utils/StaticAddonCard/index.js, src/blog-utils/StaticAddonCard/styles.scss, tests/unit/blog-utils/TestStaticAddonCard.js
Fixes https://github.com/mozilla/addons-frontend/issues/10684
---
After:
=> Add link to add-on name in StaticAddonCard

src/amo/languages.js
This locale (Scots) is going to ride the trains with Firefox 91 to Beta, so we'll have a language pack for it.
=> Add Scots (sco) to supported languages

src/amo/components/GetFirefoxButton/index.js, src/amo/components/InstallButtonWrapper/index.js, tests/unit/amo/components/TestGetFirefoxBanner.js, tests/unit/amo/components/TestGetFirefoxButton.js, tests/unit/amo/components/TestInstallButtonWrapper.js
Fixes https://github.com/mozilla/addons-frontend/issues/10724
---
We shouldn't try to recompute the variant of an experiment because the variant
is optional. When the experiment is disabled, there is no variant and
everything related to the experiment should take that into account. This patch
makes sure we pass the variant and deal with it correctly.
=> Pass variant instead of trying to recompute it

src/amo/components/UserReview/styles.scss
Fixes #10405 
This adds a bit more space between the bottom of the review text and the textual links, but I think that's acceptable to fix the rounded corners cutting off part of the text issue.
Before:
After:
=> Fix problem with rounded corners on add-on reviews

src/amo/components/UserReview/styles.scss
=> Fix truncation problem in edges on add-on reviews

src/amo/components/AddonsCard/index.js, src/amo/components/Card/index.js, src/amo/components/Card/styles.scss, src/amo/components/HomepageShelves/index.js, src/amo/components/LandingAddonsCard/index.js, tests/unit/amo/components/TestAddonsCard.js, tests/unit/amo/components/TestCard.js, tests/unit/amo/components/TestHomepageShelves.js, tests/unit/amo/components/TestLandingAddonsCard.js
Fixes #10373 
Fixes #10509
@bobsilverberg, as discussed, this pull request fixes the overlap between the header and footer_text within the homepage shelves by passing through a props (`isHomepageCard`) that `Card` can then utilize. If we proceed with this update, I'll work on updating the tests.
Please see screenshots below:
Homepage (width: 1024px)-
Homepage (width: 768px)- 
Homepage (width: 425px)- 
Rating (included as it utilizes `Card` component)-
Review (included as it utilizes `Card` component)-
Please review when you have a moment. Thank you!
=> RE: Fix title and footer text within homepage shelves (isHomepageCard props)

src/amo/addonManager.js, src/amo/components/AMInstallButton/index.js, src/amo/components/InstallButtonWrapper/index.js, src/amo/installAddon.js, tests/unit/amo/components/TestInstallButtonWrapper.js
Fixes #10762 
It turns out that after the changes landed in https://github.com/mozilla/addons-frontend/commit/f259dfd0bb05015f28dc0cb9cce3a3dfdcfea8d9, we no longer need the `findInstallURL` helper at all, nor do we need the code that checks that `installURL` exists in `install` in `installAddon` because Flow guarantees that it will exist at that point.
=> Address code coverage issues with addonManager and installAddon

src/amo/i18n/utils.js, src/amo/middleware/prefixMiddleware.js, tests/unit/amo/i18n/test_utils.js, tests/unit/amo/middleware/test_prefixMiddleware.js
Otherwise, the following could happen:
- Request comes in without `Accept-Language`, is cached by upstream without varying on `Accept-Language`
- Another request comes in with `Accept-Language`, upstream serves the previously cached response without knowing it shouldn't.
Required for https://github.com/mozilla/addons/issues/1344
=> Always Vary on Accept-Language for pages that redirect based on language

src/amo/withExperiment.js, tests/unit/amo/test_withExperiment.js
Fixes https://github.com/mozilla/addons-frontend/issues/10812
Fixes https://github.com/mozilla/addons-frontend/issues/10811
---
Let's start with the good thing: no tests broken! 🎉 There are a bunch of changes to simplify the HOC with the main goal of avoiding the call to `experimentSetup` (renamed to put the verb first) in `render()`. I added some assertions to make sure we don't dispatch too many actions (never a good idea).
I confirmed this patch fixes the addons-server local dev issue mentioned by @wagnerand on Matrix. I tried it locally and it looks good as well but I'll ask QA to verify everything extensively on -dev.
On addons-server local dev, there is a third issue (see #10810) but it is not required to make the frontend work in this environment. The only problem with #10810 is …
=> Refactor withExperiment HOC to make it more predictable

.circleci/config.yml, tests/unit/amo/sagas/test_users.js
Now that we use Node 14 by default at runtime, it's time to update our Circle configuration to use Node 14 by default and Node 16 as the "next" version. This should have been done earlier than today but there were errors...
There are still errors but I disabled them. The reason is that our test setup for two test cases is broken and that cannot be replicated at runtime (when the app is actually running). This is a problem with Node detecting unhandled promise rejections, which finally terminates the process (after having warned us for... many many years).
I filed to re-enable the two tests later: https://github.com/mozilla/addons-frontend/issues/10817
=> Update Node versions in Circle config

src/amo/utils/server.js, tests/unit/amo/utils/test_server.js
Fixes https://github.com/mozilla/addons-frontend/issues/10822
---
This can be tested locally with [amo-info](https://addons.mozilla.org/en-US/firefox/addon/amo-info/) or `curl -I`.
=> Set 'Access-Control-Allow-Origin: *' on /__version__

src/amo/components/AddonMoreInfo/index.js, tests/unit/amo/components/TestAddonMoreInfo.js
Fixes https://github.com/mozilla/addons-frontend/issues/10829
---
We can reproduce the bug (without this patch) by loading:
- http://localhost:3000/en-US/firefox/addon/akan-ns%C9%9Bmfuaasekyer%C9%9B/
- http://localhost:3000/en-US/firefox/addon/asturianu-language-pack/
The fix is to not render categories for add-ons that are not extensions or themes given that we only have category pages for extensions and themes. We could also render the categories without links but that wouldn't be super useful so it is best to hide them.
The second commit handles add-ons without any categories at all, e.g.:
- http://127.0.0.1:3000/en-US/firefox/addon/xuxen/
=> Do not render related categories for add-ons that are not extensions/themes

src/amo/components/Search/index.js, tests/unit/amo/components/TestSearch.js
Fixes #10831
---
This should work with all search pages, including category pages and soon tag pages. FWIW, we use this `meta` tag for other pages.
=> Render noindex,follow meta when search page does not have any results

src/amo/searchUtils.js, tests/unit/amo/test_searchUtils.js
fixes #10835 - seems to work from a quick test.  Not sure if there needs to be anything else added?
=> allow ratings and users search parameters to be passed to the search api

src/amo/components/GetFirefoxButton/index.js, src/amo/constants.js, src/blog-utils/StaticAddonCard/index.js, tests/unit/amo/components/TestGetFirefoxBanner.js, tests/unit/amo/components/TestGetFirefoxButton.js, tests/unit/blog-utils/TestStaticAddonCard.js
Fixes #10786 
This also removes logic that would have appended the `variant` to the `utm_campaign` param as we no longer need to do that. As long as we pass the `variant` in `variation`, then it will get stored in a usable format in both GA and telemetry.
=> Use variable utm_campaign for attribution

src/amo/components/SearchContextCard/index.js, tests/unit/amo/components/TestSearchContextCard.js
fixes #10847 
I flattened some of the multiple levels of `if` statements because they become hard to follow with a 3rd level for `if (tag)`
=> added strings for all the combinations of categories, tags, and queries

src/amo/components/HeroRecommendation/index.js, src/amo/components/HeroRecommendation/styles.scss, tests/unit/amo/components/TestHeroRecommendation.js
Fixes #9049 
This pull request updates the primary hero loading skeleton to reflect a hero with an image.
https://user-images.githubusercontent.com/28129806/131353745-19785f98-07c2-4fb4-9292-9c25cbd547cc.mov
Please review when you have a moment. Thank you!
=> RE: Update Primary Hero loading skeleton to reflect a hero with an image

src/amo/components/UserCollection/index.js, src/amo/pages/Collection/index.js, src/amo/pages/CollectionList/index.js, src/amo/reducers/collections.js, tests/unit/amo/components/TestUserCollection.js, tests/unit/amo/pages/TestCollectionList.js
Fixes #10886 
The problem in the issue occurs when a user navigates quickly from a collection detail page back to the same page (but with a different sort sequence), and then to the Collections list. The first navigation causes the detail for the collection to be re-fetched, but because of the quick navigation, the details for that collection are still loading when we try to render the Collections list. The code assumes this will not be the case, hence the error.
The fix is to update the code for `UserCollection` to make it smart enough to deal with a collection that is currently being loaded.
=> Fix problem on Collections page when a collection is loading

.circleci/config.yml
Fixes https://github.com/mozilla/addons-frontend/issues/10897
---
It's been 24h and it's increasingly annoying to have red crosses everywhere on this GitHub repository so here we are... I pinned the Node 16 version to 16.8, which is not affected by the Node bug (which is a v8 bug actually).
=> Update docker images for Node on Circle CI

src/amo/api/recommendations.js, tests/unit/amo/api/test_recommendations.js
Fixes https://github.com/mozilla/addons-frontend/issues/10912
---
The issue cannot be reproduced with all add-ons but it is reproducible with uBlock on -prod and for -dev/localdev, I used http://127.0.0.1:3000/en-US/android/addon/enhancer-for-youtube-2/.
This patch fixes the issue linked above because we update the Redux state when we load the recommendations. It is usually not a problem except in this particular case: while the "app" in URLs is usually interchangeable, it matters for Fenix because [only URLs with `/android/` will trigger the Interceptor](https://github.com/mozilla-mobile/fenix/blob/e00079aeafec60e18fcaa9080a656c698c0266ef/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L172). Note that this is a tricky bug because it only occurs for add-ons recommended by …
=> Pass app to recommendations API endpoint

src/amo/components/AddonQRCode/index.js, tests/unit/amo/components/TestAddonQRCode.js
Fixes https://github.com/mozilla/addons-frontend/issues/10935
---
This is needed because the images have been updated in https://github.com/mozilla/addons-frontend/issues/10927
=> Cache-bust QR code images

src/amo/languages.js
Fixes https://github.com/mozilla/addons-frontend/issues/11096
---
Lengadocian is just a variant of Occitan. In practice, the oc category on AMO includes dictionaries from other dialects such as Gascon and Aranese, so the "(Lengadocian)" qualifier is inaccurate.
See https://github.com/mdn/content/issues/11868 and https://github.com/mozilla/addons-server/pull/18624
=> Replace "Occitan (Lengadocian)" with "Occitan"

src/amo/components/Errors/AuthExpired/index.js, src/amo/components/Errors/AuthExpired/styles.scss, tests/unit/amo/components/Errors/TestAuthExpired.js
=> reformat auth expired explanation paragraph to a single l10n-able string

src/amo/components/Header/index.js, tests/unit/amo/components/TestHeader.js
Fixes #10997 
Added a check before rendering `otherSiteLinks` and `renderMenuOrAuthButton` method such that it will be rendered only if `forBlog` prop is false.
=> Hide other site links in AMO header for blog

package.json, src/amo/client/base.js, tests/unit/amo/client/test_base.js, yarn.lock
On my Android device, this fixes issues with `<select>` and doesn't regress tapping on links. Please test on yours.
Fixes https://github.com/mozilla/addons-frontend/issues/11135
=> Remove fastclick: it's obsolete and causing issues with <select>

src/amo/components/DropdownMenu/index.js, tests/unit/amo/components/TestDropdownMenu.js
This should fix the menu needing a double-tap to open on some mobile devices. I've tested it successfully on Desktop and Android, it fixes the issue for me without introducing regressions.
Fixes #11137
=> Avoid handling mouseenter/mouseleave if device doesn't support hover

src/amo/pages/UserProfile/index.js, tests/unit/amo/pages/TestUserProfile.js
fixes #11109?  It seems like a simple/simplistic fix, but appears to work 🤷
=> pass errorHandler to Page from UserProfile; show AuthExpired for all 401s

.eslintrc, package.json, tests/unit/amo/components/TestIcon.js, tests/unit/amo/components/TestIconPromotedBadge.js, tests/unit/amo/components/TestIconXMark.js, tests/unit/amo/components/TestPermission.js, tests/unit/helpers.js, yarn.lock
Fixes #11322 
We could think about adding this to [`eslint-config-amo`](https://github.com/mozilla/eslint-config-amo), but perhaps that is premature.
=> Implement eslint-plugin-testing-library

src/amo/components/Footer/index.js
Fixes #11308 
This patch removes site status from the AMO footer.
BEFORE:
AFTER:
=> remove site status from AMO footer

tox.ini
Wwhatever the image provides is enough (should be python 3.x), especially given we only have a single dumb test
=> Don't specify a python version for smoke tests

bin/build-locales, tests/unit/test_localesConfig.js
https://github.com/mikeedwards/po2json/commit/e5db448c changed the `format` property:
- `jed` no longer means compatible with jed < 1.1.0, it now means what `jed1.x` used to mean
- `jed1.x` no longer exists as a result
Fixes https://github.com/mozilla/addons-frontend/issues/11414
Fixes https://github.com/mozilla/addons-frontend/issues/11427
=> Update `format` property in po2json.parseFileSync() call

src/amo/api/index.js, tests/unit/amo/api/test_index.js
Fixes #11485 
I am fairly certain we don't need to encode the pathname. Node will do it for us on the server, and it doesn't seem to be needed on the client.
Does that make sense to you @diox?
=> Fix problem with double-encoded pathname

src/amo/components/GetFirefoxButton/index.js, tests/unit/amo/components/TestInstallButtonWrapper.js
Fixes https://github.com/mozilla/addons-frontend/issues/11562
---
Technically, we should have added a check for `version.channel` (that
must be `'listed'`) but we don't check the channel anywhere currently. I
tried to add support for it but failed because I couldn't retrieve the
current version object for some reasons...
=> Update download firefox button text for ERTAMO

tests/unit/amo/components/TestRoot.js, tests/unit/amo/components/TestVPNPromoBanner.js, tests/unit/amo/test_withExperiment.js, tests/unit/helpers.js
Fixes #11237 
This is the last test that was using the `sinon` version of `fakeCookies`, so I also renamed `fakeCookiesWithJest` in `helpers` to `fakeCookies`.
=> Migrate TestRoot.js, and replace fakeCookies with fakeCookiesWithJest

src/amo/components/AMInstallButton/index.js, tests/unit/amo/components/TestAMInstallButton.js
=> Stop showing loading animation for themes when installed, this is no longer necessary

src/blog-utils/tracking.js, tests/unit/amo/api/test_index.js, tests/unit/blog-utils/test_tracking.js
This addresses missing coverage for `blog-utils/tracking.js` and `api/index.js`.
=> Improve coverage

package.json, src/amo/client/base.js, yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/11601
https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import
- before: `amo-i18n-en_US-eb9305cb9fedfb0e1c62.js`
- after: `amo-i18n-en_US-amo-js-de725749b6745cf38ee9.js`
- before:
- uncompressed:1.2 MB (1203076 bytes)
- brotli 9: 318 kB (318058 bytes)
- after:
- uncompressed: 1.19 MB (1192066 bytes)
- brotli 9: 318 kB (317617 bytes)
- gains:
- uncompressed: 11kB (11010 bytes, 0.91%)
- brotli 9: 441 bytes
```diff
<       5129: function (e, t, n) {
<         var r,
<           o = [];
<         (e.exports = function (e) {
<           o ? o.push(e) : e(r);
<         }),
<           n
<             .e(5859)
<             .then(
<               function (e) {
<                 r = n(9571);
<                 var t = o;
< …
```
=> Load locale bundle using dynamic import rather than locale-loader

package.json, tests/setup.js, tests/unit/amo/api/test_collections.js, yarn.lock
This addresses some coverage that was missing for `api/collections.js` and also removes `sinon` from the test and uses a different ways of testing our api code which we should probably adopt for the other tests. It's fairly low priority, however, to make that change.
=> Add coverage for api/collections.js

tests/unit/amo/pages/TestUsersUnsubscribe.js
Fixes #11690
Fun one. It's a single failure, but it's kinda interesting:
The `when user is successfully unsubscribed › renders a link to edit the user profile` test was failing, expecting a link to edit your profile to be present... and it was... but with a different app in the URL that what we're expecting - `android` instead of `firefox`. We're not checking what the `<title>` says, but it was set to `Unsubscribe – Add-ons for Firefox Android (en-US)` - so the whole page was being rendered with `android` as the app. We're setting `initialEntries to `[/en-US/firefox/users/unsubscribe/...]` at the start, but I guess the `dispatchClientMetadata()` call in `beforeEach()` overrides that asynchronously ?
Since that's inconsistent with the URL, I fixed it by initializing the store with …
=> Make TestUsersUnsubscribe forward compatible with future dependencies

tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestBlock.js, tests/unit/helpers.js
Fixes #11705 
I made a couple of improvements, I think:
1. We are not calling anything *after* rendering the component, but are instead calling something *before* rendering the component. This is important as we don't want to alter the component in any way after it has been rendered.
2. I am dispatching an action to update the state in the store, rather than calling `history.push` which could have additional side effects.
@diox Let me know what you think about this improvement.
=> Improve initialEntries hack

package.json, yarn.lock
This version replaces update notifier with a simplified version pulling a lot fewer dependencies (and avoiding a security issue in one of them as a result).
=> Update nodemon to 2.0.19

src/amo/components/AddonReviewManager/styles.scss, src/amo/components/AddonReviewManagerRating/styles.scss
- On mobile, "Your star rating" and the stars should be on different lines, and the stars slightly bigger (larger target), with some margin to separate them from the textbox
- On larger screen sizes, "Your star rating" and the stars can be on the same line, with the regular small stars
Fixes https://github.com/mozilla/addons-frontend/issues/11746
=> Adjust Rating stars spacing and size when writing a review

config/default.js, src/amo/experiments/20220908_amo_dimension_test.js, src/amo/pages/LandingPage/index.js, src/amo/withExperiment.js, tests/unit/amo/components/TestPage-VPNPromoBanner.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/pages/TestLandingPage.js, tests/unit/amo/test_withExperiment.js
Fixes #11819 
It includes a small experiment which simply allocates users into branches when they visit a landing page. We can use this to validate that everything works as expected in GA, after which we can remove that experiment.
=> Record experiment name and variation as GA dimensions

tests/unit/amo/pages/TestCollection.js, tests/unit/amo/pages/error-simulation/TestSimulateAsyncError.js
=> Work around test timeout issues by using jest legacy fake timers and resetting after each test

src/amo/imageUtils.js, src/amo/reducers/addons.js, src/amo/types/addons.js, tests/unit/amo/components/TestAddonSummaryCard.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/test_imageUtils.js, tests/unit/helpers.js
Fixes #11349
Use API's `icons` object for add-on icon URL, and be able to pick a specific icon size(32, 64, 128). 
Currently, all add-ons icon URLs are coming from API's `icon_url` field.
The need is to switch to getting them from API's `icons` object.
```JSON
"icons": {
"32": "https://addons.allizom.org/static-server/img/addon-icons/default-32.2b26add4b394.png",
"64": "https://addons.allizom.org/static-server/img/addon-icons/default-64.d144b50f2bb8.png",
"128": "https://addons.allizom.org/static-server/img/addon-icons/default-128.452018499894.png"
}
````
`getAddonIconUrl` is the function responsible for getting all add-ons icons, 
it is used to get autocomplete add-ons icons too.
**Autocomplete** API **doesn't return `icons` objects**, only returns `icon_url`.
=>  Get add-on icon URL form API's icons object with specific icon size

src/amo/languages.js
We're going to release both locales, likely in 111. For Sardinian there is already a dictionary on AMO.
I don't think we can remove `fur-IT`, because it might be used by some add-ons.
=> Add fur, sc to supported languages

src/amo/components/Header/styles.scss
Fixes #11824
Tested with usernames containing 50 characters (limit)
=> Fix header display name overlap with searchbar (#11824)

src/amo/components/RatingManager/index.js, tests/unit/amo/components/TestRatingManager.js
=> Allow ratings to be loaded when the API error is a 429

src/amo/languages.js
We plan to release this locale in Firefox 113, and this change will be needed to display the language pack in the [language-tools page](https://addons.mozilla.org/firefox/language-tools/).
Native name: Тоҷикӣ
=> Add Tajik (tg) to languages.js

package.json
with `--workerIdleMemoryLimit=1G` to work around jest memory consumption issues
=> Go back to 2 workers to run tests in CI for faster tests

package.json, yarn.lock
Reverts mozilla/addons-frontend#12106
Fixes https://github.com/mozilla/addons-frontend/issues/12122
=> Revert "Bump rc-tooltip from 5.2.2 to 6.0.1"

src/amo/components/Header/styles.scss
Fixes #12033
This patch adds responsiveness to the margin of the logo in the header at medium size. This is to not overlap the user drop down menu in order to keep it clickable at this scale.
Before:
After:
=> 12033: Fixed overlapping header content onto dropdown menu at medium size

src/amo/components/AddonHead/index.js, src/amo/components/AddonMoreInfo/index.js, src/amo/components/AddonTitle/index.js, src/amo/components/EditableCollectionAddon/index.js, src/amo/components/HeroRecommendation/index.js, src/amo/components/RatingManager/index.js, src/amo/components/SearchResult/index.js, src/amo/components/ThemeImage/index.js, src/amo/installAddon.js, src/amo/pages/Addon/index.js, src/amo/pages/AddonInfo/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/AddonVersions/index.js, src/amo/reducers/addons.js, src/amo/reducers/utils.js, src/amo/types/addons.js, src/amo/types/api.js, src/blog-utils/StaticAddonCard/index.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/components/TestAddonTitle.js, tests/unit/amo/components/TestAddonsCard.js, tests/unit/amo/components/TestLandingAddonsCard.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/components/TestSearchResults.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/reducers/test_addons.js, tests/unit/amo/reducers/test_utils.js, tests/unit/blog-utils/TestStaticAddonCard.js
Fixes #3049 
Create a new type LocalizedStringWithLocale and new function SelectLocalizedContentWithLocale so that the AddonType (internal Addon) fields that previously use SelectLocalizedContent now contains a 'locale' field. Everywhere in the code where any of these 5 fields (summary, name, description, support_email, developer_comments) exist, the surrounding HTML will contain a lang tag (if applicable).
=> use lang from api for addon fields in html

src/amo/components/AddonHead/index.js, src/amo/components/AddonMoreInfo/index.js, src/amo/components/AddonTitle/index.js, src/amo/components/EditableCollectionAddon/index.js, src/amo/components/HeroRecommendation/index.js, src/amo/components/RatingManager/index.js, src/amo/components/SearchResult/index.js, src/amo/components/ThemeImage/index.js, src/amo/installAddon.js, src/amo/pages/Addon/index.js, src/amo/pages/AddonInfo/index.js, src/amo/pages/AddonReviewList/index.js, src/amo/pages/AddonVersions/index.js, src/amo/reducers/addons.js, src/amo/reducers/utils.js, src/amo/types/addons.js, src/amo/types/api.js, src/blog-utils/StaticAddonCard/index.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/components/TestAddonTitle.js, tests/unit/amo/components/TestAddonsCard.js, tests/unit/amo/components/TestLandingAddonsCard.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/components/TestSearchResults.js, tests/unit/amo/pages/TestAddon.js, tests/unit/amo/reducers/test_addons.js, tests/unit/amo/reducers/test_utils.js, tests/unit/blog-utils/TestStaticAddonCard.js
This reverts commit a9ed5b7c9acc8b2ad28d4a0874c061db692f4848.
(un)Fixes #12201
=> Revert "use lang from api for addon fields in html (#12201)"

config/default.js
Compatibility filtering still applies, this should only really affect users of 119 Nightly/Beta for now, given
https://github.com/mozilla/addons-server/issues/21162
Follow-up for #12372 which only enabled it on dev.
=> Enable non-recommended extensions for Android on all envs

src/amo/languages.js
Santali locale is being added to Beta/Release cycle. It was already enabled for langpacks, but the locale name [here](https://addons.mozilla.org/en-US/firefox/language-tools/) doesn't match the language name for the language pack / what is shown in Firefox.
This change updates the display name to match the language name in Firefox:
Locale: sat
Native (current): संताली
Native (update): ᱥᱟᱱᱛᱟᱲᱤ
=> l10n - Update Santali native name to correct Ol Chiki script in languages.js

src/amo/components/AddonMoreInfo/index.js, src/amo/components/AddonSuggestions/index.js, src/amo/components/Categories/index.js, src/amo/components/SearchContextCard/index.js, src/amo/pages/CategoryPage/index.js, src/amo/reducers/addons.js, src/amo/reducers/categories.js, src/amo/reducers/utils.js, src/amo/types/addons.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/pages/TestSearchPage.js, tests/unit/amo/reducers/test_categories.js
Fixes #12414 
This removes the need for the clientapp in category list since we are unifying categories. It also handles the unified api categories as well as legacy category object from the api addon type in the reducer.
=> flatten categorylist to not use clientapp

src/amo/reducers/categories.js, src/amo/reducers/utils.js, tests/unit/amo/components/TestAddonMoreInfo.js
Follow-up fix for #12414
Some add-ons only have `"categories": {"android": [...]}` - those should be completely ignored (categories are not currently used on Android, and they'll be merged with Firefox soon)
=> Fix loading of add-ons with only Android categories

config/default.js
This allows /abuse/ to work on local envs to work without needing to mess with nginx config. On dev/stage/prod we'll still need to change that nginx config but that will only become relevant when we start testing/deploying it in those envs.
Supports https://github.com/mozilla/addons-server/issues/21290
=> Sync validClientAppUrlExceptions with SUPPORTED_NONAPPS

.gitignore, .yarnrc.yml, package.json
yarn v2 does things a little different - I didn't bother investigating if any of the new default were better, just tried to keep it as similar as possible to v1 - to get rid of the annoying extra cruft in my local folder.
/.yarn/ is where the downloads get cached
/.yarnrc.yml is where yarn settings are now.  it just has `nodeLinker: node-modules`, which is how yarn v1 works.
=> Yarn v2 config changes

src/amo/utils/compatibility.js, tests/unit/amo/components/TestWrongPlatformWarning.js, tests/unit/amo/utils/test_compatibility.js
Fixes #12496 
Previously, the banner showed up everywhere on android that wasn't home or search. This removes that condition, so it won't show up anywhere on android while one /android/ pages.
=> Remove yellow banner on /android/ pages on android

src/amo/components/Routes/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/11331
---
While we do not specifically support the category pages on Android, we
should not have category pages for themes because Firefox for Android
doesn't support themes anyway.
=> Restrict category pages for themes to Desktop only

src/amo/api/abuse.js, src/amo/components/FeedbackForm/index.js, src/amo/installAddon.js, src/amo/reducers/abuse.js, src/amo/reducers/installations.js, src/amo/sagas/abuse.js, tests/unit/amo/api/test_abuse.js, tests/unit/amo/pages/TestFeedback.js, tests/unit/amo/reducers/test_abuse.js, tests/unit/amo/reducers/test_installations.js, tests/unit/amo/sagas/test_abuse.js
Fixes https://github.com/mozilla/addons-frontend/issues/12477
---
This PR allows add-on feedback reports to be sent with the installed add-on version when available.
=> Send installed add-on version when available

src/amo/api/abuse.js, src/amo/components/FeedbackForm/index.js, src/amo/components/FeedbackForm/styles.scss, src/amo/components/SignedInUser/index.js, src/amo/components/SignedInUser/styles.scss, src/amo/pages/Feedback/index.js, src/amo/pages/Feedback/styles.scss, src/amo/reducers/abuse.js, src/amo/reducers/addons.js, src/amo/sagas/abuse.js, src/amo/sagas/addons.js, tests/unit/amo/components/TestSignedInUser.js, tests/unit/amo/pages/TestFeedback.js, tests/unit/amo/reducers/test_abuse.js, tests/unit/amo/sagas/test_abuse.js, tests/unit/amo/sagas/test_addons.js
Fixes https://github.com/mozilla/addons-frontend/issues/12478
---
This PR updates the UI and adds some of the add-on metadata we need on this page. The "stepper" thingy is omitted on purpose for now. I'll also address the "anonymous" part in https://github.com/mozilla/addons-frontend/issues/12532. ~~As for the legal certification at the bottom, I'm still waiting on confirmation to know when that is required.~~
As described at the bottom of this description, the required certification checkbox now appears for reasons D and E only. Most fields are also optional, in fact only the reason (named `category` in the code, for now) is required.
User is signed in, add-on is listed:
User is signed in, add-on is a theme:
User is signed out, add-on is listed:
Add-on is unlisted:
Mobile view:
The …
=> Refactor add-on form, show add-on metadata

src/amo/components/FeedbackForm/index.js, tests/unit/amo/pages/TestFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12520
=> Make sure confirmation is always visible after feedback is submitted

src/amo/components/FeedbackForm/index.js, src/amo/components/FeedbackForm/styles.scss
=> Add disclaimer next to message textarea in feedback form

src/amo/components/FeedbackForm/index.js, tests/unit/amo/pages/TestFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12513
---
I also fixed the test file because there global-ish variables are not nice, and some code seemed unused.
=> Tweak the FeedbackForm for add-on types other than "extension"

src/amo/pages/Feedback/index.js, tests/unit/amo/pages/TestFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12566
---
Not sure why we conditionally fetch an add-on with group ratings but
failing to do so will throw an error when we navigate back to an add-on
detail page after a reload. This isn't exactly a normal scenario but
that might happen given that the feedback page is available from a
detail page.
=> Fetch add-on with group ratings in feedback form

src/amo/components/Routes/index.js, src/amo/pages/AddonFeedback/index.js, src/amo/pages/AddonFeedback/styles.scss, tests/unit/amo/pages/TestAddonFeedback.js
Fixes #12564
---
~~:warning: depends on https://github.com/mozilla/addons-frontend/pull/12560~~
=> Rename `Feedback` page component to `AddonFeedback`

src/amo/components/AddonFeedbackForm/index.js, src/amo/components/AddonFeedbackForm/styles.scss, tests/unit/amo/pages/TestAddonFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12592
---
=> Show add-on metadata in the add-on feedback form page

src/amo/components/AddonFeedbackForm/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/12599
---
The `Rating` component renders a `div` element, which cannot be placed
inside a `p`, though React is happy to force that to happen on the
client side while browsers "fix" this mistake in the HTML returned by
the server. That explains the short flash of content (with the stars
moving from the middle of the header to the right side in LTR mode).
I don't think we can write a good test for this...
=> Fix add-on rating stars in feedback form

src/amo/components/FeedbackForm/index.js, tests/unit/amo/pages/TestAddonFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12610
=> Use user `name` instead of `display_name` when submitting the feedback form

src/amo/components/FlagReview/index.js, src/amo/components/FlagReview/styles.scss, src/amo/components/FlagReviewMenu/index.js, tests/unit/amo/components/TestAddonReviewCard.js
Fixes #12605
---
We'll go with what we have in the doc. This PR also adds missing HTML
titles when the buttons are disabled to let users know why the buttons
are disabled.
Signed-in users should see:
Signed-out users should see:
=> Update flag review menu items

src/amo/components/Routes/index.js, src/amo/pages/Collection/index.js, src/amo/pages/Collection/styles.scss, src/amo/pages/CollectionFeedback/index.js, src/amo/pages/CollectionFeedback/styles.scss, tests/unit/amo/pages/TestCollection.js, tests/unit/amo/pages/TestCollectionFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12512
~~:warning: depends on https://github.com/mozilla/addons-frontend/issues/12594~~
---
- The report button is only visible to users who are not owners of the collection
- There is a "confirmation" message that replaces the report button after the form has been submitted (and the user has navigated back to the collection). This is similar to the other reporting features we already have
When the form has been submitted, navigating (back) to the collection page will show a confirmation message:
=> Introduce new page for collection feedback

src/amo/installAddon.js, tests/unit/amo/components/TestInstallButtonWrapper.js
Fixes https://github.com/mozilla/addons-frontend/issues/12623
=> Allow installAddon.setCurrentStatus() to set status for non-public add-ons

package.json, src/amo/components/AddonFeedbackForm/index.js, src/amo/installAddon.js, src/amo/reducers/installations.js, src/amo/sagas/addons.js, tests/unit/amo/pages/TestAddonFeedback.js, tests/unit/amo/reducers/test_installations.js
Fixes https://github.com/mozilla/addons-frontend/issues/12537
~~:warning: depends on https://github.com/mozilla/addons-frontend/issues/12623~~
=> Use installed add-on name when available, otherwise hide the add-on header when we don't have much information

package.json, yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/12637
Removes duplicated dependencies in package.json. I've verified the resolved version is not changed in yarn.lock so there is no impact on bundled code.
=> chore(): remove duplicate deps in package.json

src/amo/components/FeedbackForm/index.js, src/amo/components/FeedbackForm/styles.scss, tests/unit/amo/pages/TestAddonFeedback.js, tests/unit/amo/pages/TestCollectionFeedback.js, tests/unit/amo/pages/TestRatingFeedback.js, tests/unit/amo/pages/TestUserFeedback.js
=> Use replaceStringsWithJSX() in FeedbackForm to get proper localized strings

jsconfig.json
Fixes https://github.com/mozilla/addons-frontend/pull/12646
Adding a jsoncifg.json file to enable vscode to follow imports.
**Before: not working**
- checkout master and open with vscode. 
- (Command + click) (Ctrl + Click) on a file import in a .js file.
- Expected: Cannot open file 
https://github.com/mozilla/addons-frontend/assets/19595165/211ee374-cc2a-439b-b027-7e91dda48c3c
**After: Working**
- checkout vscode-setup
- restart vscode to parse the settings and jsconfig files
- repeat step two from the previous set trying to open a file
- Expected:  It should open the file.
https://github.com/mozilla/addons-frontend/assets/19595165/6900ac6f-5e7c-409d-ba65-29b31ef6e889
=> add jsconfig.json to support webpack aliased imports in IDE import links.

src/amo/components/GetFirefoxBanner/index.js, src/amo/components/GetFirefoxBanner/styles.scss, src/amo/components/GetFirefoxButton/index.js, src/amo/components/WrongPlatformWarning/index.js, src/amo/constants.js, tests/unit/amo/components/TestPage.js, tests/unit/amo/components/TestWrongPlatformWarning.js, tests/unit/amo/pages/TestAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/12664
---
=> Update wrong platform notice and get firefox banner for Android

.circleci/config.yml, Dockerfile
At least we get the same output in PRs and the main branch now:
```
PASS ./dist/static/amo-35683fa25eab81ca105d.js: 357.42KB < 360KB (gzip)
```
=> Use Node 18.19 everywhere

src/amo/components/AddonMoreInfo/index.js, src/amo/pages/UserProfile/index.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/pages/TestUserProfile.js
Fixes #12708
- Added `rel=nofollow` to homepage and support url on add-on's listing page, and developer user profile page
- Updated tests
- How do we also add `rel=nofollow` to any anchor links in the add-on summary field?
=> Added `rel=nofollow` to public links on AMO

src/amo/components/AddonFeedbackForm/index.js, src/amo/components/FeedbackForm/index.js, src/amo/pages/CollectionFeedback/index.js, src/amo/pages/RatingFeedback/index.js, src/amo/pages/UserFeedback/index.js, tests/unit/amo/pages/TestAddonFeedback.js, tests/unit/amo/pages/TestCollectionFeedback.js, tests/unit/amo/pages/TestRatingFeedback.js, tests/unit/amo/pages/TestUserFeedback.js
Fixes #12752
It needs to be deployed together with the fix for https://github.com/mozilla/addons-server/issues/21662, otherwise the new `something_else` category would be invalid.
=> Change "Other" category in feedback form to point to "something_else" reason API

src/amo/reducers/addons.js, tests/unit/amo/pages/TestAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/12709
---
Simplistic but good enough, I guess?
=> Hide Android badge when the add-on is not exactly compatible

src/amo/components/FeedbackForm/index.js, tests/unit/amo/pages/TestAddonFeedback.js, tests/unit/amo/pages/TestUserFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12841
---
The `Place of the violation` (location field) is now required for all
DSA related reason (i.e. not the feedback categories). In addition,
the `spam` category hides the form too.
=> Mark the 'location' field as required in the feedback form

src/amo/components/FeedbackForm/index.js, tests/unit/amo/pages/TestAddonFeedback.js, tests/unit/amo/pages/TestCollectionFeedback.js, tests/unit/amo/pages/TestRatingFeedback.js, tests/unit/amo/pages/TestUserFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12847
---
This relies on the builtin HTML validation to indicate which fields are required when a user attempts to submit a form without all the mandatory fields set.
=> Allow HTML validation to kick in

src/amo/languages.js
This is required to have the dictionary listed in the language tools page.
Unencoded language name: ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ
=> Add Standard Moroccan Tamazight (zgh) to languages.js

.circleci/config.yml
2004:2023.10.1 is not deprecated yet, but might as well stay on the latest ubuntu-2004 for consistency/futureproofness
Relates to https://github.com/mozilla/addons/issues/1565
=> Switch ubuntu image to 2004:current

Dockerfile
Reverts mozilla/addons-frontend#12920
=> Revert "Bump node from 18.19-slim to 20.12-slim"

src/amo/addonManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/12970
=> Remove reportAbuse/abuseReportPanelEnabled from the mozAddonManager type

tests/smoke/setup_docker.sh
We added an entrypoint that drops down to the correct user, so you should run things as root.
Fixes `master` build breakage.
=> Fix addons-server smoke test setup

src/amo/components/InstallWarning/index.js, tests/unit/amo/pages/TestAddonVersions.js
Fixes mozilla/addons#2207
The change should be straightforward enough to be verified by the unit test alone, and the issue explains the context a bit more, but if you want to check locally:
1) Visit /en-US/android/ with a Firefox for Android User Agent (on Desktop, Firefox responsive mode with some custom UA should do the trick)
2) Follow the link to a non-recommended add-on
3) Notice the "not actively monitored" grey banner is present
=> Show the "not actively monitored" banner on Android as well

src/amo/components/WrongPlatformWarning/index.js, tests/unit/amo/components/TestWrongPlatformWarning.js, tests/unit/amo/pages/TestAddon.js
We already had the right message for non add-on detail pages, so removing the message specific to the add-on detail page is enough to address the issue.
This causes us to show what we want, which is, on android add-on detail pages visited from a Desktop browser, a link to download Firefox for Android and a link to switch to the desktop version of the page.
Fixes mozilla/addons#2205
=> Update wrong platform copy in add-on details pages when client app is "android"

docs/caching.md, src/amo/server/base.js, tests/unit/amo/server/test_base.js
See https://github.com/mozilla/addons/issues/14798 (fixes the frontend part)
You can try it locally by observing non-authenticated HTTP responses for frontend pages are served with `cache-control: max-age=0, s-maxage=360` instead of `cache-control: max-age=0, s-maxage=180`
=> Increase default caching duration of pages to 360 seconds

config/default.js, config/dev.js, config/development.js, config/lib/shared.js, config/stage.js
- https://developers.google.com/tag-platform/security/guides/csp#google_analytics_4_google_analytics
- https://developers.google.com/tag-platform/security/guides/csp#universal_analytics_google_analytics
Cf mozilla/addons#14799 (fixes frontend side)
To test this locally, run with the various configs (`yarn amo:dev` will test the development config, but for dev/stage/prod production builds you'll need to follow https://github.com/mozilla/addons-frontend/blob/master/README.md#running-builds-locally)
=> Update CSP config to follow docs for Google Analytics 4 + Universal Analytics

src/amo/addonManager.js, src/amo/api/abuse.js, src/amo/sagas/abuse.js, tests/unit/amo/api/test_abuse.js, tests/unit/amo/sagas/test_abuse.js, tests/unit/amo/test_addonManager.js
Fixes https://github.com/mozilla/addons/issues/14807
---
When the Firefox API isn't available, we fallback to a direct HTTP call to the API (as it is currently).
=> Use mozAddonManager.sendAbuseReport() to submit add-on abuse reports

src/amo/server/base.js, tests/unit/amo/server/test_base.js
Caching has been done through the CDN for a long time (and before that nginx had been upgraded & set up to support caching through the standard Cache-Control header anyway)
Our local environments don't use the CDN (or nginx, unless you set up addons-server, and even then you don't have the same setup as prod) so you'll have to trust me that this is truly obsolete. But you can check that responses from addons-frontend nodejs no longer contain the `X-Accel-Expires` header. It should change absolutely nothing.
Fixes mozilla/addons#14814
=> Remove obsolete references to nginx caching

src/amo/components/FeedbackForm/index.js
Fixes https://github.com/mozilla/addons/issues/14884
---
The fact that we cannot verify the internal state makes it hard to verify.
=> Reset illegal_subcategory field by setting it to an empty string

src/amo/components/AddonMoreInfo/index.js, src/amo/components/ReportAbuseButton/index.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/components/TestRatingManager.js
Fixes mozilla/addons#14874
As mentioned in the issue, the following links don't need to be followed by search engines and should have a `nofollow` set to avoid search engines spending crawl budget on them:
- Feedback page (link: Report this add-on)
- Privacy Policy page (link: Read the privacy policy for this add-on - if there is one for that add-on)
- EULA page (link: Read the license agreement for this add-on - if there is one for that add-on)
- (custom) License page (link: {license name})
Unit tests should be enough, but you can load an individual add-on detail page on your local machine to test this if you want. Note that you'll need to use one which has the relevant links enabled (so if you want everything, you need it to have a privacy policy, an EULA and a custom license set on the …
=> Add rel=nofollow to links to add-on misc info pages we're not indexing

src/amo/components/RatingsByStar/index.js, src/amo/pages/AddonReviewList/index.js, tests/unit/amo/components/TestRatingsByStar.js, tests/unit/amo/pages/TestAddonReviewList.js
Also add `rel=nofollow` to links to it filtering user reviews by score as it's useless for search engines to visit, it's the same content but filtered.
Fixes mozilla/addons#14873
=> Include canonical <link> for user review pages

src/amo/pages/Collection/index.js, tests/unit/amo/pages/TestCollection.js
Non-mozilla collections are disallowed in robots.txt
Fixes mozilla/addons#14887
=> Add canonical / alternate links for mozilla collections (and only those)

src/amo/components/Search/index.js, src/amo/components/SearchFilters/index.js, src/amo/constants.js, tests/unit/amo/pages/TestSearchPage.js
=> Remove obsolete/useless `Verified` badging filter in search

src/amo/pages/AddonVersions/index.js, tests/unit/amo/pages/TestAddonVersions.js
Fixes mozilla/addons#14942
Removes the 'latest version' block and replaces the 'older versions' block with a full version history for langpacks.
**Before**
**After**
=> Removed "Latest Version" Block from Add-on Version History for Langpacks

package.json, src/amo/api/search.js, src/amo/components/SearchFilters/index.js, src/amo/components/SearchFilters/styles.scss, src/amo/searchUtils.js, tests/unit/amo/pages/TestSearchPage.js
Fixes mozilla/addons#14971
Adds ability to filter search by color when searching through themes (need to select the `Add-on Type` or be on a theme category page, which filters by type behind the scenes).
The API side has been implemented years ago in https://github.com/mozilla/addons/issues/6257 but never used. It's not 100% perfect, we could tweak it, but should be good enough for a first iteration.
Using dev as the backend server (`yarn amo:dev`) it should work out of the box. Filter your search to only show themes and then choose a color. The last circle with the gradient allows any arbitrary color to be selected, making it possible to find pink or orange themes for instance.
=> Implement filtering of theme searches by color

src/amo/reducers/categories.js, src/amo/reducers/utils.js, src/amo/types/addons.js, tests/unit/amo/components/TestAddonMoreInfo.js, tests/unit/amo/pages/TestAddon-AddonSuggestions.js, tests/unit/amo/pages/TestSearchPage.js, tests/unit/amo/reducers/test_categories.js, tests/unit/helpers.js
Fixes mozilla/addons#2195
Since https://github.com/mozilla/addons/issues/4579 the v5 API has stopped returning per-application categories: the application property is gone in the category API, the add-on API returns a list instead of an object.
This should be a transparent change, see https://github.com/mozilla/addons/issues/2195#issuecomment-2328630067 for more details.
=> Remove code handling categories with an application

src/amo/components/FeedbackForm/index.js
That information _is_ required now, so that line no longer makes sense.
Fixes mozilla/addons#14988
=> Remove obsolete and now inaccurate line in feedback form

config/default.js, src/amo/components/ServerHtml/index.js
Fixes https://github.com/mozilla/addons/issues/14951
Needs https://github.com/mozilla/addons-server/pull/22650
=> Update favicon query string to bust cache and reference new Firefox logo favicon

src/amo/languages.js
Saraiki locale was added to Firefox starting from 128. The locale needs to be added in order to make the language available in the Language Tools page.
This adds the following:
Locale: skr
English: Saraiki
Native: سرائیکی
=> l10n - add Saraiki (skr) to languages.js

src/amo/pages/Block/index.js, tests/unit/amo/pages/TestBlock.js
Fixes https://github.com/mozilla/addons/issues/15051
=> Mark block reason as an en-US English paragraph

src/amo/pages/Block/index.js, src/amo/reducers/blocks.js, tests/unit/amo/pages/TestBlock.js, tests/unit/helpers.js
=> Expose whether a version is soft or hard-blocked in the blocked page

locale/ko/LC_MESSAGES/amo.po
This should only revert two strings. This might not be the right fix, but I am not sure what else to do...
=> Revert some of the latest changes to the ko PO file to fix test failures

.github/dependabot.yml
Fixes mozilla/addons#15203
addons-frontend uses https://github.com/faisalman/ua-parser-js and version 2.x of that library is still under development, but it [has breaking changes](https://github.com/faisalman/ua-parser-js/blob/master/CHANGELOG.md), including a license change that might be an issue for us. Let's make sure we don't accidentally upgrade yet.
=> Prevent dependabot from offering us to upgrade to UAParser 2.x

src/amo/components/SearchResult/index.js, src/amo/pages/Addon/index.js, src/blog-utils/StaticAddonCard/index.js, tests/unit/amo/pages/TestAddon.js, tests/unit/blog-utils/TestStaticAddonCard.js
Relates to mozilla/addons#15254
Changes the add-on summary to render just as plaintext. Linebreaks are not supported.
=> Render Add-on Summary as Plaintext

src/amo/sagas/addonsByAuthors.js, tests/unit/amo/sagas/test_addonsByAuthors.js
Fixes mozilla/addons#15287
We were not customizing the `sort` when calling that saga from the card, and it doesn't make sense to default to trending anyway (it's not a really useful sort outside of the home/landing page) for fetching add-ons by author, so I changed the default in the saga.
To test, alter the `hotness` and `average_daily_users` values for add-ons that would show up and wait for reindex (+ caching to expire, if logged out). Then load an add-on and look at the "More extensions by..." box on the left.
Example right now with https://addons-dev.allizom.org/en-US/firefox/addon/ublock-origin_testdev/ (both values for each add-on will be overridden tomorrow though):
=> When fetching add-ons by author, sort by popularity by default instead of trending

bin/push-locales
On addons-server, there are 2 `.pot` files (`django.pot`, `djangojs.pot`) so the extraction always create 2 lines of changes across 2 files. On addons-frontend there is only one, so the diff threshold must be set differently.
Fixes mozilla/addons#15127
=> Don't push locales changes if there are no substantial changes

src/amo/components/AddonReviewCard/index.js, src/amo/pages/UserFeedback/index.js, src/amo/pages/UserProfile/index.js, src/amo/pages/UserProfileEdit/index.js, src/amo/reducers/users.js, tests/unit/amo/components/TestAddonReviewCard.js, tests/unit/amo/pages/TestUserProfile.js, tests/unit/amo/pages/TestUserProfileEdit.js
Fixes mozilla/addons#15403
Shows user account links for all ratings, and hides the fields that won't be present on the user profile page.
before
(before https://github.com/mozilla/addons/issues/15402 changed the API it would have been a 404)
after
before
after
=> linkify all user names on ratings list; handle an account response with undefined fields

src/amo/purify.js, tests/unit/amo/utils/test_index.js
Fixes https://github.com/mozilla/addons/issues/14989
This matters when displaying the versions page, where each version is in a `<li>` already, and developers can have release notes containing `<li>` of their own. This can be seen:
- On dev: https://addons-dev.allizom.org/en-US/firefox/addon/ratopuse-weasp-vulturkal/versions/
- On prod: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/
(Look at the output carefully, the HTML from the footer is duplicated, the "clone" appearing either in the sidebar or on top of the existing footer)
You have to manually craft HTML with `<li>` and no parent `<ul>` and get it passed to our sanitize functions to test this. That is harder to achieve now that we have markdown, so best to modify the entry in the database, or …
=> Ensure <li>s are wrapped in a <ol> or <ul> after sanitizing HTML

src/amo/components/ShowMoreCard/styles.scss, src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss, tests/unit/amo/pages/TestAddon.js
Change the logic around when to show the "Read More" link for the Description area when it's over 300px like permissions, instead of always showing the full content.
Fixes https://github.com/mozilla/addons/issues/15463
- Try navigating to an add-on detail page with a small description: it should be fully displayed without "Read More"
- Try navigating to an add-on detail page with a large enough description to be more than 300px height: it should be displayed behind "Read More" regardless of screen size
- Repeat with developer comments added into the mix, note that they no longer have their own card but instead are shown inside "About this add-on" after the description.
- The other uses of `ShowMoreCard`, like permissions, shouldn't regress.
On a local env with dev data (`yarn amo:dev`), …
=> Move Developer Comments to "About this add-on" area & tweak "Read More" behavior

src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss, tests/unit/amo/pages/TestAddon.js
And not just if there is a description, now that the developer comments are part of this area as well.
Follow-up fix for https://github.com/mozilla/addons/issues/15463#issuecomment-2841273057
Fixes mozilla/addons#15592
=> Show "About this add-on" area if there are developer comments

src/amo/components/Badge/styles.scss
Fixes: mozilla/addons#15679
- badge font size should be 12px or 16px for small/large badges
- there should be a appropriate padding on badge content
- there should be a 6px gap between badge content and icon.
TBD
=> Fix spacing and sizing of Badge and Badge Content

src/amo/components/ThemeImage/styles.scss, src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss
fixes: mozilla/addons#15685
Fix layout for theme details page switching between inline thumbnail and full row theme preview
https://github.com/mozilla/addons-frontend/pull/13638 introduced a regression for themes that render a 720px width theme preview. This doesn't fit in our left column thumbnail section.
Run dev mode
```bash
yarn amo:dev
```
Check both URLs on various breakpoints, should scale from stacked to grid layout and on theme addons the theme preview should always be above the header content (within the header card)
https://github.com/user-attachments/assets/4f8fac5f-0ea4-4d03-ad50-d5ccdb94623c
https://github.com/user-attachments/assets/c2f1eecd-b824-480c-907b-cb76ea440c42
https://github.com/user-attachments/assets/a69cf162-9623-4075-9a18-983ec8e2064f
=> Fix broken theme thumbnail (quick fix)

src/amo/components/AddonReviewCard/styles.scss, src/amo/components/Rating/styles.scss, src/amo/components/RatingManager/index.js, src/amo/components/RatingManager/styles.scss, src/amo/pages/Addon/index.js, tests/unit/amo/components/TestRatingManager.js, tests/unit/amo/pages/TestAddon.js
Fixes mozilla/addons#15684
Adjusts the label, header, and stars for the rating card, and includes the breakdown.  I reduced the star size or the "click to rate" label looked tiny in comparison, (and had to add bottom margins to make it look non-terrible), but otherwise left styling changes for phase 2.
I couldn't see anything in particular in the spec about the logged out view; adding review text, or deleting ratings/reviews, so those are as now.
logged out at 900px:
logged in at 900px:
card at 500px
card at 720px (the "click..." text is only wrapped because the card is size-constrained - when we move to single column it won't happen)
card at 900px
card at 1150px:
video
https://github.com/user-attachments/assets/a12c31ea-16bc-43fc-830a-73980d13d410
=> Adjust rating card layout and show rating breakdown

src/amo/components/AddonRecommendations/styles.scss, src/amo/components/AddonsByAuthorsCard/styles.scss, src/amo/pages/Addon/index.js
Fixes mozilla/addons#15631 and fixes mozilla/addons#15627
Moves Recommendations (aka Other popular extensions) and Permissions cards to their eventual final position in the new detail page layout.  
Also adjusts the number of columns to match figma (2 at large, 3 at extraLarge) - and repeats that style adjustment for the extensions by author card for consistency (author card is not shown on the figma, so it remains at it's old position, at the bottom of the page)
=> move Recommendations and Permissions cards; set to 3 columns

src/amo/components/DefinitionList/index.js, src/amo/components/DefinitionList/styles.scss
An alternative would have been to set break-after: avoid(-column) on the <dt> but that's not supported by Firefox yet.
Fixes mozilla/addons#15726
=> Wrap <dl> contents and avoid breaking columns inside

src/amo/components/RatingManager/index.js, src/amo/components/ShowMoreCard/styles.scss, src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss
Fixes https://github.com/mozilla/addons/issues/15733
- Stopped displaying "Click to rate" text if not logged in (it was overlapping with the "Log in to rate this extension" in some sizes, and obviously redundant)
- Reduced margin between cards overall in larger breakpoint to reduce wasted vertical space since the card layout is going away soon anyway
- Added some min/max widths where appropriate
- Moved overall ratings and description in a wrapper card, and let both be displayed side by side are higher resolutions
- Overrode the rounded corners on both cards as a result, the rounded corners are coming from the wrapper now
- Tweaked description area height before triggering "Read more"
Because the final design doesn't have the card-style layout with rounded corners etc I had to improvise a …
=> Combine overall ratings with about card at extraExtraLarge breakpoint

config/dev.js, config/development.js, config/lib/shared.js
Fixes mozilla/addons#15687 again
I stupidly changed the name of the `langs` config to `lang` while refactoring
=> `langs` not `lang`

src/amo/pages/StaticPages/About/index.js
Fix https://github.com/mozilla/addons/issues/15774.
This removes amo-admins as a destination to report security issues. Bugzilla remains and is a better way to handle them.
=> Remove amo-admins for filing security issues

src/amo/searchUtils.js, tests/unit/amo/test_searchUtils.js
Companion to https://github.com/mozilla/addons/issues/15814
Allows using `created` and `updated` threshold parameters in the search page by modifying the URL.
`http://localhost:3000/en-US/firefox/search/?created__gte=2025-01-01` for instance locally should only return add-ons created in 2025.
=> Pass updated/created threshold query parameters to search API

src/amo/pages/Addon/index.js, tests/unit/amo/pages/TestAddon.js
=> Remove AddonsByAuthor (more extensions by) card from addons detail page

src/amo/pages/Addon/index.js, src/amo/pages/Addon/styles.scss
Fixes https://github.com/mozilla/addons/issues/15862
---
This is the first step to have a unified body. We'll figure out the exact spacing/sizes in a different patch.
(1) Before: https://addons-dev.allizom.org/fa/firefox/addon/cas-current-theme-1/
After:
---
(2) Before: https://addons-dev.allizom.org/en-US/firefox/addon/release-lang-pack777/
After:
---
(3) Before: https://addons-dev.allizom.org/en-US/firefox/addon/just-recommended-for-firefox/
After:
---
(4) Before: https://addons-dev.allizom.org/en-US/android/addon/mixed-unlisted-pending-rej/
After:
---
(5). Before: https://addons-dev.allizom.org/en-US/firefox/addon/dark22reader/
After:
=> Unify most detail page components in a single card

jest.config.js, package.json, src/amo/components/ScreenShots/index.js, tests/unit/amo/components/TestScreenShots.js, yarn.lock
Refs https://github.com/mozilla/addons/issues/2030
---
This is the first step to get captions in the screenshot viewer.
~~The only change I've noticed is that the lightbox background is less dark than before, which we can easily address if needed.~~ fixed
=> Upgrade PhotoSwipe

src/amo/pages/Addon/styles.scss
Fixes https://github.com/mozilla/addons/issues/15866
---
Each commit does something a bit different. The biggest one is probably the "simplify grid" one, which simplifies the grid and make things a bit better overall.
=> Update style of the add-on header in the detail page

src/amo/pages/Addon/styles.scss, src/amo/pages/LandingPage/styles.scss
Fixes https://github.com/mozilla/addons/issues/15871
---
Before:
After:
=> Fix margin bottom on some pages
