- README.md
- package.json
- src/amo/api/addonInfo.js
- src/amo/components/CollectionDetails/index.js
- src/amo/components/EditableCollectionAddon/index.js
- src/amo/components/ReportUserAbuse/index.js
- src/amo/components/SearchResult/index.js
- src/amo/components/UserProfileEditPicture/index.js
- src/amo/pages/UserProfile/index.js
- src/amo/pages/UserProfileEdit/index.js
- src/core/installAddon.js
- src/core/store.js
- src/core/tracking.js
- src/disco/components/AddonCompatibilityError/index.js
- src/ui/components/UserReview/index.js
- yarn.lock
Thanks for opening a Pull Request (PR), here's a few guidelines as to what we need in your PR before we review it.
Please delete anything that isn't relevant to your patch.
Once you have met the above requirements please replace this section with a `Fixes #ISSUENUM` linking to the issue fixed by this PR along with an explanation of the changes. Thanks for your contribution!
> Greenkeeper/prettier 1.15.1

- src/amo/pages/UserProfile/index.js
- src/amo/pages/UserProfile/styles.scss
- src/core/constants.js
- tests/unit/amo/pages/TestUserProfile.js
> Add admin user link to user profile page

- config/default-amo.js
- config/dev-amo.js
- config/development-amo.js
> Enable installButtonColor experiment in all AMO envs

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/App/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SectionLinks/index.js
- src/amo/components/SuggestedPages/index.js
- src/amo/pages/CategoriesPage/index.js
- src/amo/pages/Category/index.js
- src/amo/pages/Home/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/utils.js
- src/amo/utils/errors.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/components/TestSectionLinks.js
- tests/unit/amo/components/TestSuggestedPages.js
- tests/unit/amo/pages/TestCategoriesPage.js
- tests/unit/amo/pages/TestCategory.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/test_utils.js
- tests/unit/amo/utils/test_errors.js
- tests/unit/amo/utils/test_index.js
Fixes #6689
---
I believe everything is covered. I tried to browse this version locally and I cannot get any static themes stuff.
> Static themes and Android

- src/amo/components/App/index.js
- src/amo/components/AutoSearchInput/index.js
- src/amo/components/CollectionAddAddon/index.js
- src/amo/components/Header/index.js
- src/amo/components/SearchForm/index.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestSearchForm.js
Fixes #6771
---
This PR also updates some related files.
> Remove `componentWillReceiveProps()` in `AutoSearchInput`

- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
> Do not render featured theme collections on Android

- src/amo/pages/Addon/index.js
- src/core/reducers/versions.js
- src/core/types/addons.js
- src/core/utils/compatibility.js
- src/disco/components/Addon/index.js
- src/disco/components/AddonCompatibilityError/index.js
- src/disco/store.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/reducers/test_versions.js
- tests/unit/core/utils/test_compatibility.js
- tests/unit/disco/components/TestAddon.js
- tests/unit/disco/helpers.js
- tests/unit/disco/test_store.js
> Update compatibility.js to work with a specific version

- src/amo/components/HomeHeroBanner/index.js
- src/core/withExperiment.js
- tests/unit/amo/components/TestHomeHeroBanner.js
> I6538 remove ab exp/logs from homepg

- src/amo/pages/Addon/index.js
- src/core/components/AMInstallButton/index.js
- src/core/reducers/versions.js
- src/disco/components/Addon/index.js
- tests/unit/core/components/TestAMInstallButton.js
> Convert AMInstallButton to use platformFiles from currentVersion

- src/amo/components/AddonHead/index.js
- src/amo/components/HeadMetaTags/index.js
- tests/unit/amo/components/TestAddonHead.js
- tests/unit/amo/components/TestHeadMetaTags.js
> Create a `HeadMetaTags` component

- src/amo/components/AddonHead/index.js
- src/amo/pages/Addon/index.js
- src/core/installAddon.js
- src/core/utils/addons.js
- tests/unit/amo/components/TestAddonHead.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/test_installAddon.js
- tests/unit/core/utils/test_addons.js
> Update core/utils/addons.js to use a direct version

- tests/ui/requirements/requirements.txt
- tests/ui/tests/test_discopane.py
> Install static theme in ui tests

- tests/unit/core/test_installAddon.js
Fixes #6894
---
This PR fixes a bunch of test cases to support both #6894 and #6727.
> Refactor some tests in test_installAddon

- config/default.js
Looks like we forgot this occurrence.
> remove unused config param

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Addon should be able to render without a version

- src/amo/reducers/landing.js
- src/amo/sagas/landing.js
- src/core/reducers/versions.js
- tests/unit/amo/reducers/test_landing.js
- tests/unit/amo/sagas/test_landing.js
- tests/unit/core/reducers/test_versions.js
> change landing constants

- docs/telemetry.md
- src/core/tracking.js
- tests/unit/core/test_tracking.js
> Add origin to HCT collection

- src/amo/components/HomeHeroGuides/index.js
- src/amo/pages/Guides/index.js
- tests/unit/amo/pages/TestGuides.js
> I6744 guide pgs remaining content

- src/core/tracking.js
> Add Flow types to the tracking code

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/GuidesAddonCard/index.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestGuidesAddonCard.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/helpers.js
> Allow AddonCompatiblityError to determine its own compatibility

- src/core/components/AMInstallButton/index.js
- tests/unit/core/components/TestAMInstallButton.js
> Allow AMInstallButton to work with a null currentVersion

- src/core/reducers/abuse.js
- tests/unit/core/reducers/test_abuse.js
> Add full flow coverage to abuse reducer

- src/amo/components/AddonCompatibilityError/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
> Do not show a notice from TestAddonCompatibilityError when the browser is not Firefox

- src/core/api/categories.js
- src/core/api/index.js
- src/core/sagas/categories.js
- tests/unit/core/api/test_categories.js
- tests/unit/core/api/test_index.js
- tests/unit/core/sagas/test_categories.js
> Update categories API

- config/default-disco.js
- config/dev-disco.js
- config/development-disco.js
> Enable HCT for the disco pane in production

- src/amo/components/GuidesAddonCard/index.js
- src/amo/components/GuidesAddonCard/styles.scss
- tests/unit/amo/components/TestGuidesAddonCard.js
> I6990 makes guides addons titles linkable

- src/core/api/versions.js
- src/core/reducers/versions.js
- src/core/sagas/versions.js
- src/core/types/addons.js
- tests/unit/core/api/test_versions.js
- tests/unit/core/reducers/test_versions.js
- tests/unit/core/sagas/test_versions.js
> Provide the ability to retrieve and load a single version

- src/amo/pages/Guides/index.js
- src/amo/reducers/guides.js
- tests/unit/amo/pages/TestGuides.js
- tests/unit/amo/reducers/test_guides.js
> I6928 guides pg dble load fix

- src/amo/components/GetFirefoxButton/index.js
- src/amo/pages/Addon/index.js
- src/core/components/AMInstallButton/index.js
- src/core/utils/compatibility.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/components/TestAMInstallButton.js
- tests/unit/core/utils/test_compatibility.js
> Implement an isFirefox function in compatibiliy.js

- .gitignore
- package.json
- stories/setup/config.js
- stories/setup/webpack.config.babel.js
- webpack-common.js
- yarn.lock
Fixes #6955 
---
Some commits come from #7009.
~~The build step has been fixed, but the `Badge` component does not list the props anymore...~~ This has been fixed.
> Storybook upgrade

- src/amo/components/AddonInstallError/index.js
- src/amo/components/AddonInstallError/style.scss
- src/amo/components/GuidesAddonCard/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/Addon/styles.scss
- src/amo/pages/Guides/styles.scss
- tests/unit/amo/components/TestAddonInstallError.js
- tests/unit/amo/components/TestGuidesAddonCard.js
- tests/unit/amo/pages/TestAddon.js
> I6902 extracting out installError component

- src/amo/pages/Guides/index.js
> I7048 rearranging addons order on media guide pg

- src/amo/components/AddonMoreInfo/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/AddonInfo/index.js
- src/core/reducers/versions.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestRoutes.js
- tests/unit/amo/pages/TestAddonInfo.js
- tests/unit/core/reducers/test_versions.js
Fixes #3697 
~~Depends on #7016~~
>  Implement a Custom License page 

- package.json
- src/core/errors.js
- src/core/utils/index.js
- yarn.lock
> Remove es6-error

- tests/unit/amo/pages/TestGuides.js
I think this was mostly fixed in #7022. This is just small nits..
fixes #6945
> I6945 test guides

- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/GuidesAddonCard/index.js
- src/amo/components/GuidesAddonCard/styles.scss
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/components/InstallButtonWrapper/styles.scss
- src/amo/pages/Addon/index.js
- src/core/components/AMInstallButton/index.js
- src/core/installAddon.js
- src/disco/components/Addon/index.js
- src/disco/pages/DiscoPane/index.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/components/TestGuidesAddonCard.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/test_installAddon.js
- tests/unit/disco/components/TestAddon.js
> Extract code to display install button and Get Firefox button

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonReviewManager/index.js
- src/core/utils/i18n.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAddonReviewManager.js
- tests/unit/core/utils/test_i18n.js
> I6983-refactor w/ text and link helper

- src/amo/components/HomeHeroBanner/index.js
- src/amo/pages/Home/index.js
> Update homepage for December 13rd

- src/amo/components/GuidesAddonCard/index.js
> I7101 change guides button text

- src/amo/pages/Guides/index.js
fixes #7098 
fixes #7099 
fixes #7100
> guides pages edits

- src/core/i18n/utils.js
- src/core/reducers/versions.js
- src/core/utils/compatibility.js
- tests/unit/core/reducers/test_versions.js
> Enhance getVersionInfo to return more information needed by the Versions page

- tests/ui/run-functional-tests.sh
Should fix the ```integration-test``` job that is failing in CircleCI
> Updates to script to match -server changes.

- src/amo/components/Routes/index.js
- src/amo/pages/Collection/index.js
- tests/unit/amo/pages/TestCollection.js
Fixes #7137
~~:warning: depends on #7136~~
---
More renaming before starting the real work!
> User `userId` instead of `username` in collection routes

- tests/ui/run-functional-tests.sh
Builds on #7160, I removed the build step by accident.
> Re-add build step.

- src/amo/components/HomeHeroGuides/index.js
- src/amo/components/HomeHeroGuides/styles.scss
- src/amo/pages/Guides/index.js
- tests/unit/amo/components/TestHomeHeroGuides.js
- tests/unit/amo/pages/TestGuides.js
> I7026 adding check for clientApp type for guide blocks/pages

- README.md
Fixes https://github.com/mozilla/addons-frontend/issues/7198
> yarn amo:dev is the preferred way to develop

- src/amo/components/AddonVersionCard/index.js
- src/amo/components/AddonVersionCard/styles.scss
- tests/unit/amo/components/TestAddonVersionCard.js
> Create an AddonVersionCard

- src/amo/pages/Guides/index.js
> updating guides guid

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Pass prefixed guid in utm_content for return to AMO

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/AddonVersionCard/index.js
- src/amo/components/AddonVersionCard/styles.scss
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/AddonVersions/index.js
- src/amo/pages/AddonVersions/styles.scss
- src/core/api/versions.js
- src/core/sagas/versions.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestAddonVersionCard.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/components/TestRoutes.js
- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/core/sagas/test_versions.js
Fixes #2770 
Screenshots:
An add-on with multiple versions:
An add-on with multiple versions, where one is incompatible:
An add-on with no versions (an edge-case, only viewable by administrators):
> Implement the All Versions page

- src/amo/components/HomeHeroGuides/styles.scss
> I7248 guides mobile style fix

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Use `base64.encode` on valid values

- src/amo/components/ErrorPage/NotFound/index.js
- tests/unit/amo/components/ErrorPage/TestNotFound.js
> Update copy of the not found page

- src/amo/components/AddonReviewManager/index.js
- src/amo/components/AddonReviewManager/styles.scss
- tests/unit/amo/components/TestAddonReviewManager.js
> I6236 Update AddonReviewManager to use RatingManagerNotification 

- src/amo/pages/AddonReviewList/index.js
- tests/unit/amo/pages/TestAddonReviewList.js
This reverts commit 0e48636f6bd13759b3f42775b5d1d4a55ea42357, pushed to `master` by mistake. This commit will be proposed as a Pull Request instead.
> Revert "Do not dispatch action when an error has occured"

- src/amo/components/ErrorPage/NotFound/index.js
> Minor update on 404 page

- src/amo/components/AddonSummaryCard/styles.scss
- src/amo/components/RatingsByStar/styles.scss
> Use flex-start/flex-end

- src/amo/components/GuidesAddonCard/index.js
- src/amo/components/GuidesAddonCard/styles.scss
- src/amo/pages/Guides/index.js
- src/amo/pages/Guides/styles.scss
- tests/unit/amo/components/TestGuidesAddonCard.js
- tests/unit/amo/pages/TestGuides.js
> I6900 guides pages with LoadingText

- src/amo/components/AddonReviewCard/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
> Do not attempt to create a link to a review that has an empty reviewAddon.slug

- src/amo/components/CollectionDetailsCard/index.js
- src/core/constants.js
- tests/unit/amo/components/TestCollectionDetailsCard.js
Fixes #7325 
---
This PR updates the collection code for editing Mozilla collections.
> Fix mozilla collection editing

- src/amo/components/SectionLinks/styles.scss
> Hiding the border line around the menu

- src/amo/components/RatingManagerNotice/styles.scss
Fixes #7355
---
Not sure why I did not catch that earlier...
> Fix CSS for RatingManagerNotice

- src/disco/reducers/telemetry.js
- src/disco/store.js
- tests/unit/core/reducers/test_telemetry.js
- tests/unit/disco/test_store.js
> I7369-setting up telemetry reducer

- src/amo/components/AddonVersionCard/styles.scss
Fixes #7346 
cc @bobsilverberg 
Sorry for recreating the PR , last one https://github.com/mozilla/addons-frontend/pull/7372 was closed due to my mistake  , I did forced push by mistake to the branch 
After:
> Fixing style add to FF button on small screens on versions page

- src/amo/components/SearchForm/index.js
- tests/unit/amo/components/TestSearchForm.js
> Add opensearch meta 3836

- src/amo/pages/Collection/index.js
- tests/unit/amo/pages/TestCollection.js
> Fix error with username in collection URLs

- config/default-disco.js
- config/default.js
- config/dev-disco.js
- config/development-disco.js
Fixes #7445
---
~~follow up to #7218~~ 
see https://github.com/mozilla/addons-frontend/issues/7218#issuecomment-455609361
> I7218 enabling taar header for all of disco

- config/dev-amo.js
- config/development-amo.js
> Enable ST in -dev

- src/amo/components/AddonsCard/index.js
Fixes #7450
---
Before:
After:
> Fix theme pages

- src/core/searchUtils.js
- tests/unit/core/test_searchUtils.js
~~:warning: Depends on #7454~~ – Fixes #7410
> Return ST in search results (Android)

- tests/ui/run-functional-tests.sh
> Add new -server javascript steps to circleci integration test job.

- config/default-amo.js
- config/default.js
- stories/setup/webpack.config.babel.js
- webpack-common.js
> I7468 fixing broken storybook

- src/amo/components/SearchContextCard/index.js
- tests/unit/amo/components/TestSearchContextCard.js
> I6531 search result title update

- config/default-amo.js
- config/default.js
- src/core/components/AMInstallButton/index.js
- src/core/components/AMInstallButton/styles.scss
- tests/unit/core/components/TestAMInstallButton.js
Fixes #7486 
Removes install button A/B experiment and keeps install button blue always.
> Fixes #7486 - removes install button experiment

- src/amo/components/UserProfileEditNotifications/index.js
- tests/unit/helpers.js
> Remove option for notifications related to addon-sdk

- src/amo/components/CollectionManager/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestCollectionManager.js
> Restrict collection slug to 30 char

- src/disco/components/Addon/styles.scss
> Fix disco layout with long strings

- locale/pt_BR/LC_MESSAGES/amo.po
> fixing locale bug

- src/amo/components/CollectionManager/styles.scss
Added 2px Margin Between Buttons
> Fixes #7529: Added 2px Margin Between Buttons

- src/core/languages.js
Fixes #7556
---
I uploaded an add-on in -dev so that we can prove the fix works.
> Add Guarani lang

- .travis.yml
- tests/ui/requirements/requirements.txt
> Upgrade Geckodriver and FoxPuppet

- src/disco/pages/DiscoPane/index.js
- tests/unit/disco/pages/TestDiscoPane.js
Fixes #7573 
---
This patch makes sure we pass the client ID to the API only when browser version is >= 65.0.1.
> Do not pass the client ID to the API when browser version is < 65.0.1

- locale/pt_BR/LC_MESSAGES/amo.po
> Change order of the linkStart/linkEnd params in a localized pt-BR string

- src/disco/components/Addon/styles.scss
Fixes #7580 
Fixed
https://github.com/mozilla/addons-frontend/issues/7580#issuecomment-465631237
> Fixes #7580: Updated Property value

- src/amo/pages/Home/index.js
> Homepage update 28 Feb

- config/default-amo.js
Fixes https://github.com/mozilla/addons/issues/924
> Sync validLocaleUrlExceptions & validClientAppUrlExceptions w/ addons-server

- config/default-amo.js
> Re-sync valid(Locale|ClientApp)UrlExceptions w/ addons-server

- tests/ui/run-functional-tests.sh
Should fix #6906 
This updates the script to match how addons-server starts and runs the tests.
> Update uitest script for CI.

- .circleci/config.yml
- tests/ui/run-functional-tests.sh
I hope this is the last PR for this...
> Add uuid and fix docker command for integration tests.

- tests/ui/run-functional-tests.sh
> Add sysctl command for docker vm's.

- config/default.js
This should fix the broken builds.
> Add pa-IN locale

- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
> Update homepage for March 21st

- tests/ui/run-functional-tests.sh
> Move env variable declaration.

- bin/loading-page.html
- src/amo/components/Footer/index.js
- src/amo/components/Header/index.js
- src/amo/components/Header/styles.scss
- tests/unit/amo/components/TestFooter.js
- tests/unit/amo/components/TestHeader.js
> Add Extension Workhop link to header and Footer 

- locale/th/LC_MESSAGES/amo.po
> Fix th locale

- locale/es/LC_MESSAGES/amo.po
- locale/kab/LC_MESSAGES/amo.po
- tox.ini
Fixes #7797
Adding this dennis command to the tests should prevent this happening again.
> Detect localization errors detected as W202 warnings by Dennis

- CODE_OF_CONDUCT.md
> Update Code of Conduct (fixes #7795)

- README.md
- package.json
- src/amo/components/SearchFilters/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
- tests/unit/core/components/TestAMInstallButton.js
Fixes #7823
The first commit should fail the tests. Once that's proven, prettier can be run to catch-up the files that have been missed.
> Update prettier check

- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
> Update homepage for 11 April

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
- src/amo/components/Footer/index.js
- src/amo/components/Header/index.js
- tests/unit/amo/components/TestFooter.js
- tests/unit/amo/components/TestHeader.js
Fixes #7812
---
There is no EW -dev environment yet, so I use the stage URL for -dev and local dev.
> Link Extension Workshop dev and stage environments to AMO

- src/amo/pages/SearchTools/index.js
- tests/unit/amo/pages/TestSearchTools.js
> Sort by ratings by default on SearchTools page

- src/amo/reducers/users.js
- src/amo/sagas/users.js
- tests/unit/amo/reducers/test_users.js
- tests/unit/amo/sagas/test_users.js
Fixes #7853
~~⚠️ depends on #7854 and #7844~~
---
This patch adds the reducer/saga logic for the unsubscribe page.
> Unsubscribe reducer

- src/amo/pages/UserProfileEdit/index.js
- src/amo/pages/UserProfileEdit/styles.scss
- src/amo/reducers/users.js
- tests/unit/amo/pages/TestUserProfileEdit.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/7806
> Allow reviewers to change their reviewer name when editing their profile

- tests/ui/run-functional-tests.sh
Forgot to add this change when this script was added on `-server`.
> Add auto_approve script command.

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Allow accessing product page by add-on ID

- tests/ui/tests/test_discopane.py
> Installing themes seem to require a confirmation step now

- src/amo/components/RatingsByStar/index.js
- tests/unit/amo/components/TestRatingsByStar.js
Fixes #7216 
I made the rating bar clickable, but not sure it is the right way to do it...
> Making rating bar clickable #7216

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> Avoid infinite setState() calls when user logs out

- src/amo/components/AddonVersionCard/index.js
- src/core/reducers/versions.js
- tests/unit/amo/components/TestAddonVersionCard.js
> Fallback to a default license name when it is null

- src/amo/components/AutoSearchInput/index.js
Fixes #7604 
Allow searching for 1 or 2
> Allow searching for 1 or 2

- src/amo/pages/Home/index.js
> Update home for next push

- src/amo/pages/Addon/index.js
- src/amo/pages/AddonInfo/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/AddonVersions/index.js
- src/amo/pages/Guides/index.js
- src/core/reducers/addons.js
- src/disco/components/Addon/index.js
- tests/unit/core/reducers/test_addons.js
> Refactor addon state selectors to take AddonsState

- src/ui/components/RecommendedBadge/index.js
> Update hover text for RecommendedBadge component

- src/amo/components/AddonBadges/index.js
- tests/unit/amo/components/TestAddonBadges.js
> Only show recommended badge for extensions

- src/amo/components/Search/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SearchFilters/styles.scss
- src/amo/components/SearchResults/index.js
- src/core/api/search.js
- src/core/searchUtils.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/components/TestSearchResults.js
> Replace "Featured" with "Recommended" in AMO Search

- locale/ja/LC_MESSAGES/amo.po
> Fix ja locale file

- src/amo/components/AddonsCard/index.js
- src/amo/components/LandingAddonsCard/index.js
- src/amo/components/SearchResult/index.js
- src/amo/components/SearchResult/styles.scss
- tests/unit/amo/components/TestAddonsCard.js
- tests/unit/amo/components/TestSearchResult.js
~~Depends on #7959~~
Fixes #7793 
It probably makes sense to wait until #7959 lands to review this.
Screenshot:
> Show recommended badge on search results page

- src/amo/components/AddonBadges/index.js
- src/amo/components/AddonBadges/styles.scss
- src/ui/components/RecommendedBadge/styles.scss
- tests/unit/amo/components/TestAddonBadges.js
> Display a recommended badge for all add-on types, and hide the featured badge for all add-on types

- src/amo/components/SearchSuggestion/index.js
- tests/unit/amo/components/TestSearchSuggestion.js
> Do not show Recommended icon in autocomplete results on Android

- src/amo/components/Categories/index.js
- src/core/constants.js
- tests/unit/amo/components/TestCategories.js
> Replace Category pages with search results pages

- src/amo/pages/LandingPage/index.js
- src/amo/reducers/landing.js
- src/amo/sagas/landing.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/reducers/test_landing.js
- tests/unit/amo/sagas/test_landing.js
> Include only recommended add-ons on the Extensions landing page

- src/amo/components/Categories/index.js
- src/amo/pages/Home/index.js
- tests/unit/amo/components/TestCategories.js
- tests/unit/amo/pages/TestHome.js
> Change the links from the theme category shelf on the home page to Search Results

- src/amo/components/Categories/index.js
- src/core/server/base.js
- src/core/utils/index.js
- tests/unit/amo/components/TestCategories.js
- tests/unit/core/server/test_base.js
- tests/unit/core/utils/test_index.js
> Redirect category URLs to the Search Results page

- src/amo/constants.js
- src/amo/pages/LandingPage/index.js
- src/amo/reducers/landing.js
- src/amo/sagas/landing.js
- src/core/reducers/versions.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/reducers/test_landing.js
- tests/unit/amo/sagas/test_landing.js
- tests/unit/core/reducers/test_versions.js
Fixes #8028 
~~Depends on #8090~~
> Replace Featured shelves with Recommended shelves

- src/amo/pages/Home/index.js
- src/amo/pages/Home/styles.scss
- src/amo/reducers/home.js
- src/amo/sagas/home.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/sagas/test_home.js
- tests/unit/core/reducers/test_versions.js
> Update homepage to work with recommended add-ons

- src/ui/components/RecommendedBadge/index.js
> Update link from Recommended Badge to point to correct SUMO article

- src/core/server/base.js
- tests/unit/core/server/test_base.js
> Removes the redirection of url's code

- src/amo/components/SearchResult/index.js
- src/amo/components/SearchResult/styles.scss
- src/ui/components/RecommendedBadge/index.js
- tests/unit/amo/components/TestSearchResult.js
- tests/unit/ui/components/TestRecommendedBadge.js
> Allow recommended badge to be a link on the SearchResult component

- src/amo/components/AddonCompatibilityError/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
> Fix correct project name for Fenix in AMO

- src/amo/components/AddonCompatibilityError/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
> Do not render an error on the server for opensearch add-ons

- src/amo/pages/LanguageTools/index.js
- tests/unit/amo/pages/TestLanguageTools.js
Fixes #7702
Checked if the hiliguyon spell checker is showing or not above the hindi spell checker.
@willdurand Test case is working now.
> Test case is working for the issue #7702

- src/amo/pages/StaticPages/About/index.js
Fixes #8245
Spelling typo fixed.
"publically" should be "publicy"
> Fixes #8245

- tests/ui/requirements/flake8.txt
> Temporarily install pydocstyle < 4.0.0

- config/default.js
- config/dev-amo.js
- config/development-amo.js
> Enable recommended badges in all environments

- src/ui/components/RecommendedBadge/index.js
- tests/unit/ui/components/TestRecommendedBadge.js
> Do not add visually hidden Recommended text for RecommendedBadge component

- src/amo/components/AutoSearchInput/index.js
- tests/unit/amo/components/TestAutoSearchInput.js
> Do not pass a `random` sort filter from AutoSearchInput

- src/amo/components/SearchFilters/index.js
- src/core/api/search.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/core/api/test_search.js
> Fix search filters when recommended/featured checkbox is unchecked

- .circleci/config.yml
> Update pip before using it in circle-ci

- src/amo/components/EditableCollectionAddon/index.js
Fixes #5395 
In View mode :
In Edit mode :
> Updated title of text box in edit collection page. Fixes #5395

- src/core/client/base.js
- src/core/server/base.js
- src/core/utils/build.js
- src/core/utils/sentry.js
- tests/unit/core/client/test_base.js
- tests/unit/core/utils/test_build.js
- tests/unit/core/utils/test_sentry.js
- version.json
- webpack-common.js
Fixes #8270 
---
You can see it in action here: https://sentry.prod.mozaws.net/operations/addons-frontend-test/releases/
> Pass release ID to Sentry

- src/amo/components/EditableCollectionAddon/styles.scss
Fixes #8316 
**Edit mode:**
**View mode:**
> Fixed the "Remove" button misalignment problem

- src/amo/pages/Home/index.js
- src/amo/sagas/home.js
- tests/unit/amo/pages/TestHome.js
Fixes https://github.com/mozilla/addons-frontend/issues/8317
The home page shows the error and does not keep fetching data now:
> Do not keep fetching home page data on error

- .circleci/config.yml
- tests/ui/run-functional-tests.sh
> Move pytest addopts.

- .circleci/config.yml
This should fix me disabling the wrong suite of tests.
> Fix tests that are run.

- src/amo/components/EditableCollectionAddon/styles.scss
> Fixed exceeding layout issue of collector's note

- config/default.js
Fixes https://github.com/mozilla/addons-frontend/issues/8388
> Redirect bn-BD to bn

- package.json
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/8384
> Switch to the official babel-gettext-extractor lib

- src/core/withExperiment.js
- tests/unit/core/test_withExperiment.js
Fixes #8363 
@kumar303 and/or @willdurand I'd very much like to try to land this experiment, at least on dev, before I disappear for two weeks next week, so if someone could prioritize reviewing this and also #8348, I'd really appreciate it. There will be a third PR after both of those land, but it's pretty small. Thanks!
> Add an enrollment event into withExperiment

- .circleci/config.yml
Should fix the errors on circleci for the smoke tests.
> Add tox for smoke tests on circleci.

- src/amo/components/SectionLinks/index.js
- tests/unit/amo/components/TestSectionLinks.js
> Highlight “Themes” from the menu on search page

- tests/unit/amo/components/TestSearchResult.js
- tests/unit/core/i18n/test_utils.js
- tests/unit/helpers.js
- tests/unit/test_helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/8453 (again)
> Fix non-breaking space test in i18n/test_utils

- .circleci/config.yml
- tests/ui/run-functional-tests.sh
We generate UUID's differently now, so this updates this repo to use that method.
> Update to new UUID

- tests/ui/run-functional-tests.sh
Should fix integration-tests and if a command fails in the future, the script will exit.
> Attempt fix integration tests

- tests/ui/run-functional-tests.sh
The ```pull``` command was failing so just using ```up -d``` which should pull the images as well.
> Remove pull command from integration test script.

- .circleci/config.yml
> Change integration-test job to run on master commits.

- config/default-amo.js
- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/InstallWarning/index.js
- src/amo/components/InstallWarning/styles.scss
- src/core/withExperiment.js
- tests/unit/amo/components/TestInstallWarning.js
- tests/unit/core/test_withExperiment.js
~~Depends on #8363~~ 
Fixes #8347
> Create an InstallWarning component

- package.json
- yarn.lock
> Specify higher sinon version than 7.4.0 which is a 404

- src/amo/components/HeroRecommendation/styles.scss
> Fix unbroken string issue for Primary Hero Shelf

- config/default-amo.js
- config/default.js
- config/dev-amo.js
- config/development-amo.js
> Enable the installButtonWarning experiment on all environments

- package.json
- src/amo/components/HeroRecommendation/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/utils/test_index.js
> Add appropriate params to internal and external URLs for Primary Hero cta

- src/amo/components/HeroRecommendation/index.js
- src/amo/reducers/home.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
~~Depends on #8539~~
Fixes #8538 
This includes some fixes to the `PrimaryHeroShelfType` that I realized we should probably have.
> Log a GA event when the Primary Hero CTA is clicked

- src/amo/components/HeroRecommendation/styles.scss
> Use a consistent font-weight for the Primary Hero heading

- src/amo/components/InstallWarning/index.js
> Update link from InstallWarning

- src/amo/components/HeroRecommendation/index.js
- tests/unit/amo/components/TestHeroRecommendation.js
~~Depends on #8549~~
Fixes #8533
> Open external links from the Primary Hero shelf in a new tab

- src/amo/components/AddonSummaryCard/index.js
- src/amo/components/AddonTitle/index.js
- src/amo/components/HeroRecommendation/index.js
- src/amo/components/SearchResult/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/LanguageTools/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestAddonTitle.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/components/TestSearchResult.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/utils/test_index.js
Fixes #8563 
Hey @bobsilverberg !
How does this look?
Let me know if this needs any changes and I would be more than happy to look at them!
Thanks!
> fix - created shared function for generating Addon URL

- src/amo/components/SecondaryHero/index.js
- src/amo/components/SecondaryHero/styles.scss
- src/amo/pages/Home/index.js
- src/core/css/inc/vars.scss
- tests/unit/amo/components/TestSecondaryHero.js
- tests/unit/amo/pages/TestHome.js
> Add dynamic Secondary Hero Shelf to desktop homepage

- config/default-amo.js
- config/default-disco.js
- config/default.js
- config/dev-amo.js
- config/dev-disco.js
- config/dev.js
- config/development.js
- config/lib/shared.js
- config/stage-amo.js
- config/stage-disco.js
- config/stage.js
- config/uitests-disco.js
Fixes https://github.com/mozilla/addons-frontend/issues/8620
> Update CSP config for prefetch + rename cdn variables

- src/ui/components/UserCollection/styles.scss
Fixes #5426 
**Before Fix :**
**After Fix :**
> Fixed My Collections container exceeding layout issue

- config/default.js
> Disable browserSniff

- src/amo/components/HeroRecommendation/index.js
- src/amo/components/HeroRecommendation/styles.scss
> Remove decorations (swoosh) from Primary Hero shelf

- stories/amo/HeroRecommendation.js
> Fix HeroRecommendation story

- src/amo/components/HeroRecommendation/index.js
- src/amo/components/SecondaryHero/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/components/TestSecondaryHero.js
- tests/unit/amo/utils/test_index.js
> Set required parameters for URLs in the secondary hero component

- src/amo/components/SecondaryHero/index.js
- tests/unit/amo/components/TestSecondaryHero.js
~~Depends on #8627~~ 
Fixes #8559
> Send a tracking event when a Secondary Hero cta is clicked

- src/amo/components/Link/index.js
- tests/unit/amo/components/TestLink.js
Follow-up cleanup for Link from #8652
See: https://github.com/mozilla/addons-frontend/pull/8652#discussion_r327340829
> Follow-up cleanup for Link from #8652

- src/amo/components/InstallWarning/index.js
- tests/unit/amo/components/TestInstallWarning.js
Fixes #8642 
I'm unsure about one of the tests that I updated. I'll comment in the diff on that.
> Always show `InstallWarning` when we could

- package.json
- src/amo/components/HeroRecommendation/index.js
- src/amo/components/HeroRecommendation/styles.scss
- src/core/css/inc/vars.scss
- tests/unit/amo/components/TestHeroRecommendation.js
- yarn.lock
~~Depends on #8630~~
Fixes #8499
> Make gradients for Primary Hero Shelf dynamic

- src/core/addonManager.js
- tests/unit/core/test_addonManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/8668
---
You can use the steps in https://github.com/mozilla/addons-frontend/pull/8653 to setup a working https local dev env.
> Do not reject error in mozAddonManager.install()

- src/amo/utils/index.js
- tests/unit/amo/utils/test_index.js
> Put the logic for relative URLs back into `checkInternalURL`

- config/default.js
- config/development.js
- src/core/client/base.js
Fixes #8586 
- Disables `StrictMode` by default.
- Enables `StrictMode` in local development.
> Disable StrictMode by default

- src/amo/components/App/index.js
- src/amo/components/App/styles.scss
- src/amo/components/AppBanner/index.js
- src/amo/components/AppBanner/styles.scss
- src/amo/components/Header/index.js
- src/amo/components/Header/styles.scss
- src/amo/components/HeroRecommendation/index.js
- src/amo/components/HeroRecommendation/styles.scss
- src/amo/pages/Home/index.js
- src/amo/pages/Home/styles.scss
- src/amo/reducers/viewContext.js
- tests/unit/amo/components/TestApp.js
- tests/unit/amo/components/TestAppBanner.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/reducers/test_viewContext.js
Fixes #8623 
I suspect there are better ways to do this. I'm not a huge fan of what I have here, but it works, so it seems like a reasonable starting point for a review cycle. I haven't written tests yet as I expect it will change. My hope is to come to a decent design for the implementation, and then update any tests that need to be updated.
<details>
<summary>Some screenshots of various sizes, with a site notice</summary>
</details>
<details>
<summary>And one without a site notice</summary>
</details>
> Update primary hero gradient to be full-width of viewport

- config/default.js
> Temporarily disable the non-recommended warning banner

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
Fixes #8738 
Note that I am going to review the code for the `render` function of all `page` components to see if this problem might exist elsewhere as well.
> Address layout issue for non-logged-in UserProfileEdit page

- config/stage-amo.js
> Enable the new hero promo shelves on stage

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> Use http redirect for after-profile-save

- src/core/constants.js
- src/core/utils/index.js
- tests/unit/amo/components/TestAddonHead.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/reducers/test_categories.js
- tests/unit/core/utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/8804
> Remove ADDON_TYPE_COMPLETE_THEME

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
> Enable new hero promo shelves on Production

- tests/ui/docker-compose.functional-tests.yml
Fixes https://github.com/mozilla/addons-server/issues/12690
> Bump docker-compose version to 2.4

- src/amo/components/ErrorPage/NotFound/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SectionLinks/index.js
- src/amo/components/SuggestedPages/index.js
- src/amo/pages/CategoriesPage/index.js
- src/amo/pages/Home/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/reducers/addonsByAuthors.js
- src/amo/sagas/addonsByAuthors.js
- src/amo/sagas/home.js
- src/amo/sagas/landing.js
- src/core/constants.js
- src/core/utils/index.js
- tests/unit/amo/components/TestSectionLinks.js
- tests/unit/amo/pages/TestCategoriesPage.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/sagas/test_addonsByAuthors.js
- tests/unit/amo/sagas/test_home.js
- tests/unit/amo/sagas/test_landing.js
- tests/unit/core/utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/8256
> Remove `getAddonTypeFilter()`

- src/amo/components/SearchContextCard/index.js
- src/core/constants.js
- tests/unit/amo/components/TestSearchContextCard.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/core/test_searchUtils.js
Fixes https://github.com/mozilla/addons-frontend/issues/8821
> Remove ADDON_TYPE_THEMES_FILTER

- src/amo/api/hero.js
- src/core/api/index.js
- tests/unit/amo/api/test_hero.js
- tests/unit/core/api/test_index.js
> Do not send wrap_outgoing_links param for hero API

- src/core/addonManager.js
- tests/unit/core/test_addonManager.js
> Add code to addonManager.js to support abuse reporting

- src/amo/components/AddonAdminLinks/index.js
- src/amo/components/AddonsByAuthorsCard/index.js
- src/amo/components/AddonsCard/index.js
- src/amo/components/SearchResult/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/reducers/home.js
- src/amo/sagas/landing.js
- src/core/addonManager.js
- src/core/components/AMInstallButton/index.js
- src/core/tracking.js
- src/core/utils/index.js
- src/disco/components/Addon/index.js
- src/ui/components/ThemeImage/index.js
- tests/unit/core/utils/test_index.js
> Remove helper `isTheme`

- src/core/reducers/abuse.js
- src/core/sagas/abuse.js
- tests/unit/core/reducers/test_abuse.js
- tests/unit/core/sagas/test_abuse.js
> Add actions for abuse reporting via Firefox

- src/amo/components/InstallWarning/index.js
- src/core/components/AMInstallButton/index.js
- src/core/withExperiment.js
- tests/unit/amo/components/TestInstallWarning.js
- tests/unit/core/components/TestAMInstallButton.js
- tests/unit/core/test_withExperiment.js
> Allow for more than 2 branches in withExperiment

- src/amo/components/ReportAbuseButton/index.js
- tests/unit/amo/components/TestReportAbuseButton.js
> Support Abuse Report hand-off in clients that support it

- src/amo/components/WrongPlatformWarning/index.js
> Remove ability to dismiss the WrongPlatformWarning

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/InstallWarning/index.js
> Update the id for the new A/B experiment

- src/amo/components/ContributeCard/index.js
- tests/unit/amo/components/TestContributeCard.js
> Send a tracking event when the contribute button is clicked

- docs/moz-addon-manager.md
> Fix typo in https docs

- src/amo/components/Errors/NotFound/index.js
- tests/unit/amo/components/Errors/TestNotFound.js
Fixes https://github.com/mozilla/addons-frontend/issues/8952
---
> Update content of the 404 page

- tests/smoke/setup_docker.sh
- tests/ui/run-functional-tests.sh
> Updating scripts to attempt at fixing circleci job.

- tests/smoke/setup_docker.sh
- tests/ui/run-functional-tests.sh
> Fix typo in integration test script for circleci

- tests/smoke/setup_docker.sh
- tests/ui/run-functional-tests.sh
> Fix docker build directory for integration test script.

- tests/smoke/setup_docker.sh
- tests/ui/run-functional-tests.sh
> Remove step.

- tests/ui/run-functional-tests.sh
> Fix base url.

- tests/ui/run-functional-tests.sh
> Remove baseurl CLI flag from integration test script.

- bin/loading-page.html
- server.js
- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
Fixes #8934
Replace this sentence with a description of how your patch fixes the issue.
> Remove cookie anchor in a footer link

- webpack-common.js
Fixes #9092
---
The issue linked above contains more information about why this is a problem.
> Fix the replacement regexp for 'config'

- locale/ro/LC_MESSAGES/amo.po
> Fix errant placeholder

- config/stage-amo.js
Fixes https://github.com/mozilla/addons-frontend/issues/9108
> Remove search tools in stage

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- config/stage-amo.js
- tests/unit/amo/components/TestSectionLinks.js
Fixes https://github.com/mozilla/addons-frontend/issues/9110
> Remove search tools in all envs

- config/default.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SectionLinks/index.js
- src/amo/pages/SearchTools/index.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/components/TestSectionLinks.js
- tests/unit/amo/pages/TestSearchTools.js
Fixes #9112 
Removed the codes related to "enableFeatureRemoveSearchTools"
> Remove the "enableFeatureRemoveSearchTools" feature flag

- tests/frontend/run-integration-test.sh
- tests/frontend/ui/pages/desktop/base.py
- tests/frontend/ui/test_home.py
- tests/frontend/ui/test_install.py
Should fix the integration tests on circleci. Also added a second test command that runs tests in parallel.
> Updates to integration tests after -server changes.

- tests/frontend/generate_fxa_email.py
- tests/frontend/run-integration-test.sh
Working during #allhands is hard.
> Fixup for inegration tests

- tests/jest-reporters/fingers-crossed.js
Fixes #9124 
@willdurand Do you think we should add tests for the reporter? We don't have any tests for any of the reporters.
> Fix FingersCrossedReporter error

- src/amo/components/AddonsCard/styles.scss
- src/amo/components/SearchResult/index.js
- src/amo/components/SearchResult/styles.scss
- tests/unit/amo/components/TestSearchResult.js
> Revert patches to fix keyboard navigation problem

- src/amo/components/Footer/index.js
- src/amo/components/Footer/styles.scss
- tests/unit/amo/components/TestFooter.js
>  Update footer links to align with new Firefox products

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/WrongPlatformWarning/index.js
- src/amo/pages/Addon/index.js
- src/core/utils/compatibility.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/core/utils/test_compatibility.js
> Update compatibility warning shown for mobile users

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/WrongPlatformWarning/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
Fixes #9177 
Depends on #9189 
Before:
After:
> Show install button warning for iOS users

- tests/frontend/ui/pages/desktop/base.py
- tests/frontend/ui/test_home.py
Should hopefully fix https://github.com/mozilla/addons-frontend/issues/9195
---
I did what @jrbenny35 said.
> Fix python tests

- src/amo/components/AddonMoreInfo/index.js
- tests/unit/amo/components/TestAddonMoreInfo.js
Fixes https://github.com/mozilla/addons-frontend/issues/9227
> Also pass src query param to custom license pages

- src/amo/pages/UserProfile/styles.scss
Fixes: https://github.com/mozilla/addons-frontend/issues/7880
Fix avatar size proportions
Before: 
After:
> Fix avatar style

- src/amo/components/Footer/index.js
- src/amo/components/Footer/styles.scss
- tests/frontend/ui/pages/desktop/base.py
- tests/unit/amo/components/TestFooter.js
> Update the Browser section in footer

- src/amo/components/UserProfileEditPicture/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9237
---
Before:
After:
> Fix avatar style in edit mode

- tests/frontend/ui/pages/desktop/base.py
- tests/frontend/ui/test_home.py
> [WIP ]Attempt for Ui tests fix

- tests/frontend/ui/test_home.py
> Fix the integration tests, remove useless link from tests

- src/core/components/SiteNotices/index.js
Fixes #9255 
Fixed the console warning of adding keys to the list items by adding unique keys to the items.
> [fix]: Fixed console warning by adding keys to the items

- src/amo/components/Routes/index.js
- tests/unit/amo/components/TestRoutes.js
Fixes https://github.com/mozilla/addons-frontend/issues/9269
> Serve blocked pages under /addon-blocked/ (for QA)

- src/amo/components/UserProfileEditPicture/styles.scss
- src/amo/pages/UserProfile/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9275
---
I reverted the two commits related to the user profile avatar changes.
> Revert user profile avatar changes

- src/amo/components/Routes/index.js
- tests/unit/amo/components/TestRoutes.js
Fixes https://github.com/mozilla/addons-frontend/issues/9286
> Change path for blocked pages

- locale/sl/LC_MESSAGES/amo.po
Fixes https://github.com/mozilla/addons-frontend/issues/9288
> Fix sl locale

- .circleci/config.yml
Fixes https://github.com/mozilla/addons-frontend/issues/9293
> Update circle ci version

- src/amo/components/AddAddonToCollection/styles.scss
- src/amo/pages/AddonReviewList/styles.scss
Fixes #9301 
Added style for changing cursor from `normal` to `pointer` on hover to dropdown for making it look selectable.
> [fix]: Added cursor pointer style to dropdown

- src/amo/components/Header/index.js
- src/amo/components/Header/styles.scss
- tests/unit/amo/components/TestHeader.js
Fixes https://github.com/mozilla/addons-frontend/issues/9312
> Fix logo in Header (small screen/anonymous pages)

- src/amo/components/AddAddonToCollection/styles.scss
- src/amo/pages/AddonReviewList/styles.scss
Fixes #9317
Reverted all the changes committed in the #9302.
> [revert]: Reverted the changes committed in #9302

- src/amo/components/Header/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/9323
I just noticed that our integration tests where failing and that's because of this issue :(
> Fix typo in className

- src/amo/pages/Block/index.js
- tests/unit/amo/pages/TestBlock.js
Fixes https://github.com/mozilla/addons-frontend/issues/9330
> Do not index blocked pages

- src/amo/components/RatingsByStar/index.js
- src/amo/components/RatingsByStar/styles.scss
- tests/unit/amo/components/TestRatingsByStar.js
This patch implements the approach of the single link instead of multi links as mentioned in the patch #9254 .
Fixes #8860 
@muffinresearch @willdurand @bobsilverberg Please review the code!
> Implemented single link instead of multiple links to read reviews

- src/amo/components/RatingsByStar/index.js
- src/amo/components/RatingsByStar/styles.scss
- tests/unit/amo/components/TestRatingsByStar.js
Reverts mozilla/addons-frontend#9295
> Revert "Implemented single link instead of multiple links to read reviews"

- .travis.yml
Fixes https://github.com/mozilla/addons-frontend/issues/9378
> Use official mkcert

- src/amo/components/HeroRecommendation/index.js
- src/core/i18n/utils.js
- src/core/middleware/prefixMiddleware.js
- src/core/server/base.js
Refs https://github.com/mozilla/addons-frontend/issues/9389
---
This patch might not fix the issue above entirely but it is a good start.
I changed `info` to `debug` in most cases because (1) we almost never look at the logs and (2) the messages are not very useful in production anyway. Not all messages should be changed to `debug` of course but those ones are very very frequent in Stackdriver (for very very little value).
I changed one message from `info` to `error` because it's an exception.
Once we have #9391, it will be easier to identify other messages that could be changed from info to debug..
> Reduce the logging verbosity of our app (a bit)

- src/amo/components/AddonSummaryCard/styles.scss
- src/amo/components/AddonTitle/styles.scss
- src/amo/components/App/styles.scss
- src/amo/components/CollectionDetails/styles.scss
- src/amo/components/EditableCollectionAddon/styles.scss
- src/amo/components/HeroRecommendation/styles.scss
- src/amo/components/RatingManager/styles.scss
- src/amo/components/Search/styles.scss
- src/amo/components/SearchContextCard/styles.scss
- src/amo/components/SearchResult/styles.scss
- src/amo/components/SecondaryHero/styles.scss
- src/amo/pages/Addon/styles.scss
- src/amo/pages/UserProfile/styles.scss
- src/disco/components/Addon/styles.scss
- src/ui/components/Card/styles.scss
- src/ui/components/DefinitionList/styles.scss
- src/ui/components/MetadataCard/styles.scss
- src/ui/components/ShowMoreCard/styles.scss
- src/ui/components/UserCollection/styles.scss
- src/ui/components/UserReview/styles.scss
Fixes: https://github.com/mozilla/addons-frontend/issues/8396
> Unify long string handling in CSS

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/Routes/index.js
- tests/unit/amo/components/TestRoutes.js
Fixes https://github.com/mozilla/addons-frontend/issues/9426
This is needed to actually see whether this feature is enabled...
> Rename blockpage feature flag

- README.md
> Add Windows Guidelines to main instructions too

- config/default.js
- config/dev-amo.js
- config/development-amo.js
Fixes https://github.com/mozilla/addons-frontend/issues/9451
> Enable new block pages in all envs

- src/amo/components/AddonMoreInfo/index.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/helpers.js
> Remove the use of public_stats

- src/amo/components/AddonMoreInfo/index.js
- tests/unit/amo/components/TestAddonMoreInfo.js
Fixes https://github.com/mozilla/addons-frontend/issues/9471
Fixes https://github.com/mozilla/addons-frontend/issues/9460
> Hide stats link for dictionaries and language packs

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> Update user delete copy as addons&related content are auto-deleted

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> stop disabling the delete profile button when user has addons

- config/default.js
- config/dev.js
- config/lib/shared.js
- config/stage.js
- src/core/server/base.js
- tests/unit/core/server/test_base.js
Fixes #9490 (again)
Fixes #9491 (again)
> Return domain in set-cookie

- src/core/server/base.js
- tests/unit/core/server/test_base.js
Hopefully fixes https://github.com/mozilla/addons-frontend/issues/9495
---
I couldn't fully reproduce the STR in local dev because of the FxA instance.
> Delete session cookie in addition to the auth cookie

- tests/ui/requirements/flake8.txt
> Attempt to fix flake8 failure

- tests/ui/requirements/flake8.txt
> Bump the version of flake8-isort, remove pinning of isort

- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/pages/TestUserProfileEdit.js
Fixes https://github.com/mozilla/addons-frontend/issues/9515
---
> Make the Delete button in the Edit profile page red

- src/amo/components/SearchResult/index.js
- tests/unit/amo/components/TestSearchResult.js
> Enhance `SearchResult` to allow for recording of impressions and clicks

- src/amo/components/PromotedAddonsCard/index.js
- src/amo/components/PromotedAddonsCard/styles.scss
- src/amo/constants.js
- src/core/css/inc/vars.scss
- stories/amo/PromotedAddonsCard.js
- stories/index.js
- stories/setup/styles.scss
- tests/unit/amo/components/TestPromotedAddonsCard.js
> Create a PromotedAddons shelf

- src/amo/components/AddonMeta/index.js
- src/amo/components/AddonMoreInfo/index.js
- src/amo/components/SearchResult/index.js
- tests/unit/amo/components/TestAddonMeta.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestSearchResult.js
Fixes https://github.com/mozilla/addons-frontend/issues/9527
---
I reverted the two patches previously used to handle langpacks/dicts differently.
> All supported add-ons should have average daily users

- src/amo/components/PromotedAddonsCard/styles.scss
- src/core/css/inc/vars.scss
> Change fonts for Promoted shelf to match other shelves

- .prettierignore
> Exclude coverage from prettier

- src/amo/components/AddonsCard/index.js
- src/amo/components/PromotedAddonsCard/index.js
- src/amo/components/SearchResult/index.js
- tests/unit/amo/components/TestAddonsCard.js
- tests/unit/amo/components/TestPromotedAddonsCard.js
- tests/unit/amo/components/TestSearchResult.js
> Configure the promoted add-ons shelf to interact with GA

- src/amo/components/HeroRecommendation/index.js
- tests/unit/amo/components/TestHeroRecommendation.js
> Only display loading indicators for Primary Hero when it's actually loading

- locale/ar/LC_MESSAGES/amo.po
- locale/fy_NL/LC_MESSAGES/amo.po
- locale/hr/LC_MESSAGES/amo.po
- locale/nb_NO/LC_MESSAGES/amo.po
- locale/nn_NO/LC_MESSAGES/amo.po
- tests/unit/test_localesConfig.js
Fixes #9566
Interestingly adding a test for this highlighted a bunch of other errors.
> Add placeholder test and fix locales

- src/amo/components/WrongPlatformWarning/index.js
Fixes #9595 
android sumo link fixed
> android target link fixed

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestSearchResult.js
- tests/unit/core/test_addonManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/9616
> Enable UTM params feature

- src/amo/components/Search/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/components/SearchResults/index.js
- src/amo/pages/Home/index.js
- src/amo/pages/LandingPage/index.js
- src/amo/sagas/home.js
- src/amo/sagas/landing.js
- src/core/api/search.js
- src/core/constants.js
- src/core/searchUtils.js
- src/core/utils/addons.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/components/TestSearchResults.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/sagas/test_home.js
- tests/unit/amo/sagas/test_landing.js
- tests/unit/core/api/test_search.js
Depends on ~~https://github.com/mozilla/addons-server/issues/15462~~
Depends on ~~https://github.com/mozilla/addons-server/issues/15432~~
Fixes #9615
> Update AMO Search to work with promoted categories

- src/core/constants.js
> Use promoted=badged

- src/amo/components/SearchFilters/index.js
- tests/unit/amo/components/TestSearchFilters.js
> Update the label and "all" item for the Promoted drop-down

- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
Fixes #9649
I removed the send link from the list in the footer component and also the required tests.
> remove send from footer

- src/amo/components/InstallWarning/index.js
- tests/unit/amo/components/TestInstallWarning.js
> Update InstallWarning for Promoted Add-Ons

- config/default-disco.js
- config/default.js
- src/amo/components/AddonMeta/index.js
- src/amo/components/AddonMoreInfo/index.js
- src/amo/components/AddonReviewCard/index.js
- src/amo/components/AddonSummaryCard/index.js
- src/amo/components/HeroRecommendation/index.js
- src/amo/components/RatingsByStar/index.js
- src/amo/components/SearchResult/index.js
- src/amo/components/SecondaryHero/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/reducers/reviews.js
- src/amo/utils/index.js
- src/core/utils/url.js
- tests/unit/amo/components/TestAddonMeta.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAddonSummaryCard.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/components/TestRatingsByStar.js
- tests/unit/amo/components/TestSearchResult.js
- tests/unit/amo/components/TestSecondaryHero.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/reducers/test_reviews.js
- tests/unit/amo/utils/test_index.js
- tests/unit/core/utils/test_url.js
> Remove feature flag for UTM params

- src/ui/components/PromotedBadge/index.js
- tests/unit/ui/components/TestPromotedBadge.js
> Update promoted badge tooltips

- src/amo/components/InstallButtonWrapper/index.js
- src/amo/components/InstallButtonWrapper/styles.scss
- src/amo/pages/Addon/styles.scss
- tests/unit/amo/components/TestInstallButtonWrapper.js
> Display a download link when the add-on is incompatible

- .stylelintrc
> Replace stylelint `function-blacklist` with `function-disallowed-list`

- src/amo/components/InstallButtonWrapper/index.js
- src/amo/components/InstallButtonWrapper/styles.scss
- src/amo/pages/Addon/styles.scss
- tests/unit/amo/components/TestInstallButtonWrapper.js
> Fix layout issues with install button

- src/amo/components/InstallWarning/index.js
- tests/unit/amo/components/TestInstallWarning.js
> Change warning message

- tests/frontend/ui/pages/desktop/category.py
- tests/frontend/ui/test_home.py
> Fix for issue #9652

- tests/frontend/ui/pages/desktop/base.py
Integration tests on circleci seem to be failing on search tests. This should help.
> Update search integration tests.

- Dockerfile
> Upgrade node version to v12

- tests/frontend/ui/test_search.py
Seems there are some resource issues on circleci causing extra lag. Running the search tests one by one should help.
> Move search integration tests to serial run.

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
Fixes https://github.com/mozilla/addons-frontend/issues/9667
> Avoid infinite dispatches in Addon component

- tests/frontend/ui/pages/desktop/base.py
> Change search wait locator for integration tests.

- .circleci/config.yml
- tests/frontend/run-integration-test.sh
CircleCI Integration tests reports were missing, this should help with debugging
> Re-enable integration tests HTML reports.

- src/core/css/inc/mixins.scss
- src/ui/components/PromotedBadge/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/9711
> Fix promoted badges

- src/amo/components/SecondaryHero/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestSecondaryHero.js
- tests/unit/amo/utils/test_index.js
> Strip the language out of the url passed to GA for the secondary hero

- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
> Update the homepage for Fenix users

- src/amo/components/Header/index.js
- tests/unit/amo/components/TestHeader.js
> Update the site header for Fenix

- src/amo/pages/Addon/index.js
- src/amo/pages/AddonInfo/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/AddonVersions/index.js
- src/core/reducers/addons.js
- src/core/sagas/addons.js
- src/disco/sagas/disco.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonInfo.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/core/reducers/test_addons.js
- tests/unit/core/reducers/test_versions.js
- tests/unit/core/sagas/test_addons.js
- tests/unit/disco/helpers.js
- tests/unit/disco/sagas/test_disco.js
Fixes https://github.com/mozilla/addons-frontend/issues/9731
> Load add-on returned by the API

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/pages/Home/index.js
- tests/unit/amo/pages/TestHome.js
Fixes #9735 
I also renamed the flag as I was planning to do that in the other work I'm doing for the shelf for Q4.
> Enabled sponsored add-ons shelf on the homepage

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Send GA event for clicks on Download Firefox button

- config/default.js
Fixes https://github.com/mozilla/addons-frontend/issues/9740
> Remove no longer valid Helmet config

- src/amo/components/SponsoredAddonsShelf/index.js
- src/amo/components/SponsoredAddonsShelf/styles.scss
- src/amo/pages/Home/index.js
- stories/amo/SponsoredAddonsShelf.js
- stories/index.js
- stories/setup/styles.scss
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
- tests/unit/amo/pages/TestHome.js
> Rename PromotedAddonsCard to SponsoredAddonsShelf

- src/amo/api/shelves.js
- src/amo/reducers/shelves.js
- src/amo/sagas/index.js
- src/amo/sagas/shelves.js
- src/amo/store.js
- src/core/reducers/addons.js
- src/core/types/addons.js
- tests/unit/amo/api/test_shelves.js
- tests/unit/amo/reducers/test_shelves.js
- tests/unit/amo/sagas/test_shelves.js
- tests/unit/helpers.js
> Implement API, saga and reducer code for new sponsored endpoint

- src/amo/components/HeroRecommendation/index.js
- tests/unit/amo/components/TestHeroRecommendation.js
> Send a GA ping for Primary Hero Impressions

- config/default.js
- config/dev-amo.js
- config/development-amo.js
- src/amo/components/SponsoredAddonsShelf/index.js
- src/amo/reducers/shelves.js
- stories/amo/SponsoredAddonsShelf.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
- tests/unit/amo/reducers/test_shelves.js
- tests/unit/amo/sagas/test_shelves.js
- tests/unit/helpers.js
> Fetch homepage sponsored shelf using specific addons-server API

- .eslintrc
- config/development.js
- src/amo/components/SponsoredAddonsShelf/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
- tests/unit/amo/utils/test_index.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/9758~~
Fixes #9720
> Call impression URL when displaying sponsored homepage shelf

- src/amo/components/SponsoredAddonsShelf/index.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
> Always show all add-ons returned by the sponsored endpoint

- src/amo/components/SponsoredAddonsShelf/index.js
- src/amo/utils/index.js
- src/core/constants.js
- src/core/tracking.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
- tests/unit/amo/utils/test_index.js
- tests/unit/core/test_tracking.js
> Move sendBeacon into tracking

- src/core/tracking.js
- tests/unit/core/test_tracking.js
> Take the DNT setting into account for sendBeacon

- config/default.js
- src/core/constants.js
- src/core/utils/compatibility.js
- tests/unit/core/utils/test_compatibility.js
> Change source of truth for Fenix compatibility

- src/amo/components/SponsoredAddonsShelf/index.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
> Fetch sponsored shelf data on update if needed

- src/amo/components/SponsoredAddonsShelf/index.js
- src/core/installAddon.js
- src/core/tracking.js
- tests/unit/amo/components/TestSponsoredAddonsShelf.js
- tests/unit/core/test_installAddon.js
- tests/unit/core/test_tracking.js
> Measure installation of add-ons in the sponsored shelf

- config/default.js
- src/core/constants.js
- src/core/reducers/addons.js
- src/core/reducers/versions.js
- src/core/server/base.js
- tests/unit/core/reducers/test_addons.js
Fixes #9805 
Also removes some other code that was only there to support discopane.
> Remove code that was there to support discopane

- .circleci/config.yml
> Login to dockerhub before pulling docker images for building

- config/default.js
- config/dev-amo.js
- config/development-amo.js
> Enable adzerk integration for Sponsored shelf

- src/core/reducers/api.js
- tests/unit/core/server/test_base.js
- tests/unit/helpers.js
> Fix types in api reducer

- src/core/utils/compatibility.js
- tests/unit/core/utils/test_compatibility.js
> Treat all non-extensions as not android compatible

- src/amo/components/Errors/UnavailableForLegalReasons/index.js
- tests/unit/amo/components/Errors/TestUnavailableForLegalReasons.js
Fixes #9856 
Just awaiting a response from @jvillalobos on https://github.com/mozilla/addons-frontend/issues/9856#issuecomment-726256724
> Adjust copy for "Not available in this region" page

- config/default.js
- config/development.js
- src/core/utils/compatibility.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
- tests/unit/core/utils/test_compatibility.js
- tests/unit/helpers.js
> Disable install button for all add-ons on Fenix

- src/amo/components/AutoSearchInput/styles.scss
Fixes #9865 
Hide the search button outline for all browsers.
> Hide search-btn outline for all browsers

- src/amo/components/HeroRecommendation/index.js
- src/amo/components/SecondaryHero/index.js
- src/amo/pages/Home/index.js
- src/amo/reducers/home.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/components/TestSecondaryHero.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
> Enable homepage to handle missing hero data

- config/dev.js
> Enable install buttons on Android on dev

- src/amo/components/Page/index.js
- src/amo/pages/Addon/index.js
- src/amo/pages/AddonInfo/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/AddonVersions/index.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonInfo.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/helpers.js
> Refactor page override code into Page component

- src/amo/components/Page/index.js
- tests/unit/amo/components/TestPage.js
> Update logging that happens when an API request returns an unexpected status

- src/core/api/index.js
- src/core/api/search.js
- src/core/searchUtils.js
- tests/unit/core/api/test_index.js
- tests/unit/core/api/test_search.js
- tests/unit/core/test_searchUtils.js
> Searching for mobile add-ons should only display compatible results

- src/core/searchUtils.js
- tests/unit/core/api/test_index.js
- tests/unit/core/test_searchUtils.js
> Exclude all but extensions from search results on Android

- src/amo/components/SearchFilters/index.js
- tests/unit/amo/components/TestSearchFilters.js
> Hide the Badging and Add-On Type filters on Android

- .eslintrc
- package.json
- tests/unit/amo/components/TestCategories.js
- tests/unit/core/api/test_index.js
- tests/unit/core/reducers/test_api.js
- tests/unit/core/reducers/test_errors.js
- tests/unit/core/server/test_base.js
- tests/unit/core/utils/test_server.js
- tests/unit/test_localesConfig.js
- tests/unit/test_packageJson.js
- yarn.lock
I updated a few things in eslint-config-amo:
- prettier is configured out of the box
- jest is configured with the recommended settings
There were a few things to update but nothing major.
> Upgrade to eslint-config-amo v4

- src/amo/components/AutoSearchInput/index.js
> Trim search query

- src/amo/reducers/shelves.js
- tests/unit/amo/reducers/test_shelves.js
> Fix problem with shelves reducer

- src/core/reducers/languageTools.js
- tests/unit/amo/pages/TestLanguageTools.js
- tests/unit/core/reducers/test_languageTools.js
- tests/unit/helpers.js
> Fix languageTools reducer

- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
Fixes #9923 
Changed the URL in the component to the correct one. Updated the test according to the new url.
https://user-images.githubusercontent.com/52133994/103737968-3c3d8000-5019-11eb-8852-bc1f40ff21c6.mp4
> Fix 404 on report a bug link in footer

- src/core/reducers/addons.js
- tests/unit/core/reducers/test_addons.js
> test selectLocalizedUrlWithOutgoing

- src/amo/components/AddonMoreInfo/index.js
- src/amo/components/ContributeCard/index.js
- src/amo/pages/Block/index.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestContributeCard.js
- tests/unit/amo/pages/TestBlock.js
Fixes https://github.com/mozilla/addons-frontend/issues/3580
> Show URL when hovering an outgoing URL

- bin/run-l10n-extraction
> Update run-l10n-extraction to use --no-verify

- tests/unit/amo/components/TestAutoSearchInput.js
> Add a test for the new trim functionality in AutoSearchInput

- src/amo/components/PromotedBadge/index.js
- tests/unit/amo/components/TestPromotedBadge.js
> Change wording of Line badge tooltip

- README.md
Minor change to the grammar under the section titled "What version is deployed?" for better flow
> updated grammar of README file

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/WrongPlatformWarning/index.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
> Enable installation buttons for supported extensions in Fenix on prod

- src/amo/pages/Block/index.js
- src/amo/reducers/blocks.js
- tests/unit/amo/pages/TestBlock.js
- tests/unit/amo/reducers/test_blocks.js
> Add l10n support to Block

- src/amo/components/HeroRecommendation/index.js
- src/amo/reducers/home.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/helpers.js
> Fix Primary Hero External prop to deal with l10n

- src/amo/components/RatingsByStar/index.js
- src/amo/reducers/reviews.js
- tests/unit/amo/components/TestRatingsByStar.js
- tests/unit/amo/reducers/test_reviews.js
> Prevent duplicate fetch of grouped ratings

- src/amo/reducers/home.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/helpers.js
fixes #10075 - the companion to mozilla/addons-server#16531
> handle api returning localized fields in hero api

- .circleci/config.yml
> Print node version in Circle CI

- src/amo/components/CollectionManager/index.js
- src/amo/reducers/api.js
- tests/unit/amo/components/TestCollectionManager.js
> Make clientApp and lang into string types and default to ''

- src/amo/components/PermissionsCard/index.js
- src/amo/components/ShowMoreCard/index.js
- src/amo/components/UserReview/index.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/components/TestPermissionsCard.js
- tests/unit/amo/components/TestShowMoreCard.js
- tests/unit/amo/components/TestUserReview.js
- tests/unit/amo/pages/TestAddon.js
> Update logic for ShowMoreCard to determine when it needs to reset

- package.json
> Disable webpack verbose output

- src/amo/components/Routes/index.js
(found while I was looking at https://github.com/mozilla/addons-frontend/pull/10146)
> Fix/remove comment in Routes component

- renovate.json
> Bundle dependency updates for `stylelint` and `stylelint-config-standard

- src/amo/components/AppBanner/index.js
- src/amo/components/SurveyNotice/index.js
- tests/unit/amo/components/TestAppBanner.js
Fixes #10166
---
From 435.43KB to 434.28KB according to `bundlesize` (it's not a lot but we don't need it so...)
> Remove SurveyNotice in AppBanner

- package.json
> Decrease bundlesize threshold

- src/amo/components/ScreenShots/index.js
- tests/unit/amo/components/TestScreenShots.js
> add loading="lazy" to detail page screenshot thumbs

- README.md
- bin/config-check.js
- config/local.js.dist
> Update docs for running a build locally

- src/amo/constants.js
- src/amo/middleware/prefixMiddleware.js
- src/amo/middleware/security.js
- src/amo/server/base.js
- tests/unit/amo/middleware/test_prefixMiddleware.js
- tests/unit/amo/server/test_base.js
> Add header to allow nginx to cache successful responses from anonymous requests

- package.json
Fixes https://github.com/mozilla/addons-frontend/issues/10186
> Configure bundlesize for CSS

- src/amo/components/Footer/styles.scss
> Fix footer text by using regular font weight

- src/amo/middleware/responseTime.js
- tests/unit/amo/middleware/test_responseTime.js
> Fix statsd prefix

- src/amo/components/Categories/index.js
- src/amo/components/Routes/index.js
- src/amo/components/Search/index.js
- src/amo/components/SearchContextCard/index.js
- src/amo/components/SearchFilters/index.js
- src/amo/constants.js
- src/amo/pages/CategoryPage/index.js
- src/amo/pages/Home/index.js
- src/amo/pages/SearchPage/index.js
- src/amo/pages/SearchTools/index.js
- src/amo/reducers/categories.js
- src/amo/searchUtils.js
- src/amo/utils/categories.js
- tests/unit/amo/components/TestCategories.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/components/TestSearchFilters.js
- tests/unit/amo/pages/TestCategoryPage.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/pages/TestSearchTools.js
- tests/unit/amo/test_searchUtils.js
- tests/unit/amo/utils/test_categories.js
> Make category pages indexable

- src/fonts/inter.scss
Fixes https://github.com/mozilla/addons-frontend/issues/10222
> Remove font-display: swap

- src/amo/middleware/responseTime.js
- tests/unit/amo/middleware/test_responseTime.js
Fixes https://github.com/mozilla/addons-frontend/issues/10229
> Update statsd keys in responseTime middleware

- package.json
- webpack.dev.config.babel.js
- webpack.prod.config.babel.js
> Generate files in dist/static/

- bin/loading-page.html
- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
> Fix the link to developer policies in footer

- config/default.js
- config/dev.js
- config/stage.js
- tests/unit/amo/middleware/test_cspMiddleware.js
> Update CSP to include /static/ path for frontend files

- src/amo/components/AddonSummaryCard/styles.scss
- src/amo/components/AddonTitle/styles.scss
- src/amo/components/AddonVersionCard/styles.scss
- src/amo/components/App/styles.scss
- src/amo/components/Badge/styles.scss
- src/amo/components/Button/styles.scss
- src/amo/components/CollectionDetails/styles.scss
- src/amo/components/DropdownMenuItem/styles.scss
- src/amo/components/EditableCollectionAddon/styles.scss
- src/amo/components/Footer/styles.scss
- src/amo/components/HeroRecommendation/styles.scss
- src/amo/components/InstallButtonWrapper/styles.scss
- src/amo/components/PromotedBadge/styles.scss
- src/amo/components/SearchContextCard/styles.scss
- src/amo/components/SearchResult/styles.scss
- src/amo/components/SectionLinks/styles.scss
- src/amo/components/StaticPage/styles.scss
- src/amo/components/TooltipMenu/styles.scss
- src/amo/components/UserCollection/styles.scss
- src/amo/css/inc/vars.scss
- src/amo/pages/Addon/styles.scss
- src/amo/pages/CollectionList/styles.scss
- src/amo/pages/Home/styles.scss
- src/amo/pages/LandingPage/styles.scss
- src/amo/pages/LanguageTools/styles.scss
- src/amo/pages/UserProfile/styles.scss
- src/amo/pages/UserProfileEdit/styles.scss
Fixes #9078 
It looks like people are happy with this change, so requesting a review. Will wait for @verdi's ok before landing.
> Bump up default font sizes, and fix Download file button

- config/custom-environment-variables.json
- config/default.js
- src/amo/middleware/responseTime.js
- tests/unit/amo/middleware/test_responseTime.js
Fixes https://github.com/mozilla/addons-frontend/issues/10215
> Rename statsd config parameters

- src/amo/components/AddonReviewCard/styles.scss
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/FlagReviewMenu/styles.scss
- tests/unit/amo/components/TestFlagReviewMenu.js
Fixes #10184, just had a discussion with Bob , that it might work too, will remove the code for test if it works for everyone
> Fix the wrapping issue for flag on review component

- src/amo/components/SearchResult/index.js
- tests/unit/amo/components/TestSearchResult.js
> lazy load theme search result images

- src/amo/css/inc/vars.scss
> Revert change to default line-height

- src/amo/components/Header/index.js
- tests/unit/amo/components/TestHeader.js
> Hide Workshop and DevHub links for non-Firefox users

- webpack-common.js
> Add withBrowserWindow parameter to webpack's getPlugins()

- src/amo/components/WrongPlatformWarning/index.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
> Fixes Compatibility message for iOS users

- src/amo/components/Footer/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestFooter.js
Fixes #10285
---
I also added flow types.
> Allow Footer to render without a language picker

- src/amo/components/App/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestApp.js
- tests/unit/amo/utils/test_index.js
> Reset clientApp if it differs on the URL

- src/amo/withExperiment.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/helpers.js
> Update experiment code to deal with anonymous page caching

- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxBanner/styles.scss
- tests/unit/amo/components/TestGetFirefoxBanner.js
Fixes #10306 
See the issue for screenshots of what it looks like.
> Create a GetFirefoxBanner component

- src/amo/server/base.js
- tests/unit/amo/server/test_base.js
> Add Link rel=preconnect header to our CDN domains

- src/amo/middleware/prefixMiddleware.js
- tests/unit/amo/middleware/test_prefixMiddleware.js
fixes #10308 - I hope in not a _too_ naive way (existing tests pass so...)
> handle server urls that are both app and locale exceptions

- src/amo/components/AuthenticateButton/index.js
- src/amo/components/Header/index.js
- src/amo/components/Header/styles.scss
- tests/unit/amo/components/TestAuthenticateButton.js
Fixes #10163 
This patch changes the authentication button to a link.
> Changes made in AuthenticateButton/index.js to convert button to link

- src/amo/components/GetFirefoxButton/index.js
> Make download buttons blue

- src/amo/middleware/prefixMiddleware.js
- tests/unit/amo/middleware/test_prefixMiddleware.js
Fixes https://github.com/mozilla/addons-frontend/issues/10331
A regression was reported at https://github.com/mozilla/addons-frontend/issues/10308#issuecomment-814879754, so we need to revert this change.
> Revert change to prefixMiddleware

- .circleci/config.yml
- .npmrc
- README.md
Fixes #10298
---
This should do the trick.
> Allow to publish addons-frontend-blog-utils to npm

- src/amo/client/base.js
- src/amo/reducers/tracking.js
- src/amo/store.js
- src/amo/tracking.js
- src/amo/withExperiment.js
- tests/unit/amo/client/test_base.js
- tests/unit/amo/components/TestHeroRecommendation.js
- tests/unit/amo/reducers/test_tracking.js
- tests/unit/amo/test_installAddon.js
- tests/unit/amo/test_tracking.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/helpers.js
Fixes #10296 
This works well, but interested in feedback from @willdurand before going ahead and writing tests for it.
> Log an enrollment event on the server, and issue it on the client

- bin/create-package-json-for-blog-utils
- bin/create-readme-for-blog-utils
- package.json
Fixes #10355
---
This PR updates the metadata in the generated `package.json` file for blog-utils and adds a script to generate a README, which should make https://www.npmjs.com/package/addons-frontend-blog-utils a bit nicer.
> Some improvements for the `blog-utils` npm package

- .gitignore
Re: https://github.com/mozilla/addons-frontend/pull/10287#issuecomment-818466465
> Add .husky folder to .gitignore

- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
> Update the event category for the GetFirefoxBanner click

- src/amo/components/GetFirefoxButton/styles.scss
> Update callout styles based on feedback

- config/dev.js
> Disable the current experiment on dev

- package.json
- src/amo/server/base.js
- tests/unit/amo/server/test_base.js
- yarn.lock
> Enable compression middleware

- src/blog-utils/StaticAddonCard/index.js
- src/blog-utils/StaticAddonCard/styles.scss
- tests/unit/blog-utils/TestStaticAddonCard.js
> Add unavailable state to the StaticAddonCard (blog-utils)

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/Footer/index.js
- src/amo/components/Page/index.js
- src/blog-utils/index.js
- tests/unit/amo/components/TestFooter.js
- tests/unit/amo/components/TestPage.js
- tests/unit/blog-utils/test_index.js
Fixes https://github.com/mozilla/addons-frontend/issues/10388
Fixes https://github.com/mozilla/addons-frontend/issues/10389
> Add link to new AMO blog (with a feature flag)

- src/amo/server/base.js
- tests/unit/amo/server/test_base.js
> Vary on User-Agent in addons-frontend instead of letting nginx do it

- src/amo/components/AddonVersionCard/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/pages/AddonVersions/index.js
- src/amo/pages/AddonVersions/styles.scss
- tests/unit/amo/components/TestAddonVersionCard.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/pages/TestAddonVersions.js
Fixes #9811 
This replaces https://github.com/mozilla/addons-frontend/pull/10237 and includes the commits from both @sarthakkundra and @smitbarmase.
> changed older versions button to links

- locale/sk/LC_MESSAGES/amo.po
> Fix invalid variable in locale/sk/LC_MESSAGES/amo.po

- src/amo/components/AddonReviewManagerRating/styles.scss
> Fix alignment of rating stars

- src/amo/css/inc/vars.scss
> Change default-line-height to 1.5 to fix truncation issue 

- config/default.js
- config/dev.js
- config/development.js
- config/test.js
- jest.config.js
- src/amo/utils/server.js
- src/amo/withExperiment.js
- tests/unit/amo/test_withExperiment.js
> Enable the CTA experiment on all environments

- src/amo/components/App/styles.scss
> Add break-word for safari and ios to fix layout issues on IOS

- src/amo/components/GetFirefoxBanner/styles.scss
- src/amo/components/GetFirefoxButton/styles.scss
> Use grey-90 color for download banners and warnings

- src/amo/components/Header/styles.scss
Fixes #10416 
Before:
After:
Before:
After:
> Fix alignment of username and login link

- src/amo/components/FlagReviewMenu/styles.scss
> Fix breaking of Flag button on review page

- locale/ia/LC_MESSAGES/amo.po
> Fix invalid variable in locale/ia/LC_MESSAGES/amo.po

- config/default.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
Fixes https://github.com/mozilla/addons-frontend/issues/10469
Fixes https://github.com/mozilla/addons-frontend/issues/10470
---
I tried not to make too many changes to avoid conflicts when we'll cherry-pick the commits (they should apply cleanly right now).
> Two fixes for RTAMO

- src/amo/pages/Addon/styles.scss
> Fix truncation of Download button for non-FF browsers

- src/amo/components/SecondaryHero/index.js
- src/amo/reducers/home.js
- tests/unit/amo/components/TestHomepageShelves.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/amo/reducers/test_versions.js
- tests/unit/helpers.js
> Fix shelf types (and rename types/functions for clarity)

- package.json
- src/amo/utils/compatibility.js
- yarn.lock
> Use addons-moz-compare

- package.json
- src/amo/components/ServerHtml/index.js
- src/amo/server/WebpackAssetsFontsPlugin.js
- src/amo/server/webpack-assets-fonts.js
- tests/unit/amo/server/test_WebpackAssetsFontsPlugin.js
- webpack-common.js
- webpack.prod.config.babel.js
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/10473
> Fix preloading of subset fonts in production environment

- src/amo/pages/SearchPage/index.js
- src/amo/utils/index.js
- tests/unit/amo/pages/TestSearchPage.js
> Handle invalid add-on types in SearchPage

- tests/unit/blog-utils/test_index.js
> Add some more assertions to cover class names used by addons-blog

- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/Header/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/utils/index.js
- src/amo/withExperiment.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/components/TestHeader.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/amo/utils/test_index.js
> Pass experiment and variation in download firefox URL

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Make sure all RTAMO supported categories display the RTAMO button text

- src/blog-utils/StaticAddonCard/index.js
- tests/unit/blog-utils/TestStaticAddonCard.js
~~:warning: depends on #10518~~
Fixes https://github.com/mozilla/addons-frontend/issues/10368
> Override some query params on download FF link in StaticAddonCard 

- codecov.yml
Fixes #10535 
Submitting this PR to make sure it doesn't break anything. Then I will add a commit that would result in a minor overall coverage change and see how that behaves.
> Set a threshold for code coverage of 0.02%.

- src/amo/components/AddonSummaryCard/styles.scss
Fixes #10483 
Screenshot after update:
> Updated AddonSummaryCard-header styling.

- src/amo/components/TooltipMenu/styles.scss
> Fix truncation of tooltip items on small screens

- src/amo/components/AddonVersionCard/index.js
- src/amo/components/AddonVersionCard/styles.scss
- src/amo/pages/AddonVersions/styles.scss
Fixes https://github.com/mozilla/addons-frontend/issues/10484
> Fix all versions page on all screens

- src/amo/components/PermissionsCard/styles.scss
> Fix Alignment of Text and Icon in permission card header

- src/amo/pages/AddonVersions/index.js
- src/amo/pages/AddonVersions/styles.scss
> Avoid generating a <p> inside another <p> in addons versions notice

- config/default.js
> Disable the current experiment

- src/amo/components/AddonsByAuthorsCard/styles.scss
> Reduce gap in More extensions by author card

- src/amo/components/SearchResult/styles.scss
> Fix Users Icon width for SearchResult Addons

- src/amo/components/InstallButtonWrapper/styles.scss
> Fix problem with callout style

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/AddonVersionCard/index.js
- src/amo/pages/AddonVersions/index.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestAddonVersionCard.js
- tests/unit/amo/pages/TestAddonVersions.js
> Stop showing AddonInstallError and AddonCompatibilityError for any versions other than the current one

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/utils/compatibility.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/utils/test_compatibility.js
> Remove special casing for Download Firefox link for Facebook Container

- config/development-local.js
> Disable trailing slashes middleware for addons-server local dev

- src/amo/components/AMInstallButton/index.js
- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/InstallButtonWrapper/index.js
- tests/unit/amo/components/TestAMInstallButton.js
- tests/unit/amo/components/TestAddonCompatibilityError.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
> Align incompatible Firefox version error with non-Firefox browser CTA

- config/dev.js
- config/development.js
- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/constants.js
- src/amo/experiments/20210531_download_funnel_experiment.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
> Create an experiment for the download funnel

- config/default.js
- config/dev.js
- config/development.js
Fixes https://github.com/mozilla/addons-frontend/issues/10672
> Link to the new blog in all envs

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Change the name of the param used for the experimental download page

- config/test.js
- src/amo/components/AddonVersionCard/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/pages/Addon/index.js
- src/amo/reducers/experiments.js
- src/amo/store.js
- src/amo/withExperiment.js
- tests/unit/amo/components/TestAddonVersionCard.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/reducers/test_experiments.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/helpers.js
> Render experiments on the server

- src/amo/experiments/20210531_download_funnel_experiment.js
- src/amo/withExperiment.js
- tests/unit/amo/experiments/test_20210531_download_funnel_experiment.js
- tests/unit/amo/test_withExperiment.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/10704~~
Fixes #10669 
Fixes #10618
Fixes #10598
Fixes #10687
> Allow for excluding users from experiments based on values from state

- src/amo/components/Footer/index.js
Fixes #10705 
Updated Footer's link text
> Updated Footer text

- src/amo/experiments/20210531_download_funnel_experiment.js
- tests/unit/amo/experiments/test_20210531_download_funnel_experiment.js
> Exclude non en-US users from download funnel experiment

- config/default.js
- src/amo/components/Footer/index.js
- src/amo/components/Page/index.js
- src/amo/components/SectionLinks/index.js
- src/blog-utils/index.js
- tests/unit/amo/components/TestFooter.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/components/TestSectionLinks.js
Fixes https://github.com/mozilla/addons-frontend/issues/10711
> Remove enableFeatureLinkToNewBlog flag

- tests/unit/amo/reducers/test_addons.js
> Improve code coverage for addons reducer

- locale/ur/LC_MESSAGES/amo.po
> Fix invalid variable in locale/ur/LC_MESSAGES/amo.po

- src/amo/utils/index.js
- tests/unit/amo/utils/test_index.js
> Update checkInternalURL to exclude blog pages

- src/amo/utils/index.js
> Improve code coverage for utils/index.js

- src/amo/components/Categories/index.js
- src/amo/components/Link/index.js
- src/amo/pages/SearchPage/index.js
- src/amo/pages/SearchTools/index.js
- src/amo/pages/UserProfileEdit/index.js
- tests/unit/amo/components/TestCategories.js
- tests/unit/amo/components/TestLink.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> Update tests for Categories, Link, SearchPage and UserProfileEdit

- src/amo/reducers/addonsByAuthors.js
- tests/unit/amo/sagas/test_reviews.js
will fix #10498 (when it's done)
> add comments to not override page_size

- src/amo/components/Search/index.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/components/TestSearchContextCard.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/10747
> Updated tests for pages/Addon and components/Search

- src/amo/reducers/api.js
- src/amo/utils/compatibility.js
- tests/unit/amo/reducers/test_api.js
- tests/unit/amo/utils/test_compatibility.js
> Allow for identifying users as on desktop or not

- package.json
- src/amo/components/CollectionDetails/index.js
- src/amo/components/CollectionManager/index.js
- src/amo/utils/index.js
- tests/unit/amo/components/TestCollectionDetails.js
- tests/unit/amo/components/TestCollectionManager.js
- tests/unit/amo/utils/test_index.js
Fixes #10179 (was unblocked by https://github.com/mozilla/addons-server/issues/7648)
> Stop decoding HTML entities for collection descriptions

- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/tracking.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/test_tracking.js
> Allow sendEvent to send an extra event

- config/dev.js
- config/development.js
- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/experiments/20210531_amo_download_funnel_experiment.js
- src/amo/withExperiment.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/experiments/test_20210531_amo_download_funnel_experiment.js
- tests/unit/amo/test_withExperiment.js
> Update experiment naming convention to support custom GA dimension on www.mozilla.org

- config/default.js
- config/dev.js
- config/development.js
- config/test.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/pages/TestAddon.js
> Enable download funnel experiment on stage and prod

- Dockerfile
> Upgrade to node v14

- src/amo/components/Page/index.js
- src/amo/pages/Addon/index.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/pages/TestAddon.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/10769~~
Fixes #10773
> Only display the VPN Promo Banner on the detail page for extensions

- config/dev.js
- config/development.js
- src/amo/components/Page/index.js
- src/amo/components/VPNPromoBanner/index.js
- src/amo/experiments/20210714_amo_vpn_promo.js
- src/amo/reducers/api.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/components/TestVPNPromoBanner.js
- tests/unit/amo/experiments/test_20210714_amo_vpn_promo.js
> Limit the VPN Promo Experiment to users from specific regions and desktop only

- src/amo/components/VPNPromoBanner/index.js
- tests/unit/amo/components/TestVPNPromoBanner.js
- tests/unit/helpers.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/10782~~
Fixes #10772
> Keep track of impression count and send it with click and dismiss events

- src/amo/components/HomepageShelves/index.js
- src/amo/reducers/home.js
- tests/unit/amo/components/TestHomepageShelves.js
- tests/unit/amo/reducers/test_home.js
- tests/unit/helpers.js
> remove support for building shelf footer url based on critera

- config/default.js
> Disable the Download Funnel Experiment

- src/amo/components/Page/index.js
- src/amo/components/VPNPromoBanner/index.js
- tests/unit/amo/components/TestPage.js
> Move withExperiment from VPNPromoBanner to Page

- src/amo/components/AddonMoreInfo/index.js
- src/amo/pages/AddonInfo/styles.scss
- src/amo/types/addons.js
- tests/unit/amo/components/TestAddonMoreInfo.js
> show tags in addon more info component

- src/amo/components/VPNPromoBanner/index.js
- src/amo/withExperiment.js
- tests/unit/amo/components/TestVPNPromoBanner.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/helpers.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/10783~~
Fixes #10770
>  Remember the dismissed status of the VPN Promo Banner 

- src/amo/api/search.js
- src/amo/constants.js
- src/amo/pages/TagPage/index.js
- tests/unit/amo/pages/TestTagPage.js
fixes #10824, spun off draft PR #10820
> Add new TagPage component

- src/amo/components/AddonAdminLinks/index.js
- tests/unit/amo/components/TestAddonAdminLinks.js
> Use the AMO ID for reviewer links

- config/default.js
- src/amo/components/Routes/index.js
- tests/unit/amo/components/TestRoutes.js
Fixes https://github.com/mozilla/addons-frontend/issues/10836
> Remove enableFeatureBlockPage flag

- config/default.js
- config/dev.js
- config/lib/shared.js
- config/stage.js
- src/amo/middleware/staticAssets.js
- src/amo/server/base.js
- tests/unit/amo/middleware/test_cspMiddleware.js
- tests/unit/amo/middleware/test_staticAssets.js
- webpack.prod.config.babel.js
> Load statics from /static-frontend/ and stop using a separate domain on dev

- config/default.js
- src/amo/utils/compatibility.js
- tests/unit/amo/utils/test_compatibility.js
Fixes https://github.com/mozilla/addons-frontend/issues/10838
> Remove enableFeatureAllowAndroidInstall flag

- locale/ia/LC_MESSAGES/amo.po
> Fix errors in locale file

- src/amo/components/RatingsByStar/index.js
- src/amo/components/RatingsByStar/styles.scss
- tests/unit/amo/components/TestRatingsByStar.js
Fixes #10688 
Star ratings are rounded to the nearest integer percent.
Before
After
> Fix star rating precision

- config/default.js
- config/dev.js
- config/development.js
- tests/unit/amo/components/TestPage.js
> Enable the VPN Promo and experiment on prod

- src/amo/components/VPNPromoBanner/index.js
- tests/unit/amo/components/TestVPNPromoBanner.js
> Pass an add-on identifier in utm_content for the VPN promo

- src/amo/reducers/addons.js
- src/amo/reducers/versions.js
- tests/unit/amo/components/TestAMInstallButton.js
- tests/unit/amo/components/TestAddonHead.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestAddonVersionCard.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/components/TestPermissionsCard.js
- tests/unit/amo/reducers/test_addons.js
- tests/unit/amo/reducers/test_versions.js
- tests/unit/amo/test_installAddon.js
- tests/unit/amo/utils/test_addons.js
- tests/unit/amo/utils/test_compatibility.js
- tests/unit/helpers.js
fixes #10900.  works with addons-dev now.
> change reducers to support a single version->file in the api

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/AddonQRCode/index.js
- src/amo/components/AddonQRCode/styles.scss
- src/amo/components/AddonQRCodeLink/index.js
- src/amo/components/AddonQRCodeLink/styles.scss
- src/amo/pages/Addon/index.js
- src/amo/pages/Addon/styles.scss
- tests/unit/amo/components/TestAddonQRCodeLink.js
- tests/unit/amo/pages/TestAddon.js
~~Depends on #10904~~
Fixes #10905
> Display the QR code on the add-on detail page

- src/amo/components/AddonCompatibilityError/index.js
- src/amo/components/AddonHead/index.js
- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/HeroRecommendation/index.js
- src/amo/components/SearchResult/index.js
- src/amo/components/VPNPromoBanner/index.js
Fix: a typo , rename DefaultProps as DeafultProps
> rename DefaultProps #10919

- locale/sk/LC_MESSAGES/amo.po
I reverted the changes. That will tell localizers to update this string in Pontoon.
> Fix sk locale

- config/default.js
> Disable the VPN Promo experiment

- bin/fenix-qr-codes.js
> Write images to component folder, clear folder first, and check for presence of files after

- src/amo/components/AutoSearchInput/index.js
- tests/unit/amo/components/TestAutoSearchInput.js
> Don't pass non-strings into Autosuggest

- src/amo/components/HomepageShelves/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestHomepageShelves.js
> use specific utm param for tag shelf addons

- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestFooter.js
> Update the Products section in the footer

- src/amo/components/HomepageShelves/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestHomepageShelves.js
> review suggestions from #11006 that weren't picked up before merge

- src/amo/server/base.js
- tests/unit/amo/server/test_base.js
> Catch URIErrors from `createHistory`

- src/amo/components/AddonVersionCard/index.js
- src/amo/components/AddonVersionCard/styles.scss
- src/amo/components/InstallWarning/styles.scss
- src/amo/pages/Addon/index.js
Fixes #11042.
**Please review this PR with care, I don't have much experience with the frontend.**
> Move the InstallWarning above the install button

- config/default.js
- src/amo/server/base.js
- src/amo/utils/server.js
- tests/unit/amo/utils/test_server.js
> Implement __heartbeat__ and __lbheartbeat__

- src/amo/components/GetFirefoxButton/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestGetFirefoxBanner.js
- tests/unit/amo/components/TestGetFirefoxButton.js
> Update download Firefox links to use the direct link

- src/amo/pages/UserProfileEdit/index.js
- src/amo/pages/UserProfileEdit/styles.scss
- src/amo/reducers/users.js
- tests/unit/amo/pages/TestUserProfileEdit.js
> Remove reviewer_name

- yarn.lock
> Update caniuse-lite in yarn.lock

- src/amo/components/Errors/AuthExpired/index.js
- src/amo/components/Errors/AuthExpired/styles.scss
- src/amo/components/Page/index.js
- tests/unit/amo/components/Errors/TestAuthExpired.js
- tests/unit/amo/components/TestPage.js
- tests/unit/helpers.js
> Show special error when 401 is because of auth expiry

- config/default.js
- src/amo/components/App/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestApp.js
fixes #11020 - don't merge until after #11014 is closed and users get a useable error.
> Drops the setTimeout that auto logs the user out

- src/amo/api/index.js
- tests/unit/amo/api/test_index.js
> Use an absolute path for login when running locally

- config/default.js
- docs/caching.md
- src/amo/api/index.js
- tests/unit/amo/api/test_index.js
- tests/unit/amo/components/TestAuthenticateButton.js
- tests/unit/amo/reducers/test_api.js
- tests/unit/amo/sagas/test_users.js
- tests/unit/amo/server/test_base.js
- tests/unit/helpers.js
> Use addons-server's SessionIDAuthentication instead

- src/amo/components/Permission/index.js
- tests/unit/amo/components/TestBadge.js
- tests/unit/amo/components/TestCategoryIcon.js
- tests/unit/amo/components/TestIcon.js
- tests/unit/amo/components/TestIconPromotedBadge.js
- tests/unit/amo/components/TestIconStar.js
- tests/unit/amo/components/TestIconXMark.js
- tests/unit/amo/components/TestPermission.js
- tests/unit/amo/components/TestUserAvatar.js
Fixes #11258 
Fixes #11227 
Fixes #11212 
Fixes #11210 
Fixes #11179 
Fixes #11174 
Fixes #11144 
Fixes #11211
> Migrate a number of tests to react-testing-library

- src/amo/components/AddAddonToCollection/index.js
- tests/unit/amo/components/TestAddAddonToCollection.js
- tests/unit/helpers.js
> Migrate TestAddAddonToCollection.js

- tests/unit/amo/components/TestAddAddonToCollection.js
- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestBadge.js
- tests/unit/amo/components/TestIconPromotedBadge.js
- tests/unit/helpers.js
> Improve the API of our custom test queries

- tests/unit/amo/components/TestAddAddonToCollection.js
- tests/unit/helpers.js
> Convert some tests in TestAddAddonToCollection.js to be more like integration tests

- .circleci/config.yml
- package.json
Attempt to address the test timeout issue with `test-next`
> Configure just the test-next task to run with Jest's -i option

- src/amo/reducers/versions.js
- tests/unit/amo/reducers/test_versions.js
> Adjust the min compatibility version for ESR 91.x

- .circleci/config.yml
> Replace legacy circleci images (both executor for release and container for tests)

- tests/unit/amo/test_withExperiment.js
- tests/unit/helpers.js
Fixes #11275 
I decided to tackle this one as I was working on TestAddon, which led me to TestPage, which led me to TestVPNPromoBanner, which eventually led me to this component. The changes here are pretty straightforward, but I faced some challenges with dealing with cookies in other components, which I will tackle next.
> Migrate test_withExperiment.js

- tests/unit/amo/components/TestVPNPromoBanner.js
- tests/unit/helpers.js
> Migrate TestVPNPromoBanner.js

- tests/unit/amo/components/TestPage-VPNPromoBanner.js
- tests/unit/helpers.js
> Create an integration test for Page rendering VPNPromoBanner

- tests/unit/amo/components/TestWrongPlatformWarning.js
> Migrate TestWrongPlatformWarning.js

- README.md
See also: https://github.com/mozilla/addons-blog/pull/379
> Add a note about the addons-blog WordPress theme in README

- src/amo/components/LoadingText/index.js
- tests/unit/amo/components/TestMetadataCard.js
Fixes #11220 
Another small test that I migrated while working on the larger TestAddon.js
> Migrate TestMetadataCard.js

- tests/unit/amo/components/TestButton.js
> Migrate TestButton.js

- tests/unit/amo/components/TestAddonMeta.js
- tests/unit/helpers.js
> Migrate TestAddonMeta.js

- tests/unit/amo/components/TestCardList.js
Fixes #11177 
Here's a nice short one. 😄
> Migrate TestCardList.js

- src/amo/pages/UserProfile/index.js
- tests/unit/amo/pages/TestUserProfile.js
- tests/unit/helpers.js
fixes #11304 ~(and include #11315)~
> rewrite tests/unit/amo/pages/TestUserProfile to testing-library

- tests/unit/amo/components/TestConfirmationDialog.js
> Migrate TestConfirmationDialog

- src/amo/components/Search/index.js
- src/amo/pages/CategoryPage/index.js
- src/amo/pages/SearchPage/index.js
- src/amo/pages/TagPage/index.js
- tests/unit/amo/components/TestSearch.js
- tests/unit/amo/pages/TestCategoryPage.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/pages/TestTagPage.js
> Remove enableSearchFilters property from Search component

- tests/unit/amo/components/TestConfirmButton.js
> Migrate TestConfirmationButton

- src/amo/components/MetadataCard/index.js
- tests/unit/amo/components/TestMetadataCard.js
> Update TestMetadataCard to demonstrate best practices for targeting its elements

- tests/unit/amo/components/TestAddonSummaryCard.js
> Migrate TestAddonSummaryCard.js

- src/amo/components/ShowMoreCard/index.js
- tests/unit/amo/components/TestShowMoreCard.js
> Migrate TestShowMoreCard.js

- README.md
- package.json
- yarn.lock
> Switch from bundlesize to the more maintained bundlewatch

- package.json
- tests/unit/test_packageJson.js
- yarn.lock
> Use more recent po2json git version to remove/update some old/unsecure dependencies

- package.json
- src/amo/components/ServerHtml/index.js
- src/amo/server/sriDataPlugin.js
- tests/unit/amo/components/TestServerHtml.js
- tests/unit/amo/server/test_sriDataPlugin.js
- webpack.dev.config.babel.js
- webpack.l10n.config.babel.js
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/issues/11419
> Update webpack, html-webpack-plugin and webpack-subresource-integrity

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/ReportAbuseButton/index.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestFlagReviewMenu.js
- tests/unit/amo/components/TestReportAbuseButton.js
> Replace conditionals with invariants in some components for unreachable code

- src/amo/components/AddonReviewCard/index.js
- src/amo/components/FlagReview/index.js
- src/amo/components/RatingManager/index.js
- src/amo/components/ReportAbuseButton/index.js
> Update errorHandler config in some components for testing

- src/amo/components/UserReview/index.js
- tests/unit/amo/components/TestUserReview.js
> Remove className prop from UserReview

- tests/unit/amo/components/TestRatingManager.js
~~Depends on #11429~~
Fixes #11232
> Migrate TestRatingManager.js

- package.json
- src/amo/api/index.js
- tests/unit/amo/api/test_index.js
- tests/unit/amo/api/test_search.js
- yarn.lock
> Encode URIs with encodeURI() instead of utf8.encode() before calling fetch()

- tests/unit/amo/components/TestAddonReviewCard.js
> Migrate TestAddonReviewCard.js

- src/amo/api/index.js
- tests/unit/amo/api/test_index.js
> Remove double encoding of querystring

- package.json
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/security/dependabot/10
> Update node-sass to 7.0.1 and misc dependencies

- bin/merge-locales
Fixes https://github.com/mozilla/addons-frontend/issues/11462
> Pass `--no-fuzzy-matching` to `msgmerge`

- src/amo/components/AuthenticateButton/index.js
- tests/unit/amo/components/TestAuthenticateButton.js
> Migrate TestAuthenticateButton.js

- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/helpers.js
> Migrate pages/TestAddonVersions.js

- src/amo/components/AMInstallButton/index.js
- tests/unit/amo/components/TestAMInstallButton.js
> Migrate TestAMInstallButton.js

- tests/unit/amo/components/TestScreenShots.js
> Migrate TestScreenShots.js

- tests/unit/amo/components/TestInstallButtonWrapper.js
> Migrate TestInstallButtonWrapper.js

- src/amo/components/CollectionManager/index.js
Fixes #11391 
Removed the check for null and comments associated with the same.
> removed check for null from onTextInput and associated comment referring to this issue

- tests/unit/amo/components/TestApp.js
- tests/unit/amo/components/TestNestedStatus.js
> Migrate TestApp.js

- tests/unit/amo/pages/TestSearchTools.js
Fixes https://github.com/mozilla/addons-frontend/issues/11302
> Migrate TestSearchTools to react-testing-library

- src/amo/pages/LanguageTools/index.js
- tests/unit/amo/pages/TestLanguageTools.js
> Migrate TestLanguageTools to react-testing-library

- src/amo/pages/LandingPage/index.js
- tests/unit/amo/pages/TestLandingPage.js
> Migrate pages/TestLandingPage.js

- tests/unit/amo/pages/error-simulation/TestSimulateAsyncError.js
- tests/unit/amo/pages/error-simulation/TestSimulateSyncError.js
> Migrate pages/error-simulation/TestSimulateAsyncError.js and pages/error-simulation/TestSimulateSyncError.js

- tests/unit/amo/test_tracking.js
Fixes #11274 
This one didn't need to be changed because of Enzyme, but it did still use Sinon for mocking, as opposed to Jest. I went ahead and migrated this file, but I don't think we want to take on migrating every test away from Sinon as part of this project. It makes sense to migrate those files that we need to touch, but I think there will be a fairly large number of tests that don't need to be migrated away from Enzyme, but should, eventually, be migrated away from Sinon.
I will open a separate project for that effort, which we can consider undertaking once this current project is over.
> Migrate test_tracking.js

- tests/unit/amo/pages/TestBlock.js
> Migrate pages/TestBlock.js

- tests/unit/amo/pages/ErrorPages/TestNotAuthorizedPage.js
- tests/unit/amo/pages/ErrorPages/TestNotFoundPage.js
- tests/unit/amo/pages/ErrorPages/TestServerErrorPage.js
- tests/unit/amo/pages/ErrorPages/TestUnavailableForLegalReasonsPage.js
- tests/unit/amo/pages/TestAddon-new.js
- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/amo/pages/TestCategoriesPage.js
- tests/unit/amo/pages/TestCollectionList.js
- tests/unit/amo/pages/TestHome-new.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/pages/TestLanguageTools.js
- tests/unit/amo/pages/TestSearchTools.js
- tests/unit/amo/pages/TestStaticPages.js
- tests/unit/amo/pages/TestUserProfile.js
> Clean up calls to renderPage

- tests/unit/amo/test_withUIState.js
> Migrate test_withUIState.js

- config/default.js
Supports https://github.com/mozilla/addons-server/issues/19245
> Put `update` in the supported nonapps/nonlocale paths for update service

- docs/testing.md
Fixes #11374 
I am sure that I have left some rules out. I will continue to update this file as I think of things to add. For the most part, developers will be expected to look at existing test cases for examples of how to write tests.
> Document new best practices for writing tests with React Testing Library

- tests/unit/amo/test_errorHandler.js
> Migrate test_errorHandler.js

- src/amo/components/ScrollToTop/index.js
- tests/unit/amo/components/TestScrollToTop.js
> Migrate TestScrollToTop.js

- src/amo/components/ServerHtml/index.js
- tests/unit/amo/components/TestServerHtml.js
> Migrate TestServerHtml.js

- tests/unit/amo/pages/TestUsersUnsubscribe.js
> Migrate TestUsersUnsubscribe to react-testing-library

- tests/unit/amo/components/TestLoadingText.js
> Migrate TestLoadingText.js

- tests/unit/amo/components/TestCard.js
- tests/unit/amo/components/TestDefinitionList.js
- tests/unit/amo/components/TestListItem.js
- tests/unit/amo/components/TestSelect.js
Fixes #11176 
Fixes #11189 
Fixes #11218 
Fixes #11250
> Migrate TestCard.js, TestDefinitionList.js, TestListItem.js and TestSelect.js

- tests/unit/amo/components/TestLink.js
> Migrate TestLink.js

- tests/unit/amo/components/TestNotice.js
> Migrate TestNotice.js

- tests/unit/amo/components/TestErrorList.js
> Migrate TestErrorList.js

- src/amo/components/AMInstallButton/index.js
- src/amo/components/InstallButtonWrapper/index.js
- src/amo/installAddon.js
- tests/unit/amo/components/TestAMInstallButton.js
- tests/unit/amo/test_installAddon.js
> Stop trying to enable static themes after install, this is no longer necessary

- tests/unit/amo/components/TestExpandableCard.js
> Migrate TestExpandableCard.js

- src/amo/components/DismissibleTextForm/index.js
> Undo changes to DismissibleTextForm that landed for the test migration

- tests/unit/blog-utils/TestStaticAddonCard.js
> Migrate blog-utils/TestStaticAddonCard.js

- tests/unit/amo/i18n/TestProvider.js
- tests/unit/amo/i18n/test_translate.js
- tests/unit/amo/i18n/test_utils.js
- tests/unit/helpers.js
> Migrate test_translate.js and TestProvider.js

- tests/unit/amo/utils/test_compatibility.js
> Address coverage change for utils/compatibility

- tests/unit/amo/utils/test_errors.js
> Migrate /utils/test_errors.js

- tests/unit/amo/components/TestInstallButtonWrapper.js
- tests/unit/amo/components/TestRoot.js
- tests/unit/amo/test_errorHandler.js
- tests/unit/amo/test_withExperiment.js
> Remove any remaining references to Sinon from migrated tests

- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonInfo.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/helpers.js
> Fix tests that are failing with the latest dependency updates

- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonInfo.js
- tests/unit/amo/pages/TestBlock.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/pages/TestSearchTools.js
- tests/unit/helpers.js
~~Depends on #11692~~
Fixes #11677 
Fixes #11678 
Fixes #11680
> Fix TestAddon.js

- tests/unit/amo/components/TestNotice.js
> Make TestNotice forward compatible with future dependencies

- tests/unit/amo/components/TestOverlayCard.js
Fixes https://github.com/mozilla/addons-frontend/issues/11667
> Make TestOverlayCard forward compatible with future dependencies

- tests/unit/amo/components/TestHeadLinks.js
- tests/unit/amo/components/TestHeadMetaTags.js
Fixes https://github.com/mozilla/addons-frontend/issues/11664
Fixes https://github.com/mozilla/addons-frontend/issues/11663
> Make TestHeadMetaTags and TestHeadMetaLinks forward compatible with future dependencies

- tests/unit/amo/pages/TestBlock.js
- tests/unit/amo/pages/TestCategoriesPage.js
> Fix pages/TestBlock.js and pages/TestCategoriesPage.js

- src/amo/components/ScrollToTop/index.js
- tests/unit/amo/components/TestScrollToTop.js
> Make TestScrollToTop forward compatible with future dependencies

- tests/unit/amo/pages/TestCollectionList.js
> Fix pages/TestCollectionList.js

- tests/unit/amo/pages/ErrorPages/TestNotFoundPage.js
- tests/unit/amo/pages/ErrorPages/TestServerErrorPage.js
- tests/unit/amo/pages/ErrorPages/TestUnavailableForLegalReasonsPage.js
Fixes #11675 
Fixes #11674 
Fixes #11676
> Fix failing ErrorPages tests

- tests/unit/amo/pages/TestCategoryPage.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/pages/TestTagPage.js
- tests/unit/helpers.js
Fixes #11682 
Fixes #11687 
Fixes #11686
> Fix pages/TestCategoryPage.js, pages/TestSearchPage.js and pages/TestTagPage.js

- tests/unit/amo/pages/TestLandingPage.js
> Fix pages/TestLandingPage.js

- tests/unit/amo/test_withUIState.js
> Fix amo/test_withUIState.js

- tests/unit/amo/components/TestExpandableCard.js
- tests/unit/amo/components/TestShowMoreCard.js
> Make TestShowMoreCard and TestExpandableCard forward compatible with future dependencies

- tests/unit/amo/components/TestVPNPromoBanner.js
> Make TestVPNPromoBanner forward compatible with future dependencies

- tests/unit/amo/components/TestAddAddonToCollection.js
> Fix components/TestAddAddonToCollection.js

- tests/unit/amo/components/TestDismissibleTextForm.js
> Make TestDismissibleTextForm forward compatible with future dependencies

- tests/unit/amo/components/TestInstallButtonWrapper.js
> Make TestInstallButtonWrapper forward compatible with future dependencies

- tests/unit/amo/components/TestConfirmButton.js
- tests/unit/amo/components/TestDropdownMenu.js
> Fix components/TestConfirmButton.js and components/TestDropdownMenu.js

- tests/unit/amo/pages/TestUserProfile.js
> Make TestUserProfile forward compatible with future dependencies

- tests/unit/amo/components/TestRating.js
- tests/unit/amo/components/TestRatingManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/11670
Fixes https://github.com/mozilla/addons-frontend/issues/11669
>  Make TestRating & TestRatingManager forward compatible with future dependencies

- tests/unit/amo/components/TestAddonMoreInfo.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAddonsCard.js
Fixes #11654 
Fixes #11655 
Fixes #11656
> Fix components/TestAddonMoreInfo.js, components/TestAddonsCard.js andcomponents/TestAddonReviewCard.js

- tests/unit/amo/pages/TestCollection.js
> Fix TestCollection.js

- tests/unit/amo/components/TestApp.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/helpers.js
~~Depends on https://github.com/mozilla/addons-frontend/pull/11723~~
Fixes #11657 
Fixes #11658 
Fixes #11668
> Fix components/TestApp.js, components/TestAutoSearchInput.js and components/TestPage.js

- package.json
- tests/unit/amo/components/TestAddonReviewCard.js
- yarn.lock
> Remove @testing-library/dom from package.json

- src/amo/components/VPNPromoBanner/index.js
- tests/unit/amo/components/TestVPNPromoBanner.js
> Remove calls to onLocationChanged from TestVPNPromoBanner.js

- package.json
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestAutoSearchInput.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/components/TestRatingManager.js
- yarn.lock
> Update @testing-library/user-event to the latest version

- package.json
- yarn.lock
> Remove `copy-webpack-plugin`

- tests/unit/amo/pages/TestUserProfile.js
> add a test for UserProfile getting an auth expired error

- src/amo/utils/index.js
- tests/unit/amo/pages/TestLandingPage.js
- tests/unit/amo/utils/test_index.js
> Allow for mixed case in URL parameters relating to add-on types

- docs/experiments.md
- docs/index.md
> Update docs to include info on how to configure experiments

- tests/unit/amo/pages/TestLandingPage.js
> Fix intermittent in `calls setDimension for the configured experiment`

- src/amo/withExperiment.js
- tests/unit/amo/test_withExperiment.js
> Experiment cookie should be set to SameSite=Strict

- locale/si/LC_MESSAGES/amo.po
Fixes an error in the po file.
> Fix error in si locale

- tests/unit/amo/pages/TestLandingPage.js
> Another attempt to fix the intermittent failure in TestLandingPage.js

- tests/unit/amo/pages/TestLandingPage.js
> Another attempt to deal with this pesky intermittent

- package.json
- yarn.lock
Fixes https://github.com/mozilla/addons-frontend/security/dependabot/35
> Bump node-sass to 7.0.3

- .circleci/config.yml
- Dockerfile
- README.md
- package.json
- yarn.lock
> Switch to Node 16 by default, drop 14, start testing with 18

- src/amo/reducers/versions.js
- tests/unit/amo/reducers/test_versions.js
> Fix newly uncovered error in `LOAD_CURRENT_COLLECTION` logic

- src/amo/constants.js
- src/amo/installAddon.js
- tests/unit/amo/components/TestInstallButtonWrapper.js
> Send a GA event when a trusted add-on is installed

- src/amo/withExperiment.js
- tests/unit/amo/test_withExperiment.js
> Don't inject an experiment variant when the experiment is disabled

- src/amo/components/LandingAddonsCard/index.js
- tests/unit/amo/components/TestLandingAddonsCard.js
> Update LandingAddonsCard to support the experiment

- src/amo/reducers/collections.js
- src/amo/reducers/suggestions.js
- src/amo/sagas/index.js
- src/amo/sagas/suggestions.js
- src/amo/store.js
- tests/unit/amo/reducers/test_suggestions.js
- tests/unit/amo/sagas/test_suggestions.js
> Implement suggestions reducer and saga

- src/amo/components/HeadMetaTags/index.js
- tests/unit/amo/components/TestHeadMetaTags.js
Fixes https://github.com/mozilla/addons-frontend/issues/11983
> Strip HTML from <meta name="description" />

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/AddonSuggestions/index.js
- src/amo/components/AddonSuggestions/styles.scss
- src/amo/constants.js
- src/amo/experiments/20221130_amo_detail_category.js
- src/amo/pages/Addon/index.js
- src/amo/pages/Collection/index.js
- src/amo/reducers/suggestions.js
- src/amo/sagas/suggestions.js
- src/amo/searchUtils.js
- tests/unit/amo/components/TestPage-VPNPromoBanner.js
- tests/unit/amo/experiments/test_20221130_amo_detail_category.js
- tests/unit/amo/pages/TestAddon-AddonSuggestions.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/reducers/test_suggestions.js
- tests/unit/amo/sagas/test_suggestions.js
- tests/unit/helpers.js
Fixes #11959 
My apologies for the large patch. I did try to break this feature up into smaller pieces, a number of which have now been reviewed and merged, but this one kind of needs all of these parts.
> Create an experiment to run on the add-on detail page

- src/amo/components/AddonSuggestions/index.js
- tests/unit/amo/pages/TestAddon-AddonSuggestions.js
> Remove authorId and slashes from some collection slugs

- config/stage.js
> Enable the suggestions experiment on stage

- src/amo/components/Paginate/index.js
- src/amo/components/Search/index.js
- src/amo/reducers/search.js
- src/amo/sagas/search.js
- tests/unit/amo/components/TestPaginate.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/reducers/test_search.js
- tests/unit/amo/sagas/test_search.js
- tests/unit/helpers.js
Fixes #10689 
Changes:
- Added the "page_count" number received by the request triggered from SEARCH_STARTED action into the "search" redux state.
- Mapped the search.page_count state to the SearchBase component's state.
- Adjusted Paginate component to receive one more prop called `receivedPageCount`. If this prop is passed down, then the Paginate component no longer compute the page count manually and it will use this value instead.
**Before**:
The paginator does not stop at page index 1200 although this is the last page the backend will return.
The paginator computes the total number of pages manually using the total number of items (received from API) and the total number of items per page (received from API).
Clicking paginator's page index 1201 leads to an error message (as it …
> Adjust paginator to use api page_count

- config/default.js
- config/dev.js
- config/development.js
- config/lib/shared.js
- config/stage.js
- src/amo/components/ServerHtml/index.js
- src/amo/tracking.js
- tests/unit/amo/components/TestServerHtml.js
- tests/unit/amo/test_tracking.js
Fixes #11992 
A couple of notes:
I haven't been able to get this working to actually publish data to our new GA4 property from `localhost`, but the debug tools make it look like data is being sent. I am hoping that once we get it running on dev, we might be able to get it to work and verify everything.
I am not 100% sure we need all of the CSP changes, but after speaking with someone on Bedrock it seemed like a good idea to make these changes to start, and we can tweak them later after we verify it's working.
> Enable reporting to GA4

- config/default.js
- config/dev.js
- config/development.js
- config/stage.js
> Enable the add-on suggestions experiment everywhere

- src/amo/tracking.js
- tests/unit/amo/test_tracking.js
Fixes #12012 
This also includes a couple of cleanups that I found when looking at `tracking.js`.
> Send all current events to GA with the same parameters and values

- src/amo/tracking.js
- src/amo/withExperiment.js
- src/blog-utils/tracking.js
- tests/unit/amo/components/TestPage-VPNPromoBanner.js
- tests/unit/amo/pages/TestAddon-AddonSuggestions.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/test_tracking.js
- tests/unit/amo/test_withExperiment.js
- tests/unit/blog-utils/test_tracking.js
- tests/unit/helpers.js
> Implement the equivalent of custom experiment dimensions in GA4

- config/default.js
> Disable the suggested add-ons experiment

- tests/unit/amo/components/TestApp.js
> Remove tests that explicitly call mapStateToProps

- src/amo/reducers/errors.js
- tests/unit/amo/reducers/test_errors.js
> Sanitize error messages coming from API calls

- src/amo/components/PermissionsCard/permissions.js
- src/amo/reducers/versions.js
- tests/unit/amo/components/TestPermissionUtils.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/helpers.js
> Display host_permissions

- docs/fenix.md
This is a small patch to fix a few things in order to build Fenix for testing the AMO integration.
> Update Fenix docs

- docs/regional_restrictions.md
Functionality has existed for a while but adding some docs to explain the logic behind it.
Helps debug https://bugzilla.mozilla.org/show_bug.cgi?id=1840632
> Add regional restrictions docs

- config/default.js
- config/development.js
- src/amo/searchUtils.js
- tests/unit/amo/api/test_search.js
- tests/unit/amo/test_searchUtils.js
Fixes https://github.com/mozilla/addons-frontend/issues/12379
> Remove `restrictSearchResultsToAppVersion` config option

- src/amo/utils/fxa.js
Just bumping the datetime forward to allow #12407 to be tested
> move mza_launch_datetime to allow it to be tested

- config/default.js
- config/dev.js
- config/development.js
- src/amo/api/abuse.js
- src/amo/components/FeedbackForm/index.js
- src/amo/components/FeedbackForm/styles.scss
- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/Feedback/index.js
- src/amo/pages/Feedback/styles.scss
- src/amo/reducers/abuse.js
- src/amo/sagas/abuse.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestFeedback.js
- tests/unit/amo/reducers/test_abuse.js
- tests/unit/amo/sagas/test_abuse.js
> add feedback form

- src/amo/utils/fxa.js
resets the date back to 1st November
> revert mza_launch_datetime bump

- src/amo/api/abuse.js
- src/amo/components/FeedbackForm/index.js
- src/amo/components/FeedbackForm/styles.scss
- src/amo/reducers/abuse.js
- src/amo/sagas/abuse.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/pages/TestFeedback.js
- tests/unit/amo/reducers/test_abuse.js
- tests/unit/amo/sagas/test_abuse.js
> add location field to feedback form

- src/amo/components/FeedbackForm/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/12515
> Fix typo in FeedbackForm

- src/amo/constants.js
- src/amo/pages/Home/index.js
- src/amo/sagas/home.js
- tests/unit/amo/pages/TestHome.js
- tests/unit/amo/sagas/test_home.js
Fixes https://github.com/mozilla/addons-frontend/issues/12523
> Update homepage for Android

- .circleci/config.yml
- Dockerfile
- package.json
- tests/pino-mozlog/test_index.js
> Bump Node.js to 18.x, start testing with 20.x

- docs/regional_restrictions.md
- docs/testing.md
This pull request fixes typos under docs folder. I request repository maintainers to review and merge it.
environnement -> environment 
neccesary -> necessary 
Replace this sentence with a description of how your patch fixes the issue.
> docs: fixed typos

- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
> Hide add-on recommendations on Android

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/ReportAbuseButton/index.js
- tests/unit/amo/components/TestRatingManager.js
> Add new feature flag to link to the new feedback form on AMO

- src/amo/api/abuse.js
- src/amo/components/FeedbackForm/index.js
- src/amo/components/FeedbackForm/styles.scss
- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/SignedInUser/index.js
- src/amo/components/SignedInUser/styles.scss
- src/amo/reducers/abuse.js
- src/amo/sagas/abuse.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestFeedback.js
Fixes #12532
---
In addition to supporting anonymous reports, it also fixes a small UI issue: checkbox/radio button labels and "help" texts are now correctly centered:
https://github.com/mozilla/addons-frontend/assets/217628/ae91cefd-9fff-4837-8496-494a8d42f739
User not signed-in:
> Allow users to report feedback anonymously

- src/amo/pages/Feedback/index.js
- src/amo/sagas/addons.js
- tests/unit/amo/pages/TestFeedback.js
- tests/unit/amo/sagas/test_addons.js
Fixes https://github.com/mozilla/addons-frontend/issues/12539
> Assume non-public add-on when the API returns a 404

- src/amo/components/RatingManager/index.js
- tests/unit/amo/components/TestRatingManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/12561
> Hide abuse report button for langpacks

- src/amo/components/FeedbackForm/index.js
- tests/unit/amo/pages/TestFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12550
> Hide location when the does_not_work category is selected

- src/amo/api/abuse.js
- src/amo/components/ReportUserAbuse/index.js
- src/amo/reducers/userAbuseReports.js
- src/amo/sagas/userAbuseReports.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/reducers/test_userAbuseReports.js
- tests/unit/amo/sagas/test_userAbuseReports.js
Fixes https://github.com/mozilla/addons-frontend/issues/12568
> Allow to submit user feedback with more information

- src/amo/components/FeedbackForm/index.js
- src/amo/sagas/addons.js
- src/amo/types/addons.js
- tests/unit/amo/pages/TestFeedback.js
- tests/unit/amo/sagas/test_addons.js
> Set location to "addon" for non-public add-ons and `does_not_work` category

- .circleci/config.yml
- Dockerfile
- package.json
- tests/pino-mozlog/test_index.js
This reverts commit d146c0eec74d0f225324ad70db5b569660dd4164 / #12531
> Revert "Bump Node.js to 18.x, start testing with 20.x (#12531)"

- .circleci/config.yml
This reverts commit 0852123f20a1a8bfb3345dc8837db19e58741be3.
> Revert "Fix build with new ubuntu image"

- src/amo/components/AddonFeedbackForm/index.js
- src/amo/components/AddonFeedbackForm/styles.scss
- src/amo/pages/Feedback/index.js
Fixes https://github.com/mozilla/addons-frontend/issues/12559
---
This is a rather small and self-contained PR on purpose because there will be more changes that move existing code around, and that is unreviewable when submitted as a single patch...
> Rename FeedbackForm to AddonFeedbackForm

- src/amo/components/FeedbackForm/index.js
- tests/unit/amo/pages/TestAddonFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12571
> Fix spam label

- src/amo/actions/reviews.js
- src/amo/api/reviews.js
- src/amo/reducers/reviews.js
- src/amo/sagas/reviews.js
- tests/unit/amo/actions/test_reviews.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/reducers/test_addons.js
- tests/unit/amo/reducers/test_reviews.js
- tests/unit/amo/sagas/test_reviews.js
> Fix add-on name (type) in review API response

- src/amo/components/ReportUserAbuse/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/AddonFeedback/index.js
- src/amo/pages/UserFeedback/index.js
- src/amo/pages/UserFeedback/styles.scss
- tests/unit/amo/pages/TestUserFeedback.js
- tests/unit/amo/pages/TestUserProfile.js
- tests/unit/helpers.js
> Introduce new page for user feedback

- config/default.js
- config/dev.js
- config/development.js
Fixes https://github.com/mozilla/addons-frontend/issues/12556
> Enable `enableFeatureFeedbackForm` everywhere

- tests/unit/amo/pages/TestAddonFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12590
---
These are things I wanted to fix eventually...
> Use constants in `TestAddonFeedback`

- src/amo/components/FeedbackForm/index.js
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/Routes/index.js
- src/amo/pages/RatingFeedback/index.js
- src/amo/pages/RatingFeedback/styles.scss
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/pages/TestRatingFeedback.js
Fixes #12507
---
~~:warning: depends on #12585~~
Developer replies look similar to the "regular" reviews:
> Introduce new page for rating feedback

- src/amo/pages/AddonFeedback/index.js
- src/amo/pages/RatingFeedback/index.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12597
> Add more test coverage for the feedback pages

- package.json
- src/amo/api/abuse.js
- src/amo/reducers/collectionAbuseReports.js
- src/amo/sagas/collectionAbuseReports.js
- src/amo/sagas/index.js
- src/amo/store.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/reducers/test_collectionAbuseReports.js
- tests/unit/amo/sagas/test_collectionAbuseReports.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons-frontend/issues/12594
> Add reducer/saga/api logic for reporting a collection

- .circleci/config.yml
> Pin fonttools for now

- src/amo/components/FlagReview/index.js
- src/amo/components/FlagReview/styles.scss
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/TooltipMenu/styles.scss
- tests/unit/amo/components/TestAddonReviewCard.js
Fixes #12588 (maybe)
---
For signed-out users:
For signed-in users:
> Allow unauthenticated users to flag user reviews

- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/ReportUserAbuse/index.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestUserProfile.js
Fixes #12607
---
Before:
After:
> Update confirmation message after a report is submitted

- src/amo/components/AddonFeedbackForm/index.js
- src/amo/components/ReportAbuseButton/index.js
- src/amo/reducers/abuse.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/reducers/test_abuse.js
Fixes https://github.com/mozilla/addons-frontend/issues/12618
> Always load add-on abuse reports by GUID

- config/default.js
- config/dev.js
- config/development.js
- src/amo/components/SearchFilters/index.js
- src/amo/searchUtils.js
- src/amo/utils/compatibility.js
- tests/unit/amo/pages/TestSearchPage.js
- tests/unit/amo/test_searchUtils.js
- tests/unit/amo/utils/test_compatibility.js
Fixes https://github.com/mozilla/addons-frontend/issues/12401
> Remove the `enableFeatureMoreAndroidExtensions` flag

- src/amo/pages/RatingFeedback/index.js
- tests/unit/amo/pages/TestRatingFeedback.js
Fixes https://github.com/mozilla/addons-frontend/issues/12628
> Hide ratings for developer replies

- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/ReportUserAbuse/index.js
- src/amo/pages/Collection/index.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/amo/pages/TestUserProfile.js
> Update report button text

- src/amo/pages/UserFeedback/index.js
> Update copy in user profile feedback form

- src/amo/components/FeedbackForm/index.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestCollectionFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
> Improve accessibility of the feedback form

- config/default.js
- config/dev.js
- config/development.js
> Set enableFeatureFeedbackFormLinks flag to true by default

- src/amo/constants.js
> Bump APPVERSION_FOR_ANDROID to 120

- src/amo/components/GetFirefoxBanner/index.js
- src/amo/components/GetFirefoxButton/index.js
- src/amo/components/WrongPlatformWarning/index.js
- src/amo/constants.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
Fixes https://github.com/mozilla/addons-frontend/issues/12667
> Add UTM params to the Play Store download URL

- package.json
> Bump max bundlesize to 360kB

- src/amo/components/GetFirefoxButton/index.js
- tests/unit/amo/components/TestPage.js
- tests/unit/amo/components/TestWrongPlatformWarning.js
Fixes https://github.com/mozilla/addons-frontend/issues/12698
> Fix how we pass the UTM parameters to the Play Store

- src/amo/api/abuse.js
- tests/unit/amo/api/test_abuse.js
Fixes https://github.com/mozilla/addons-frontend/issues/12682
> Pass lang to the abuse endpoints as a form param

- config/default.js
- src/amo/addonManager.js
- src/amo/components/FlagReviewMenu/index.js
- src/amo/components/ReportAbuseButton/index.js
- src/amo/components/ReportAbuseButton/styles.scss
- src/amo/components/ReportUserAbuse/index.js
- src/amo/components/ReportUserAbuse/styles.scss
- src/amo/components/Routes/index.js
- src/amo/pages/Collection/index.js
- src/amo/reducers/abuse.js
- src/amo/reducers/userAbuseReports.js
- src/amo/sagas/abuse.js
- tests/unit/amo/components/TestAddonReviewCard.js
- tests/unit/amo/components/TestRatingManager.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestCollection.js
- tests/unit/amo/pages/TestCollectionFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
- tests/unit/amo/pages/TestUserProfile.js
- tests/unit/amo/reducers/test_abuse.js
- tests/unit/amo/reducers/test_userAbuseReports.js
- tests/unit/amo/sagas/test_abuse.js
- tests/unit/amo/test_addonManager.js
Fixes https://github.com/mozilla/addons-frontend/issues/12654
> Remove feedback form feature flags

- .circleci/config.yml
- Dockerfile
Fixes https://github.com/mozilla/addons-frontend/issues/12768
> Install git in Docker image

- src/amo/components/Footer/index.js
- tests/unit/amo/components/TestPage.js
> Update "Legal" link in footer to point to new AMO-specific page

- package.json
- src/amo/components/FeedbackForm/index.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestCollectionFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
> Make it clear how to report a copyright/trademark infringment

- tests/smoke/setup_docker.sh
Fixes https://app.circleci.com/pipelines/github/mozilla/addons-frontend/11330/workflows/86da9ee7-8a95-4ca2-b3c9-54bf49c0d512/jobs/81336
> Fix smoke test with latest addons-server docker local env changes

- src/amo/components/FeedbackForm/index.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestCollectionFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
Fixes https://github.com/mozilla/addons/issues/14816
> Make the "Provide more details" field mandatory in the abuse reporting form

- package.json
- src/amo/actions/reviews.js
- src/amo/api/abuse.js
- src/amo/components/AddonFeedbackForm/index.js
- src/amo/components/FeedbackForm/index.js
- src/amo/components/FeedbackForm/styles.scss
- src/amo/pages/CollectionFeedback/index.js
- src/amo/pages/RatingFeedback/index.js
- src/amo/pages/UserFeedback/index.js
- src/amo/reducers/abuse.js
- src/amo/reducers/collectionAbuseReports.js
- src/amo/reducers/userAbuseReports.js
- src/amo/sagas/abuse.js
- src/amo/sagas/collectionAbuseReports.js
- src/amo/sagas/reviews.js
- src/amo/sagas/userAbuseReports.js
- tests/unit/amo/api/test_abuse.js
- tests/unit/amo/components/TestFeedbackForm.js
- tests/unit/amo/pages/TestAddonFeedback.js
- tests/unit/amo/pages/TestCollectionFeedback.js
- tests/unit/amo/pages/TestRatingFeedback.js
- tests/unit/amo/pages/TestUserFeedback.js
- tests/unit/amo/reducers/test_abuse.js
Fixes https://github.com/mozilla/addons/issues/14879
> Add new illegal_category and illegal_subcategory fields in the feedback forms

- config/default.js
Syncs constants with changes in mozilla/addons-server#22640.
> Sync constants SUPPORTED_NONLOCALES and SUPPORTED_NONAPPS

- src/amo/components/AddonAdminLinks/index.js
- tests/unit/amo/pages/TestAddon.js
Fixes https://github.com/mozilla/addons/issues/2194
> Show reviewer tools link on listing page for ReviewerTools:View permission

- src/amo/pages/Block/index.js
- src/amo/reducers/blocks.js
- tests/unit/amo/pages/TestBlock.js
Fixes https://github.com/mozilla/addons/issues/15169
> Minor fixes on blocked pages

- src/amo/pages/Block/index.js
Fixes https://github.com/mozilla/addons/issues/15221
> Add missing title to the blocked page

- .github/dependabot.yml
Fixes mozilla/addons#15332
Frontend companion PR to https://github.com/mozilla/addons-server/pull/23114
> Add github actions to dependabot.yml

- src/amo/components/IconPromotedBadge/styles.scss
- src/amo/components/PromotedBadge/styles.scss
- src/amo/components/SearchResult/styles.scss
Fixes https://github.com/mozilla/addons/issues/15372
Fixes https://github.com/mozilla/addons/issues/15373
Fixes https://github.com/mozilla/addons/issues/15374
> Tweaks to promoted badges layout

- src/amo/components/AddonsByAuthorsCard/styles.scss
Fixes https://github.com/mozilla/addons/issues/15426
> Fix extensions/themes on user profile page, keep margin for "More add-ons by" card

- .circleci/config.yml
- Dockerfile
> Bump Node.js to 20.x

- src/amo/pages/UserFeedback/index.js
- tests/unit/amo/pages/TestUserFeedback.js
Fixes https://github.com/mozilla/addons/issues/15512
> Account for non-developer profiles in feedback form

- src/amo/components/AddonHead/index.js
- src/amo/pages/AddonReviewList/index.js
- src/amo/pages/AddonVersions/index.js
- src/amo/reducers/addons.js
- src/amo/types/addons.js
- tests/unit/amo/pages/TestAddon.js
- tests/unit/amo/pages/TestAddonReviewList.js
- tests/unit/amo/pages/TestAddonVersions.js
- tests/unit/helpers.js
Fixes https://github.com/mozilla/addons/issues/15809
> Render noindex meta tag when is_noindexed is set

- .github/workflows/ci.yml
See https://wiki.mozilla.org/GitHub/Repository_Security/GitHub_Workflows_%26_Actions
> ci: update actions/checkout config

- package.json
- yarn.lock
> Bump react-cookie to 7.2.2

- locale/templates/LC_MESSAGES/amo.pot
- src/amo/pages/Addon/index.js
- tests/unit/amo/pages/TestAddon.js
This is essentially https://github.com/mozilla/addons-frontend/pull/13794, which has been merged then reverted. CI breaks for some reasons...
> Feature: remove more addons by author

- .github/workflows/ci.yml
- bin/push-locales
Fixes https://github.com/mozilla/addons/issues/15841
> ci: fix locale extraction job

- package.json
- yarn.lock
Reverts mozilla/addons-frontend#13796
> Revert "Bump jsdom from 26.1.0 to 27.0.0"

- src/amo/components/SearchSuggestion/index.js
Fixes https://github.com/mozilla/addons/issues/15864
---
This is a regression caused by #13825.
> Fix badge size in search suggestions

- package.json
- tests/unit/test_packageJson.js
- webpack-common.js
- yarn.lock
Fixes https://github.com/mozilla/addons/issues/15869
> Pin sass-embedded dep to 1.91.0 to avoid UI regressions
